### ISSUE TITLE
Toggle comment CTRL+/ not working in generic .properties editor

### ISSUE THREAD

**Issue by kdvolder** [spring-projects/sts4#100]
See: https://github.com/spring-projects/sts4/issues/97 for more details.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Kris De Volder:) 

Putting this back in started state. Noticed that compared to old editor our new implementation doesn't preserve the selection which I find midlly disturbing. So should probably try to fix this.
