### ISSUE TITLE
do not fetch metrics data right after connecting live data to an app

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#1003]
As mentioned in https://github.com/spring-projects/sts4/issues/1002#issuecomment-1464353997, at the moment the live hover mechanics fetch the live data for certain metrics right after creating a connection to the running application - whether the metrics data is used or not.

We should change this behavior in a way that metrics data is only fetched when it is needed.

Side note: we need to double check the memory visualization in the VSCode Spring Dashboard implementation that heavily relies on the metrics data when changing this behavior.

**Comment by vudayani-vmw** [comment]
@BoykoAlex 
As you mentioned in https://github.com/spring-projects/sts4/issues/1002#issuecomment-1464353997, we can remove the refresh metrics calls from [here](https://github.com/spring-projects/sts4/blob/main/headless-services/spring-boot-language-server/src/main/java/org/springframework/ide/vscode/boot/java/livehover/v2/SpringProcessConnectorService.java#L173).

On the `vscode-spring-boot-dashboard` extension, we can execute the "sts/livedata/refresh/metrics" command to query for the memory metrics before trying to fetch and display it in the memory view. (https://github.com/microsoft/vscode-spring-boot-dashboard/commit/868e02eb1a15e1ca3e80115552e2c05696cf0b2a)

**Comment by BoykoAlex** [comment]
Thank you @vudayani-vmw !
I have removed the metrics refresh from the location referenced above: ddacce5ca0d96fc8002c543965c11ec4f503d486
