### ISSUE TITLE
[spring-data-support] remove pure `findBy` method completion from proposal list

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#1014]
I am trying Petclinic, opened `OwnerRepository`, typing `findBy` and invoking content-assist. The list of proposals include a proposal `findBy` that produces

```
List<Owner> findBy();
```

which doesn't make a lot of sense. I think the code completion engine should not create this proposal.

**Comment by BoykoAlex** [comment]
Hopefully fixed with 3330e4e33e8960d8f5f5c57951fd7c43b6c3d2f0
