### ISSUE TITLE
suncertpathbuilderexception

### ISSUE THREAD

**Issue by iamyourboy** [spring-projects/sts4#1015]
suncertpathbuilderexception: unable to find valid certification path to requested target spring boot

**Comment by martinlippert** [comment]
The exception that you mentioned is usually related to the application making a request to an HTTPS URL for which the used JDK doesn't have the necessary certificate installed yet. I would recommend to lookup this on StackOverflow, there are plenty of answers around this.

In case you need more information or help about this from our side, please provide a more detailed explanation, steps to reproduce this, which version you use, that you d in the IDE to run into this issue, etc.
