### ISSUE TITLE
several live hovers are missing when running Spring Boot 3 applications

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#1019]
While the overall live hovers feature seems to be working fine for Spring Boot 3 applications, looking at the hovers in detail reveal that several hovers are missing and not showing up. We need to investigate this in more detail and fix the ones that are not showing up correctly.

**Comment by BoykoAlex** [comment]
I only remember seeing `@SpringBootApplication` not highlighted... I think others might be related to lazy bean initialization in Spring Boot...

**Comment by BoykoAlex** [comment]
This is due to the new CGLib suffix in bean types coming from the actuator. Live beans in petclinic seem to be in order now. Should be fixed with 9ad73114789823965d0e043c4dfb8c4436973a08
