### ISSUE TITLE
application.properties/yaml autocomplete for nested enums regression

### ISSUE THREAD

**Issue by alex-kormukhin** [spring-projects/sts4#1021]
**Describe the bug**
Spring Tool Suite 4.18

For nested enums:
![image](https://user-images.githubusercontent.com/99888299/228676481-0b647d0d-d434-43c6-97f1-88f3c7f574f7.png)

in list/set/map properties structs:
![image](https://user-images.githubusercontent.com/99888299/228676728-6c36cc92-c8df-4ebd-a554-2c3fdf6a0eac.png)

if enum type used in C.E form (not E with C.E import) properties autocomplete is not work.
Wrong substitution:
![image](https://user-images.githubusercontent.com/99888299/228677703-71a8e402-74d9-438d-88f7-96b70acaed0a.png)

and no value suggestions:
![image](https://user-images.githubusercontent.com/99888299/228677866-619cdc41-28e3-4ed0-b7f5-cd52eed902d2.png)

In Spring Tool Suite 3.9.22 all works fine:
![image](https://user-images.githubusercontent.com/99888299/228678213-7440d599-b63d-4c3d-99cb-5dcb9c348e91.png)

![image](https://user-images.githubusercontent.com/99888299/228678452-6e19e3ab-6a40-4ffa-b1e3-76fcfbdc40ed.png)

**To Reproduce**
Try use properties/yaml autocomplete in attached example.zip project.

**Sample**

Attach example.zip project.
[example.zip](https://github.com/spring-projects/sts4/files/11105890/example.zip)

**Comment by BoykoAlex** [comment]
The issue was that types needed to be resolved for types members. Hopefully fixed with 8067e384ea45ba348dd0502701a0b39dd034d25f
