### ISSUE TITLE
STS 4.4.18 (eclipse based) Hoovering / tooltip dialog issue

### ISSUE THREAD

**Issue by ddp1984** [spring-projects/sts4#1023]
I am having an issue with Spring STS 4.4.18 (eclipse based) on Ubuntu 22.04 / GNOME 43 / Wayland.

After downloading the tar.gz file and unpacking into my home directory, I am able to execute the application however all the tooltips based on hovering don´t show anything. When hovering on some code issue it would normally show this small tooltip dialog but instead I get two error messages in the log related to GTK:

(SpringToolSuite4:31339): Gtk-CRITICAL **: 22:04:43.605: gtk_widget_get_preferred_width_for_height: assertion 'height >= 0' failed
(SpringToolSuite4:31339): Gtk-WARNING **: 22:04:43.605: gtk_widget_size_allocate(): attempt to allocate widget with width 239 and height -1

However, if I run the application as root, the tooltips will work fine and no error will be shown in the log. Also, when executed as root the Icon displays correctly in the Ubuntu dock while with my user it only shows the default application icon as a cog.

Does anyone know if this is a bug or some sort of permission that needs to be set for it to work? 

![image](https://user-images.githubusercontent.com/13642272/230496864-3a12afe0-e348-4d61-bdba-5f53e8529285.png)

**Comment by BoykoAlex** [comment]
Sounds more like a permission issue. Are you able to reproduce the issue with plain Eclipse 4.27?

**Comment by ddp1984** [comment]
Thanks for your response. Yes, same issue with Eclipse 4.27. If I run it with root user the tooltip works fine otherwise it throws the same error and it shows an empty dialog.

```
douglas@douglas-SER:~/eclipse/java-2023-03/eclipse$ ./eclipse 
WARNING: Using incubator modules: jdk.incubator.vector, jdk.incubator.foreign
10:13:11.489 [main] DEBUG org.eclipse.m2e.core.internal.project.registry.ProjectRegistryRefreshJob - Queued refresh request: [/Tests/pom.xml]

(Eclipse:47738): Gtk-CRITICAL **: 10:13:15.792: gtk_widget_get_preferred_width_for_height: assertion 'height >= 0' failed

(Eclipse:47738): Gtk-WARNING **: 10:13:15.792: gtk_widget_size_allocate(): attempt to allocate widget with width 239 and height -1
```
I've already tried reinstalling  Spring STS several times, upgraded ubuntu to the latest Lunar Lobster version with Gnome 44.0 and still the same issue. 

If you have any ideas on how to solve this please let me know. Thank you!

**Comment by BoykoAlex** [comment]
@kdvolder does this look familiar to you at all? I think you're using Ubuntu as well... Just thought you might have run into this issue...

**Comment by martinlippert** [comment]
@ddp1984 @BoykoAlex If the same issue happens with a plan vanilla Eclipse 2023-03 (e4.27), it might be worth filing an issue at Eclipse, probably around SWT, maybe in the area of the browser integration (the hover might render HTML here, but I am not sure)

**Comment by ddp1984** [comment]
Thanks both. I will close the ticket here and open a ticket at Eclipse.
