### ISSUE TITLE
Error when trying to install new software/plugin from STS. 

### ISSUE THREAD

**Issue by PSHREYASHOLLA** [spring-projects/sts4#1029]
Whenever I try to install any new software from STS getting,
unable to read repository at http://sourceforge.net/projects/pmd/files/pmd-eclipse/update-site.

![image](https://user-images.githubusercontent.com/19671054/234092572-47f0c713-fff1-4582-b061-24f376fc66dc.png)

**Comment by martinlippert** [comment]
It looks like you have the update site URL http://sourceforge.net/projects/pmd/files/pmd-eclipse/update-site in your preferences (`Preferences -> Install / Update -> Available Update Sites`) and that update site doesn't work anymore. Please remove that update site URL from the preferences and try again. That should solve the problem.

This update site is unrelated to the Spring Tools you are trying to install, so there is nothing we can do about this specific issue on our end. You have to remove that non-working update site in your installation.
