### ISSUE TITLE
Installation of sts4 for eclipse through script

### ISSUE THREAD

**Issue by sameerhr84** [spring-projects/sts4#103]
Is it possible to install sts4 through script in eclipse using p2.director?

eclipse -nosplash -application org.eclipse.equinox.p2.director -repository <repository url>-installIU <com.*.feature.feature.group>

http://help.eclipse.org/kepler/index.jsp?topic=/org.eclipse.platform.doc.isv/guide/p2_director.html

**Comment by martinlippert** [comment]
Yes, that should be absolutely possible. You should use this p2 repo for that:
http://download.springsource.com/release/TOOLS/sts4/update/latest/

The feature IDs are:
- `org.springframework.boot.ide.main.feature`
- `org.springframework.tooling.boot.ls.feature`
- `org.springframework.tooling.cloudfoundry.manifest.ls.feature`
- `org.springframework.tooling.cloudfoundry.manifest.ls.integration.feature`
- `org.springframework.tooling.bosh.ls.feature`
- `org.springframework.tooling.concourse.ls.feature`
- `org.springsource.ide.eclipse.commons.quicksearch.feature`
- `org.springframework.ide.eclipse.boot.dash.feature`

**Comment by martinlippert** [comment]
(and sorry for the late answer)

**Comment by martinlippert** [comment]
please keep in mind that you should install this into an Eclipse 2018-09 version, we don't provide a version that is compatible with older Eclipse platform versions.

(just noticed that you are referring to a Kepler version in the link to the p2 director doc)

**Comment by martinlippert** [comment]
You have to add the main Eclipse p2 repo to the script, so that the installer can resolve additional dependencies from that repo. So please add "http://download.eclipse.org/releases/2018-09" in the script to the list of p2 repos, that should fix the issue.

**Comment by sameerhr84** [comment]
It worked :). Thank you Martin for your support and prompt response. You can close this issue now :)

**Comment by martinlippert** [comment]
Glad to hear that is it working and thanks for letting us know.
