### ISSUE TITLE
shorten the location of the resource in new property navigation feature

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#1032]
https://github.com/spring-projects/sts4/issues/761 introduced the ability to navigate from usages of properties using the `@Value` annotation to the definition of those properties in e.g. `application.properties` files. If there are multiple locations to navigate to, there is a popup showing up, letting the the user choose to which location to navigate to.

The popup shows `Open Declaration - <full URI of the resource>`. At the moment the absolute path of the resource is shown, which results in very long lines and unnecessary information to be shown, since the resource is located in the project or the workspace. We should shorten this line to show only the information that is necessary, e.g. only the path inside of the project or the path from the projects root onwards.

If this is something that needs to be fixed in LSP4E, we should transfer this to LSP4E and fix it there.

**Comment by BoykoAlex** [comment]
Yes, i saw that popup... Sounds good to me  - will look into this.

**Comment by BoykoAlex** [comment]
@martinlippert How about **Open DEclaration - project: <project name> - <project relative path>**?

**Comment by BoykoAlex** [comment]
LSP4E PR: https://github.com/eclipse/lsp4e/pull/623

**Comment by BoykoAlex** [comment]
Fixed in LSP4E
