### ISSUE TITLE
support @ConditionalOnProperty in property navigation feature

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#1033]
As a follow-up from https://github.com/spring-projects/sts4/issues/761, we should also support navigating to the property definition locations when using `@ConditionalOnProperty`, for example `@ConditionalOnProperty("petclinic.s1.message")`

Also consider navigating to property defined by `prefix` and `name`:
`@ConditionalOnProperty(prefix = "notification", name = "service")`

**Comment by BoykoAlex** [comment]
@martinlippert shouldn't be a problem at all. I'd try to sneak this into 4.18.1 Monday night.

**Comment by BoykoAlex** [comment]
Fixed with 85103b61dc8f2777b48c9a1ff1e55c7057f156f2
