### ISSUE TITLE
Having trouble downloading sts version 4.16.1

### ISSUE THREAD

**Issue by Jaydenyno** [spring-projects/sts4#1053]
Hi. I'm trying to download version 4.16.1 . I use Windows 11. I tried downloading it through the self-extracting jar but it isn't working, giving me an error saying like path variable cant be identified or something. So, I tried the zip file instead. But now, it gives me multiple errors saying paths are too long. I skipped errors and downloaded it but seems like it is full of bugs. Any kind of solution would be appreciated. Thank you.

**Comment by martinlippert** [comment]
@Jaydenyno If you want to go down the path of extracting the ZIP file yourself, you should use a dedicated zip tool like 7Zip or something similar to extract it. The built-in zip support on Windows has trouble with all those very long paths.

Hope that helps!

**Comment by Jaydenyno** [comment]
Using 7Zip to extract seems like fixed the issue. Thank you!
