### ISSUE TITLE
upgrade to Spring Boot 3.1 doesn't add jakarta dependency

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#1059]
I am trying to migrate a petclinc sample from 2.7 to 3.1, but this doesn't add the jakarta dependency to the pom, so the IDE complains about jakarta imports not being resolvable.

**Comment by BoykoAlex** [comment]
is this just the `xml.bind-api` missing? Error in `Vet` and `Vets` classes?

**Comment by martinlippert** [comment]
> is this just the `xml.bind-api` missing? Error in `Vet` and `Vets` classes?

Exactly

**Comment by martinlippert** [comment]
Same happens for the upgrade to Spring Boot 3.0 as well. Probably this issue: https://github.com/openrewrite/rewrite-spring/issues/367
