### ISSUE TITLE
LIBARCHIVE.creationtime

### ISSUE THREAD

**Issue by pstric** [spring-projects/sts4#1063]
**Describe the bug**
Unpacking spring-tool-suite-4-4.19.0.RELEASE-e4.28.0-linux.gtk.x86_64.tar.gz gives repeated error messages from tar: Ignoring unknown extended header keyword 'LIBARCHIVE.creationtime'

**To Reproduce**
Unpack sts 4.19.0 on Linux.

**Sample**
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.creationtime'

**Comment by BoykoAlex** [comment]
Looks to me like this is nothing to worry about and is just a consequence of creating the archive on mac osx.
See https://stackoverflow.com/questions/51655657/tar-ignoring-unknown-extended-header-keyword-libarchive-xattr-security-selinux

**Comment by martinlippert** [comment]
We package the product using the tycho p2 director plugin and I haven't seen a way to provide any options here to avoid this header keyword problem. I would suggest to report this against the tycho project (https://github.com/eclipse-tycho/tycho).

**Comment by manueljordan** [comment]
I have the issue for `4.20.1` for Linux too. Can I safely ignore that message?

**Comment by martinlippert** [comment]
> I have the issue for `4.20.1` for Linux too. Can I safely ignore that message?

Yes, you can safely ignore this warning

**Comment by manueljordan** [comment]
Thanks I've already installed in 3 PCs

**Comment by BoykoAlex** [comment]
Can you try installing one of the recent linux distros from https://cdn.spring.io/spring-tools/snapshot/STS4/nightly-distributions.html
Just curious if the warning is gone with any of these distros...

**Comment by manueljordan** [comment]
Yes, of course, I am going to unpack the 3 releases 4.29, 4.30 and 4.31 for Linux x64. It for tomorrow.

**Comment by manueljordan** [comment]
I downloaded the following files

* spring-tool-suite-4-4.21.1.202312130026-SNAPSHOT-e4.31.0-linux.gtk.x86_64.tar.gz
* spring-tool-suite-4-4.21.1.202312130026-SNAPSHOT-e4.30.0-linux.gtk.x86_64.tar.gz
* spring-tool-suite-4-4.21.1.202312130026-SNAPSHOT-e4.29.0-linux.gtk.x86_64.tar.gz

And happens as follows

```
tar xzf spring-tool-suite-4-4.21.1.202312130026-SNAPSHOT-e4.31.0-linux.gtk.x86_64.tar.gz 
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.creationtime'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.creationtime'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.creationtime'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.creationtime'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.creationtime'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.creationtime'
...
```

```
tar xzf spring-tool-suite-4-4.21.1.202312130026-SNAPSHOT-e4.30.0-linux.gtk.x86_64.tar.gz 
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.creationtime'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.creationtime'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.creationtime'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.creationtime'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.creationtime'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.creationtime'
...
```

```
tar xzf spring-tool-suite-4-4.21.1.202312130026-SNAPSHOT-e4.29.0-linux.gtk.x86_64.tar.gz
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.creationtime'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.creationtime'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.creationtime'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.creationtime'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.creationtime'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.creationtime'
```

I am ready here to help as I can as possible

**Comment by BoykoAlex** [comment]
I was hoping that building distros on GH Ubuntu 22.04 runner with its tar 1.34+dfsg-1ubuntu0.1.22.04.1 would resolve this... (i.e. tycho plugin with its apache common compress lib would use the tar installed on the platform)
I'm not really sure what else we can do here. Given that this header is completely harmless I'm tempted to close this as "no plan fix" unless another idea comes up.

**Comment by manueljordan** [comment]
Interesting the situation and the answer is behind of the following question

* What changed between STS 4.17/4.19 to 4.21 about how was generated the .tar.gz file?

I worked with 4.17 and 4.19 (neither 4.18 nor 4.20) So I detected this situation with 4.21

**Comment by BoykoAlex** [comment]
We switched to the latest tycho 4.x plugin to be able to use PGP signing for p2 repos. Don't think we'd want to downgrade tycho and lose the GPG signing

**Comment by manueljordan** [comment]
Thus a special note in STS4 page at spring.io would be added indicating the `tar: Ignoring unknown extended header keyword 'LIBARCHIVE.creationtime'` message can be ignored in peace

**Comment by BoykoAlex** [comment]
@manueljordan can you please give linux distros here https://cdn.spring.io/spring-tools/snapshot/STS4/nightly-distributions.html another try? Since we switched to linux GH runner for the build i figured it might be okay to untar what tycho has created and use tar from the linux runner to archive it. The tar on ubuntu 22.04 seems to be GNU.

**Comment by manueljordan** [comment]
@BoykoAlex now all work as expected - zero messages 👍
