### ISSUE TITLE
"open declaration of manager version", the location cannot be correctly located

### ISSUE THREAD

**Issue by signup-github** [spring-projects/sts4#1066]
**Describe the bug**
When there are duplicate defined versions in the pom.xml file, the prompt "Overriding managed version of xxx for xxx" is displayed. When clicking "open declaration of manager version", the location cannot be correctly located.

**To Reproduce**
The version number of the third-party dependency has already been defined in the parent module or dependent module. If the version number is defined again in the current project, it will prompt "Overriding managed version of xxx for xxx". In the previous version of STS, it would prompt which third-party dependency defined the version number of this dependency and could be linked to it, but the latest version of "4.19.0. RELEASE" did not have this feature.

**Comment by martinlippert** [comment]
Sounds like this is related to the Maven support in Eclipse, so should probably reported against the m2e project (https://github.com/eclipse-m2e/m2e-core)
