### ISSUE TITLE
Let show `optional:` prefix for `spring.sql.init.schema-locations`  and `spring.sql.init.data-locations`

### ISSUE THREAD

**Issue by manueljordan** [spring-projects/sts4#1067]
Currently for STS 4.17.2 

About Spring Boot for these two Application Properties 

* `spring.sql.init.schema-locations` 
* `spring.sql.init.data-locations`

When are declared in the `application.properties` file, when autocomplete is used, is expected that the `optional:` prefix appears too. But it does not happen.

For more details see the following specific comment:

* https://github.com/spring-projects/spring-boot/issues/36176#issuecomment-1618980669

And for that specific comment read its next comment too - it for a better guidance about how it works behind the scene. The point is, if other Application Properties can work with this `optional:` prefix, it should be listed too.

Thanks for your understanding

**Comment by BoykoAlex** [comment]
Should be fixed with: 2d8cd9d8497d796e47fc1056f52ebf2648397d97
