### ISSUE TITLE
Show all the current Starter Dependencies when a new one is attempted to be added through GUI

### ISSUE THREAD

**Issue by manueljordan** [spring-projects/sts4#1078]
For a `Spring Boot` project created through https://start.spring.io, with some _starter dependencies_ and based with `Maven` .

And of course, imported into the IDE:

* `File` -> `Import` -> `Maven` - > `Existing Maven Projects`

And taking then the scenario when later is need it to add another _starter dependencies_, therefore is possible do:

* Select the `pom.xml` file -> Right Click -> `Spring` -> `Add Starters`

It according with:

* [Eclipse Spring Tool Suite add dependencies using GUI after project creation](https://stackoverflow.com/questions/49133904/eclipse-spring-tool-suite-add-dependencies-using-gui-after-project-creation)

**Expected Behavior**

Show all the current or previous _Starter dependencies_

**Current Behavior**

Is **not** shown all the current or previous _Starter dependencies_

**Context**

* How has this issue affected you?

Is confuse: is mandatory first open the `pom.xml` file to see what is already added. 

I am not sure how is handled if some _starters dependencies_ are added through the GUI **but** some of them are already available in the `pom.xml` file. Therefore duplication

**Comment by martinlippert** [comment]
Thanks for raising this @manueljordan. We discussed and thought about this some time ago and decided not to implement this. The reason for that is that there is no clear and exact way to determine the set of selected starters from an existing `pom.xml` file.

If you select a set of starters in initializr, they are not just added as dependencies in your `pom.xml` file. There is a lot of logic behind the scenes that allows the project to automatically add additional dependencies if you select a specific set of starters, create specific other files, etc. If you see this as a function `f(set of starters) -> generated project`, there is no inverse function `f(project) -> set of starters` that could be implemented in a reasonable way, therefore we decided to not go down this path.

**Comment by manueljordan** [comment]
Thanks for the polite reply 

I understand. Therefore the GUI approach is practically _only_ valuable to create a Spring Boot project from the scratch

And I did realize the follow: is **not** possible add new starters through the GUI, I mean, once located in the dialog window where the dependencies can be added, if is added an extra dependency with the total confidence that it is not already included, when is pressed the `next` button, the next dialog window shows the GUI variation of the `pom.xml` file but is **not** possible go forward. Is it the expected behavior?

Fore replication purposes: create a project from https://start.spring.io/ with 2 starter dependencies, such as `Web` and `MySQL`, get the zip file and import it into the IDE, through the GUI add the `Thymeleaf ` dependency, press the `next` button, is not possible do anymore.

**Comment by martinlippert** [comment]
Here is what it looks to me when I follow your steps:

<img width="1144" alt="image" src="https://github.com/spring-projects/sts4/assets/107705/506f04b5-6f05-432f-8191-6ce2d64855e2">

The diff dialog shows nicely which dependency would be added (on the left) and you can decide what to do:
- merge the change in the left to the right (into your local project)
- check the `pom.xml` file in the list of files in the upper section to apply all changes to your local file

You could even do the same when double clicking on the HELP.md file. You could see in the diff what would be added to your local project and you can decide whether to apply all those changes, individual ones, or nothing.

This dialog shows you all the stuff that start.spring.io would generate and how that compares to your local project, even if you edited your `pom.xml` manually in between or start.spring.io does additional things like add things to your `application.properties` file (or `HELP.md` in this case). It is quite a powerful way to adding starters and all the things associated with them and can do much more than just add a dependency to your `pom.xml` file. But even adding the dependency to the `pom.xml` file is relatively easy and straightforward. Check the `pom.xml` in the list if files and press finish.

Looks to me like this is working as designed.

**Comment by BoykoAlex** [comment]
The compare and merge dialog allows you to merge changes from left into you local pom on the right. Select the green pane and you'd be able to move it to the right. Or hover over small green square in the divider it should have button popus to move code to the right.
Once there are change in you local file finsih button would b ernabled

**Comment by manueljordan** [comment]
Thanks Alex, let me try it this weekend with the brain refreshed ... therefore feedback is coming soon ... the point is do intuitive the GUI for this reported scenario

**Comment by manueljordan** [comment]
Hello @martinlippert  and @BoykoAlex I tried now and works fine as expected. I have two friendly observations

* Once added the new dependency, from the left to the right, how it can be removed _individually_?  

For example was added 4 new dependencies but just one of them should be removed, it because was added by mistake or should be added later. So far, the unique valid approach is press the `Back` button and then again return to the _comparison_ dialog window. The problem is that all the new dependencies are reset as expected.

* Is not possible define a custom location of the new starter - it either prior or after - to be added in the `pom.xml`. 

For example between 2 specific starters or either at the top or bottom of the `pom.xml` file. The current approach is do the updates and later open manually the `pom.xml` and apply the custom locations

For the first scenario, it should be possible accomplish through the menu item located at the top (the yellow/blue button) and through the arrow button that appears in the small green square that appears in the middle column of the two inner text areas

Thanks for your understanding

**Comment by martinlippert** [comment]
Thanks @manueljordan, all good points. The diff portion of the dialog is indeed not very flexible with regards to the exact location where you want to add dependencies, remove them again, etc. I would suggest to open two specific issues for each of those observations, so that we can discuss possible improvements there.

**Comment by manueljordan** [comment]
I am taking this main post to share a 3rd observation, if you arrive to the `diff` dialog window, be default the 2 split panes are referenced from right to left (the current to the new) and not left to right (the new to the current). Is it the standard behavior? 

This observation could be silly, but to be honest I expect the latter scenario - it perhaps because I am _left handed_. But being curious: Why was taken the current (former) scenario?, normally everybody reads from left to right and "we could expect shown the new content in the left and the current in the right" 

Let me know your thoughts, it to know if I should create or not a 3rd post

**Comment by martinlippert** [comment]
@manueljordan I am not sure I understand you correctly. The diff dialog shows you what the starter wizard would generate - based on your selection - on the left side. The right side shows the version of the file in your workspace. That means, if you want to add new things to your project, you see the new stuff in the left and would move things from left (the new stuff) to the right (into your existing files). Isn't that what you described as the desired state?

Another side note: if all new additions on the left seems plausible to you, you can simply check the file in the top section (there is a checkbox in front of the file name). That means to copy all the changes into your workspace file. This is the usual way people can (and should) use the dialog. Select new starters to add, take a quick look at the diff, select the file (to say it all looks good), then press finish -> and done.
