### ISSUE TITLE
STS-4.19.0.RELEASE on wsl ubuntu show in Terminal opens  terminal in user home directory

### ISSUE THREAD

**Issue by ksanjeev9211** [spring-projects/sts4#1080]
**Environment: Ubuntu 22.04.01 LTS on wsl2**
**STS version: 4.19**

Steps to reproduce: 

1. create or import any java/non-java project
2. rt click the project-> show in terminal

the above opens the terminal in the user's home directory and not in the project's directory.

I have recently started using STS on linux environment and am not sure if it is the correct behavior. 
On Windows it opens the terminal in the project's directory though.

**Comment by martinlippert** [comment]
The terminal view and the associated action is implemented as part of the CDT project at Eclipse, therefore I would recommend to file the issue over there to get in direct contact with the team behind this feature: https://github.com/eclipse-cdt/cdt

**Comment by ksanjeev9211** [comment]
Thank you, will file an issue there.
