### ISSUE TITLE
VS Code MS Marketplace and Open VSX extension ID

### ISSUE THREAD

**Issue by cypher256** [spring-projects/sts4#1082]
Is it possible to have the Open VSX extension ID for Spring Boot Extension Packs be the same ID as MS Marketplace?
Extension pack developers who publish their extension packs to MS Marketplace cannot publish them to Open VSX without modifying the package.json, because the extension ID is different.

e.g. VS Code My Extension package.json
```json
  "extensionPack": [
    "vscjava.vscode-java-pack",
    "vmware.vscode-boot-dev-pack", <=== "Pivotal.vscode-boot-dev-pack" for Open VSX
    "vscjava.vscode-gradle",
    "redhat.vscode-xml",
  ],
```

**Comment by cypher256** [comment]
Great! thank you.
https://open-vsx.org/extension/vmware/vscode-boot-dev-pack

**Comment by martinlippert** [comment]
The extensions got moved to the VMware namespace and I also updated them to the latest version that we just released, so they are up-to-date again.
