### ISSUE TITLE
[new validation engine] remove old open-rewrite based validation code

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#1084]
Once the new validation engine is merged, we should go ahead and cleanup the code base, especially removing all the code and preferences that are related to the OpenRewrite based source reconciling.

(follow-up action around new validation engine, based on work done for https://github.com/spring-projects/sts4/issues/1068)

**Comment by BoykoAlex** [comment]
Fixed with da89df6e60a08d77e20d2e5beb9b622d17bcf269 (at least majority of Rewrite related code is gone)
