### ISSUE TITLE
Failing to download STS4 plugin for Eclipse

### ISSUE THREAD

**Issue by wac84s** [spring-projects/sts4#1093]
**Describe the bug**
Failing ot install sts4 on eclipse.

**To Reproduce**
Try to install sts4 on eclipse

**Sample**

Visit in a browser

https://download.springsource.com/release/TOOLS/sts4/update/e4.28/content.xml
<img width="789" alt="Screenshot 2023-08-01 at 4 38 34 PM" src="https://github.com/spring-projects/sts4/assets/141072080/a0759d97-19cf-4392-a9f8-b3a3c2989cf7">

Error given:

```
Unable to read repository at https://download.springsource.com/release/TOOLS/sts4/update/e4.28/content.xml.
No route to host
```

![Screenshot 2023-08-01 at 4 38 17 PM](https://github.com/spring-projects/sts4/assets/141072080/c712a486-c14e-4039-853e-41489cfd60f8)

**Comment by BoykoAlex** [comment]
This is a p2 repo... expected usage is you try this URL https://download.springsource.com/release/TOOLS/sts4/update/e4.28 in the "Help" -> "Install New Software..." then click Add button to add the new repository where you enter a name for the repo and the URL: https://download.springsource.com/release/TOOLS/sts4/update/e4.28 (without the context.xml)

**Comment by martinlippert** [comment]
You can also use the Eclipse Marketplace from the `Help` menu.

**Comment by martinlippert** [comment]
The p2 mechanism used inside of Eclipse when accessing update repositories tries to access the file that you mentioned (`content.xml` in this case) and when it cannot find that file, it tries other files, e.g. `compositeContent.xml` - which exists in our case and is then being used moving forward.

In your case, it looks like p2 has trouble to interpret the response in the right way. The response comes back with a HTTP response code 403, which indicates that this resource is not available. Maybe there is a proxy server in between your machine and the p2 repository location that changes/corrupts the response somehow? Just guessing here...

What happens when you run a `curl -v https://download.springsource.com/release/TOOLS/sts4/update/e4.28/content.xml` on the command line from your machine? Does it show the 403 response?

**Comment by wac84s** [comment]
Does this work for you?   Maybe its my company firewall?


`> curl -v https://download.springsource.com/release/TOOLS/sts4/update/e4.28/content.xml 
*   Trying 104.26.14.15:443...
* Connected to download.springsource.com (104.26.14.15) port 443 (#0)
* ALPN: offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-AES256-GCM-SHA384
* ALPN: server did not agree on a protocol. Uses default.
* Server certificate:
*  XXXXXXXX REMOVED BY ME XXXXXXXXXXX
*  SSL certificate verify ok.
* using HTTP/1.x
> GET /release/TOOLS/sts4/update/e4.28/content.xml HTTP/1.1
> Host: download.springsource.com
> User-Agent: curl/7.88.1
> Accept: */*
> 
< HTTP/1.1 403 Forbidden
< Date: Wed, 02 Aug 2023 18:19:06 GMT
< Content-Type: application/xml
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-Cache: Error from cloudfront
< Via: 1.1 15ce0329949ac28ffe4b40b091e277ee.cloudfront.net (CloudFront)
< X-Amz-Cf-Pop: ORD51-C1
< X-Amz-Cf-Id: XXXXXXXXX
< CF-Cache-Status: BYPASS
< Report-To: XXXXXXXXXX
< NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< Server: cloudflare
< CF-RAY: 7f0853c4dadce15b-ORD
< 
<?xml version="1.0" encoding="UTF-8"?>
* Connection #0 to host download.springsource.com left intact
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>5JTX9WRB7VSB3WAD</RequestId><HostId>LBpralvK86RW8xjpWBSrCBoL4oiSxAqet8NUN32TUoVjxpjF3np8pDGkOlbxxZEsmmDudqgmJGw=</HostId></Error>`

**Comment by martinlippert** [comment]
Actually that looks quite correct, the 403 seems to get through, so I am wondering why Eclipse complains about this. The mechanism should move on and try the next URL extension... Is there anything showing up in the Error Log view that could be related?

**Comment by wac84s** [comment]
I tried again from Eclipse Market Place. Works now. I did nothing different and is using same url as above but the "things to install list" changed slightly which is interesting.  I am getting past the error now 🤷   Thanks for helping :)

**Comment by martinlippert** [comment]
Glad to hear that and thanks for letting us know.
