### ISSUE TITLE
Wrong spring-boot app displayed/started in dashboard

### ISSUE THREAD

**Issue by apupier** [spring-projects/sts4#110]
I have 2 spring-boot app visible in dashboard:

![image](https://user-images.githubusercontent.com/1105127/46942263-3be9f080-d06d-11e8-86d8-40de03f051df.png)

I right-click on "name-service" -> Start
Then I have a green dot for "greetings-service":
![image](https://user-images.githubusercontent.com/1105127/46942332-60de6380-d06d-11e8-8ff0-60bc9b294274.png)

based on logs, it seems that the greetings-service has been started instead of the name-service:
![image](https://user-images.githubusercontent.com/1105127/46942370-7c496e80-d06d-11e8-9803-fabf33dcdcc9.png)

I'm using this project https://github.com/jboss-fuse/fuse-springboot-circuit-breaker-booster

**Comment by kdvolder** [comment]
Interesting and thanks for the bug report. But I think the report should go to https://github.com/Microsoft/vscode-spring-boot-dashboard

I'll re-raise it there.
