### ISSUE TITLE
quick fix to remove unnecessary `@Autowired` appears twice

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#1106]
I have a simple Rest Service guide project created and added an `@Autowired` constructor to the `GreetingController`. It is flagged with a warning, but invoking the quick fix popup, the `remove unnecessary @Autowired` appears twice.

**Comment by martinlippert** [comment]
This has a timing component to it. If you invoke the quick fixes quickly after the warning appears, there is only one quick fix showing up. But invoking the quick fix popup again, you will see the second quick fix appearing.

**Comment by martinlippert** [comment]
The same happens for the validation / quick fix that flags unnecessary `public` modifiers for `@Bean` methods, where all three quick fixes (remove, remove in file, remove in project) appear twice as well in the quick fix popup.

**Comment by BoykoAlex** [comment]
@martinlippert can you paste the screenshot of the popup? It's not the hover and not the dialog you get when invoken quick fix from the problems view... It is the shell that pops up when you click on an icon in the gutter, correct?

**Comment by martinlippert** [comment]
I hit Cmd-1 from within the editor with the cursor placed at the first character of the annotation

**Comment by BoykoAlex** [comment]
Fixed with e79da3946aca91b2a687f3983d7d755c6495b4e1, unit tested with 2a397ae57c751ae2939432982dbe39d931dcc5ed
