### ISSUE TITLE
 Nightly Builds

### ISSUE THREAD

**Issue by navy1978** [spring-projects/sts4#1108]
Firstly, I would like to commend the Spring Tool Suite team for the outstanding work in providing a powerful and indispensable tool for Spring developers. I have been an avid user of STS for quite some time, and it has greatly enhanced my productivity.

However, I have noticed that sometimes when critical issues or bugs are identified by the community, we have to wait until the next official release to receive fixes. This can be a bit frustrating, especially when a particular issue significantly impacts our workflow. To address this, I would like to propose the introduction of nightly builds for Spring Tool Suite.

I understand that this suggestion may have been previously presented, and I apologize if that is the case. I believe it's worth reiterating, as it can greatly improve the user experience and provide more agile solutions to critical issues.

Nightly builds could serve as a valuable addition to the release cycle by providing users with access to the latest code changes and bug fixes on a daily basis. This would allow us to benefit from important updates immediately and alleviate the wait time between official releases.

I understand that introducing nightly builds might require additional resources and careful consideration, but I believe it could greatly improve the user experience and provide more agile solutions to critical issues.

Thank you for your attention to this matter,

**Comment by martinlippert** [comment]
Thanks a lot for the great and nice feedback @navy1978, that is awesome to hear. Much appreciated!

With regards to the nightly builds, we already have them for a very long time.

For Eclipse-based tooling, we have

- CI builds of the Spring Tools 4 for Eclipse full distributions
- CI builds of the Spring Tools 4 for Eclipse update sites

You can get them from here:
https://dist.springsource.com/snapshot/STS4/nightly-distributions.html

For the VSCode extensions, you can switch to the pre-release version right from within VSCode.

Both, the Eclipse-based tools as well as the VSCode pre-release builds are CI based, so usually up-to-date with the latest commit on the repository and a delay of some time (for running and publishing the builds).

Hope this is what you are looking for.

**Comment by martinlippert** [comment]
@navy1978 I fully agree to your point, we should try to make the nightly downloads more visible and accessible, no question around that. in the past, we treated this more as an internal download page and shared the URL to the page on issues when there was a fix available or we were looking for additional feedback on potential fixes. But I agree with you, we could turn this into something more visible and publicly accessible. Will keep this item open to track that,

**Comment by martinlippert** [comment]
I updated https://github.com/spring-projects/sts4/wiki/Installation and included links to the snapshot builds download locations. Therefore, closing this now. Thanks again for raising this.
