### ISSUE TITLE
reuse compilation unit cache to compute symbols for document

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#1119]
The symbols for an open document are computed via the `SpringSymbolIndex` calling the `computeSymbols` method of the indexers in order to compute symbols from the content of the edited document instead of the content of the file on disc.

The `SpringIndexerJava` implements this using the same mechanism that is used for searching for symbols in files by creating its own `ASTParser`, and do the parsing - while the reconciling is doing the same on dirty documents in parallel, but using the `CompilationUnitCache` instead, which gets updated automatically on demand. To avoid the duplicated parsing logic, we should switch the `SpringIndexerJava` to use the `CompilationUnitCache` instead of doing its own parsing.

**Comment by BoykoAlex** [comment]
@martinlippert perhaps spring java indexer reconciling of sources opened in the editor should be skipped in favour of document reconcilers? Not sure how to proceed with the cached reconcile problems in this case though... maybe it is not a problem that some (a small subset) of reconcile problems isn't cached...
