### ISSUE TITLE
Exception occurred while creating an instance of the stream connection provider

### ISSUE THREAD

**Issue by sgulci** [spring-projects/sts4#112]
Hi,

when i save the file, sts4 eclipse puts error logs , looks like language server thing but i have no idea 

> eclipse.buildId=4.0.0.201809220817-RELEASE
> java.version=1.8.0_131
> java.vendor=Oracle Corporation
> BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
> Framework arguments:  -product org.springframework.boot.ide.branding.sts4
> Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.springframework.boot.ide.branding.sts4
> 
> This is a continuation of log file D:\Users\sgulci\eclipse-workspace\.metadata\.bak_1.log
> Created Time: 2018-10-16 12:59:06.637
> 
> org.eclipse.lsp4e
> Error
> Tue Oct 16 14:39:17 EET 2018
> Exception occurred while creating an instance of the stream connection provider
> 
> java.lang.RuntimeException: Exception occurred while creating an instance of the stream connection provider
> 	at org.eclipse.lsp4e.LanguageServersRegistry$ExtensionLanguageServerDefinition.createConnectionProvider(LanguageServersRegistry.java:117)
> 	at org.eclipse.lsp4e.LanguageServerWrapper.start(LanguageServerWrapper.java:196)
> 	at org.eclipse.lsp4e.LanguageServerWrapper.getInitializedServer(LanguageServerWrapper.java:532)
> 	at org.eclipse.lsp4e.LanguageServiceAccessor$LSPDocumentInfo.getInitializedLanguageClient(LanguageServiceAccessor.java:125)
> 	at org.eclipse.lsp4e.operations.codelens.CodeLensProvider.lambda$0(CodeLensProvider.java:44)
> 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
> 	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
> 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
> 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
> 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
> Caused by: org.eclipse.core.runtime.CoreException: Plug-in "org.springframework.tooling.boot.ls" was unable to instantiate class "org.springframework.tooling.boot.ls.DelegatingStreamConnectionProvider".
> 	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:200)
> 	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:194)
> 	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:934)
> 	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:246)
> 	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
> 	at org.eclipse.lsp4e.LanguageServersRegistry$ExtensionLanguageServerDefinition.createConnectionProvider(LanguageServersRegistry.java:114)
> 	... 10 more
> Caused by: java.lang.NoClassDefFoundError: org/springframework/tooling/boot/ls/SpringBootLanguageServer
> 	at org.springframework.tooling.boot.ls.DelegatingStreamConnectionProvider.<init>(DelegatingStreamConnectionProvider.java:64)
> 	at sun.reflect.GeneratedConstructorAccessor47.newInstance(Unknown Source)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 	at java.lang.Class.newInstance(Class.java:442)
> 	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:190)
> 	... 14 more
> 

---------------------------------------------------------------------------------------------------------------

> eclipse.buildId=4.0.0.201809220817-RELEASE
> java.version=1.8.0_131
> java.vendor=Oracle Corporation
> BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
> Framework arguments:  -product org.springframework.boot.ide.branding.sts4
> Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.springframework.boot.ide.branding.sts4
> 
> This is a continuation of log file D:\Users\sgulci\eclipse-workspace\.metadata\.bak_1.log
> Created Time: 2018-10-16 12:59:06.637
> 
> org.eclipse.lsp4e
> Error
> Tue Oct 16 14:39:17 EET 2018
> Plug-in "org.springframework.tooling.boot.ls" was unable to instantiate class "org.springframework.tooling.boot.ls.DelegatingStreamConnectionProvider".
> 
> org.eclipse.core.runtime.CoreException: Plug-in "org.springframework.tooling.boot.ls" was unable to instantiate class "org.springframework.tooling.boot.ls.DelegatingStreamConnectionProvider".
> 	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:200)
> 	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:194)
> 	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:934)
> 	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:246)
> 	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
> 	at org.eclipse.lsp4e.LanguageServersRegistry$ExtensionLanguageServerDefinition.createConnectionProvider(LanguageServersRegistry.java:114)
> 	at org.eclipse.lsp4e.LanguageServerWrapper.start(LanguageServerWrapper.java:196)
> 	at org.eclipse.lsp4e.LanguageServerWrapper.getInitializedServer(LanguageServerWrapper.java:532)
> 	at org.eclipse.lsp4e.LanguageServiceAccessor$LSPDocumentInfo.getInitializedLanguageClient(LanguageServiceAccessor.java:125)
> 	at org.eclipse.lsp4e.operations.codelens.CodeLensProvider.lambda$0(CodeLensProvider.java:44)
> 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
> 	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
> 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
> 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
> 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
> Caused by: java.lang.NoClassDefFoundError: org/springframework/tooling/boot/ls/SpringBootLanguageServer
> 	at org.springframework.tooling.boot.ls.DelegatingStreamConnectionProvider.<init>(DelegatingStreamConnectionProvider.java:64)
> 	at sun.reflect.GeneratedConstructorAccessor47.newInstance(Unknown Source)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 	at java.lang.Class.newInstance(Class.java:442)
> 	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:190)
> 	... 14 more
>

**Comment by martinlippert** [comment]
I think I saw something like this before a while ago. Can you try to run your STS4 install with the `-clean` parameter once to see if that solves the issue?

If not, we would need to dive a bit deeper. For that it would be good to know if you are running a vanilla Spring Tools 4 for Eclipse distribution download or if you installed the Spring Tools 4 into an existing Eclipse installation - and if so, which version of Eclipse this was. Just as some up-front debug info request... :-)

**Comment by sgulci** [comment]
i think `-clean` resolves the issue but i use sts from toolbar, in this way i  create shortcut, hmm i think we lose some usability catch like pin to taskbar in windows, maybe next  release you to decide this. i am good for now. thanks for the quick response.

**Comment by martinlippert** [comment]
Usually you need to run with `-clean` only once to clean things up if something goes wrong, so no need to add the `-clean` option to your launch shortcut permanently.

**Comment by SanthoshiBeeram** [comment]
I am getting the same error as above even after performing the clean. Can you please suggest what to do to resolve the issue

**Comment by martinlippert** [comment]
@SanthoshiBeeram It is hard to guess what exactly is going wrong on your side, but are you running STS on Windows? And if so, how do you install STS? In case you are on Windows, it would be good to validate if downloading a fresh distribution for Windows, running the self-extracting JAR file, and then running STS would cause the same error.
