### ISSUE TITLE
remove legacy STS project checker

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#1122]
The STS legacy project checker should be removed from the codebase. We don't need this anymore and we don't need to run this code and related jobs in STS anymore.

The code is mostly here: https://github.com/spring-projects/sts4/tree/main/eclipse-language-servers/org.springsource.ide.eclipse.commons.frameworks.ui/src/org/springsource/ide/eclipse/commons/frameworks/ui/internal/legacyconversion

**Comment by BoykoAlex** [comment]
What about workspace conversion in `org.springsource.ide.eclipse.commons.frameworks.core.legacyconversion` package of plugin project `org.springsource.ide.eclipse.commons.frameworks.core`? Convert 2.x workspace into 3.x - think this long gone now... I'd remove this as well.

**Comment by BoykoAlex** [comment]
Removed legacy conversion code for both project and workspace: 2b85fb3d1f36a716ca920b6903201ca1ea20e509
