### ISSUE TITLE
SpringToolSuite 4.20 crashes on Debian (Gnome, X11)

### ISSUE THREAD

**Issue by RestlessDevil** [spring-projects/sts4#1123]
**Describe the bug**
STS 4.20 for Eclipse on Debian 11 with Gnome, configured to run on the legacy X11

/opt/sts/SpringToolSuite4
OpenJDK 64-Bit Server VM warning: Ignoring option --illegal-access=permit; support was removed in 17.0
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
No provider of eglCreateImage found.  Requires one of:
    EGL 15

**To Reproduce**
Start STS and click on the "tip of the day" in bottom right corner

**Sample**
Don't have it.

**Comment by martinlippert** [comment]
Does this happen with the vanilla Eclipse 2023-09 installation as well? Would be great if you could double check that to see where exactly to report this. Many many thanks!

**Comment by RestlessDevil** [comment]
Sorry for not responding right away, I wanted to try it out in the exact the same environment as STS 4.20, on my office workstation.
Vanilla Eclipse 2023-09 crashes right away, with the exact same error.
![Screenshot from 2023-10-15 11-27-16](https://github.com/spring-projects/sts4/assets/76730510/760b4b7f-f387-43e6-b49a-cc2961b8aae4)
