### ISSUE TITLE
Consider to add at the "Properties" dialog window icon to copy complete path location of the project

### ISSUE THREAD

**Issue by manueljordan** [spring-projects/sts4#1125]
Hello

For any project available in the IDE, for simplicity a `Spring Boot` project named as `Domingo` located at the `/home/username/spring/sts4/workspace/` directory.

If is applied _right click_ and selected the `Properties` option then appears the expected information through a Dialog Window. There appears the `Location` field with:

* The `/home/username/spring/sts4/workspace/Domingo` value
* The `Show In System Explorer` icon. 

When the icon is clicked it works by opening the `System Explorer` at the location `/home/username/spring/sts4/workspace/` showing all the projects including `Domingo`, to be honest I expected see opened at the 
`/home/username/spring/sts4/workspace/Domingo` location - I mean _within_ the `Domingo` directory and not outside of the `Domingo` directory.

Could you consider in add two more icons in `Location`? It about

* One to copy the Location's path value 

The goal is either copy/paste the path in a Terminal. It to execute anything. For example Maven/Gradle goals/tasks and execute the `java -jar Domingo.jar`. Yes - I know is possible use `Run Configurations` to create the Maven and Gradle goals/tasks ... but when the list of items for Maven/Gradle "jobs" are many, is annoying go to the specific "Job" - Consider "Job" the Maven's Goal or Gradle's Tasks

It happens currently for `Version: 4.20.0.RELEASE`

Currently is possible select and copy manually the `Location` value, but if the path is long it is lightly complicated because is mandatory move the cursor to the right (exists a horizonal scrollbar too). Other approach is do right click in the project and select either `Show In` or `Show in Local Terminal` ... But if is need it the external Terminal (not within the IDE) the _complete path_ is need it.

Thanks for your understanding.

**Comment by martinlippert** [comment]
I fully agree, something like this would be extremely useful, but the implementation would most likely belong to the platform project, so should be raised against https://github.com/eclipse-platform/eclipse.platform.ui.

@manueljordan Would you be up for raising this over there and post a link to the newly raised issue here?

**Comment by manueljordan** [comment]
Hello @martinlippert

Yes, of course.
