### ISSUE TITLE
VS Code - Document dependency on the Red Hat Language Support for Java

### ISSUE THREAD

**Issue by ThomasVitale** [spring-projects/sts4#1131]
**Expected Behavior**

The documentation should include that the Spring Boot Tools extension in Visual Studio Code has a dependency on the Red Hat Language Support for Java extension.

**Current Behavior**

When installing the Spring Boot Tools extension in Visual Studio Code, the Red Hat Language Support for Java extension is also installed, but that behaviour is not documented.

**Context**

Example of how the Spring Boot Dashboard extension documents a dependency on another extension: https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-spring-boot-dashboard

**Comment by BoykoAlex** [comment]
Hope this all that was needed for this: 2b3daff5dee07e65b6f0895ff0c853378d7aedef
