### ISSUE TITLE
spring boot tools extension not activated automatically

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#1150]
I have started with a new window in VSCode, went to the Welcome guide for Spring, selected to import a sample project (petclinic), and opened it. It all shows up nicely and the Java tooling just works, but there is no "classpath notification" event showing up in the log and I don't see the Spring Tools being activated. Opening a Java source file doesn't change this, there is only Java stuff showing up in the outline section, etc.

When I activate the Spring Dashboard perspective, our extension does get activated and everything shows up just nicely. But I think our extension should be activated right away.

**Comment by martinlippert** [comment]
I need to correct myself, all the Spring Tools features do NOT show up nicely. No symbols, nothing. Seems to be something serious is broken here...

**Comment by martinlippert** [comment]
Doesn't seem to be reproducible unfortunately... Will continue to observe this while doing other things...

**Comment by martinlippert** [comment]
I see this happening when I start the extension from source code in VSCode itself every time. Not sure if it is the same problem or a different one, but probably worth investigating.

**Comment by BoykoAlex** [comment]
I couldn't see any issues with connecting VSCode to Boot LS. Perhaps there is somwthing about the java runtime starting the server... what's the boot ls log?

**Comment by martinlippert** [comment]
It looks like the extension is not activated (for some reason), so there is no output created for the extension. The "Extension Host" output reveals that the extension is not activated.

When I click on the dashboard icon in the sidebar, it gets activated:

```
[info] ExtensionService#_doActivateExtension vmware.vscode-spring-boot, startup: false, activationEvent: 'onView:spring.apps', root cause: vscjava.vscode-spring-boot-dashboard
```

I also See this (not sure if this is related or not):

```
[info] Extension 'vmware.vscode-spring-boot' uses a document selector without scheme. Learn more about this: https://go.microsoft.com/fwlink/?linkid=872305
```

**Comment by martinlippert** [comment]
Ok, I found the reason for my special case: The extension JARs for the Java language server that I had in the `jars` directory were totally outdated and therefore didn't fire off the activation command that our extension waits for to startup the language server. Now that I updated the JARs, this scenario works nicely again.

Probably fine to close this issue as works as designed then.
