### ISSUE TITLE
Cannot navigate to file in ProjectExplorer from Compare view out of search results

### ISSUE THREAD

**Issue by pgutsa** [spring-projects/sts4#1152]
1. Search for files containing a common text string 
2. Select two files in Search Results
3. Call for "Compare with each other" using context menu on right click
4. See the compare view of two files in two panels
5. Right click inside one of the panels and choose "Show in Project Explorer" in the context menu
6. Selection in the Project Explorer trees goes to the last known location
=> Expected: the Project Explorer tree expands on the node which contains the file from the search results and the file is highlighted

Spring Tool Suite 4 

Version: 4.20.0.RELEASE
Build Id: 202309081654
Revision: 53f375c563505640d3065501ac290f0e3663359c

**Comment by BoykoAlex** [comment]
Have you tried this in plain Eclipse? It seems very much as Eclipse issue rather than STS as we don't mess with Eclipse UI much anymore.

**Comment by martinlippert** [comment]
The behavior in a plain Eclipse installation seems to be the same, so the issue should most likely be reported against https://github.com/eclipse-platform/eclipse.platform.ui
