### ISSUE TITLE
Check for update fails

### ISSUE THREAD

**Issue by MahatmaFatalError** [spring-projects/sts4#1156]
**Describe the bug**
Check for update fails:
![image](https://github.com/spring-projects/sts4/assets/776825/949705a4-9769-457e-81ab-c35cf96cfb55)

```
Cannot complete the install because of a conflicting dependency.
  Software being installed: Eclipse Help System 2.3.1600.v20231201-0110 (org.eclipse.help.feature.group 2.3.1600.v20231201-0110)
  Software currently installed: Spring Tool Suite 4 4.21.0.202312011804 (org.springframework.boot.ide.branding.sts4 4.21.0.202312011804)
  Only one of the following can be installed at once: 
    Internet Connection Management 1.5.200.v20231106-1240 (org.eclipse.core.net 1.5.200.v20231106-1240)
    Internet Connection Management 1.5.100.v20230630-1232 (org.eclipse.core.net 1.5.100.v20230630-1232)
  Cannot satisfy dependency:
    From: Eclipse Help System 2.3.1600.v20231201-0110 (org.eclipse.help.feature.group 2.3.1600.v20231201-0110)
    To: org.eclipse.equinox.p2.iu; org.eclipse.core.net [1.5.200.v20231106-1240,1.5.200.v20231106-1240]
  Cannot satisfy dependency:
    From: Eclipse Platform 4.29.0.v20230903-1000 (org.eclipse.platform.feature.group 4.29.0.v20230903-1000)
    To: org.eclipse.equinox.p2.iu; org.eclipse.core.net [1.5.100.v20230630-1232,1.5.100.v20230630-1232]
  Cannot satisfy dependency:
    From: Spring Tool Suite 4 4.21.0.202312011804 (org.springframework.boot.ide.branding.sts4 4.21.0.202312011804)
    To: org.eclipse.equinox.p2.iu; org.eclipse.platform.feature.group [4.29.0.v20230903-1000,4.29.0.v20230903-1000]
```

Version: 4.21.0.RELEASE
Build Id: 202312011804
Revision: 37b067849b907f022f6dabc8a04af38bbf291249

**To Reproduce**
I only enabled the following update sites:
https://cdn.spring.io/spring-tools/release/TOOLS/sts4/update/latest

Then I also added but does not solve the problem.
https://download.eclipse.org/releases/latest
https://download.eclipse.org/eclipse/updates/latest

**Comment by martinlippert** [comment]
This looks like the main Spring Tool Suite 4 feature that you have installed is the one from the 4.21.0 release, but the one that was build for the Eclipse 4.29 base version, not the one for the latest Eclipse 4.30 version. That mixture of base Eclipse versions causes issues in the update process:

- STS4 branding feature requires base platform 4.29
- base platform 4.29 requires a specific version of `org.eclipse.core.net`
- but the update site tries to update the help system to the version of 4.30, but that requires a different version of `org.eclipse.core.net`

I can't see why you ended up in this situation. I can't reproduce it by installing a fresh STS 4.21.0 for Eclipse 4.30 and running a `Check for Updates`. The best (and easiest) solution for this is probably to start with a fresh STS 4.21.0 release installation.
