### ISSUE TITLE
The application “SpringToolSuite4.app” can’t be opened.

### ISSUE THREAD

**Issue by MahatmaFatalError** [spring-projects/sts4#1158]
Following the recommendation to start from a new installation, I installed STS4 and also a few plugins. Everything worked.

Now, after a reboot, STS does not start anymore: The application “SpringToolSuite4.app” can’t be opened.

I know that it is nearly impossible to figure out what is the root-cause from the outside, but do you have hints how I can debug the error or where to check for logs?

STS 4.21.0.
macOS 14.2

**Comment by martinlippert** [comment]
You could start the IDE from the command line from within the `Contents/MacOS` directory by running the executable in that directory. My hope would be that this shows a lot of log output that might point at the issue.

In addition to that you could also list the additional plugins that you installed with their origin here, so that we could try to reproduce this as well.

**Comment by MahatmaFatalError** [comment]
Thanks for the tip, executing via CLI did not help, I also see no logs
```shell
❯ ./SpringToolSuite4
[1]    39940 killed     ./SpringToolSuite4
```

I had the following plugins installed:

1. https://marketplace.eclipse.org/content/jautodoc
2. https://marketplace.eclipse.org/content/macos-eclipse-launcher
3. https://marketplace.eclipse.org/content/copilot4eclipse
4. https://marketplace.eclipse.org/content/pitclipse
5. https://marketplace.eclipse.org/content/moreunit
6. https://marketplace.eclipse.org/content/spotbugs-eclipse-plugin
7. https://marketplace.eclipse.org/content/eclemma-java-code-coverage
8. https://projectlombok.org/setup/eclipse

Since Eclipse has a problem accessing ENV variables, I needed to set LSEnvironment in Info.plist
```xml
<key>LSEnvironment</key>
<dict>
    <key>mykey</key>
    <string>myvalue</string>
</dict>
```
and run `/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -v -f /Applications/SpringToolSuite4.app` according to http://sjgpsoft.blogspot.com/2018/10/eclipse-and-environment-variables-in.html (I am doing this for years since this setting gets erased with every Eclipse update)

**Comment by MahatmaFatalError** [comment]
I found the cure: `sudo codesign --force --sign -  /Applications/SpringToolSuite4.app`
I have no idea why the codesigning was broken after the reboot, but now the app starts again
