### ISSUE TITLE
 Spring Boot configuration property auto-completion does not offer properties on super classes

### ISSUE THREAD

**Issue by yl-yue** [spring-projects/sts4#116]
[Details of specific issues #186](https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/issues/186#issuecomment-430939320)

Please click the link above to jump.

Sorry！Please excuse my laziness

**Comment by martinlippert** [comment]
@kdvolder can you have a look?

**Comment by kdvolder** [comment]
I think we have ticket for this already, but it is in old spring ide repo: https://github.com/spring-projects/spring-ide/issues/315

**Comment by kdvolder** [comment]
We should probably close one of two tickets as a duplicate. Perhaps its most logical to keep this one because it has to be fixed in the boot language server which is a component of STS 4.

**Comment by kdvolder** [comment]
Note: this applies to both .yml and .properties files. So a fix should make sure it works in both contexts.
