### ISSUE TITLE
process shows up twice when changing log levels of running app

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#1164]
After invoking the `Spring Boot: Set Log Levels` action from the command palette, the running Spring Boot app that is already connected to the live hovers system shows up twice.

In the regular `Manage Live Spring Boot Process Connections` menu, there is two items for the running and connected app as well, but those two items serve a different purpose: Refresh and Disconnect. Looks like the log levels quick pick re-uses a similar logic, but seems to ignore the fact that it is all about the same process.

**Comment by BoykoAlex** [comment]
Fixed with 39bad4f173f7bc35bf8c27f4d0d84b7e55a0394d
