### ISSUE TITLE
upgrade command shows different recipes than quick fixes

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#1165]
Invoking the upgrade command from the command palette offers an upgrade to Spring Boot 3.1, even though there is an upgrade to 3.2 already available. Compared to that, the problems view correctly shows the marker for the new major version 3.2 and offers the 3.2 upgrade recipe.

**Comment by BoykoAlex** [comment]
Yes, this is sort of expected because i didn't filter 3.1 out yet... good idea to hide it since 3.2 is there.

**Comment by BoykoAlex** [comment]
Hopefully fixed with 0da07527d66678316ab827ce3ebeb76696ffc9c7
