### ISSUE TITLE
Installation of sts4 for eclipse through script #103

### ISSUE THREAD

**Issue by sameerhr84** [spring-projects/sts4#117]
This is in continuation of issue #103. https://github.com/spring-projects/sts4/issues/103
I am not able to reopen #103 hence creating a new issue

Thank you for the response and the pointer. I am using 2018-09 version. I tried the feature id's that you had shared and is failing on installation with below error. Please help to review this.

Command tried :

eclipsec.exe -nosplash -application org.eclipse.equinox.p2.director -repository http://download.springsource.com/release/TOOLS/sts4/update/latest/ -installIU org.springframework.boot.ide.main.feature.feature.group,org.springframework.tooling.boot.ls.feature.feature.group,org.springframework.tooling.cloudfoundry.manifest.ls.feature.feature.group,org.springframework.tooling.cloudfoundry.manifest.ls.integration.feature.feature.group,org.springframework.tooling.bosh.ls.feature.feature.group,org.springframework.tooling.concourse.ls.feature.feature.group,org.springsource.ide.eclipse.commons.quicksearch.feature.feature.group,org.springframework.ide.eclipse.boot.dash.feature.feature.group

Error message:

!SESSION 2018-10-18 08:21:59.619 -----------------------------------------------
eclipse.buildId=4.9.0.I20180906-0745
java.version=1.8.0_181-1-ojdkbuild
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments: -product org.eclipse.epp.package.java.product -application org.eclipse.equinox.p2.director -repository http://download.springsource.com/release/TOOLS/sts4/update/latest/ -installIU org.springframework.boot.ide.main.feature.feature.group,org.springframework.tooling.boot.ls.feature.feature.group,org.springframework.tooling.cloudfoundry.manifest.ls.feature.feature.group,org.springframework.tooling.cloudfoundry.manifest.ls.integration.feature.feature.group,org.springframework.tooling.bosh.ls.feature.feature.group,org.springframework.tooling.concourse.ls.feature.feature.group,org.springsource.ide.eclipse.commons.quicksearch.feature.feature.group,org.springframework.ide.eclipse.boot.dash.feature.feature.group
Command-line arguments: -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product -application org.eclipse.equinox.p2.director -repository http://download.springsource.com/release/TOOLS/sts4/update/latest/ -installIU org.springframework.boot.ide.main.feature.feature.group,org.springframework.tooling.boot.ls.feature.feature.group,org.springframework.tooling.cloudfoundry.manifest.ls.feature.feature.group,org.springframework.tooling.cloudfoundry.manifest.ls.integration.feature.feature.group,org.springframework.tooling.bosh.ls.feature.feature.group,org.springframework.tooling.concourse.ls.feature.feature.group,org.springsource.ide.eclipse.commons.quicksearch.feature.feature.group,org.springframework.ide.eclipse.boot.dash.feature.feature.group

!ENTRY org.eclipse.equinox.p2.director 4 10053 2018-10-18 08:22:04.294
!MESSAGE Cannot complete the install because one or more required items could not be found.
!SUBENTRY 1 org.eclipse.equinox.p2.director 4 0 2018-10-18 08:22:04.294
!MESSAGE Software being installed: Cloud Foundry Manifest Language Server Feature 4.0.0.201809220747 (org.springframework.tooling.cloudfoundry.manifest.ls.feature.feature.group 4.0.0.201809220747)
!SUBENTRY 1 org.eclipse.equinox.p2.director 4 0 2018-10-18 08:22:04.295
!MESSAGE Missing requirement: SpringSource Tool Suite (Core) 3.9.6.201809180630-RELEASE (org.springsource.ide.eclipse.commons.core 3.9.6.201809180630-RELEASE) requires 'osgi.bundle; org.apache.commons.collections 0.0.0' but it could not be found
!SUBENTRY 1 org.eclipse.equinox.p2.director 4 1 2018-10-18 08:22:04.295
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 0 2018-10-18 08:22:04.295
!MESSAGE From: Cloud Foundry Manifest Language Server 1.0.0.201809220747 (org.springframework.tooling.cloudfoundry.manifest.ls 1.0.0.201809220747)
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 0 2018-10-18 08:22:04.295
!MESSAGE To: osgi.bundle; org.springframework.tooling.ls.eclipse.commons 4.0.0
!SUBENTRY 1 org.eclipse.equinox.p2.director 4 1 2018-10-18 08:22:04.295
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 0 2018-10-18 08:22:04.295
!MESSAGE From: Cloud Foundry Manifest Language Server Feature 4.0.0.201809220747 (org.springframework.tooling.cloudfoundry.manifest.ls.feature.feature.group 4.0.0.201809220747)
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 0 2018-10-18 08:22:04.295
!MESSAGE To: org.eclipse.equinox.p2.iu; org.springframework.tooling.cloudfoundry.manifest.ls [1.0.0.201809220747,1.0.0.201809220747]
!SUBENTRY 1 org.eclipse.equinox.p2.director 4 1 2018-10-18 08:22:04.295
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 0 2018-10-18 08:22:04.295
!MESSAGE From: Eclipse Language Server Commons 4.0.0.201809220747 (org.springframework.tooling.ls.eclipse.commons 4.0.0.201809220747)
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 0 2018-10-18 08:22:04.295
!MESSAGE To: osgi.bundle; org.springsource.ide.eclipse.commons.core 0.0.0

**Comment by martinlippert** [comment]
Don't worry about not being able to re-open the issue, I will do that as soon as you add more comments and make it obvious that this issue is not yet resolved. Lets continue this on the original issue #103. So re-opening #103 and closing this one... :-)
