### ISSUE TITLE
[Concourse] `set_pipeline` step considers `team` attribute invalid

### ISSUE THREAD

**Issue by 9numbernine9** [spring-projects/sts4#1174]
**Describe the bug**
The Concourse VS Code extension considers the `team` attribute of the `set_pipeline` step to be invalid. [As per the docs](https://concourse-ci.org/set-pipeline-step.html), this is a valid attribute. 

**To Reproduce**
- Create a `set_pipeline` step
- Add a `team` attribute

**Sample**
![image](https://github.com/spring-projects/sts4/assets/2762274/369fc00b-7a53-4148-ad4c-b12f981fd3d9)

**Comment by BoykoAlex** [comment]
Should be fixed with 48fcde87e3cbbfc1f6bec2e1c4da830ea451a37b

**Comment by 9numbernine9** [comment]
Thanks for the quick fox!

**Comment by martinlippert** [comment]
@9numbernine9 In case you don't want to wait for the next release of the plugin, you could switch to the pre-release in VSCode until the next release comes out.
