### ISSUE TITLE
spring tool 3 add on not downloading

### ISSUE THREAD

**Issue by Abhi-2023** [spring-projects/sts4#1175]
**Expected Behavior**

**Current Behavior**

**Context**

**Comment by martinlippert** [comment]
The Spring Tools 3 Add-On is no longer maintained and no longer compatible with the latest versions of the Spring Tools 4 for Eclipse distribution nor the latest releases of the Eclipse IDE.

The final version of the Spring Tools 3 Add-On was made available for the Spring Tools 4.14.1 release for Eclipse 2022-03 and that version is still available on the Eclipse marketplace, but only for those older Eclipse platform versions.

**Comment by martinlippert** [comment]
Is there any specific reason why you want to download and install the Spring Tools 3 Add-On? Is there anything specific missing from the Spring Tools 4 that you would like to see ported over from the Spring Tools 3?

**Comment by Abhi-2023** [comment]
Yeah I was learning how spring boot works behind the scenes. Such like
application context


As the spring bean configuration file option is not showing.. I googled it
and there was solution to download the specific software.. but it's not
downloading.


Due to this there is an obstacle while learning the concept

**Comment by martinlippert** [comment]
@Abhi-2023 Using Spring XML configuration files is not really the preferred way to use Spring nowadays. It is still possible and supported by the underlying frameworks, but in case you are learning about Spring and Spring Boot (and how things work behind the scenes), I would recommend to get started with some nice and easy-to-use samples, for example from https://spring.io/guides.

Spring Petclinic is an obvious nice sample application. I would also recommend this session from the Spring team: https://www.youtube.com/watch?v=jDchAEHIht0

From within the IDEs, you can easily get guides imported or get the Petclinic sample project, run them, and debug through them to take a look at the internals.

If you nevertheless would like to dive into Spring XML config files, you can just create those files as regular XML files in the tools, paste some sample Spring XML configs in there and go.

**Comment by Abhi-2023** [comment]
Thanks, I'll check it out.
