### ISSUE TITLE
4.21.1 release doesn't embed JDK anymore

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#1187]
The JustJ JDK that we usually ship pre-installed into the Eclipse based distribution is not there anymore. It is also missing from the snapshot builds (so probably nothing specific to the release build).

This causes the launcher to pick up a (more or less) random JDK or does nothing if it can't find a pre-installed JDK (like in a new machine). In my case, I have a few JDKs installed via sdkman, but that only works if I launch STS from the command line. Double clicking the app icon doesn't work anymore.

**Comment by martinlippert** [comment]
I haven't noticed this during the regular release testing probably because the launcher picked up a JDK from my machine that was around, which is not the case anymore on a different machine. We need to fix this to make sure that the IDE runs on the JDK that we embed and not a random other one.

**Comment by martinlippert** [comment]
A few more observations from looking into this:
- The JDK is not embedded anymore in macOS only. The Linux and Windows builds still includes the JDK.
- The build logs indicate that the installation of the JustJ feature happens for all five platform builds and completes fine.
- Running the build locally also results in the JDK being included.

I have no idea yet why the distributions for macOS that you download from the nightly download page do not include the JDK anymore (same for the 4.21.1 release). Strange...

**Comment by BoykoAlex** [comment]
Fixed with: aa250f7fadff78bdc2d6d5294d854f99803fcf47
Installed JustJ into `.app/Contents/Eclipse` - worked fine in both Ubuntu and OSX (via local build), therefore, decided to go ahead with this solution (i.e. without platform specific paths)
