### ISSUE TITLE
STS 4.21.1 x86_64 starts failure at MACOS 12.7, but 4.21.0 works, openjdk8

### ISSUE THREAD

**Issue by Jeanvixue** [spring-projects/sts4#1198]
**Describe the bug**
STS 4.21.1 starts failure at MACOS 12.7, but 4.21.0 works. No more information can get, App Icon jumps for 3-4 seconds, and quit.

**Comment by BoykoAlex** [comment]
Likely your facing consequences of #1187 - it was an issue on mac specifically, no embedded JDK was added to the distro.
The workaround is install JDK 17 or 21 on you system and add `-vm <path to JDK home folder>` in `/Applications/STS.app/Contents/Eclipse/SpringToolSuite4.ini`

**Comment by Jeanvixue** [comment]
> Likely your facing consequences of #1187 - it was an issue on mac specifically, no embedded JDK was added to the distro. The workaround is install JDK 17 or 21 on you system and add `-vm <path to JDK home folder>` in `/Applications/STS.app/Contents/Eclipse/SpringToolSuite4.ini`

-vmargs
-vm /usr/local/Cellar/openjdk@17/17.0.10/bin
--add-opens=java.base/java.io=ALL-UNNAMED
can't work follow your instruction

**Comment by martinlippert** [comment]
> > Likely your facing consequences of #1187 - it was an issue on mac specifically, no embedded JDK was added to the distro. The workaround is install JDK 17 or 21 on you system and add `-vm <path to JDK home folder>` in `/Applications/STS.app/Contents/Eclipse/SpringToolSuite4.ini`
> 
> -vmargs -vm /usr/local/Cellar/openjdk@17/17.0.10/bin --add-opens=java.base/java.io=ALL-UNNAMED can't work follow your instruction

Please add

```
-vm
/usr/local/Cellar/openjdk@17/17.0.10/bin/java
```

as the first lines in your SpringToolSuite4.ini file. Don't inject this into the file after the -vmwargs, that section should remain unchanged. Also make sure to have `-vm` and the path to the java executable in two separate lines.

**Comment by Jeanvixue** [comment]
It works now, thanks.
