### ISSUE TITLE
adjustments to version validations

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#1199]
Adjustments to the version and support ranges include:

- change the default severity of the "out-of-oss-support" diagstic to `WARNING`
- change the default severity of the "out-of-commercial-support" diagnostic to `WARNING`

In addition to that, I would like to point users to the option of extending the support if they are running out of OSS support, but commercial support is possible.

- (1)  change the wording of the "out-of-oss-support" diagnostic to `OSS support for Spring Boot 2.7.x ended on 2023-11-18, get commercial support until 2025-11-18 via Tanzu Spring Runtime at https://tanzu.vmware.com/spring-runtime` (in case this is within the commercial support range)

- (2) keep the wording of the "out-of-oss-support" diagnostic to `OSS support for Spring Boot 2.7.x ended on 2023-11-18` (in case this is outside the commercial support range)

If possible, we could also offer a quick fix for (1) with the title  `get commercial Spring Boot support via Tanzu Spring Runtime`, which then opens the above mentioned URL.

**Comment by BoykoAlex** [comment]
@martinlippert for (1):
Should the `get commercial support until 2025-11-18 via Tanzu Spring Runtime at https://tanzu.vmware.com/spring-runtime` text be part of the validation problem text? Or should this only be present in the quick fix text as `Get commercial support until 2025-11-18 via Tanzu Spring Runtime`

**Comment by martinlippert** [comment]
> @martinlippert for (1): Should the `get commercial support until 2025-11-18 via Tanzu Spring Runtime at https://tanzu.vmware.com/spring-runtime` text be part of the validation problem text? Or should this only be present in the quick fix text as `Get commercial support until 2025-11-18 via Tanzu Spring Runtime`

It should be part of the validation problem text as well.

**Comment by BoykoAlex** [comment]
Should be fixed with 387e8b1a9b70cb66f378c56a253b60d58602bc8d and 1b148dec76e7ca704ab4706637f453728b2b4555
