### ISSUE TITLE
change the actions to refresh live information to show application right away

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#1204]
At the moment, the way users can update live information in their VSCode environment is to invoke the command `Spring Boot: Manage Live Spring Boot Process Connections`, which is somewhat weird if all you are looking for is to disable or to refresh the live information.

We should remove this "all-in-one" command and replace it with specific commands for the specific actions, like `Show Live Information` (which allows you to connect to a running Spring Boot app), `Refresh Live Information`, which either just calls the fresh command if there is only one app connected to live information or shows a quick pick for the connected processes if there are multiple processes connected and showing live information, and `Hide Live Information` (for disconnecting, with the same logic as the refresh command with regards to one vs. multiple processes connected).

**Comment by BoykoAlex** [comment]
Fixed with eb3d46d400fdb777f0d7ac4016ce065da4bd632b as discussed
