### ISSUE TITLE
provide preference to open code lens URLs in simple browser

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#1207]
Add a preference to choose where to open URLs from code lenses. At the moment, the browser from your operating system is launched externally to show the URL. The spring dashboard in VSCode opens the URLs of request mappings in a `Simple Browser` in VSCode directly.

We should add a preference to allow users to define where to open these URLs (from code lenses) and add the option to open them in a simple browser inside of VSCode.

**Comment by BoykoAlex** [comment]
CodeLenses is the tip of the iceberg... I have implemented the setting for CodeLenses but there are other means of opening requst mappings URLs via symbols and hovers. Not sure how to deal with symbols at all yet... The hovers seem to support a link that executes a command but looks like this is in VSCode only... Seems more difficult than i was hoping for ;-)

**Comment by martinlippert** [comment]
I don't think we need to align everything here. If we directly control the "open browser" activity, let's use the preference to allow users to choose between the external and the internal simple browser. If we do not control the action to open a browser, let's not invest a lot of time into working around that.

**Comment by BoykoAlex** [comment]
VSCode hovers are also supported via 1883cebe235a06a372beb1d20320fb01a3462a4f
