### ISSUE TITLE
inlay hint in pom.xml file to upgrade to latest Spring Boot version

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#1211]
We could show an inlayHint (similar to the edit starters inlay hint) right aside of the spring boot parent starter version to upgrade to the latest spring boot version - in case there is a newer patch version.

Initial version of this could focus on upgrading to latest patch version with one click. Later versions could offer more (different inlay hints) to execute the upgrade recipe for minor or major upgrades.

**Comment by BoykoAlex** [comment]
Fixed with 0300cded42a1b403f4caef76c5cc96460e0c056d
