### ISSUE TITLE
I really need spring config editor. Help me

### ISSUE THREAD

**Issue by callor** [spring-projects/sts4#1214]
You really need the Spring config editor in STS 4.
I am creating Spring Legacy MVC in STS 4.
everything else is ok
However, I am having a lot of trouble creating the Spring Bean Configuration file.
Can you create a plugin so that I can use Spring Config Editor in STS 4?

Thank you so much

**Comment by martinlippert** [comment]
Please have a look at https://github.com/spring-projects/sts4/issues/1163. There you can also find a quick description of the recently added support for this and how to enable that.
