### ISSUE TITLE
Error while installing STS 4.4

### ISSUE THREAD

**Issue by singha36** [spring-projects/sts4#1217]
**Describe the bug**
Someone have uploaded wrong file at STS downloading link.

**To Reproduce**
Steps to reproduce the behavior.

Replace the PDF file with Installation file. When we download, it download a pdf file instead of installer file.

https://spring.io/tools
After Selecting 4.22.0 Windows [x86_64]
![Screenshot (5)](https://github.com/spring-projects/sts4/assets/156675861/8961b873-81cf-489a-a98a-c2529643f3e6)

**Comment by martinlippert** [comment]
I have verified that the download location on https://spring.io/tools provides the correct, self-extracting JAR file. Maybe a proxy server in between your machine and the network alters the file?
