### ISSUE TITLE
Extract to local variable, replace all occurrences broken

### ISSUE THREAD

**Issue by mtran-ces** [spring-projects/sts4#1218]
Spring Tool Suite 4 

Version: 4.22.0.RELEASE
Build Id: 202403071427
Revision: 44291b464093d161f115d8e16059e5272ed3c81d

**Describe the bug**
When attempting to refactor by extracting to local variable and replace all occurrences, it skips the all occurrences part.

**To Reproduce**
example code to refactor
```
foo.bar().me();
foo.bar().you();
```
highlight foo.bar() on first line, use quickfix menu, select extract to local variable (replace all occurrences)

only replaces the first line and ignores the second

**Sample**

sorry no sample

**Comment by BoykoAlex** [comment]
I think this should be reported to Eclipse JDT project as this is not an STS refactoring...

**Comment by mtran-ces** [comment]
No problems, I can do that. How do I work out what version of Eclipse this STS is using? I don't seem to see anything in the about box.

**Comment by BoykoAlex** [comment]
It is probably 4.31 (2024-03). Find "About SpringToolSuite4" menu item in the top level menu. It is either under Help top level menu or under SpringToolSuite4 top level menu for mac.

Open it, click on "Installation Details" and then in the features tab find Eclipse Platform

![Screenshot 2024-04-02 at 20 35 16](https://github.com/spring-projects/sts4/assets/6433390/c7803971-1079-457f-97f1-efa9846fa4a5)

This is an example of 4.30 version of Eclipse

**Comment by mtran-ces** [comment]
@BoykoAlex many thanks!
