### ISSUE TITLE
[Question] Any consideration of supporting Java Platform Extension

### ISSUE THREAD

**Issue by gayanper** [spring-projects/sts4#1223]
Given that oracle is now releasing a vscode extension with thin Netbeans LS module, is there a plan to change this extension so that it can either run this JDT.LS or NB.LS by providing the shim layer to convert the expectations of JDT.LS from NB.LS ?

I know some time back I did something similar to get the STS4 LS support in IntelliJ CE with a community LS Client plugin implementation for IntelliJ CE. But here can we do the same other way around where we add a provide the required language information from NB.LS instead o JDT.LS ?

cc: @martinlippert @BoykoAlex

**Comment by martinlippert** [comment]
Closing this as a duplicate of https://github.com/spring-projects/sts4/issues/1132. Happy to continue the conversation over there. If someone from that team is interested in opening up their implementation for an extension like the Spring Tools, happy to collaborate.
