### ISSUE TITLE
Show active profiles in Boot Dash

### ISSUE THREAD

**Issue by BoykoAlex** [spring-projects/sts4#1225]
VSCode Boot Dashboard is going to have active profiles shown

The same would be useful for Eclipse. If Live Data is available then profiles should be obtained from the Live Data. Furthermore, Eclipse Boot Dash local elements correspond to launch configs which might have a profile set in the launch config boot tab - this is should be the profile displayed if launch config isn't running.

(See https://github.com/microsoft/vscode-spring-boot-dashboard/pull/321)

**Comment by BoykoAlex** [comment]
This should be addressed with: 9cd237b97afcf4c4d271513d6cb8634548a64898 Please have a look at a snapshot build @martinlippert - feedback is welcomed.

**Comment by martinlippert** [comment]
Looks great!!!
