### ISSUE TITLE
'var' is not allowed here Java Problem in STS4 with Java 11

### ISSUE THREAD

**Issue by jerelw** [spring-projects/sts4#123]
I installed the Java 11 support plug-in, and am unable to compiled classes using vars.

**Comment by kdvolder** [comment]
Works for me. I am guessing some of your projects settings are such that its compiler compliance and/or classpath are telling Eclipse to use an older JRE. If you don't think that is the case please provide exact steps to reproduce the problem and we can reopen this ticket.

![java-11-works-for-me](https://user-images.githubusercontent.com/1002156/47443511-51e06b00-d769-11e8-8a7e-15476f390340.png)
