### ISSUE TITLE
show a nice message when trying to change log levels without a connected running app

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#1232]
If there is no live data or connection for live data for a running Spring Boot app around, the command to change log levels shows up just empty. It is understandable that there is no quick pick list showing up (since there is no launched app), but it would be nice to let the user know that this is the case, maybe via some greyed out message in the text field.

**Comment by BoykoAlex** [comment]
Fixed with cb9c438bc8d3a8c3369d8204297aef1d01dee2b4

**Comment by BoykoAlex** [comment]
I've decided to popup the info message and hide the quick pick. However, we can leave the quick pick open and have the title of the quickpick showing "No running Spring Boot Apps Found" or have both: the quickpick still showing and the info message popup... Ot just the quickpick showing.
The greyed out text in the quickpick is the **placeholder**... o ne can type in there, once something is typed the placeholder text is gone hence i'd not use that.

**Comment by BoykoAlex** [comment]
This should show the same message in log levels UI: 9b60d60035aae214f3101d93b26d1b65d1bb0f97

**Comment by martinlippert** [comment]
LGTM
