### ISSUE TITLE
SpEL Syntax Highlighting

### ISSUE THREAD

**Issue by BoykoAlex** [spring-projects/sts4#1234]
SpEL syntax highlighting via LSP semantic tokens inside:
- Java annotations
- Inside JPQL queries

**Comment by BoykoAlex** [comment]
Fixed with 15f20b6f9d7c46781cc972f5b3847b52bec27c64 exceptfor embedded inside SQL queries which is be addressed via #1270

**Comment by MahatmaFatalError** [comment]
@BoykoAlex could you please share a sample screenshot how the syntax highlighting looks like for SpEL? I am not sure if it works for me

**Comment by BoykoAlex** [comment]
![Screenshot 2024-08-05 at 10 49 40](https://github.com/user-attachments/assets/3e5bd61a-b0be-430c-bb6f-587c21064c2b)

Something like the above.

What are you getting @MahatmaFatalError ? Send a screenshot and a snippet please.

**Comment by MahatmaFatalError** [comment]
ah ok, only VSCode, the release notes https://github.com/spring-projects/sts4/releases/tag/4.24.0.RELEASE lead to the impression that it is generally available, i.e. including eclipse

**Comment by martinlippert** [comment]
@MahatmaFatalError Totally agree, the release notes should be more precise about this. I added a section here https://github.com/spring-projects/sts4/issues/1235. Thanks again for pointing us at this.
