### ISSUE TITLE
improve parser-based validation for SpEL snippets

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#1237]
At the moment, the validation logic for SpEL expressions is pretty simple using the standard SpEL parser that comes with Spring itself. If the parser reports a problem while parsing, this problem is reported as a diagnostic for the whole expression.

The goal is to use a more sophisticated diagnostics detection for SpEL expressions and report more fine grained and detailed diagnostics. Maybe we need to adopt an ANTLR-based parser for this (instead of the standard SpEL parser), but that depends on the features the parser offers for this more detailed diagnostics.

**Comment by BoykoAlex** [comment]
Hopefully fixed with 15f20b6f9d7c46781cc972f5b3847b52bec27c64 exceptfor embedded inside SQL queries which is be addressed via #1270
