### ISSUE TITLE
`Map<K,V>` with escaped key not works properly in `application.yml`

### ISSUE THREAD

**Issue by musashi-miyamoto** [spring-projects/sts4#1243]
**Describe the bug**
If map key is escaped string (like `[/**]`), VSCode YAML code completion not works properly.

**To Reproduce**

- Windows 11 23H2 (Build 22631.3447)
- OpenJDK 21.0.2
- Spring Boot v3.2.5
- VSCode v1.88.1
  - Language Support for Java(TM) by Red Hat 1.30.0
  - Spring Boot Tools v1.53.0

Sample configuratin class:
```java
@ConfigurationProperties(prefix = "demo")
public class RootConfig {
    private Map<String, ChildConfig> pathMap;
    // Getters and Setters...
}

public class ChildConfig {
    private String host;
    private int port;
    // Getters and Setters...
}
```

Key without escape works properly:
![image](https://github.com/spring-projects/sts4/assets/44890163/bea41f7d-e7be-4c9c-b23f-0a34ebb9e91e)

Key with escape provides no completion:
![image](https://github.com/spring-projects/sts4/assets/44890163/687761d5-39b5-43fa-a955-80575816484c)

Requires one extra deeper indentation:
![image](https://github.com/spring-projects/sts4/assets/44890163/458d9e13-5c3a-4849-b38d-685264635b18)

Completion provides no `host`, used in previous key:
![image](https://github.com/spring-projects/sts4/assets/44890163/85f4e2e3-a320-42a3-b257-97908cfb0eaf)

**Sample**

https://github.com/musashi-miyamoto/sts4-configuration-issue-reproduce-sample

**Comment by BoykoAlex** [comment]
Fixed with 212dacff69f361ab01dcf1270042f0972b2a8999
