### ISSUE TITLE
lombok stable does not work with sts4

### ISSUE THREAD

**Issue by arjunsekar1991** [spring-projects/sts4#125]
I tried to run the boot project built using sts 3 in sts4 but jackson gives a lot of errors. Please fix this issue.

**Comment by martinlippert** [comment]
Can you describe in more detail what the problem exactly is? And how to reproduce this? And maybe attach a sample project that would help us to reproduce the issue?

**Comment by arjunsekar1991** [comment]
sorry i deep dived  and found out it was lombok which is in compatible with sts 4 / lombok version 1.18.2

**Comment by arjunsekar1991** [comment]
Are there any work around i can use to make lombok stable version to work with sts 4? I think only edge release works
