### ISSUE TITLE
"Code Completion" not work in application.yml file

### ISSUE THREAD

**Issue by youhuiji** [spring-projects/sts4#1253]
![show](https://github.com/spring-projects/sts4/assets/71420071/d37a9a5c-4ca2-475d-a1cc-b62189a81ef6)
 vscode version :1.89.1
spring boot tools version : 1.54

**Comment by BoykoAlex** [comment]
what's the issue? No completions proposals? Did you try pressing Ctrl-Space or Cmd-Space to invoke it?

**Comment by youhuiji** [comment]
> What's the issue? No completions proposals? Did you try pressing Ctrl-Space or Cmd-Space to invoke it? If yes, does it look like a duplicate of #1242 ?

Thank you, I know where the problem lies.
