### ISSUE TITLE
vscode @DependsOn navigation not linked

### ISSUE THREAD

**Issue by lamplification** [spring-projects/sts4#1254]
Spring uses the class name and converts the first letter to lowercase by default.  In vscode, @DependsOn("BEAN_NAME") won't able to find the bean and not able to navigate to DependsOn bean class.  

**To Reproduce**
Create 2 Compoments.
```
@Component 
public class TestBean1 {}
```
```
@Component
@DependsOn("testBean1")
public class TestBean2 {}
```
Notice DependsOn(`testBean1`) is not clickable.  
If it use the class name TestBean1 then that will work, but it won't work during the run time.
```
@Component
@DependsOn("TestBean1")
public class TestBean2 {}
```
[demo.tar.gz](https://github.com/spring-projects/sts4/files/15406766/demo.tar.gz)

**Comment by lamplification** [comment]
@martinlippert , thank you for looking into this.

**Comment by martinlippert** [comment]
Actually, the case with an upper case - `@DependsOn("TestBean1")` in your case - only works by accident due to the Java language tooling itself interpreting this as random string as a class name and searches for that class.

Will add proper support for navigating to the actual referenced bean definition. Just keep in mind that there might be multiple definitions for that bean being found in your project.

**Comment by martinlippert** [comment]
Okay, so navigation support (https://github.com/spring-projects/sts4/commit/7ee4e072233b54d05a67a8c1235cdc3bcd7b2f7d) as well as auto-completion for bean names (https://github.com/spring-projects/sts4/commit/d8e067ad9d36453eefbf0239f0c56b675c58fce4) is in now. Closing this as fixed for upcoming 4.23.0 release.

**Comment by lamplification** [comment]
@martinlippert , thank you for the quick turn around!

**Comment by martinlippert** [comment]
In VSCode, you could switch the extension install over to the pre-release to try this out already, btw.

**Comment by lamplification** [comment]
@martinlippert , I switched to pre-release and that patch works like a charm!  Thank you!

**Comment by martinlippert** [comment]
Awesome, great to hear it works for you. Thanks for the feedback!
