### ISSUE TITLE
STS 4.22.1 - EclEmma Code Coverage not showing.

### ISSUE THREAD

**Issue by auntivirus** [spring-projects/sts4#1259]
Hello everyone,
First time posting.

Can anyone help me out?
It seems that JaCoCo / EclEmma is not showing when I click on a project.

Previous STS4 version: 
Version: 4.21.1.RELEASE

My current STS4 version: 
Version: 4.22.1.RELEASE 
Build Id: 202405011620 
Revision: 71bcc7a580385ea1ae7aa7af1ae8bef30aaea50a

I had updated my STS4 version via **Check For Update** under **Help** section.

I checked with other colleague having 4.21.1.RELEASE version and the **Coverage** option is showing.

No **Coverage** option under Window -> Show View -> Other as well. When clicked on a project, **Coverage** option is missing as well.

![No Coverage option showing](https://github.com/spring-projects/sts4/assets/79374977/b87b46b8-676b-4857-b2cc-d0f80fe2494f)

**Comment by martinlippert** [comment]
Hey @auntivirus, I double checked this and there is indeed a wiring problem going on behind the scenes when you install the EclEmma extension into the latest version of the Spring Tools for Eclipse 4.22.1. Seems like the EclEmma extension is not yet compatible with the latest Eclipse release (2024-03).

STS 4.21.1 is based on Eclipse 2023-12, for which EclEmma seems to work fine.
STS 4.22.1 is based on Eclipse 2024-03, for which EclEmma doesn't seem to work yet.

Therefore, I would recommend to reach out to the maintainers of the EclEmma extension and ask for help.

**Comment by martinlippert** [comment]
See also the discussion on SO: https://stackoverflow.com/questions/78575658/sts-4-22-1-eclemma-code-coverage-not-showing - with a comment mentioning a manual installation of the latest EclEmma version should fix the issue.
