### ISSUE TITLE
JPQL syntax - Support Concatenated Strings

### ISSUE THREAD

**Issue by raulvaldoleiros** [spring-projects/sts4#1262]
## Suggestion

JPQL syntax is a great feature, it would be great if it supports:

- Text blocks
- String concatenation

In the following image you can see that right now isn't supported
![image](https://github.com/spring-projects/sts4/assets/10415832/e554eebf-3d97-4c75-96ca-9f9b50475abe)

Created from [issue](https://github.com/microsoft/vscode-java-pack/issues/1353)

**Comment by zarembo** [comment]
This may be more important than it looks like. The problem is there is no syntax check at all. It just shows nothing. There is not even a warning that no check has been performed.

**Comment by BoykoAlex** [comment]
Fixed with ea033714b47e3d8088a5f6135343743df0369d61
