### ISSUE TITLE
navigation to class of wired bean is broken

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#1268]
Running Petclinic in VSCode, looking at the live hovers of `OwnerController`, then clicking on the link in the hover for the wired bean `OwnerRepository` that shows up as `org.springframework.samples.petclinic.owner.OwnerRepository`. Clicking on that link results in an error message showing up.

<img width="302" alt="image" src="https://github.com/spring-projects/sts4/assets/107705/ee6ca27a-1865-4413-b4ab-6bed47b04e34">

**Comment by martinlippert** [comment]
Maybe related to Side note: maybe this is related to https://github.com/spring-projects/sts4/issues/1269

**Comment by martinlippert** [comment]
Side note: used Spring Boot 2.7.3 in the petclinic project - in case that makes a difference.

**Comment by BoykoAlex** [comment]
Fixed with 5a68303f7d6c4e4e4a61e0710c1b4c5d8ead69ac
