### ISSUE TITLE
navigation to bean class of live bean in dashboard is broken

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#1269]
Clicking on beans on the Spring Dashboard in VSCode when that beans list shows live beans results in an error. This happens for every bean that shows up in the list of live beans.

I used the petclinic sample project.

<img width="485" alt="image" src="https://github.com/spring-projects/sts4/assets/107705/291768b2-0bb4-4ad9-bf91-36aeeae334a1">

Side note: the project used Spring Boot 2.7.3, I haven't tried a newer Spring Boot version yet, maybe that makes a difference.
Side note: maybe this is related to https://github.com/spring-projects/sts4/issues/1268

**Comment by BoykoAlex** [comment]
Looks like the fix to #1268 fixes this as well
