### ISSUE TITLE
Two new changes introduced in version 4.23.0 RELEASE (1.55) is generating false positive errors

### ISSUE THREAD

**Issue by familygw** [spring-projects/sts4#1274]
Hello,

I am experiencing an issue with the latest update to Spring Boot, specifically with the new features introduced for syntax validation and highlighting in Visual Studio Code. The features in question are:

    Syntax validation for JPQL, SQL, and HQL embedded in Java code.
    Syntax highlighting for SQL embedded into Spring Data query annotations.

Since these features were introduced, I've encountered numerous false positives where valid queries are being flagged as errors. This issue seems to primarily affect the development environment in Visual Studio Code.

Steps to Reproduce:
    Write a valid SQL/JPQL query embedded within Java code or Spring Data annotations.
    Observe that the syntax validation incorrectly flags these valid queries as having errors.
<img width="975" alt="image" src="https://github.com/spring-projects/sts4/assets/670078/776c1b7f-6105-479e-857c-43ad964480a1">

<img width="1380" alt="image" src="https://github.com/spring-projects/sts4/assets/670078/6189c9e9-c292-498a-be4d-33222369b96e">

Expected Behavior:
The syntax validation should accurately recognize valid SQL, JPQL, and HQL queries without flagging them as errors.

Actual Behavior:
Valid queries are being incorrectly flagged as errors, leading to unnecessary confusion and hindrance in the development process.

Could you please look into this issue? It seems that the new validation rules might be overly strict or not fully aligned with the actual syntax rules of SQL, JPQL, and HQL.

**Comment by BoykoAlex** [comment]
See https://github.com/spring-projects/sts4/issues/1236#issuecomment-2166001442 to workaround the issue for now.

We are working on the patch release for early next week. Sorry for the inconvenience

**Comment by BoykoAlex** [comment]
@familygw do you mind showing issues with HQL and JPQL? I'm only seeing SQL so far... we can switch off SQL validation by default... wonder if HQL and JPQL need to be switched off by default as well...

**Comment by familygw** [comment]
I performed a downgrade and then updated the component again. Now, I'm only seeing SQL-related errors, with no more HQL errors. I don’t remember seeing any related to JPQL; almost all of them are for SQL (native) queries.

Which setting can I use to disable this validation in the meantime?

**Comment by BoykoAlex** [comment]
@familygw you'd need to use an nightly update site and then look at Settings Spring -> Validation -> Data Query. See https://github.com/spring-projects/sts4/issues/1236#issuecomment-2166001442 for list of nightly build update sites and the setting page screenshot.

**Comment by BoykoAlex** [comment]
Fixed for 4.23.1 which should come out early next week
