### ISSUE TITLE
Incorrect SQL Errors shown in Problems Tab

### ISSUE THREAD

**Issue by TE-Devharajan-Rangarajan** [spring-projects/sts4#1276]
The SQL errors were shown in release 4.23.0.Release for the queries which have a named parameter (eg: where id = :id). This was fixed on 4.23.1.Release however the problems tabs still shows them as errors and will only go away after opening the file.

**To Reproduce**
I have attached the video showing how to reproduce the error. Please look into this.
[Screencast from 18-06-24 02:41:35 PM IST.webm](https://github.com/spring-projects/sts4/assets/19388534/cc5b54fc-b241-422b-8775-32569e6c7fbd)

**Comment by BoykoAlex** [comment]
Go to your `<home folder>/.sts4`. Either wipe everything out or find a file `<project-name>-java-diagnsotics-<HEX-Id>.json` and remove this file. (for example `spring-petclinic-java-diagnostics-2E4FDB31FDF5B6781799C4C881150459.json`)

**Comment by martinlippert** [comment]
This is an oversight on our side to not automatically clean up the old diagnostics with the `4.23.1` release. The workaround is what @BoykoAlex described, future changes will wipe out those stale diagnostics automatically again.
