### ISSUE TITLE
Double-click to quickly launch the springboot project 

### ISSUE THREAD

**Issue by Shiaming** [spring-projects/sts4#1282]
![image](https://github.com/spring-projects/sts4/assets/42745553/775b1ad9-68a7-4f1c-9c68-2f19ded55bad)

**Comment by martinlippert** [comment]
Side note: Double click here would have a different meaning depending on the state of the app:
- inactive: double click - would run the app
- running: double click - opens a browser and jumps to the default url (this is the current behavior)
- starting: double click - no action

**Comment by Shiaming** [comment]
Thank you. I misunderstood

**Comment by Shiaming** [comment]
Thank you. I misunderstood
