### ISSUE TITLE
change name of problem description for "unnecessary web annotation names" validation

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#1301]
At the moment the validation that checks for unnecessary name attribute definitions inside of `@PathVariable` creates a marker that says "Remove Implicit Web Annotation Names", which is a somewhat strange message for a validation. It is more the title of the corresponding quick fix action.

Instead, the validation marker should say something like "Unnecessary Web annotation attribute definition" or "Unnecessary path variable definition" (for the case of `@PathVariable` name attributes).

**Comment by BoykoAlex** [comment]
Fixed
