### ISSUE TITLE
When editing a Spring XML configuration file, the package names and class names do not appear accurately

### ISSUE THREAD

**Issue by batobolg** [spring-projects/sts4#1317]
When editing a Spring XML configuration file, the package names and class names do not appear accurately.

**To Reproduce**
My test project is simple, I have just one package test.java and one Class TestMain.java
when I make a Spring XML configuration file, and edit it like below , it not show up my class name at the top

**Sample**
<img width="1202" alt="image" src="https://github.com/user-attachments/assets/fb6b10cd-02f3-489e-9606-88f7b2b122dc">

the error log is 
<img width="1031" alt="image" src="https://github.com/user-attachments/assets/65e9ad79-e923-46e5-878c-6f4c64e10a8d">

**Comment by martinlippert** [comment]
Looks like the auto completion proposals that show up while trying `test.java.` or somewhat weird and don't fit well. When you invoke auto-completion manually after typing `test.java.`, the proposals are are a much better fit here. Let me investigate this so see what is going on here and how we could improve this.

**Comment by martinlippert** [comment]
I made some changes to the underlying mechanism that produces better results than before. It is still not optimal, for example it doesn't show up class proposals for types that are not public (whereas having a non-public class as bean is totally fine in Spring). But reworking that part requires us to change the way we identify the proposals altogether, so a lot more work.

@batobolg Feel free to give this improved version a try. The snapshot builds will be published here sometime soon: https://cdn.spring.io/spring-tools/snapshot/STS4/nightly-distributions.html

(make sure you grab a build that is older than `4.25.0.202408300825`)
