### ISSUE TITLE
SpEL parsing issue in Query annotation

### ISSUE THREAD

**Issue by elmuerte** [spring-projects/sts4#1320]
**Describe the bug**

I have the following SpEL expression in a `@Query` annotation

```
group by r having count(p) = ?#{[1].size().longValue()}
```

The input parameter is a `Set<String>`.

This produces the following error marker in Eclipse:

> SPEL: extraneous input '[' expecting {'++', '+', '--', '-', '(', '#', '@', '^[', '![', '!', '&', '?[', '$[', LCURLY, 'true', 'false', 'new', 'null', 'T', IDENTIFIER, NUMERIC_LITERAL, STRING_LITERAL}

**To Reproduce**

Create a `@Query` where the value contains a SpEL expression referencing an input parameter, e.g. `?#{[1]}`

I'm using Eclipse 2024-06 with STS 4.24

**Comment by BoykoAlex** [comment]
Fixed with ece638010fdb57f6d273763ec5c61ae158e76d4f
