### ISSUE TITLE
[Spring Data Queries] Show document highlights when the cursor is at query parameter AST node

### ISSUE THREAD

**Issue by BoykoAlex** [spring-projects/sts4#1332]
All Spring Data Query whether it is JPQL/HQL or a native SQL query support parameters coming from java code. Typically `@Query` annotates a method, then `:1` or `?2` found in the query would stand for the first and second parameter of the Java method respectively. It's be useful to show the Java parameter and its usage in Java code once the cursor is at the parameter node (or perhaps when hovering the mouse over that node).
LSP has [Document Highlights](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_documentHighlight) feature that we could try using for this scenario

**Comment by BoykoAlex** [comment]
Fixed with 00636085cadeb624448de8a0c8f2cba41d50dce4. Only highlights method parameter. These methods are inside an interface typically so no need to go through the method body. Works in VSCode but in Eclipse Java editor LSP support is required

**Comment by martinlippert** [comment]
@BoykoAlex Let's track the missing support in the Eclipse Java source editor as a separate issue.

**Comment by martinlippert** [comment]
Feels like we should also cover additional cases as well. If you have a query string like:

```
"SELECT DISTINCT owner FROM Owner owner left join  owner.pets WHERE owner.lastName LIKE :lastName% "
```

we should highlight all occurrences of `owner` when you have the cursor inside of of the occurrences.
