### ISSUE TITLE
[Spring Data Queries] Show inline hint for query parameter

### ISSUE THREAD

**Issue by BoykoAlex** [spring-projects/sts4#1333]
All Spring Data Query whether it is JPQL/HQL or a native SQL query support parameters coming from java code. Typically @Query annotates a method, then `:1` or `?2` found in the query would stand for the first and second parameter of the Java method respectively. It's be useful to show the name of the Java method parameter as [inline hint](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_inlayHint) to indicate which parameter the number corresponds to

**Comment by BoykoAlex** [comment]
Fixed with 00636085cadeb624448de8a0c8f2cba41d50dce4 but doesn't seems that it is only useful for parameter ordinal

**Comment by martinlippert** [comment]
I tried VSCode only for the moment, the space between `:1` and `lastname` looks good to me, but I would move the hint entirely behind the `%` character, with spacing before and after.

**Comment by BoykoAlex** [comment]
The PR for LSP4E inlay hint padding issue: https://github.com/eclipse/lsp4e/pull/1089
Corrections to positioning of inlay hint on our side: fb072bfa8c2859574c5b68b8b88558bab5ed5d7a
