### ISSUE TITLE
[Spring Data Queries] Navigate to definition of Java fields and methods used in queries

### ISSUE THREAD

**Issue by BoykoAlex** [spring-projects/sts4#1334]
Consider the following HQL query:
```
SELECT DISTINCT owner FROM Owner owner left join  owner.pets WHERE owner.lastName LIKE :lastName%
```

The `pets` property from `Owner` class can be navigated to. The same goes for instance methods if any are used.

**Comment by BoykoAlex** [comment]
Fixed with 00636085cadeb624448de8a0c8f2cba41d50dce4

**Comment by martinlippert** [comment]
I do See navigation working from `Owner` to the corresponding Java class definition, but I don't see `pets` in the `owner.pets` part navigating to anything. Therefore, re-opening this issue.

I also haven't seen a test case around this case (`pets` here), so maybe some work left here.

**Comment by BoykoAlex** [comment]
Oops, I have only meant to address the parameters... let me open a separate issue for parameters and resolve it and keep this one opened for later as it'll require some type attribution work for the query AST nodes

**Comment by BoykoAlex** [comment]
Parameters "go to definition" has moved to #1336 

The fields and methods are to be handled here.

**Comment by martinlippert** [comment]
@BoykoAlex So this issue can be closed as fixed, right?
