### ISSUE TITLE
Quick Search with Command+Shift+L not working with Sonoma 14.6.1

### ISSUE THREAD

**Issue by castriottaa** [spring-projects/sts4#1335]
After upgrading the Mac OS version to 14.6.1, the Quick Search doesn't work anymore with the combination of keys Commmand+Shift+L (with Eclipse Version: 2024-06 (4.32.0) Build id: 20240606-1231 )

In Keys settings, the Command+Shift+L is not accepted as a valid keys combination.

However, it works again with other combinations of keys, like for example Shift+L (without Command).

**Comment by martinlippert** [comment]
The default key combination for the Quick Search is Command+Option+Shift+L on macOS (for a standard install of the distribution), which seem to work fine. Not sure why exactly you can't set the preference for this to Command-Shirt-L, probably already used for another action.

**Comment by castriottaa** [comment]
I don't know what exaclty I've just yet done: pressing Ctrl+Shift+L, it was like if you made a clic on Eclipse in the top bar.
I was in the "keys" menu option. Now it works again...
Probably is not a bug of the plugin, maybe a bug of Eclipse itself.
I think you can close this issue, apologize for the wasting of time...

**Comment by martinlippert** [comment]
@castriottaa No worries, if there is anything we can help you with, let us know.
