### ISSUE TITLE
Makes auto-completion in application.yml consistent with application.properties.

### ISSUE THREAD

**Issue by 11D-Beyonder** [spring-projects/sts4#1341]
**Expected Behavior**

In `application.properties`, the auto-completion is smooth when typing any words. But in yml, you need to press `.` or `Ctrl`+`Space` to pop up the window, which is troublesome. I want a consistent experience.

**Current Behavior**

`application.properties`
![image](https://github.com/user-attachments/assets/5178b8c2-64c5-41dc-8983-07d78be2aa3b)

`application.yml` (need to press `.` or `Ctrl`+`Space` to pop up the window)
![image](https://github.com/user-attachments/assets/43e4a72c-38db-4410-99a6-3bcc959c8d92)

**Comment by BoykoAlex** [comment]
I investigated this issue and created a bug for VSCode: https://github.com/microsoft/vscode/issues/230277

**Comment by BoykoAlex** [comment]
Fixed with a63fc2a541dd1213b9153635e7445fd134620a4d
