### ISSUE TITLE
Refactor ConditionalOnResource attribute to be based on AnnotationAttributeCompletionProcessor

### ISSUE THREAD

**Issue by ksankaranara-vmw** [spring-projects/sts4#1344]
Both AnnotationAttributeCompletionProcessor and the ConditionalOnResource annotation should be refactored so that they work with each other. This would reduce lot of the repetitive code to generate the completion proposals on the attributes.

**Comment by martinlippert** [comment]
Fixed with https://github.com/spring-projects/sts4/commit/565904de190e296a1e1ba8d462fd8e8f77d38886
