### ISSUE TITLE
Duplicate spring symbol cannot be found

### ISSUE THREAD

**Issue by Shiaming** [spring-projects/sts4#1346]
Duplicate spring symbol cannot be found
Global search can not find  duplicate spring symbol
I hope you can search for duplicate files in both. Thank you

**Comment by Shiaming** [comment]
![1725588705394](https://github.com/user-attachments/assets/c7ad90dc-bf19-47bf-aefb-544a9087dbe5)

**Comment by martinlippert** [comment]
Thanks for raising this @Shiaming.

For my understanding: You would like to see both symbols for `name` when you do the search in that quick access search, correct?

**Comment by martinlippert** [comment]
Looking at this example, it might also make sense to enhance the symbol for request mappings with information about to annotated method/class directly from within the symbol. What do you think?

**Comment by Shiaming** [comment]
> Thanks for raising this @Shiaming.
> 
> For my understanding: You would like to see both symbols for `name` when you do the search in that quick access search, correct?

Yes

**Comment by Shiaming** [comment]
Because eclipse is multi-project, there will be multiple identical spring symbols，so i hope to see both symbols for name when i do the search in that quick access search. . Thank you

**Comment by martinlippert** [comment]
Submitted a PR to the LSP4E project for this: https://github.com/eclipse/lsp4e/pull/1124

**Comment by martinlippert** [comment]
PR got merged in LSP4E, so marking this as fixed.

**Comment by Shiaming** [comment]
Thanks @martinlippert
