### ISSUE TITLE
multi module maven project working with STS 3.X is not imported correctly, shows src.main.java as part of package and creates bin as target folder

### ISSUE THREAD

**Issue by ksanjeev9211** [spring-projects/sts4#135]

**Comment by martinlippert** [comment]
in order to reproduce the issue, it would be awesome if you could attach a sample project and provide a few steps how to reproduce the issue.

**Comment by ksanjeev9211** [comment]
project shown on the screen shot is imported perfectly fine on STS-3.x
![inkedcapture_li](https://user-images.githubusercontent.com/4118153/48861958-80faf400-ed8a-11e8-89c4-e78301874097.jpg)

**Comment by ksanjeev9211** [comment]
project shown on the screen shot is imported perfectly fine on STS-3.x
![inkedinkedcapture_li](https://user-images.githubusercontent.com/4118153/48862137-fbc40f00-ed8a-11e8-99a5-2fc71fa5afb3.jpg)

**Comment by ksanjeev9211** [comment]
will upload the project after masking it.

**Comment by kdvolder** [comment]
> will upload the project after masking it.

Great. Please also include a exact step-by-step on how you import the projects. Eclipse being Eclipse, there many different ways to import projects using various wizards and menu options, not all of which will lead to the same result. So it is important to include these steps so we can follow them exactly.

**Comment by ksanjeev9211** [comment]
file->import->maven->existing maven project

**Comment by ksanjeev9211** [comment]
Today  I tried  run mvn eclipse:eclipse first and then import as:
**file->import->General->Existing Project into workspace**,
Fortunately this resolves the issue
I guess may be the m2e is not working as expected when I import the project as "**existing maven project**"

**Comment by kdvolder** [comment]
> I guess may be the m2e is not working as expected when I import the project as "existing maven project"

Sounds like that is the case. It would be good to raise a bug ticket about this with m2e on the Eclipse bugzilla. https://bugs.eclipse.org/bugs/enter_bug.cgi?product=m2e

Normally I would do this kind of follow up myself, but it is pointless if we don't have a way to reproduce the problem. So I'll leave it up to you to decide if you want to invest the effort to report it to them with a sample project.
