### ISSUE TITLE
Not auto prompt application-dev.properties config

### ISSUE THREAD

**Issue by shadowrk** [spring-projects/sts4#1354]
I have application.properties and application-dev.properties，when I use @valid, item in dev properties not auto prompt.
![image](https://github.com/user-attachments/assets/21e442c2-9f13-4d0a-bbc2-90b693f0d29e)

dev propertis 
![image](https://github.com/user-attachments/assets/fb33c369-8fe9-4e02-864c-50fd595b3e77)

**Comment by martinlippert** [comment]
Fixed with https://github.com/spring-projects/sts4/commit/7fa81e88fc860d747288ff91a63b837b14ad89d6
