### ISSUE TITLE
There are no update sites to search

### ISSUE THREAD

**Issue by cassiusvm** [spring-projects/sts4#137]
I did update Spring Tools Suite 4. Restarted it.

When I try to check for updates again then appears dialog box "No Updates Found" : There are no update sites to search. Do you wish to open the "Available Software Sites" preferences ?

menu Windows -> Preferences -> Available Software Sites is empty.

Spring Tool Suite 4 
Version: 4.0.1.RELEASE
Build Id: 201810300749
OS: Windows 10, v.10.0, x86_64 / win32
Java version: 1.8.0_192

**Comment by martinlippert** [comment]
The list of the available update sites is empty?!? Hmmm... I wonder why the update trashed the content of the update site preferences. Can you double check other preferences, just to see if there is more stuff that got trashed?

You can easily add the update sites back:
- http://download.eclipse.org/releases/2018-09/ (for Eclipse 2018-09)
- http://download.springsource.com/release/TOOLS/sts4/update/latest (for STS4)

(as a quick fix for now)

**Comment by cassiusvm** [comment]
I closed STS4.

I started it again.

The menu WIndow -> Preferences -> Install/Update -> Available Software Sites is showing several update sites.

So, I think this issue can be closed.

Thanks for the attention.

**Comment by martinlippert** [comment]
Ok, good to hear that this is working again, even though we have no clue why those update sites disappeared and re-appeared again. Strange... But nevertheless, good that you got it back to a working state and thanks for letting us know.
