### ISSUE TITLE
VSCode - Error reported when using collate on @Query annotation

### ISSUE THREAD

**Issue by raulvaldoleiros** [spring-projects/sts4#1393]
When using the postgres collate function in @Query with nativeQuery set to true, vscode presents an erro but the query is ok and works.
The following image shows the error.
![image](https://github.com/user-attachments/assets/eb635ac7-a8d8-43a2-a921-0675b40475b2)

**Comment by martinlippert** [comment]
Thanks for reporting this, we will look into this to improve the validation here. In the meantime, you can switch off the query validation in the preferences (if the error is too annoying).

**Comment by raulvaldoleiros** [comment]
Thanks for sharing :)

**Comment by BoykoAlex** [comment]
Fixed with ea033714b47e3d8088a5f6135343743df0369d61 and b31e63468fa7607335d06ed5f8ac910ea31eea47
