### ISSUE TITLE
When Adding spring boot starters, another dependencies element is generated.

### ISSUE THREAD

**Issue by gladiator67** [spring-projects/sts4#1394]
OS : Windows 11 pro 23H2
VScode : 1.94.2 64bit System Installer
Spring Boot : 3.3.4

I use maven with Spring boot extensions. Spring boot version is 3.3.4. I generate spring boot maven projects and add some spring boot starters. The generated projects work without errors. But adding the other starters on existing projects bring the serious errors. Below is the image of adding starters on existing pom.xml file.

![error_1](https://github.com/user-attachments/assets/86ddf801-50cf-4e86-85fc-1cef0334e8d4)

And I add another spring starters on pom.xml. But duplicated element is generated and compilation fails. The added dependency can not be inserted into existing dependencies elements. I also attach the related image.

![error_2](https://github.com/user-attachments/assets/2b704e3d-a241-441a-bfe6-3eb9a710bd05)

**Comment by martinlippert** [comment]
I think the underlying functionality is implemented as part of https://github.com/microsoft/vscode-spring-initializr, but let's have a look.

**Comment by gladiator67** [comment]
I found the following issue. I hope this is helpful.

https://github.com/microsoft/vscode-spring-initializr/issues/242

**Comment by BoykoAlex** [comment]
The issue above has two PRs now :-) One from me and another from someone else created much earlier...

**Comment by BoykoAlex** [comment]
This is fixed in `vscode-spring-initializr` via https://github.com/microsoft/vscode-spring-initializr/issues/242
