### ISSUE TITLE
【yml Editor】The question appeared after #116

### ISSUE THREAD

**Issue by yl-yue** [spring-projects/sts4#141]
Thank you for your optimized treatment of question #116

But here comes a new question

**question describe**
This question caused the background color of the yml editor to not take effect

_Correct example_
![image](https://user-images.githubusercontent.com/39790401/48622891-1b51e500-e9e3-11e8-9ecf-4fb9b3578c01.png)

_Wrong example_
![image](https://user-images.githubusercontent.com/39790401/48622745-b6968a80-e9e2-11e8-93ae-e81af9b1b584.png)

**Comment by yl-yue** [comment]
**Append a small BUG**
![image](https://user-images.githubusercontent.com/39790401/48623551-f1012700-e9e4-11e8-8582-db1229bc4457.png)
![image](https://user-images.githubusercontent.com/39790401/48623559-f8c0cb80-e9e4-11e8-8b76-2ed7fc19fb0c.png)

Spring's default icon is missing

**Comment by kdvolder** [comment]
I think I have answered the question, so closing this ticket now. Let me know if you have further questions.
