### ISSUE TITLE
Navigation to Spring-specific elements not showing anything in Windows 10.

### ISSUE THREAD

**Issue by manojp1988** [spring-projects/sts4#142]
I have tried STS4 in both windows10 and MAC. In Windows 10, the CTRL+6 option is not listing any mapping or bean defs. But it did in MAC with spring boot project.

So is this discovery only works with spring boot projects.? Not ordinary MVC Project.

**Comment by BoykoAlex** [comment]
Correct for now, but i believe we are changing it to all spring projects at least for Spring symbols... Don't recall exactly which STS 4.x version is going to have it though...

**Comment by martinlippert** [comment]
Alex is correct, the enhancement request is here in case you would like to comment, vote (+1), and/or follow: https://github.com/spring-projects/sts4/issues/96
