### ISSUE TITLE
Eclipse 4.10 compatibility

### ISSUE THREAD

**Issue by heruan** [spring-projects/sts4#143]
We have switched to Java 11 and we are previewing Eclipse 4.10 (4.10-M2 currently), but Spring Tools does not appear in the Marketplace. Is it compatible with 4.10 yet?

**Comment by kdvolder** [comment]
There are snapshot builds available, that you can try. Here:

http://dist.springsource.com/snapshot/STS4/nightly-distributions.html

There is a link there to a snapshot update site:

http://dist.springsource.com/snapshot/TOOLS/sts4/nightly/e4.10

... or a 'all in one' full distribution build futher down the page under the heading 'SPRING TOOL SUITE 4 - BASED ON ECLIPSE 2018-12 MILESTONE BUILDS (4.10.0)'.
