### ISSUE TITLE
`@GetMapping` completions should automatically add imports

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#1430]
Using the `@GetMapping(..)` completion snippets does not automatically add the necessary import statements, but this should happen to ensure a smooth flow.

**Comment by BoykoAlex** [comment]
Hmm... I can't reproduce this... any special conditions for this to happen? A sample project perhaps? :-) I've tried this in a few existing and a new project (with spring-web on the classpath). The import for `GetMapping` was added every time I used the get mapping snippet proposal.

**Comment by martinlippert** [comment]
🤔 Can't reproduce this either, must have been a very special situation that I came across this that I can't reproduce anymore. So need to close this one here as can't reproduce and re-open in case I came across this again.
