### ISSUE TITLE
SQL Parsing Error

### ISSUE THREAD

**Issue by Devharajan-Rangarajan** [spring-projects/sts4#1439]
There is an issue with the parsing of the native SQL Queries for both the .id options and the Group by clause

![image](https://github.com/user-attachments/assets/35459943-6a09-4eed-a8a9-74d7141ea9db)

Sample Code for Quick Copy:

  @Query(
      value =
          """
            SELECT v.name AS vendor_name,
                   COUNT(m.id) AS mould_count
            FROM moulds m
            LEFT JOIN vendor v ON v.id = m.converter_id
            WHERE AND m.mould_code_lifecycle_stage != 'RETIRED'
                  AND m.mould_type = 'PRODUCTION'
                  AND m.id IN (SELECT unnest(allowed_moulds::bigint[])
                           FROM user_allowed_items
                           WHERE user_id = :userId)
            GROUP BY v.name
            ORDER BY mould_count DESC
            LIMIT 5
            """,
      nativeQuery = true)
  List<Object[]> getTopConverter(@Param("userId") Long userId);
  
  
Errors Thrown:

1. PostgreSQL: no viable alternative at input '(m' [SQL_SYNTAX]
2. PostgreSQL: no viable alternative at input 'GROUP' [SQL_SYNTAX]

**Comment by BoykoAlex** [comment]
Which STS version is this? Did you upgrade from another version and these error markers appeared?
You can workaround it by disabling SQL syntax validation in the Settings -> Spring -> Validation -> Data Queries

**Comment by TE-Devharajan-Rangarajan** [comment]
![image](https://github.com/user-attachments/assets/73028112-4849-469d-be0e-a671f0e7bba8)
The above is the version I am using which is the latest version. I upgraded from the previous version.

**Comment by TE-Devharajan-Rangarajan** [comment]
# System Details Report
---

## Hardware Information:
- **Hardware Model:**                              Hewlett-Packard HP 240 14 inch G9 Notebook PC
- **Memory:**                                      32.0 GiB
- **Processor:**                                   12th Gen Intel® Core™ i5-1235U × 12
- **Graphics:**                                    Intel® Graphics (ADL GT2)
- **Disk Capacity:**                               512.1 GB

## Software Information:
- **Firmware Version:**                            F.05
- **OS Name:**                                     Ubuntu 24.04.1 LTS
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               46
- **Windowing System:**                            X11
- **Kernel Version:**                              Linux 6.8.0-51-generic

**Comment by BoykoAlex** [comment]
Okay, I had an syntax error at `::` in `unnest(allowed_moulds::bigint[])` because I has MySql connector rather than PostgreSql. Switching to PostgreSql does not produce any syntax error. 
@Devharajan-Rangarajan please remove the erroneous `AND` as mentioned in the comment above and everything should work.
