### ISSUE TITLE
m2e-wtp - Maven Integration for WTP: installation fails

### ISSUE THREAD

**Issue by swdhsn** [spring-projects/sts4#144]
Dear Spring Tools 4-Team,
 
I tried to install the 
_m2e-wtp - Maven Integration for WTP_
into a fresh 
_STS 4.0.1_
via the update site
_2018-09	http://download.eclipse.org/releases/2018-09_

The installation terminates with

> An error occurred while collecting items to be installed
> session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
> No repository found containing: osgi.bundle,javax.xml.soap,1.3.0.v201105210645
>

**Comment by kdvolder** [comment]
This could be an issue with some cached update site contents. You could try opening the 'available update sites' proference page and forcing update-site content to be reloaded. Restarting STS may also help flush out stale content from local caches.

**Comment by swdhsn** [comment]
Thank you for your suggestion. I reloaded the update site and restarted the STS. However I get the same error message on installing _m2e-wtp - Maven Integration for WTP_.

**Comment by martinlippert** [comment]
In the meantime, we updated the STS4 distribution builds to include the m2e-wtp extensions by default, so I think we can close this one here.

**Comment by swdhsn** [comment]
Thank you!
