### ISSUE TITLE
STS4 web page is lacking description of an update site to install it into an existing Eclipse installation

### ISSUE THREAD

**Issue by marioja** [spring-projects/sts4#146]
When I look at the following page:

https://spring.io/tools3/sts/all

which is linked from the "See all versions" link from the STS3 page (https://spring.io/tools3).  There is no such page on the STS4 page but there is an update site at https://download.springsource.com/release/TOOLS/sts4/update/latest

Can we use this issue to track the addition of this information to the STS4 page.

**Comment by martinlippert** [comment]
Instead, we have a detailed install page on the project wiki (which itself is linked from the main tools page): https://github.com/spring-projects/sts4/wiki/Installation

**Comment by marioja** [comment]
Hi Marin,  I am a big fan of Spring and I hope also someone who is adept at finding information.  It took me a long time to figure out the update site and I never looked at the linked because I never thought that Learn more on the Project Wiki would provide me with this information.  Would it be possible to modify the page to say something like: "For additional installation instructions and to learn more".

**Comment by martinlippert** [comment]
Yes, that makes a lot of sense, will trigger that change. Thanks for the suggestion, always welcome!!!

**Comment by martinlippert** [comment]
https://github.com/spring-io/sagan/pull/869
