### ISSUE TITLE
Cannot set conditional debug breakpoint or evaluate expressions in external maven sources (like Spring)

### ISSUE THREAD

**Issue by phillipuniverse** [spring-projects/sts4#152]
Final output:

<img width="1324" alt="screen shot 2018-11-29 at 9 15 34 am" src="https://user-images.githubusercontent.com/684275/49231352-61318480-f3b7-11e8-8345-5dad4a5856fe.png">

```console
Conditional Breakpoint has Compilation error(s).

Reason:
Unable to compile conditional breakpoint - missing Java project context.
```

Reproduction steps:

1. Download the latest STS from https://spring.io/tools (I got `4-4.0.1.RELEASE-e4.9.0-macosx.cocoa.x86_64.dmg`)
2. I added the Lombok jar and `-javaagent` to the `.app` folder in order to use Lombok annotations
3. Went to File -> New Project -> Spring Starter Project and hit next until the project was created (just accepted all the defaults)
4. In the generated pom.xml, I changed it around to add `spring-boot-starter-web` and JUnit Jupiter
5. Changed the `DemoApplicationTests` to look like this:
    ```java
    @ExtendWith(SpringExtension.class)
    @SpringBootTest
    public class DemoApplicationTests {
	
        @Configuration
        static class Config {
		
	    }

        @Component
        static class BeanFromTest {

        }

        @Autowired
        ApplicationContext ctx;

        @Test
        public void containsBean() {
            assertNotNull(ctx.getBean(BeanFromTest.class));
        }

     }
    ```
6. CMD + Shift + T to open `DefaultListableBeanFactory`, set a breakpoint in `registerBeanDefinition()` to hit when the `BeanFromTest` is registered
7. Hit 'Debug as Junit Test' to debug the test

The breakpoint hits on every single invocation because of the "Unable to compile conditional breakpoint - Missing Java Project Context". Also if you look in the screenshot, you'll see that 2 instances of `DefaultListableBeanFactory` are opened: 1 that has the little Java bytecode argument (which is where I originally set the breakpoint) and one that just has a `J`, which was opened when the breakpoint hit. The `J` icon usually means that the project is not a Java project.

Also might be interesting is that before running the JUnit test at all, I had previously downloaded the sources for `spring-context` so that was already in my `~/.m2/repository`. It did not need to download it on-demand.

I also cannot do things I normally can in Java debugging, like right-click and "Inspect" with 'Unable to evaluate the selected expression' (even though hovering works):

![screen recording 2018-11-29 at 09 29 am](https://user-images.githubusercontent.com/684275/49232448-8f17c880-f3b9-11e8-993d-b9727b94b844.gif)

**Comment by phillipuniverse** [comment]
Exact project ready to import: [failing-conditional-breakpoint.zip](https://github.com/spring-projects/sts4/files/2629754/failing-conditional-breakpoint.zip)

**Comment by phillipuniverse** [comment]
Bummer, this also happens in core Eclipse. Opened issue at https://bugs.eclipse.org/bugs/show_bug.cgi?id=542089, I'll close this one.

**Comment by martinlippert** [comment]
Thanks for double checking with a vanilla Eclipse and reporting over there. Much appreciated.
