### ISSUE TITLE
No executable in build

### ISSUE THREAD

**Issue by youcangetme** [spring-projects/sts4#156]
spring-tool-suite-4-4.0.2.RELEASE-e4.9.0-win32.win32.x86_64.zip is 343MB of nothing. I see all sorts of files for Eclipse plugins just no executable to actually start the stupid thing up.

**Comment by martinlippert** [comment]
I cannot confirm that the ZIP file is 343MB "of nothing". I downloaded the file myself a moment ago and double-checked and it extracts nicely into a folder, containing everything you need to run the IDE, including the executable. Maybe a proxy server or something else on your network side removed things from the zip file.

**Comment by youcangetme** [comment]
Interesting because I changed the URL and got an older copy with no
problems:
http://download.springsource.com/release/STS4/4.0.0.RELEASE/dist/e4.9/spring-tool-suite-4-4.0.0.RELEASE-e4.9.0-win32.win32.x86_64.zip

**Comment by martinlippert** [comment]
Did you try to re-download the 4.0.2 release version? You could also try to modify the download link for the 4.0.2 version to use the `dist.springsource.com` domain instead of the `download.springsource.com` one. Could help in case the corrupted or broken file got cached somewhere down the way.

**Comment by martinlippert** [comment]
You can also grab a MD5 and SHA1 hash in order to verify that your download is correct. You can find and download those files via the same URL than the distribution ZIP file + `.md5` or `.sha1`.

**Comment by youcangetme** [comment]
The second time I downloaded the file it extracted with the complete
package. I'm not clear as to why the first time seemed to be truncated by
just a few kilobytes. The file extracted without error but was missing the
executable. The second file extracted cleanly. Weird stuff!

Thanks for your time.


--jb

**Comment by martinlippert** [comment]
Glad to hear that you got it working by downloading the file a second time and happy to help. Maybe you can avoid a wording like "full of nothing" and "the stupid thing" the next time you ask for help. Would be much appreciated.

**Comment by youcangetme** [comment]
Oh, did I offend you, poor little snowflake?

Too funny.

Happy Holidays!

On Dec 5, 2018 3:30 AM, "Martin Lippert" <notifications@github.com> wrote:

Glad to hear that you got it working by downloading the file a second time
and happy to help. Maybe you can avoid a wording like "full of nothing" and
"the stupid thing" the next time you ask for help. Would be much
appreciated.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/spring-projects/sts4/issues/156#issuecomment-444400992>,
or mute the thread
