### ISSUE TITLE
Color of Generic editor 

### ISSUE THREAD

**Issue by Spark4J** [spring-projects/sts4#158]
When I open .yml  file with Generic Editor **once again** , it lose color from the **custom properties** to the end.
How to resolved it?

Spring Tool Suite 4 

Version: 4.0.2.RELEASE
Build Id: 201811300843

**Comment by Spark4J** [comment]
![issue_158](https://user-images.githubusercontent.com/42914744/49501084-10d18f80-f8ad-11e8-9eee-ce59578e2d4b.jpg)

**Comment by yl-yue** [comment]
Spring Tool Suite 4 
Version: 4.0.2.RELEASE
Build Id: 201811300843

**_resolved_**

**Comment by Spark4J** [comment]
> Spring Tool Suite 4
> Version: 4.0.2.RELEASE
> Build Id: 201811300843
> 
> **_resolved_**

Neither 4.0.1 nor 4.0.2 works.

**Comment by Spark4J** [comment]
It has been resolved by add a space after the custom properties!
