### ISSUE TITLE
Ctrl+Shift+C does not work for properties file

### ISSUE THREAD

**Issue by ksanjeev9211** [spring-projects/sts4#160]

**Comment by ksanjeev9211** [comment]
In any properties file I can't comment any entry or set of entries using the above command.

**Comment by kdvolder** [comment]
This should have been fixed in the latest release of STS (version is 4.0.2). Is that the version you are using?

**Comment by ksanjeev9211** [comment]
Ok.
I am using 4.0.1.

**Comment by martinlippert** [comment]
Closing this as a duplicate of https://github.com/spring-projects/sts4/issues/100
