### ISSUE TITLE
maven plugin issue

### ISSUE THREAD

**Issue by TrumanDu** [spring-projects/sts4#169]
![image](https://user-images.githubusercontent.com/16727775/50418293-979eda00-0865-11e9-9382-3c2c7550a9e3.png)
disable ```Download Artifact Sources``` after restart fail.

how to disabled ```Download Artifact Sources and doc```?

![image](https://user-images.githubusercontent.com/16727775/50418363-f2383600-0865-11e9-818d-66c2885c277f.png)

**Comment by martinlippert** [comment]
Sounds like a general issue with the Maven Integration for Eclipse, so I would suggest to file a bug with the m2e project at Eclipse: https://bugs.eclipse.org
