### ISSUE TITLE
Add support to view project symbols in "goto symbol"

### ISSUE THREAD

**Issue by gayanper** [spring-projects/sts4#172]
As a further enhancement for #96 it would be really good to add support for "goto symbol" on project. Right now the goto symbol is either on the current file or the whole workspace. it would be good if the symbols can be filtered for current project, may be it would be really nice if it can be presented as part of the project tree like it was in STS3.

**Comment by martinlippert** [comment]
How is that different from your PR for https://github.com/spring-projects/sts4/issues/173 ?

In case this refers to showing the project symbols automatically inline with the project resources tree  in the project explorer, we should change the title for this issue accordingly.

**Comment by gayanper** [comment]
My bad seems like i have reported the same issue twice. I will close this.
