### ISSUE TITLE
Syntax highlighting in Spring Properties Editor broken since upgraded to STS 4.1.0

### ISSUE THREAD

**Issue by tjstuart** [spring-projects/sts4#175]
This issue could very well not be a bug.  Possibly something weird with my STS as I did once mess about with themes (so could be some rubbish hanging around) though since I upgraded from an earlier version of STS 4 to 4.1.0, the generic properties editor syntax highlighting has gone all weird.

Below image is fairly self explanatory.  Left is with the spring properties editor, right is plain old text editor.

![image](https://user-images.githubusercontent.com/19812676/50748804-375d5e80-128f-11e9-8ac1-1222b75617fb.png)

In STS, I am using default everything when it comes to themes ie. no theme.

![image](https://user-images.githubusercontent.com/19812676/50748869-a2a73080-128f-11e9-900c-79624b6e4701.png)

Anyone have any ideas before I have to start over clean?

Host is Win10 x64 with STS launched via Oracle Java 8 SDK.

**Comment by kdvolder** [comment]
Does it work in a 'fresh' workspace? 

I suspect something is messing up how editor and content type is inferred from file names. So basically the file is being treated as plaintext and so no syntax highlights.

Some things to try:

- new workspace (if workspace is clean whatever is 'wierd' in the workspace may be gone)
- Use the 'Open With" action from context menu. Select 'Generic Editor'. 
- Have look inside workspace preference around content types. (E.g. go to menu "Window >> Preferences >> General >> Content Types". Select "Spring Properties File" play around with this.

**Comment by tjstuart** [comment]
Yes, it works in a 'fresh' workspace.  I just created a new workspace and imported an existing project and it is now OK ie. the white property keys are now black.

However I was hoping to avoid new workspace as have many projects, so if you have any other suggestions eg. stuff to delete from existing workspace or similar, that would be great.  Otherwise it's no big deal, I can cope :)

Close the issue if you wish.

**Comment by kdvolder** [comment]
> However I was hoping to avoid new workspace

I understand. I know its painful to rebuild your workspace from scratch. 

> stuff to delete from existing workspace or similar, that would be great. Otherwise it's no big deal, I can cope :)

My best guess would be that its something related to content type and editor selection. So I'd suggest playing with these settings to ensure that it assigns type 'Spring Properties' to the files you are having problems with. 

But you say you already tried to play with these preferences to no success. 

Beyond that I have really not much helpful to suggest. 

I'll close ticket now as it looks like something in the workspace got messed up. 

Feel free to comment further. If the problem happens again (we don't know yet you can create another ticket and we can give anothe try at figuring out what/why/how workspace could get into this 'broken' state.
