### ISSUE TITLE
vscode function declarations

### ISSUE THREAD

**Issue by dsyer** [spring-projects/sts4#18]
I like the `CTRL-T >` feature, but it only seems to work for `@Beans` (not for `Functions` in a `@FunctionScan` or `@ComponentScan`).

**Comment by martinlippert** [comment]
Functions in a `@FunctionScan`or `@ComponentScan` are identified as such if there is a class that implements `java.util.function.Function`, `java.util.function.Supplier`, or `java.util.function.Consumer`, right?

That sounds quite straight forward to realize for the symbol infrastructure.

Another case: Could it also be a class that implements a subtype of those function types? (so I define my own interface that extends `j.u.f.Function` and then have a class that implements my own interface). And if so, where should the symbol point to? The implementing class or my interface?

**Comment by dsyer** [comment]
> right?

Correct.

> The implementing class or my interface?

Dunno. The implementing class sounds more useful to me.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Martin Lippert:) 

This is implemented now and available from the nightly CI builds. Specific symbols for function beans are now generated for classes that implement `Function`, `Supplier`, or `Consumer` interfaces, either directly or indirectly.
