### ISSUE TITLE
Add the possibility to filter Quick Text Search results

### ISSUE THREAD

**Issue by thackel** [spring-projects/sts4#185]
The "Quick Text Search" is probably the most used STS-only feature, thanks for that.
The Idea Community has this kind of search functionality for quite a long time.

But for larger projects its possible that you have many false positive results, so it would be nice that you could filter the results.

- Filename
- Extension
- Path
- Package
- more (size etc, see the idea dialog)

A suggestion could be a second input field where its possible to reduce the source files with a regular expression when "real" UI extension with lots of fields is too cumbersome.

**Comment by kdvolder** [comment]
Seems like a good idea to me, if we can come up with something that isn't too cumbersome / complex. The whole point of the 'Quick Search' feature was that it meant to provide very simple and easy to use alternative to Eclipse own full-featured and immensely complicated search UI.

I'm not opposed to adding a simple way to restrict the file names based on a pattern of sorts. But I definitely don't want us to start filtering based on stuff like package, size etc. etc. etc.

**Comment by martinlippert** [comment]
There was another comment on the marketplace from someone requesting a "search whole word" feature for the quick search. Would be quite useful, I think.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Kris De Volder:) 

I've got something implemented. I'm not entirely thrilled with having some space 'wasted' on the extra widgets to type in  a 'filter' pattern. 

I'm also not sure if the type of filter will serve well enough in practice. I chose to use a 'glob' pattern matcher that I borrowed from jgit. So it is similar to what you'd put into a gitignore file. At the moment only 'positive' patterns are supported. So you can use something like `*.java` to search only java files. Or `**/src/*.java` to search only Java files in a source folder or `/project-name` to search only files in a give project (paths match against workspace paths, so first path segment is the project name).

Multiple such expressions can be given in a list (separated by `,`). They are 'or-ed' together so if you want to search .java and pom files you could do:

`*.java,pom.xml` 

I'll push it out shortly. I think it would be good if we have some folks (including myself :-) use this for a bit and see how it feels. Then maybe some feedback / ideas on whether this is 'good enough' or also some ideas on improving it.

**Comment by kdvolder** [comment]
If you want try this out (and provide feedback :-). You can install it from this update site:

https://dist.springsource.com/snapshot/TOOLS/eclipse-integration-commons/nightly

Note: don't click the link. Instead, open "Help >> Install New Software". Paste the link in the "Work with" input box at the top. Then select "Eclipse Quicksearch" under "Core / Eclipse Integration Commons".

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Martin Lippert:) 

works for me in general, but I would like to get the text box positioned differently, causes too much clutter from my point of view. But I will file another item for that.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Martin Lippert:) 

created a new item for the improved layout here with a few thoughts and ideas: #163720761

**Comment by thackel** [comment]
Tried the version 20190204 and i am pleased ;-)

Thanks for your hard work!
