### ISSUE TITLE
concourse-vscode plugin - any way to utilize the outline

### ISSUE THREAD

**Issue by EugenMayer** [spring-projects/sts4#19]
Any way to use https://marketplace.visualstudio.com/items?itemName=patrys.vscode-code-outline to have a outline like one has in atom?

I am aware of lookup symbols and thats already great, but having the whole tree to explore is something very useful.

Extremely valuable plugin overall, thank you very much!

**Comment by martinlippert** [comment]
Thanks for the feedback. I am not sure what the VSCode outline extension is doing under the hood, but maybe you can file an issue with them to support language servers?

**Comment by martinlippert** [comment]
I think the latest versions of the Concourse extension for VSCode produce hierarchical symbols that nicely show up in the outline view, so closing this now.
