### ISSUE TITLE
Completion not work for application.y*a*ml files

### ISSUE THREAD

**Issue by Eskibear** [spring-projects/sts4#191]
As mentioned [here](https://yaml.org/faq.html): 
> Q: Is there an official extension for YAML files?
> A: Please use ".yaml" when possible.

Currently it looks that the completion only works for `.yml` files.
https://github.com/spring-projects/sts4/blob/e8f2840966e9bee7ce3948ee4662136e78103862/eclipse-language-servers/org.springframework.tooling.boot.ls/plugin.xml#L44-L57

I don't know if it's a bug or Spring convention to only use `.yml` as file extension.  Maybe it would be better to also include support for such `.yaml` files.

**Comment by kdvolder** [comment]
The properties files for spring boot apps are typically called `application.yml`. I'm not sure if spring boot will pick it up if its called `application.yaml`. To be honest it never occurred to me as I'd never seen an example project with a `application.yaml` in it. I'll give it a try though and report back in a bit.

**Comment by kdvolder** [comment]
Looks like `application.yaml` works just as well. So I think it would make good sense to extend the file associations to allow either `.yml` or `.yaml`.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Kris De Volder:) 

Should be working now for vscode and eclipse. Assinging this to @alexboyko to take a look at atom.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Kris De Volder:) 

Looks like I messed something up pushing changes. Pushed a old version which has a typo in the package.json. Should be fixed now but I'll double-check snapshot build before redelivering.
