### ISSUE TITLE
"class" snippet is not available

### ISSUE THREAD

**Issue by kawnnor** [spring-projects/sts4#192]
Spring Boot Tools Extension 1.3.0 caused the class / interface snippets and package / public keywords of "Language Support for Java by Red Hat" extension to be unusable. Rolled back to 1.2.0, everything works fine.

**Comment by kdvolder** [comment]
Gave it another try. Looks like I made a mistake the first time around. My new file wasn't actually a '.java' file. I forgot to add the '.java' extension.

So the steps from above seem to work to get the interface and class snippets to show up (i.e. empty .java file, press CTRL-space).

I then installed Spring boot tools 1.3.0 and tried the same steps again. It still works for me.

So... I think I did figure out which snippets we are talking about and how to invoke them but they seem to work for me just fine, with and without Spring Boot Tools 1.3.0 installed.

Cllosing this ticket as 'cannot reproduce'. 

If you can add precise steps, we can re-open the ticket and I'll give it another try. But as far as I can tell right now it is working fine. 

That probably means we are missing some details on what are the exact steps, or circumstances that cause this to break. Or perhaps you made silly mistake (much like I did when I tried first time to reproduce it :-)

**Comment by kawnnor** [comment]
@kdvolder 
Demo Video - [https://d.pr/v/QXZBPp](https://d.pr/v/QXZBPp)

**Comment by martinlippert** [comment]
Maybe there is a relationship between this and https://github.com/spring-projects/sts4/issues/193 ?

**Comment by kawnnor** [comment]
@kdvolder spring-boot-tools 1.4.0-201902011927 works fine. 👍
