### ISSUE TITLE
JAVA_HOME issue on MacOs

### ISSUE THREAD

**Issue by teterovic** [spring-projects/sts4#20]
After I install the Spring Boot Java Support for VS Code i get the following error (when opening a .java file):

![image](https://user-images.githubusercontent.com/7413906/33432576-d2f67ace-d5d8-11e7-9c7b-3dd26ea1acfa.png)

`JAVA_HOME environment variable points either to JRE or JDK missing "lib/tools.jar" hence Boot Hints are unavailable`

```
echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home
```

The environment variable is well defined(see image) and recognised by following extensions without issues the:
Language Support for Java(TM) by Red Hat
Java Debugger by Microsoft

Probably I miss something else but the message is misleading - what are Boot Hints ?

VS Code 1.18.1
MacOS High Sierra

**Comment by martinlippert** [comment]
Did you check whether this JDK contains the mentioned `lib/tools.jar` file? What happens if you update to a more recent JDK (1.8.0_152)?

**Comment by martinlippert** [comment]
The `hints` that are mentioned in the message are a feature of the tooling, see https://github.com/spring-projects/sts4/wiki/User-Guide#live-application-information-hovers, and this feature is not available if the tooling can't find the tools.jar in the JDK install.

**Comment by teterovic** [comment]
![image](https://user-images.githubusercontent.com/7413906/33433332-777948c2-d5db-11e7-841a-495bfcb4ce68.png)

jes it's there, I will try to update JDK and report back

**Comment by martinlippert** [comment]
If this continues to not work with a more recent JDK8 version, we definitely need to investigate this further.

**Comment by teterovic** [comment]
It worked ! Tnx !

**Comment by martinlippert** [comment]
Great, thanks for letting us know.

**Comment by ton3r** [comment]
What is the solution? I've the same problem.

**Comment by teterovic** [comment]
Download the latest JDK
