### ISSUE TITLE
[question] Spring Bean XML editor as a separate plugin

### ISSUE THREAD

**Issue by gayanper** [spring-projects/sts4#201]
When working with legacy spring projects which still contains spring bean xml definitions files, the STS3 XML Editor becomes really handy. So can we fork the STS3 and extract the XML editor as a separate tool plugin which can be installed as a optional plugin together with STS4 ?

**Comment by martinlippert** [comment]
You can already install the STS3 Add-On Pack from the Eclipse Marketplace into an STS4 installation to get the STS3 tooling added to your STS4-based IDE:

https://marketplace.eclipse.org/content/spring-tools-3-add-aka-spring-tool-suite-3

Do you need anything else?

**Comment by gayanper** [comment]
I was hoping to get only the xml editor behavior as a separate install-able plugin so that we don't need to install all the default STS3 plugins just for xml editor

**Comment by gayanper** [comment]
And why are these optional components are marked as required
![image](https://user-images.githubusercontent.com/7471994/52853829-bcffe400-3142-11e9-9700-c6bba9f7df2c.png)

**Comment by martinlippert** [comment]
You could try to minimize the number of plugins that you install into STS4 down to a smaller set that includes the bean XML editor piece, but you would still get the underlying mechanics of loading the beans model, etc. Feel free to use the p2 repo and install just the `Spring IDE Core` feature, that includes the XML editor.

**Comment by martinlippert** [comment]
Regarding your question about the marketplace entry, the list of features that are required for the marketplace entry is more or less a random list, to be honest. It is a direct successor of the previous entry in the marketplace that was used to install STS3 into Eclipse before STS4 existed and therefore copied those settings. But we can change that for sure and turn those optional components into optional, but pre-selected features. Would be somewhat consistent with the feature name, telling people that it is "optional"... :-)

**Comment by martinlippert** [comment]
I updated the marketplace definition accordingly, those optional features are now also optional on the marketplace entry. Feel free to give it a try (might need to restart Eclipse in order to get the latest def from the marketplace).
