### ISSUE TITLE
Installation compatibility problem between STS 4.1.2 and STS 3.9.7 Add-on

### ISSUE THREAD

**Issue by hbrands** [spring-projects/sts4#206]
Eclipse IDE for Enterprise Java Developers.
Version: 2018-12 (4.10.0)
Build id: 20181214-0600
with STS 4.1.2 installed from Marketplace
on Windows 10 Prof:

When trying to install the Spring Tools 3 Add-on from Marketplace (3.9.7) the installation cannot be completed. 
Error follows:

Will not be installed:
Spring IDE Boot Support

Cannot complete the install because of a conflicting dependency.
  Software being installed: Spring IDE Boot Support 3.9.7.201812201020-RELEASE (org.springframework.ide.eclipse.boot.feature.feature.group 3.9.7.201812201020-RELEASE)
  Software currently installed: Spring Tool Suite 4 Main Feature 4.1.2.201902210640-RELEASE (org.springframework.boot.ide.main.feature.feature.group 4.1.2.201902210640-RELEASE)
  Only one of the following can be installed at once: 
    Templates 3.9.8.201902210359-CI-B2163 (org.springframework.ide.eclipse.boot.templates 3.9.8.201902210359-CI-B2163)
    Templates 3.9.7.201812201020-RELEASE (org.springframework.ide.eclipse.boot.templates 3.9.7.201812201020-RELEASE)
  Cannot satisfy dependency:
    From: Spring Tool Suite 4 Main Feature 4.1.2.201902210640-RELEASE (org.springframework.boot.ide.main.feature.feature.group 4.1.2.201902210640-RELEASE)
    To: org.eclipse.equinox.p2.iu; org.springframework.ide.eclipse.boot.templates [3.9.8.201902210359-CI-B2163,3.9.8.201902210359-CI-B2163]
  Cannot satisfy dependency:
    From: Spring IDE Boot Support 3.9.7.201812201020-RELEASE (org.springframework.ide.eclipse.boot.feature.feature.group 3.9.7.201812201020-RELEASE)
    To: org.eclipse.equinox.p2.iu; org.springframework.ide.eclipse.boot.templates [3.9.7.201812201020-RELEASE,3.9.7.201812201020-RELEASE]

I think STS 4.1.0 und 3.9.7 seemed to work fine,
What to do? Can I proceed the installation without installing "Spring IDE Boot Support" from 3.9.7?
Will there be a 3.9.x version compatible with 4.1.2?

**Comment by martinlippert** [comment]
This happens because STS 4.1.2 includes a newer version of some of the common bundles than the STS3 Add-On entry on the marketplace, therefore the marketplace install complains about the fact that you want to install two different versions of some underlying commons bundles.

You can safely ignore that and continue the installation without the `Spring IDE Boot Support` feature. You already got all the nice boot support via the STS4 install.
