### ISSUE TITLE
Unable to install STS on Eclipse: peer not authenticated

### ISSUE THREAD

**Issue by heruan** [spring-projects/sts4#208]
I'm testing Eclipse 2019-03 M3 but I'm not able to install STS from the Marketplace as it gives me this error:

```
Unable to read repository at https://download.springsource.com/release/TOOLS/sts4/update/e4.11/compositeContent.xml.
peer not authenticated
```

Other Marketplace products install fine.

**Comment by heruan** [comment]
I've tried to install LSP4E snapshot as described in https://github.com/spring-projects/sts4/issues/207#issuecomment-469245551 but it didn't make any difference: still unable to install with same error.

**Comment by martinlippert** [comment]
The LSP4E snapshot solves a different problem, so that is unrelated. The solution to the "peer not authenticated" problem is to import the certificate into your JDKs keystore:

https://stackoverflow.com/questions/22887829/peer-not-authenticated-while-importing-gradle-project-in-eclipse

Another way to work around this is to use a `http` URL for the p2 repo (instead of the `https` variant) and install it from there.

But let me keep this issue open for now. We should try to find a better solution for this.

**Comment by heruan** [comment]
Trusting the certificate didn't help, unfortunately. I tried trusting both the CA (but it was already trusted) and the host, but I get the same error.

**Comment by heruan** [comment]
Plus, even if I use the `http` update site it eventually fails with:

```
An error occurred while collecting items to be installed
session context was:(profile=epp.package.jee, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Unable to read repository at https://download.springsource.com/release/TOOLS/sts4/update/4.1.2.RELEASE/e4.11/plugins/io.projectreactor.reactor-core_3.1.9.201901081830-RELEASE.jar.
No PSK available. Unable to resume.
Unable to read repository at https://download.springsource.com/release/TOOLS/sts4/update/4.1.2.RELEASE/e4.11/features/org.springframework.boot.ide.main.feature_4.1.2.201902210653-RELEASE.jar.
No PSK available. Unable to resume.
Unable to read repository at https://download.springsource.com/release/TOOLS/sts4/update/4.1.2.RELEASE/e4.11/plugins/org.springframework.ide.eclipse.imports_3.9.8.201902210359-CI-B2163.jar.
No PSK available. Unable to resume.
```

**Comment by martinlippert** [comment]
@heruan That sucks and it looks like the switch to https isn't as easy as I thought it would/should be. I apologize for the pain that this is causing. Let me switch the necessary p2 repos back to http for now, so that you can proceed - and troubleshoot the https issues separately.

**Comment by martinlippert** [comment]
In the meantime, feel free to use this p2 repo directly:

http://download.springsource.com/release/TOOLS/sts4/update/4.1.2.RELEASE/e4.11/

(for Eclipse 2019-03 installs)

**Comment by martinlippert** [comment]
@heruan btw, the `No PSK available. Unable to resume.` error might be a bug in the JDK. Are you running JDK11? If so, switching the IDE to JDK8 solves that issue.

**Comment by heruan** [comment]
@martinlippert Yes, I'm running JDK11. Can I use that repo to install via Marketplace? I tried to install via "Install new software" but I'm not sure what to select to have the same outcome as the install from the Marketplace.

**Comment by martinlippert** [comment]
@heruan I updated the marketplace entry as well as the composite update sites to use http again, so after pressing reload in the preferences for the installed update sites you should be able to get things installed using the marketplace again. It might happen that there is cached data somewhere in the middle (there are various levels of caching in place for these urls and I am not able to wipe all those caches at the moment).

So you can wait for a day or two and try again or download a ready-to-use STS4 distribution, which is based on Eclipse 2018-12. You could also try a nightly build of STS4 on Eclipse 2019-03 from here: https://dist.springsource.com/snapshot/STS4/nightly-distributions.html

**Comment by martinlippert** [comment]
OK, I am done with the in-depth analysis of this and it turns out to be the bug in JDK11 when accessing TLS 1.3.

The the reference, the JDK11 bug is:
https://bugs.openjdk.java.net/browse/JDK-8211806

Therefore we disabled TLS 1.3 on those domains and offer TLS 1.2 only until JDK11 fixes that bug. This allows me to turn all the download URLs and composite update sites back to https, which I will do now.

**Comment by barathgdkrish** [comment]
> In the meantime, feel free to use this p2 repo directly:
> 
> http://download.springsource.com/release/TOOLS/sts4/update/4.1.2.RELEASE/e4.11/
> 
> (for Eclipse 2019-03 installs)

You're a life savior ! May I ask if there's been any fix/update for resolving this?

**Comment by duyplus** [comment]
(for Eclipse 2022-06 installs)
`https://download.springsource.com/release/TOOLS/sts4/update/e4.24/`
