### ISSUE TITLE
Developer documentation on language server

### ISSUE THREAD

**Issue by AlexFalappa** [spring-projects/sts4#209]
Please consider adding some pages on the Wiki about technical details of the language server.

This documentation should ideally be targeted at developers who would like to integrate the language server into plugins for IDE/editors other than Eclipse, VsCode and Atom.

I would like to start experimenting with the language server in a plugin for the Apache NetBeans IDE where initial support for the Language Server Protocol landed recently (https://github.com/apache/incubator-netbeans/pull/629 and https://github.com/apache/incubator-netbeans/pull/1088).

Some topics I would suggest to cover:
* VM options recommendations for launching the server
* Supported Protocol API (version and methods)
* Command line arguments, if any
* Protocol debugging facilities, if any
* Relation/dependencies on a Java language server
* Relation/dependencies on build systems (Maven, Gradle), if any

**Comment by martinlippert** [comment]
@AlexFalappa Sorry for being late here, it is awesome that you are interested in working on some Netbeans support for the language servers (or plugging the language servers into the Netbeans LSP support).

I started this wiki page to write down some documentation of what you are asking for. I am starting this right now, so it will take a bit until it answers all your questions, but please feel free to post more questions here and ask for more details here. We are very happy to help you getting the Netbeans support working.

**Comment by martinlippert** [comment]
Will collect things here:
https://github.com/spring-projects/sts4/wiki/Developer-Documentation

**Comment by AlexFalappa** [comment]
@martinlippert thanks for taking my documentation request into consideration.

I will follow the development on the wiki page.

**Comment by martinlippert** [comment]
The mentioned page turned into a whole section in the meantime, please take a look at the wiki and look for the "Developer Manual" section. If you are missing something, please let us know and we can add more details to those pages. Would just be good to know where you need more details.

For now, I will close this issue - but re-open anytime if you are missing anything.
