### ISSUE TITLE
Allow configuration of VM arguments for LSP process "PropertiesLauncher"

### ISSUE THREAD

**Issue by hbrands** [spring-projects/sts4#211]
Spring STS 4 seems to launch a separate process called PropertiesLauncher. I guess it's for supporting the Language Server Protocol.

Currently there is no way to pass VM arguments for this process, for example to customize garbage collector and memory settings.

Please provide a way to customize these options.

Reason:
I notice from time to time a slow down which seems to be related to increased garbage collection activity because of a full old generation in the heap. The max heap seems to be limited to 1G.

**Comment by martinlippert** [comment]
This got implemented for the 4.2.0 release:

To set specific VM arguments for the language server, please add a specific system property to your eclipse.ini file (or SpringToolSuite4.ini, depending on your install): -Dboot.ls.custom.vmargs

For example, you could add a line like this:

-Dboot.ls.custom.vmargs=-Xmx3G to enable 3G of max heap space for the language server JVM. If you want to set more than one argument, you can add them all at once, for example:

-Dboot.ls.custom.vmargs=-Xmx3048m,-Dsomething=super,-Xdebug,-Xrunjdwp:server=y,transport=dt_socket,address=4000,suspend=n

The individual arguments are comma separated and the value of this property is split into the individual pieces using ,- as the indicator for different arguments.
