### ISSUE TITLE
Do not use jmods-directory to find JRE installation

### ISSUE THREAD

**Issue by ChristianCiach** [spring-projects/sts4#264]
https://github.com/spring-projects/sts4/blob/d86becebe7e672044de93b2da3afbed5bee47438/eclipse-language-servers/org.springframework.tooling.ls.eclipse.commons/src/org/springframework/tooling/ls/eclipse/commons/JRE.java#L88

This line uses the jmods directory to find the JRE since java 9. I think this should be changed, because the jmods are not necessary for this plugin to work.

We noticed this because under Fedora/CentOS the jmods are found in their own rpm package (java-11-openjdk-jmods). Neither the JRE (java-11-openjdk) nor the JDK (java-11-openjdk-devel) depend on java-11-openjdk-jmods, so most developers didn't have this package installed.

**Comment by kdvolder** [comment]
Thanks for reporting this.

We can change it sure, but do you have a better suggestion on how we would recognize or find a JRE location then? 

Also, we would need to be able to determine whether the installation is a JRE versus a JDK. Any thoughts on that?

Also, I am not certain whether all our tooling would actually work correctly when the jmods are not installed. This is something that would have to be tested. We have only tested our tools with a standard/complete installation not something that has been deliberately stripped down.

**Comment by ChristianCiach** [comment]
> Also, we would need to be able to determine whether the installation is a JRE versus a JDK. Any thoughts on that?

Well, since Java 9 there isn't really the concept of a JRE anymore (at least not in the sense of a system-wide installation, but as application-bundled runtime images). 

> We have only tested our tools with a standard/complete installation not something that has been deliberately stripped down.

Looking at my previous paragraph, I get the feeling that I've just weakened my own argument :) In the same way at it doesn't really make sense to search for a JRE (which would be just a stripped down JDK since java 9, heavily depending on the distributor), it also doesn't make sense to accept a jmod-less JDK. 

This really comes down to this question: Is there a better way to distinguish a pre-java-9 JAVA_HOME from a post-java-9 one? While I have yet to encounter an OpenJDK 9+ distribution without a "release" file in its home, I don't know if this file is mandatory. 

So, as long as I don't have a better idea to find the JDK, it seems unreasonable to ask you to do so. I will close this issue now.

In my opinion, the class "JRE" should be renamed to "JDK", because you are actually searching for JDK installations and JREs are not a thing anymore.

**Comment by martinlippert** [comment]
I agree about the renaming... :-)

The reason why we are looking for a JDK is: we need the tools.jar (in the pre-Java9 world) to be available at runtime (which ships with a JDK only). In the post-Java8 world, there is a corresponding jmod file that contains the necessary API for us to use, but it seems indeed hard to identify whether it is there on all the various platforms and configs.
