### ISSUE TITLE
4.2.0 RELEASE ?

### ISSUE THREAD

**Issue by yl-yue** [spring-projects/sts4#266]
![image](https://user-images.githubusercontent.com/39790401/55047909-47602f80-5081-11e9-9e9c-ff5299aa4697.png)

I can't find anywhere to download him.
He solved the problem I am facing now, so I am eager to be updated.

**Comment by martinlippert** [comment]
The release got delayed by about one week, coming out this week. Will update the wiki, thanks for the pointer.
