### ISSUE TITLE
4.2.0 RELEASE bug summary

### ISSUE THREAD

**Issue by yl-yue** [spring-projects/sts4#268]
It is now rolled back to 4.1.0.

1. Compilation problems
After jdk9 modularization, javax.xml compilation report invalid version is introduced through maven
As shown in figure:
![image](https://user-images.githubusercontent.com/39790401/55525564-22447000-56c4-11e9-931b-0f606ac45486.png)
This compilation problem does not exist after rolling back the IDE

2. Performance issues
Ide has been continuously stuck, the overall use of fluency greatly decreased

**Comment by martinlippert** [comment]
1. would it be possible to point us at a sample project that could help us to reproduce the issue? I haven't come across this one yet, so I would love to see this happening on my machine for debugging.

2. we desperately need more details and information about this one, it would be wonderful if you could help us with that and re-create that environment. Then, when the IDE is stuck or hanging, please capture a thread dump (using jps and jstack) and attach a few of those here. You could also fire up `jconsole` to see if the language server process is running out-of-memory (we had another user reporting this) and therefore causing hangs. Can you have a look?

**Comment by martinlippert** [comment]
@yl-yue why did you close this? Did you solve the issue? If so, how?

**Comment by yl-yue** [comment]
@martinlippert Sorry, this problem has not been solved.
The most intuitive feeling I get from performance problems is that they are caused by compilation (win10 processes often go into a state of suspended animation), which may only need to solve the compilation problems introduced by JAVA9 modules.
Perhaps it was a compilation problem, and I was also in a state of suspended animation when I used the prompt in the springboot project application.yml file.I apologize for not being able to provide a sample project for this.

**Comment by martinlippert** [comment]
One of the most important questions here is whether this is a problem with the underlying Eclipse platform and the JDT tooling or not (and instead a specific problem for the Spring Tools 4). Can you try this on a vanilla Eclipse 2019-03 installation, just to see if the problem exists there, too? If so, filing a bug with Eclipse might be useful to gather more insights into what happens, I think.
