### ISSUE TITLE
Font size - Java 11

### ISSUE THREAD

**Issue by naturzukunft** [spring-projects/sts4#270]
Hi there , 
if I start STS with java 11 
C:\xxxxxxx\sts-4.0.0.RELEASE\SpringToolSuite4.exe -vm "C:\xxxxx\openjdk-11.0.2\bin\javaw.exe"
Then the font size e.g. in the package explorer is very big. This is only the case, if I use java 11. It's undependend from opendJdk or commercialJdk.

In #219 there is a hint, that the font size is relating to the system settings, but that means, that jdk11 changes the system settings ???

STS:
Version: 4.2.0.RELEASE
Build Id: 201903290612

**Comment by martinlippert** [comment]
I am not aware of any specific changes to with regards to JDK11, but we should try to double check. First step would be to try a vanilla Eclipse 2019-03 installation with JDK8 and JDK11 to see if this is something related to the underlying Eclipse platform or not. Can you double check?

**Comment by naturzukunft** [comment]
Yesterday i had trouble with adding the -vm settings to the SpringToolSuite4.ini. That was the reason, why I pass the jdk per argument to SpringToolSuite4.exe. Today the SpringToolSuite4.ini is working and the Font Size Issue is not an issue any more ?!?! And now, I'm not able to reproduce the problem any more ;-(
Seems to be a problem on my machine! Will update the issue, if it happens again!

**Comment by martinlippert** [comment]
Glad to hear it is working again and thanks for letting us know.
