### ISSUE TITLE
netbeans support

### ISSUE THREAD

**Issue by yudar1024** [spring-projects/sts4#271]
netbeans began support lsp ,can you consider provide netbeans support ?

netbeans lsp link
https://blogs.apache.org/netbeans/entry/initial-language-server-protocol-support

**Comment by martinlippert** [comment]
Super awesome to see that Apache Netbeans is going to have support for the language server protocol. Absolutely fantastic news!!! And having our language servers being available for Netbeans would be great, too.

I wonder if someone from the community or someone working on the LSP support for Netbeans could provide some help here? There are already people from the community working on the integration of our language servers into Emacs (#76) and IntelliJ and we would love to support and help someone who is interested in connecting the language server to the new LSP support in Netbeans.

Anyone interested?

**Comment by martinlippert** [comment]
Ah, while browsing through the remaining issues, I found #209, so lets close this as a duplicate and help @AlexFalappa over there... :-)
