### ISSUE TITLE
STS-4.2.0 with Mint 19.1 auto-logout crashing

### ISSUE THREAD

**Issue by casper5822** [spring-projects/sts4#272]
Hello,
i have the latest Mint 19.1 with STS 4.2.0.

omething strange happens:

Assumption:
STS 4.2 works without problem with Mint 18.X.

Problem description:

When i start writing a method on an Java object, so i write just the dot and the  method autocomplete  appears, Mint kill the current session and go to the login page.
The same thing happens with the normal and latest version of the standard Eclipse:
When i run the "eclipse-inst" file, Mint kill the current session and makes an auto logout.

--------------------------------------------------------------------------------------------------------------

More information:

1. If i run STS 4 from a terminal there are these errors:
Gtk-CRITICAL **: 23:13:56.116: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

2. If i run from a terminal the eclipse-inst file there is this warning: a GTK2 no longer supported, continuing with GTK3 and then linux session crashes again.

---------------------------------------------------------------------------------------------------------------------

I tried other ide like Atom, and this problem is only with STS and in general with Eclipse 

Hope you can help me, if you have some tips.
Best regards

**Comment by martinlippert** [comment]
If this is a problem with the underlying Eclipse platform (and that is what it sounds like from your description), I would suggest to file a bug report at Eclipse via: https://bugs.eclipse.org/bugs/enter_bug.cgi?product=Platform
