### ISSUE TITLE
install Spring Tools Suite (STS) for eclipse neon(version 4.6.3) online

### ISSUE THREAD

**Issue by Tsingkai** [spring-projects/sts4#274]
How to install Spring Tools Suite (STS) for eclipse neon(version 4.6.3) online?
I do not find the update website on "https://spring.io/tools3/sts/legacy", also on "marketplace.eclipse.org".
And I just want to install online.
I do not mind the version of Spring Tools Suite (STS) ,3 or 4?

**Comment by martinlippert** [comment]
Spring Tools 4 are not available for Eclipse Neon (4.6.3), they support the latest Eclipse versions only. The latest version of Spring Tool Suite 3 (3.9.8) supports Eclipse 2018-09, 2018-12, and 2019-03.

The latest version of the Spring Tool Suite 3 that was built for compatibility with Eclipse 4.6 is 3.9.4, which you can install from this update site:

https://download.springsource.com/release/TOOLS/update/3.9.4.RELEASE/e4.6/

**Comment by martinlippert** [comment]
But please keep in mind that this version is not supported anymore, so you should seriously consider using a more recent Eclipse version as a base platform and go from there.
