### ISSUE TITLE
sts4 cannot set compiler level correctly under Centos GNOME

### ISSUE THREAD

**Issue by c3y28** [spring-projects/sts4#278]
All STS4 releases
OS: Centos 7.6 GNome

sts cannot set compiler level to java 11 even jdk 11 configured and java.version set to 11 under Centos 7.6 GNOME, but it works under Ubuntu 18.04 kde(I'm not sure if it can work on gome)

![java compiler level wrong](https://user-images.githubusercontent.com/2386133/56402722-07135c00-6291-11e9-99a1-62587f49b0ef.png)

![installed jdks](https://user-images.githubusercontent.com/2386133/56402790-5c4f6d80-6291-11e9-915e-f22286765300.png)

**Comment by martinlippert** [comment]
From a first look it sounds strange to me that the OS should have an influence here (as long as you have configured the JRE in the preferences). Did you select the JDK11 as the default one for the `JavaSE-11` execution environment? And does this work with an plain Eclipse 2019-03 install, for example the JEE package?

**Comment by c3y28** [comment]
Did you select the JDK11 as the default one for the JavaSE-11 execution environment? 
**YES, you can see it in the snapshot upper**

According your advice, I test the plain Eclipse 2019-03(Eclipse IDE for Java Developers) under Centos 7.6 GNOME, I reproduces the issue again. the configuration snapshots are listed in the following

![image](https://user-images.githubusercontent.com/2386133/56547246-67670e00-65af-11e9-928d-7e4efb75752c.png)

![image](https://user-images.githubusercontent.com/2386133/56547269-76e65700-65af-11e9-93c3-a797242ac53f.png)

![image](https://user-images.githubusercontent.com/2386133/56547281-81a0ec00-65af-11e9-9f16-b0e197dd4aa6.png)

**Comment by martinlippert** [comment]
If you click on the `Execution Environment` node in the preferences tree (the node directly under the `Installed JREs` node, which JRE is selected for the `JavaSE-11` environment?

**Comment by kdvolder** [comment]
Just making some guesses and sugestions.

1. I see in your screenshot the pom editor is dirty. So make sure to save it. If you just edited it, the change will not take effect until you do.

2. After you save the pom, you need m2e (maven/eclipse integration tooling) to update the project configuration for changes like the JRE version to take effect in the Eclipse project. So you may have to force an update by selecting 'Maven >> Update Project...' from the context menu that appears upon right-clicking on the project.

Please try those and see if it helps.

**Comment by c3y28** [comment]
> Just making some guesses and sugestions.
> 
> 1. I see in your screenshot the pom editor is dirty. So make sure to save it. If you just edited it, the change will not take effect until you do.
> 2. After you save the pom, you need m2e (maven/eclipse integration tooling) to update the project configuration for changes like the JRE version to take effect in the Eclipse project. So you may have to force an update by selecting 'Maven >> Update Project...' from the context menu that appears upon right-clicking on the project.
> 
> Please try those and see if it helps.

Thanks for your reply, but my pom editor seems dirty just because I changed the groupId since I don't want to display my company. Actually I did all you mentioned before.

**Comment by kdvolder** [comment]
@c3y28 Building and running a spring-boot app (app was generated from spring intializer) works with Java 11 for me. This is on Linux (Ubuntu 18.04.02). And I used a OpenJDK 11 that I had downloaded onto my system a while ago. 

I'm a bit at a loss why it doesn't work for you. My only guess at the moment is that it could be something todo with the JVM that you are using and how it has been configured in the workspace. From the screenshot it looks correct though so its just a wild guess. Still, maybe try to download a fresh copy of OpenJDK from an official source like here: https://jdk.java.net/archive/ 

After unpacking the fresh install, remove any other Java 11 installs from your Eclipse workspace settings. Then add the new one in. You may also need to use 'Maven >> Update Project' again to make sure M2E updates the project. Not sure if it will help, but its the only idea I have.

**Comment by c3y28** [comment]
> Ubuntu 18.04.02

Maybe you did not get what I wrote. Actually it works on my kubuntu 18.04 kde environment, what I said is ** Centos 7.6 GNOME **, you can see it in my first post.

**Comment by kdvolder** [comment]
> Actually it works on my kubuntu 18.04 kde environment, what I said is ** Centos 7.6 GNOME **, you can see it in my first post.

Yes, I did see that. It just doesn't make sense to me that this would be really *because* of the OS. It is more likely that it has something to do with the JVM that is installed and how it is setup. This is why I recommeded you try and download and use a 'official' JVM from it's source rather than use the one that is (pre-)installed via your OS. I don't really know why it doesn't work for you, and I think its going to be mostly up to you to determine what is the reason the Centos setup isn't working. To summarise though, my guess is that its not so likelty this 'because it is Centos', and more likely because of something related to the setup of the JVM, the workspace, or the Eclipse installation, or a combination of all three.

**Comment by martinlippert** [comment]
I am closing this one here due to no more activity here. If you still come across this issue, please comment and we can re-open this one again.

In that case, please also take a look at the comment from above and maybe comment on this one:

> If you click on the `Execution Environment` node in the preferences tree (the node directly under the `Installed JREs` node, which JRE is selected for the `JavaSE-11` environment?

Haven't seen a reply to that one, which might be related to the issue that is described here.
