### ISSUE TITLE
Detect @RequestMapping with path defined as constant instead of literal string

### ISSUE THREAD

**Issue by aaguilera** [spring-projects/sts4#281]
It seems that Navigation (cmd+6) cannot detect @RequestMapping-annotated methods when the URL is defined as a constant instead of a literal string.
For example:

    public class MyPaths {
        public static final String RESOURCE_PATH = "/somepath/resource";
    }
    
    @Controller
    public class MyController {
        @RequestMapping(MyPaths.RESOURCE_PATH)
        public String method() {
            ... 
        }
    }

In STS4, if I press Ctrl+6 (I'm using Eclipse-based STS4 on Linux) and start typing something like "@/some", the results list does not include the mapping for "/somepath/resource".

It would be nice if STS4 implemented such detection.

**Comment by martinlippert** [comment]
There is a CI build available that includes the implementation for this, if you want to give it an early try and provide feedback: http://dist.springsource.com/snapshot/STS4/nightly-distributions.html

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Martin Lippert:) 

Tested this again, works in general, but not for constants defined in the same source file as the request mapping. Will file a separate issue for that.

**Comment by aaguilera** [comment]
> There is a CI build available that includes the implementation for this, if you want to give it an early try and provide feedback: http://dist.springsource.com/snapshot/STS4/nightly-distributions.html

I have tested `spring-tool-suite-4-4.2.2.CI-B1732-e4.12.0-linux.gtk.x86_64.tar.gz` and it works perfectly. Kudos to the team for such a quick response!

**Comment by martinlippert** [comment]
Great to hear that it works for you and thanks for reporting this in the first place. Much appreciated.
