### ISSUE TITLE
Cannot find the option Run On Server under Run As

### ISSUE THREAD

**Issue by d02wang** [spring-projects/sts4#283]
Hi, I need help for running my existing maven project in STS 4.
I have a maven project using Java 7 and Tomcat 8.0, created by using STS 3.7. Now I download STS 4 and launch it, then point the workspace to the original one. After build, there is no error. Tomcat 8.5 is added.

Now I want to run my project on the server tomcat 8.0 or tomcat 8.5, but I cannot find the option Run As --> Run On Server like in STS 3 for the project in STS 4.

**Comment by martinlippert** [comment]
That is correct, this is a missing feature in the latest Spring Tools 4.2.1 release that got added (and fixed) for the next upcoming release (4.2.2), to be released in late May 2019.

More details on this can be found here (including a description how to fix an existing STS 4.2.1 install): https://github.com/spring-projects/sts4/issues/96#issuecomment-484522744

**Comment by Astrogeek77** [comment]
I am facing the Same issue in version 4.19.1, any method to resolve it?

**Comment by martinlippert** [comment]
The drag&drop part of this as well as the `Run On Server` menu item is part of the `Eclipse Java EE Developer Tools` feature that we don't install by default anymore into the Spring Tools distribution for Eclipse.

Yon can install this feature anytime yourself by going to `Help -> Install New Software`, then select the `Latest Eclipse Release - https://download.eclipse.org/releases/latest` update site from the dropdown, and search for the feature.

Depending on all the update sites you have collected over time in your preferences, there might be an error showing up that certain there is no repository found that contains certain bundles. In that case, make sure to de-activate all the other update sites in the preferences except from the main Eclipse one (the one mentioned above) and try the install again. Once installed and restarted, the menu items and drag&drop actions are back.

**Comment by akashsagar8** [comment]
i m also facing the same issu , although you proivided the ans ------------- help-install-new software----but i could not understand in better way, can you explain again

**Comment by martinlippert** [comment]
Please go to `Help -> Install New Software`. This opens a dialog. In the `Work with` drop-down box, select the update site `Latest Eclipse Release - https://download.eclipse.org/releases/latest`. Search for `Java EE` in the filter text field, this will trim down the list of features a bit. Then, select the `Eclipse Java EE Developer Tools`from that list, deactivate the `Contact all update sites during install...` checkbox below, and press `Next`. Then follow the next dialog pages, press finish in the end, and your are done. Hope this helps.

**Comment by akashsagar8** [comment]
thank you so much sir ji,................................................😍😍😍😍😍😍😍😍😍😍😍😘😘😘😘😘😘😘😘😘😘😘😘
