### ISSUE TITLE
Concourse VSCode Does not recognize "initial_path" param for S3 resource

### ISSUE THREAD

**Issue by timlharrison** [spring-projects/sts4#284]
The S3 resource has an 'initial_path' parameter and the concourse editor does not recognize it as a valid property.

**Comment by kdvolder** [comment]
For easy reference docs: https://github.com/concourse/s3-resource

**Comment by timlharrison** [comment]
I'm confused by the above response... the issue is tha tthe VSCode plugin gives me an error when I use the 'initial_path' parameter.

![image](https://user-images.githubusercontent.com/33101253/57152688-27b7d780-6da2-11e9-9a48-fde175cae2fa.png)

**Comment by kdvolder** [comment]
> I'm confused by the above response... the issue is that the VSCode plugin gives me an error when I use the 'initial_path' parameter.

Sorry about that. I just pasted the link to the docs so it would be easy for me to find. It was not in any way questioning the validity of your bug report. It would have been nice to add some more info to your report though, maybe an example of some actual content producing that error would have been nice, as well as the exact text of the error you see reported (which you have now provided).

Sure, I can probably figure out what you are talking about somehow (and the docs... I will need for that), but if you provided an actual example that I can paste and try in the editor... that really would help somewhat.

**Comment by timlharrison** [comment]
Got it - thank you for the feedback.

**Comment by kdvolder** [comment]
Looking at the docs 3 other related properties are also missing from the schema. So all 4 of these need to be added:

- initial_path
- initial_version
- initial_content_text
- initial_content_binary

**Comment by kdvolder** [comment]
Took a bit longer to implement than I thought. There's some interesting constraints amongs the 4 properties that I wanted to capture in the schema. 

The constraints are as follows:
- at most one of 'initial_path' or 'initial_version' should be defined
- at most one of (or zerof 'initial_content_text' or 'initial_content_binary' should be defined
- when 'initial_path' is used, then 'regexp' must also be used
- when 'initial_version' is used, then 'versioned_file' must also be used.

When any of these constraints are violated the editor shows a error marker.

**Comment by kdvolder** [comment]
@timlharrison You can try the fixed version. Just download and install snapshot .vsix file from this page: http://dist.springsource.com/snapshot/STS4/nightly-distributions.html

Hopefully it now works as you expect. Do let me know if you find other problems.

**Comment by timlharrison** [comment]
Its happy now - thanks very much!
