### ISSUE TITLE
Passing multiple arguments to gradlew in Run Configuration of STS4

### ISSUE THREAD

**Issue by hanct** [spring-projects/sts4#285]
Spring Tool Suite: v4.2.1 Gradle: v5.3.1

Hi all,

I try passing multiple arguments to the gradle task (called bootRun) into my spring boot application via the STS Run configuration dialog box. 
![RunConfigurationSTS4](https://user-images.githubusercontent.com/4410920/57114115-4c985480-6d7a-11e9-8441-49e8a43ac476.png)

But my StS4 throws error as shown below
![RunConfigurationSTS4-result](https://user-images.githubusercontent.com/4410920/57114163-88cbb500-6d7a-11e9-8602-d6622e806b3b.png)

But yet, when i run on the same project using commandline (instead of STS4), it is successful
![gradlew-result](https://user-images.githubusercontent.com/4410920/57114227-d2b49b00-6d7a-11e9-8da9-1686b1aacbf6.png)

Is this a bug in the STS4 tool? Or is it the way I configure STS4 wrongly? Even if i pass the entire string **--args="--data.server=remoteHost:999 --spring.main.banner-mode=off"** into the Program or JVM arguments of the Run Configuration dialog box, also no work.

**Comment by kdvolder** [comment]
> Is this a bug in the STS4 tool? Or is it the way I configure STS4 wrongly? 

If its a bug or not? I'm not sure. But if it is a bug it is a problem with BuildShip (Eclipse Grade Tooling). BuildShip is shipped / included with STS but it's part of 'generic' Eclipse, it's not an STS specific component that we ourself maintain.

I advise you try and get help here: https://discuss.gradle.org/c/help-discuss/buildship

If you are doing something wrong, they'll be able to help you, and if its a bug, they'll probably direct you were to report it.
