### ISSUE TITLE
JHipster Spring Boot fails after import on Maven projects

### ISSUE THREAD

**Issue by AndreKrebs** [spring-projects/sts4#288]
I created a Spring Boot project with Maven using JHipster (without the front end) and I imported the project to STS-4 as a Maven project and every time I import that, the error that appears in the image occurs.

![baXbf](https://user-images.githubusercontent.com/6606494/57527016-546d7100-7305-11e9-8cf4-915a16a7f455.png)

I tried:
- project > clean;
- right click in project > Run > Maven clean;
- right click in project > Maven > Update project;

Usually this steps work, but not in this project. When i open the terminal and write mvn clean package and run the .war or execute ./mvnw the API works.

STS-4 version:
Version: 4.2.1.RELEASE
Build Id: 201904170946

Project source: https://drive.google.com/open?id=1bxMnGQCWY7_tcCxgzvN6RVZ4s72vh3O-

**Comment by kdvolder** [comment]
This sounds like a problem with Eclipse platform / JDT /  M2E rather than a problem specific to STS... unless it works properly in a vanilla Eclipse, have you tried that?

**Comment by martinlippert** [comment]
Closing this one due to no additional information being provided here. If you come across something like this again, please comment and we can re-open or create a new issue and we will investigate.
