### ISSUE TITLE
Open Call Hierarchy (Ctrl + Alt + H) invalid

### ISSUE THREAD

**Issue by yl-yue** [spring-projects/sts4#289]
**version**
Version: 4.2.1.RELEASE
Build Id: 201904170946

**issues**
Open Call Hierarchy (Ctrl + Alt + H) invalid
Show Caller Hierarchy
![image](https://user-images.githubusercontent.com/39790401/57602762-9eb75200-7592-11e9-9d8a-588e105f2ff9.png)
The invocation hierarchy could not be found

**Comment by martinlippert** [comment]
This sounds a lot like a duplicate of https://github.com/spring-projects/spring-ide/issues/372 and probably related to an issue in the underlying Eclipse platform. Would be great if you could take a look and see if you can reproduce this issue with a vanilla Eclipse 2019-03 or 2019-06 version to see if we can identify the issue in more detail.

**Comment by yl-yue** [comment]
This issue has been resolved in the Spring Tool Suite 4.4.0.release

**Comment by martinlippert** [comment]
Good to hear that this works again for you. Thanks for letting us know.
