### ISSUE TITLE
Ide hangs waiting for language server on ctrl click actions

### ISSUE THREAD

**Issue by fosorio** [spring-projects/sts4#29]
-Start fresh install of sts4 beta
-Create a demo project (similar to [https://spring.io/blog/2017/12/04/spring-tips-spring-tool-suite-4](url))
-Open DemoApplication.java
-Ctrl-click on an annotation, (or press ctrl-6)
-Eclipse hangs for around a minute, then nothing happens.

This is the main thread stacktrace during that time:
`    java.util.concurrent.locks.LockSupport.parkNanos line: 215 
   java.util.concurrent.CompletableFuture$Signaller.block line: 1695 
   java.util.concurrent.ForkJoinPool.managedBlock line: 3323 
   java.util.concurrent.CompletableFuture.timedGet line: 1775 
   java.util.concurrent.CompletableFuture.get line: 1915 
   org.eclipse.lsp4e.LanguageServerWrapper.getServerCapabilities line: 488 
   org.eclipse.lsp4e.LanguageServiceAccessor.getLSWrappers line: 243 
   org.eclipse.lsp4e.LanguageServiceAccessor.getLSPDocumentInfosFor line: 354 
   org.eclipse.lsp4e.operations.documentLink.DocumentLinkDetector.detectHyperlinks line: 86 
   org.eclipse.ui.texteditor.HyperlinkDetectorRegistry$HyperlinkDetectorDelegate.detectHyperlinks line: 78 
   org.eclipse.jface.text.hyperlink.HyperlinkManager.findHyperlinks line: 286 
   org.eclipse.jface.text.hyperlink.HyperlinkManager.findHyperlinks line: 259 
   org.eclipse.jface.text.hyperlink.HyperlinkManager.mouseMove line: 454 
   org.eclipse.swt.widgets.TypedListener.handleEvent line: 213 
   org.eclipse.swt.widgets.EventTable.sendEvent line: 86 
   org.eclipse.swt.widgets.Display.sendEvent line: 4428 
   org.eclipse.swt.widgets.Widget.sendEvent line: 1079 
   org.eclipse.swt.widgets.Display.runDeferredEvents line: 4238 
   org.eclipse.swt.widgets.Display.readAndDispatch line: 3817 
`

I also noted that when opening sts, a long time (several minutes) was spent on "Initialize Languague Server For DemoApplication". Stacktrace:

`   sun.misc.Unsafe.park line: not available [native method]
   java.util.concurrent.locks.LockSupport.park line: 175 
   java.util.concurrent.CompletableFuture$Signaller.block line: 1693 
   java.util.concurrent.ForkJoinPool.managedBlock line: 3323 
   java.util.concurrent.CompletableFuture.waitingGet line: 1729 
   java.util.concurrent.CompletableFuture.join line: 1934 
   org.eclipse.lsp4e.LanguageServerWrapper.getServer line: 445 
   org.eclipse.lsp4e.LanguageServiceAccessor.getLSPDocumentInfosFor line: 357 
   org.eclipse.lsp4e.ConnectDocumentToLanguageServerSetupParticipant$1.run line: 74 
   org.eclipse.core.internal.jobs.Worker.run line: 56 `

**Comment by martinlippert** [comment]
Running on Windows? Then it is probably a duplicate of #25 . Wanna try a latest CI build to see if that works better? 
http://dist.springsource.com/snapshot/STS4/nightly-distributions.html

Gonna release an updated public beta with a fix very soon.

**Comment by fosorio** [comment]
Yes, I'm on Windows, probably a duplicate. Sorry, didn't see that one. I'll try the latest build.

Thanks for the quick response!

**Comment by fosorio** [comment]
Confirmed it's working with latest CI build

**Comment by martinlippert** [comment]
Great to hear the CI build is working for you. And thanks for checking.
