### ISSUE TITLE
Maven configuration error

### ISSUE THREAD

**Issue by jmc420** [spring-projects/sts4#291]
Hi

I downloaded STS 4.2.1.RELEASE and created a simple demo project.

I get a weird Problem saying:

Description	Resource	Path	Location	Type
Unknown	pom.xml	/demo	line 1	Maven Configuration Problem

When I open the pom.xml, the first line <?xml version="1.0" encoding="UTF-8"?> is highlighted with an error.

I can load the pom.xml into another version of eclipse without problem.

Here is the screen shot
<img width="810" alt="Screen Shot 2019-05-17 at 12 28 07" src="https://user-images.githubusercontent.com/11723529/57925216-57390a80-789f-11e9-9105-b8017253060c.png">

**Comment by BoykoAlex** [comment]
We are looking into it already. Looks like M2E there is NPE occurring in Maven Jar Archiver plugin and that is the source for that error... I have created: https://bugs.eclipse.org/bugs/show_bug.cgi?id=547409 for now

**Comment by thackel** [comment]
Until its fixed just downgrade the `maven-jar-plugin` like here:
https://github.com/spring-projects/spring-boot/issues/16846
