### ISSUE TITLE
AspectJ in STS4 no coverage

### ISSUE THREAD

**Issue by Mehlstaub** [spring-projects/sts4#296]
For every single Project that is using AspectJ i get an Error in Eclipse and the Project won't work correctly.

Description	Resource	Path	Location	Type
Plugin execution not covered by lifecycle configuration: org.codehaus.mojo:aspectj-maven-plugin:1.8:compile (execution: default, phase: compile)	pom.xml	/3D-Service-server	line 245	Maven Project Build Lifecycle Mapping Problem

I tried update sites for AJDT but it seems these are not ready for STS4 yet. Is there a way to get a working AspectJ Integration for STS4?

**Comment by aclement** [comment]
AJDT dev builds should be fine they just aren't included in STS4 (IIRC) so you need to manually install. Some variant of `http://download.eclipse.org/tools/ajdt/410/dev/update` should be fine as an update site. What error do you get that makes you think they aren't ready?

**Comment by Mehlstaub** [comment]
You are absolutly right. I was only using Marketplace. Thanks.
