### ISSUE TITLE
Eclipse Quick Text Search: History of search terms

### ISSUE THREAD

**Issue by achimmihca** [spring-projects/sts4#297]
I would like to have the text field to enter the search term as a dropdown like in the normal search dialog of Eclipse. When clicking on the dropdown, it will show the last n searched terms (let's say 10). Clicking on such a search term will enter it in the search box.

It is a minor issue but common for search boxes and useful at times.

**Comment by martinlippert** [comment]
Indeed, good idea. The quick text search feature got contributed to the Eclipse platform itself, so it would be great if you could submit this feature request now to: https://bugs.eclipse.org/bugs/enter_bug.cgi?product=Platform
