### ISSUE TITLE
Eclipse Quick Text Search: Regular Expressions

### ISSUE THREAD

**Issue by achimmihca** [spring-projects/sts4#298]
Would be nice to have a toggle option to search using regular expressions.
This would also enable to look for whole words using "\bMYWORD\b".

**Comment by martinlippert** [comment]
The quick text search is designed to be super fast and the performance aspect of it is very important here, so we would need to carefully investigate the impact of regex matching on the overall execution speed here.

In the meantime, the quick text search feature got contributed to the Eclipse platform itself, so it would be great if you could submit this feature request now to: https://bugs.eclipse.org/bugs/enter_bug.cgi?product=Platform
