### ISSUE TITLE
Eclipse Quick Text Search: Scroll in Preview Window

### ISSUE THREAD

**Issue by achimmihca** [spring-projects/sts4#299]
Would be nice if one could scroll in the preview window. Sometimes I am missing a few lines and extending the viewport is not a solution for me.

**Comment by martinlippert** [comment]
Indeed, good idea. The quick text search feature got contributed to the Eclipse platform itself, so it would be great if you could submit this feature request now to: https://bugs.eclipse.org/bugs/enter_bug.cgi?product=Platform
