### ISSUE TITLE
Support in_parallel step in Concourse Language Server

### ISSUE THREAD

**Issue by jghiloni** [spring-projects/sts4#300]
In Concourse 5.0, the `aggregate` step was deprecated in favor of the new `in_parallel` step. Using that in VS Code causes syntax errors from the language server. I'll be happy to provide a PR to solve this.

**Comment by kdvolder** [comment]
PR would be welcome. Be aware however that we can't take PR unless you sign the CLA. See: https://github.com/spring-projects/sts4/blob/master/CONTRIBUTING.adoc

Please let me know if/when you have signed the CLA (or if there is a reason that you cannot, in which case I can fix the issue myself and I thank you for at least reporting it :-)

**Comment by kdvolder** [comment]
Feedback on PR. Looks good at first sight for the most part. I will still need to do a more thorough review. Some quick feedback:

- aggregate should be deprecated (as you stated). I could also consider this a separate issue however so its not a requirement for accepting your PR.

- the hover docs should be in markdown (yes, there is some html hoverdoc in the repo, but this is a holdover / legacy, the intention is to turn everything into markdown going forward, so newly added docs should be in markdown only).

**Comment by jghiloni** [comment]
Thanks for the feedback -- I'll convert the doc and get that added to the PR.

**Comment by jghiloni** [comment]
Also re: deprecating `aggregate` ... that's only true for 5.x and beyond, and currently, Pivotal only supports 4.2.3. That's not to say it shouldn't be marked deprecated, but I call it out to point to the fact that a large portion of the Concourse userbase is still on 4.x. Calling `fly set-pipeline` on a 5.x server with a pipeline that has `aggregate` steps gives a useful deprecation warning and, IMO, is sufficient for now.

**Comment by kdvolder** [comment]
Okay, fair enough, let's hold of on the deprecation, maybe a bit too soon :-)
