### ISSUE TITLE
Unable to debug multiple projects in Visual Studio Code

### ISSUE THREAD

**Issue by pravinpatil83** [spring-projects/sts4#305]
Hi, I am unable to debug if I start multiple projects in debug mode using Spring Boot Dashboard extension in VS Code. Single project debug works great. Any help on this would be great.

**Comment by martinlippert** [comment]
I would suggest to raise the issue over here: https://github.com/Microsoft/vscode-spring-boot-dashboard - that team knows the boot dashboard as well as the launch/debug features pretty well
