### ISSUE TITLE
[vscode-concourse] complains about vars in task step

### ISSUE THREAD

**Issue by pascalwhoop** [spring-projects/sts4#307]
![image](https://user-images.githubusercontent.com/2284951/59683302-77722700-91c7-11e9-8768-fa4240e90949.png)
Docs of concourse:
https://concourse-ci.org/task-step.html#task-step-vars

**Comment by kdvolder** [comment]
The fix should now be available from snapshot build. A vscode vsix file can be downloaded here:

http://dist.springsource.com/snapshot/STS4/nightly-distributions.html
