### ISSUE TITLE
Text becomes garbled when scrolling left or right

### ISSUE THREAD

**Issue by hafarey** [spring-projects/sts4#312]
In both the Editor view (containing a Java source file) and the Console view, the text becomes garbled when scrolling left or right.  It seems to be worse when scrolling slowly.  Refer to the attached screenshot for an example.

This issue started happening after I upgraded to the latest version of STS 4 (via "Check for Updates").  The version info is below.

Spring Tool Suite 4 
Version: 4.3.0.RELEASE
Build Id: 201906200901
(Running on macos High Sierra version 10.13.6)

![image](https://user-images.githubusercontent.com/17915941/59993178-97578e00-9692-11e9-9aae-0b264d0500ce.png)

**Comment by martinlippert** [comment]
(I also moved this issue over to the STS4 project since it got reported against an STS4 version, although it will probably affect the STS 3.9.9 version on Eclipse 2019-06, too)

**Comment by kdvolder** [comment]
> It is a bit risky to use, since we haven't really tested it much and it incorporates stuff from the Eclipse 4.13 

Perhaps worth mentioning that nighty build also produces distribution based on Eclipse 4.11 (the previous Eclipse release). So that is also an option since the bug was introduced in Eclipse 4.12. Eclipse 4.11 is probably a lot less unstable/risky to use.

**Comment by hafarey** [comment]
I'm trying version 4.3.1.CI-B1911 (build 201906280200), based on Eclipse 4.13.0.  It looks like this issue is indeed resolved.  So far, I haven't run into any other issues with this CI build.

@kdvolder - I tried the CI build based on Eclipse 4.11.  However, it wasn't working well for me.  Things like dragging a tab and resizing the window were quite problematic--it's like the mouse drag wasn't being caught.

Thanks again!

**Comment by martinlippert** [comment]
Great to hear that the fix in the Eclipse platform for 4.13 works for you and thanks for letting us know. I marked this as fixed for the 4.4.0 release (since that is the one that we will officially ship on the Eclipse 4.13 release when it gets released in late September 2019), but feel free to continue to use the CI builds on Eclipse 4.13 in the meantime.
