### ISSUE TITLE
Wrong error markers in properties files

### ISSUE THREAD

**Issue by slavap** [spring-projects/sts4#314]
If value has \ then "Missing LineBreak" error is wrongly shown.
Example:
btnNewEntity=New \n Entity

**Comment by martinlippert** [comment]
@kdvolder can you take a look at this?

**Comment by kdvolder** [comment]
I've actually seen it too while working on some Eclipse code... the error showed up in a "plugin.properties" file somehow. I haven't debugged this problem and not yet sure where it might be coming from. But the fact that it showed up in 'plugin.properties' file probably means its not actually an STS but an Eclipse platform issue. I'll try debugging it now.

**Comment by kdvolder** [comment]
Error also shows up 'application.properties' file in boot project in STS 4. When I open this same file / project in Vanilla Eclipse it doesn't show an error in the file. Still not sure what is producing this error, I suspect it may be the generic editor together with text mate grammar for properties files. Maybe a 'bug' in the textmate grammar.

**Comment by kdvolder** [comment]
Had a bit of trouble getting setup for debugging, but finally... I was able to confirm that actually the error does originate inside our language server.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Kris De Volder:) 

Wanted to verify the fix in a recent snapshot / nightly build, but for some reason they haven't run since this fix was pushed last week. I've kicked a few builds to try and see if they'll go through this time.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Nieraj Singh:) 

Verified in 4.3.1 Release. I no longer get a `missing LineBreak at 'n'` error when I add something like:

```
btnNewEntity=New \n Entity
```

to `application.properties`
