### ISSUE TITLE
Downloading archived version of STS 4 is very hard

### ISSUE THREAD

**Issue by kdvolder** [spring-projects/sts4#324]
There doesn't seem to be a link to old downloads anywhere on the spring.io site. Or... if there is, then it's extremely hard to find. I couldn't find it myself for example.

See: https://github.com/spring-projects/sts4/issues/322

We should follow up on this and get a archival page setup. There is actually one already here:

https://spring.io/tools3/sts/legacy

But that only lists 3.9.x versions it seems.

**Comment by martinlippert** [comment]
There is no page at spring.io that lists all the previous STS4 versions, that is correct. I would suggest to add a page to the project wiki for this.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Martin Lippert:) 

We have now this wiki page for previous STS4 versions:
https://github.com/spring-projects/sts4/wiki/Previous-Versions
