### ISSUE TITLE
Download For Mac is not working no mountable filesystem error

### ISSUE THREAD

**Issue by agileguru** [spring-projects/sts4#329]

**Comment by agileguru** [comment]
Tried with Browser and Curl Command

**Comment by nierajsingh** [comment]
Thank you for raising this issue. Could you please provide us with more information on which STS4 Mac download did not work for you, what URL you used, and what version of macOS you are using?

For example, I downloaded STS4 4.3.1.RELEASE (spring-tool-suite-4-4.3.1.RELEASE-e4.12.0-macosx.cocoa.x86_64.dmg) from [https://spring.io/tools](https://spring.io/tools) and installed it in macOS Mojave 10.14.5, and it installed and launched fine for me using Java 1.8.0_191.

I downloaded both using a browser (Firefox 67.0.2 (64-bit)), as well as curl: 
```
curl https://download.springsource.com/release/STS4/4.3.1.RELEASE/dist/e4.12/spring-tool-suite-4-4.3.1.RELEASE-e4.12.0-macosx.cocoa.x86_64.dmg --output spring-tool-suite-4-4.3.1.RELEASE-e4.12.0-macosx.cocoa.x86_64.dmg
```

Thank you.

**Comment by martinlippert** [comment]
@agileguru Does the download work for you now? (since you closed the issue). And what was the issue and how did you solve that? Might be good to know, so that others can find your solution here. Thanks!!!

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Nieraj Singh:) 

Closing for now as related github issue also was closed.
