### ISSUE TITLE
Language server processes reuse

### ISSUE THREAD

**Issue by paulvi** [spring-projects/sts4#33]
I wonder, would it be possible to reuse language server processes, for example if I open directory in Code, start editing `application.properties` (with completion) and then decided to open project in Eclipse IDE.

For reference Gradle would reuse daemon process if the same version is used in command line and IDE.

**Comment by martinlippert** [comment]
Hey @paulvi , this is certainly an interesting and quite useful idea. But it goes slightly beyond what is specified in the language server protocol at the moment. It is very much designed for an individual client(editor)-server(language-server-process) connection and doesn't deal with issues that you would need to take into account when multiple clients access the same language server. I am sure this is possible to engineer, but would go beyond the scope of the current language server architecture.

Another aspect that makes it difficult (at least at the moment) is that the language server is configured in a specific way for each client. You could say that "it runs in the VSCode mode", for example. So the language server would need to be able to switch modes depending on the client calling it. Also possible to engineer, but adds additional complexity here.

To cut a long story short, I don't see us working on such a feature in the near future. If you are interested, I would recommend to also raise this question on the language-server-protocol repo to start the discussion over there, too.
