### ISSUE TITLE
代码空格

### ISSUE THREAD

**Issue by Yaklo** [spring-projects/sts4#333]
Issue Type: <b>Bug</b>

#不重要的介绍
  我是代码（√）

#不重要的介绍
我是代码（×）

代码前面需要两个空格否则运行起来会报错，问题目前仅知道在Hexo会出错

Extension version: 1.9.0
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (8.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by martinlippert** [comment]
I am sorry but I don't understand the bug report at all. Can you explain this in more detail, please? And is this a problem with the Spring Tools in VSCode or VSCode in general?

**Comment by martinlippert** [comment]
No further details provided, closing the issue.
