### ISSUE TITLE
javadoc background color is black, and can not change the color

### ISSUE THREAD

**Issue by xht555** [spring-projects/sts4#334]
**STS version: 4.3.1**

![](https://user-images.githubusercontent.com/5810513/62229206-c54a9380-b3f1-11e9-9c61-11666d9695ff.jpg)

I try to change the background color, when I clicked the buttom "Apply and close", it back to black background again.
![](https://user-images.githubusercontent.com/5810513/62229685-d2b44d80-b3f2-11e9-8d62-eefa84817bb3.png)

**Comment by martinlippert** [comment]
I guess this is an issue in the underlying Eclipse platform itself, since we usually don't do anything in this area on top of Eclipse. Can you verify that by downloading a plain Eclipse install and check if that behaves the same?

**Comment by martinlippert** [comment]
Closing this one here since there wasn't any additional feedback and the issue was probably related to the underlying Eclipse platform. If this is still a problem that occurs in the Spring Tools 4 and not in Eclipse in general, please comment and we can re-open.
