### ISSUE TITLE
Live hovers not working in VS Code 

### ISSUE THREAD

**Issue by mohan-kumar** [spring-projects/sts4#335]
Live hovers not working in VS code.

Environment

MacBook Pro 
VS code version: 1.36.1
Spring Boot: 2.1.6.RELEASE
JAVA: 1.8
Embedded Tomcat

dependencies used spring boot starters: web, actuator, dev tools, etc.

**Comment by kdvolder** [comment]
Please attach contents from the server log. You can find out where it is by opening the 'Output' view and selecting 'vscode-spring-boot-debug-log'. It will show something like:

```
directing server logs to ...
```

Open that file and attach the contents to this bug report.

**Comment by mohan-kumar** [comment]
Thanks for the reply.

Below are the logs from 'vscode-spring-boot-1564707270063.log'. I have observed after testing it multiple times that it actually some times works, but this is not the case every time. It is not consistent. It does not work more often than not.

```
13:09:40.718 [ForkJoinPool.commonPool-worker-7] INFO  o.s.i.v.c.boot.app.cli.SpringBootApp - check for spring jmx beans (retry no. 0) -- LocalSpringBootApp [id=25161, name=`com.example.demo.DemoApplication`]
13:09:40.721 [elastic-27] INFO  o.s.i.v.c.boot.app.cli.SpringBootApp - Creating JMX connector: service:jmx:rmi://127.0.0.1/stub/rO0ABXN9AAAAAQAlamF2YXgubWFuYWdlbWVudC5yZW1vdGUucm1pLlJNSVNlcnZlcnhyABdqYXZhLmxhbmcucmVmbGVjdC5Qcm94eeEn2iDMEEPLAgABTAABaHQAJUxqYXZhL2xhbmcvcmVmbGVjdC9JbnZvY2F0aW9uSGFuZGxlcjt4cHNyAC1qYXZhLnJtaS5zZXJ2ZXIuUmVtb3RlT2JqZWN0SW52b2NhdGlvbkhhbmRsZXIAAAAAAAAAAgIAAHhyABxqYXZhLnJtaS5zZXJ2ZXIuUmVtb3RlT2JqZWN002G0kQxhMx4DAAB4cHc0AAtVbmljYXN0UmVmMgAACWxvY2FsaG9zdAAA4Ta1ey24VM3Z8gLaHh4AAAFsUUUfpYACAHg=
13:09:40.750 [elastic-27] INFO  o.s.i.v.c.boot.app.cli.SpringBootApp - Created JMX connector: javax.management.remote.rmi.RMIConnector: jmxServiceURL=service:jmx:rmi://127.0.0.1/stub/rO0ABXN9AAAAAQAlamF2YXgubWFuYWdlbWVudC5yZW1vdGUucm1pLlJNSVNlcnZlcnhyABdqYXZhLmxhbmcucmVmbGVjdC5Qcm94eeEn2iDMEEPLAgABTAABaHQAJUxqYXZhL2xhbmcvcmVmbGVjdC9JbnZvY2F0aW9uSGFuZGxlcjt4cHNyAC1qYXZhLnJtaS5zZXJ2ZXIuUmVtb3RlT2JqZWN0SW52b2NhdGlvbkhhbmRsZXIAAAAAAAAAAgIAAHhyABxqYXZhLnJtaS5zZXJ2ZXIuUmVtb3RlT2JqZWN002G0kQxhMx4DAAB4cHc0AAtVbmljYXN0UmVmMgAACWxvY2FsaG9zdAAA4Ta1ey24VM3Z8gLaHh4AAAFsUUUfpYACAHg=
13:09:45.803 [pool-7-thread-1] INFO  o.s.i.v.c.boot.app.cli.SpringBootApp - check for spring jmx beans (retry no. 1) -- LocalSpringBootApp [id=25161, name=`com.example.demo.DemoApplication`]
13:09:50.886 [pool-4-thread-1] INFO  o.s.i.v.c.boot.app.cli.SpringBootApp - check for spring jmx beans (retry no. 2) -- LocalSpringBootApp [id=25161, name=`com.example.demo.DemoApplication`]
13:09:55.945 [pool-7-thread-1] INFO  o.s.i.v.c.boot.app.cli.SpringBootApp - check for spring jmx beans (retry no. 3) -- LocalSpringBootApp [id=25161, name=`com.example.demo.DemoApplication`]
13:09:55.962 [pool-7-thread-1] INFO  o.s.i.v.c.boot.app.cli.SpringBootApp - no spring jmx beans found after trying 4 times -- LocalSpringBootApp [id=25161, name=`com.example.demo.DemoApplication`]`
```
As per the above logs 'no spring jmx beans found after trying 4 times' it is not able to find jmx beans, but some times when it works the log will print showing that it is able to find jmx beans after 2 or 3rd try.

The spring boot application which I am testing is a simple web app with just one rest endpoint, which was created using spring initializer command inside VS Code with starters web, dev tools, and actuator.

All spring and java related extensions are installed.

**Comment by kdvolder** [comment]
Is that the full log contents? What I am trying to see / determine is whether the server is receiving classpath information about the project. I don't see any output related to this.

Other questions?

- how are you launching the application? (from vscode? from commandline? ... please provide exact details here, it may matter).
- Could you attach the complete sample project? I.e. inlcuding everything like the pom.xml etc. Just zip up the whole project contents.
- when you have the project running and live hover is not working, could you please try attaching to the process using 'jconsole'? Does that work? If yesm can you explore the JMX beans and check if you see the spring beans info there? See screenshot below for what we are trying to find:

![jconsole-boot-app](https://user-images.githubusercontent.com/1002156/62382949-87d62b00-b503-11e9-85bb-0c0511ef4545.png)

**Comment by mohan-kumar** [comment]
Sorry for the late reply. 
Attaching the whole 'vscode-spring-boot-***.log' and the whole sample demo application below.
I had also tried to see if live hovers work on sprint-petclinic sample app from spring, it did not.

[demo.zip](https://github.com/spring-projects/sts4/files/3472309/demo.zip)
[vscode-spring-boot-1565095608916.log.zip](https://github.com/spring-projects/sts4/files/3472317/vscode-spring-boot-1565095608916.log.zip)

I am launching the application from vscode ui i.e SPRING-BOOT DASHBOARD > right click start.

Tried attaching the process to jconsole and I did the see the same beans as in your screenshot. Attaching the same.
<img width="1280" alt="Screenshot 2019-08-06 at 6 27 34 PM" src="https://user-images.githubusercontent.com/7701038/62542431-636aad80-b879-11e9-9ce9-812fa4720519.png">
<img width="1280" alt="Screenshot 2019-08-06 at 6 26 46 PM" src="https://user-images.githubusercontent.com/7701038/62542432-64034400-b879-11e9-83d6-b3f0d5117e7b.png">
<img width="1280" alt="Screenshot 2019-08-06 at 6 39 45 PM" src="https://user-images.githubusercontent.com/7701038/62542565-a3ca2b80-b879-11e9-8cc1-6aab20a1097a.png">

**Comment by kdvolder** [comment]
Looked at the log a bit, not much more info than in the first messages posted before. It looks like the language server is having some problems connecting to the app via JMX. 

I vaguely recall similar issues from people with Mac's in the past and that it had something todo with how their network or Wifi was configure, something to do with accessing connections on the localhost). Maybe one of our Mac developers (@nierajsingh , @BoykoAlex, @martinlippert  ?) remembers more details about how this was resolved exactly in the past.

**Comment by martinlippert** [comment]
@kdvolder I think the error messages in the log about the JMX connection problems are related to the language server trying to connect with JMX to the JConsole app, which might not be possible for good reasons, so that doesn't seem to be the issue here. Nevertheless it looks like the language server doesn't really give up on that, but tries over and over again - which it should not. Those errors should be covered by the "try n times and then give up" mechanism, too, I think.

@mohan-kumar I am wondering about the fact that it seems to work "sometimes". It looks to me like the language server can successfully connect via JMX to the process, but fails 4 times to retrieve the necessary MBean information, and then gives up. Usually I would guess that this happens when the app starts up slowly and the JMX beans are not ready yet before the language server gives up. But your app looks simple enough to startup quickly. But it would be good to dig a bit deeper here. Can you try to keep the language-server log open (to watch it) while you startup your app? And see if the app has started just fine (and quickly) before the language server gives up on it?

**Comment by mohan-kumar** [comment]
@martinlippert you were right, the app used to complete startup after language server retries(all 4 times) for finding JMX beans. Even the simple app which I was testing used to take ~19 to 25 seconds and by that time language server had completed all tries to find JMX beans. 
Made some changes in /etc/hosts, added hostname to the IPv4 & IPv6 loopback entries. This significantly improved startup time. Followed this link [https://blog.noizwaves.io/2017/09/02/slow-spring-boot-startup.html](https://blog.noizwaves.io/2017/09/02/slow-spring-boot-startup.html). Now app startup completed before language server tried to find JMX beans and live hovers worked. Now live hovers worked even in sample spring-petclinic app. Even though this worked I think maybe there should be more delay between language server retries to find JMX beans. 

Closing this issue.

**Comment by martinlippert** [comment]
First of all, glad to hear that you found the underlying reason for why your app took so long to startup. Good to have that fixed and speed up - independent of the live hovers... :-)

And yes, I agree, that we should probably make the number of tries and the pause between attempts configurable. We are also thinking about broader changes to the mechanism, but I will keep your suggestion in the list of things to keep in mind for the new mechanism for sure. Thanks again for the report and the feedback.
