### ISSUE TITLE
Increate -Xms to -Xms256m instead of 40m

### ISSUE THREAD

**Issue by vogella** [spring-projects/sts4#338]
The Eclipse project has updated a while ago their -Xms and -Xmx1024m. Looks to me (at a customer PC) like the STS still uses -Xms40. 

If that is true, I suggest to update to at least:

-Xms256m
-Xmx1024m

cc @martinlippert

**Comment by martinlippert** [comment]
STS4 distribution builds have these settings already for a longer time, but I took the chance to update the legacy STS3 bistro builds to those settings, too. Thanks for the notice!!!

**Comment by vogella** [comment]
Thanks Martin for the fast response.

On Thu, Aug 8, 2019 at 4:03 PM Martin Lippert <notifications@github.com> wrote:
>
> Closed #338.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Eclipse Platform project co-lead
CEO vogella GmbH

Haindaalwisch 17a, 22395 Hamburg
Amtsgericht Hamburg: HRB 127058
Geschäftsführer: Lars Vogel, Jennifer Nerlich de Vogel
USt-IdNr.: DE284122352
Fax (040) 5247 6322, Email: lars.vogel@vogella.com, Web: http://www.vogella.com
