### ISSUE TITLE
Not always work

### ISSUE THREAD

**Issue by cuakitiang** [spring-projects/sts4#34]
i am sorry that i don't know why it works well sometimes(for a few times), but not always? it must connect to the internet?

**Comment by martinlippert** [comment]
Can you elaborate in a bit more detail what works and what doesn't? Maybe a few steps how to reproduce the problem that sometimes doesn't work? And what environment do you use?

**Comment by cuakitiang** [comment]
@martinlippert I use the vscode-extensions. I know the reason now. The extensions download some .jar files by Maven, and there is something wrong with my Maven's settings.xml. Finally, I fixed it.

**Comment by martinlippert** [comment]
@cuakitiang glad to hear that this is working for you now. As a side note, the extension itself doesn't need anything from Maven, but as soon as you have a Maven project in your workspace, the extension tries to resolve dependencies and therefore triggers Maven to do that work.
