### ISSUE TITLE
[vscode-concourse] support 'inputs' property for type 'PutStep'

### ISSUE THREAD

**Issue by mstockd** [spring-projects/sts4#341]
VSCode Extension version: 1.10.0 (4.3.1 Release)

The extension marks the key `inputs` as an unknown property if it is part of a put step definition.
https://concourse-ci.org/put-step.html#put-step-inputs

Example:
```
- put: a-put-step
   inputs:
   - some-input-name

**Comment by kdvolder** [comment]
Pushed a fix. It can be tried already from the snapshot builds. You can download it from here:

http://dist.springsource.com/snapshot/STS4/nightly-distributions.html

**Comment by mstockd** [comment]
Thank you! :)
