### ISSUE TITLE
Spring-Boot language server RMI connection failures

### ISSUE THREAD

**Issue by bpeterson** [spring-projects/sts4#344]
If I have "Live Boot Hint Decorators" selected on Preferences->"Language Servers"->"Spring Boot Language Server"->"Spring Boot Java" then I get a bunch of these warnings whenever I run unit tests in eclipse or on the mvn cmdline:
```
WARNING: RMI TCP Accept-0: accept loop for ServerSocket[addr=0.0.0.0/0.0.0.0,localport=...] throws
java.io.IOException: The server sockets created using the LocalRMIServerSocketFactory only accept connections from clients running on the host where the RMI remote objects have been exported.
  at sun.management.jmxremote.LocalRMIServerSocketFactory$1.accept(LocalRMIServerSocketFactory.java:114)
  at sun.rmi.transport.tcp.TCPTransiort$AcceptLoop.executeAcceptLoop(TCPTransport.java:405)
  ...
```
The connection attempt is using the IP address for the machine instead of the loopback. My `/etc/hosts` file does map localhost to the loopback address.

This is on
> Eclipse 2019-03 (4.11.0)
> Spring Tool Suite 4 (4.2.2.201905232009)
> Spring Boot Language Server Feature (4.2.2.201905231938)
> Open JDK 1.8.0_222
> CentoOS 7

I saw the option under "Remote Boot Apps" to provide `jmxurl` and `hostname` using JSON format, but I wasn't sure how to configure it to use the loopback addr or simply `localhost`.

Unselecting the option avoids the RMI connection warnings.

**Comment by kdvolder** [comment]
Can you clarify where you see these errors exactly? I.e. is this in the language server's log? Or in the output of one of your own processes? Or in the Eclipse error log? Or what? 

> I saw the option under "Remote Boot Apps" to provide jmxurl and hostname using JSON format, but I wasn't sure how to configure it to use the loopback addr or simply localhost.

The remote-boot-apps preference is meant to point to a very specific (remote) process by providing a complete jmx url for that process. It will not help in your case. The process is a local process that the language server tries to connect to automatically when it sees it running on your machine.

I wouldn't expect the live hovers to really work when you run unit tests. But the language server doesn't really know what that process is when it tries to connect. So in this case the failure message is not really a problem in itself and could just be ignored without real loss of functionality.

However... I think it does seem to be indicative of a real problem. I bet that the same thing will also happen when you run your app, and it will prevent the live hovers from working properly.

So I think we should try to investigate this a little. It probably has something todo with the specifics of your OS (this doesn't happen to me, for example on Linux Ubuntu 18.04). 

In the off chance that this also has something todo with the fact that you are using an older release of STS, could you try if the problem also arises in STS 4.3.2 ?

**Comment by bpeterson** [comment]
The warnings come up in the console. I couldn't find the language server's log. I'm not very familiar with the layout of eclipse internals; if you point me to where the language server's log should be I'll take a look at it.

I couldn't figure out why a process would attempt to connect to the JMX port of a mvn run. I tracked these warnings to the language server when looking for some left over process running when I do a `$mvn test` and saw the java process running `org.springframework.ide.vscode.boot.app.BootLanguageServerBootApp`. Killing that process was enough to stop the RMI warnings. I could keep that process running as long as I uncheck that live-hover option in eclipse. 

Unfortunately I can't try STS 4.3.2. Those are the most recent versions I have available to me (at this time) in that dev env.

**Comment by kdvolder** [comment]
STS 4.3.2 is available for download from the usual place (https://spring.io/tools). But I understand it might be a bit of a hassle to try it. It is of course up to you to decide if, and how much effort you want to spend on trying out things to help us understand what is happening and how/if it can be addressed. 

TBH, if I would guess the problem probably is the same in STS 4.3.2, but unless you try we don't really know for sure. And it is a bit of a waste of time to try and fix/trouble shoot something that is already fixed.

> The warnings come up in the console

Okay, I assume this is the console that is showing the output of *your* process, given everything else you have said so far. 

The language server output also shows in the console view (in a different tab of the same view), but you have to enable it specifically from "Windows >> Preferences >> Language Servers >> Spring Language Servers".  It might show some related output (when the server tries to connect to your process and fails).

The eclipse error log shows in its own view. To see it you can do: Window >> Show View >> Error Log. 

Anyhow, the info you provided so far...  what seems to be going on is the language server it trying to connect to your process and for a still unknown reason... it cannot. This results in these errors being printed iinside your app when the connection is rejected. My guess it has something todo with the jmx url that is computed by the language server for the local processes, which may have something to do with how your OS is configured. THe server output might be helpful, it prints out some details about when its trying to connect jmx.

**Comment by luis08** [comment]
I have the same problem and I am using IntelliJ  It seems to be related to network security.  I am going to try to start the application from the CLI. 

Java describes a bug with the same exception, yet their solution has not resolved my problem. 

https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6754672

**Comment by martinlippert** [comment]
@bpeterson It didn't really make a lot of sense for the tooling to connect to those processes like unit tests in such an aggressive way. With the 4.4.1 release, we changed this mechanism altogether, so that the tooling connects to java processes only in case you start them up in the boot dashboard as spring boot apps. Alternatively, you can now manually connect to them via the quick access menu, as described in the updated project wiki: https://github.com/spring-projects/sts4/wiki/Live-Application-Information#managing-live-data-connections-to-local-processes

This should make your experience much much smoother. You will still see live hovers automatically for your boot apps started in the dashboard (or via a Spring Boot launch config in your IDE), but the mechanism will not bother with your unit tests anymore.

Therefore I will close this issue for now. Please checkout the new mechanism and let us know what you think. If you experience additional issues or come across an issue similar to this one when connecting to a process that you actually want to connect to (to show live hover information), please comment and we can re-open or create a new ticket for that.

**Comment by RaviSourav** [comment]
if you are using Intellij first check the mapping of localhost with 127.0.0.1 and then change the VM options to 
-Djava.rmi.server.hostname=localhost

This resolved my issue.

**Comment by svelj** [comment]
@RaviSourav This solves my issue. Is there a way to do this globally or do I have to add VM options on run configuration for each application?

**Comment by RaviSourav** [comment]
@svelj It has to be configured at Project level i.e., for each application as VM will be decided once the project is launched. I hope it answer your question.
