### ISSUE TITLE
Too long quick link text in empty workspace

### ISSUE THREAD

**Issue by vogella** [spring-projects/sts4#352]
The quick links in the project / package explorer are too long. See screenshot. I assume the text should be the same as in the New File Wizard.

![image](https://user-images.githubusercontent.com/139910/63675552-5e01e280-c7e9-11e9-9e71-3dc8d220ebf4.png)

**Comment by vogella** [comment]
@kdvolder Checked org.eclipse.ui.internal.views.helpers.EmptyWorkspaceHelper and it indeed uses the description. 

	for (IAction action : projectWizardActions) {
			String description = action.getDescription();
			if (description == null || description.isEmpty()) {
				description = action.getText();
			}
			createOption(optionsArea, toolkit, linkColor, action, action.getImageDescriptor(), description);
		}
> then perhaps the package explorer should not...

I think having only the short name (e.g. "Java project") and the description ("Create Java Project") lead to the decision to use the description. Description are not very visible, for example the New Wizard dialog does AFAIK not show it. I think only Quick Access shows it.

**Comment by vogella** [comment]
@kdvolder this issue is marked from @spring-issuemaster as finished. 

Should I close it?

**Comment by martinlippert** [comment]
@vogella No, we have an additional internal step to double check. Once that is done in our Pivotal Tracker instance, the issue will be closed automatically... :-)

**Comment by martinlippert** [comment]
But you could, of course, double check this, too (using a latest nightly build), so you don't have to wait for us... :-)

**Comment by vogella** [comment]
Thanks, waiting for auto-confirm is fine for me, just wanted to avoid that you are waiting for me.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Martin Lippert:) 

the links seem to be shortened, but they magically disappear whenever I open a new empty workspace right after a second - even though there is nothing in my package explorer.

I double checked this with an Eclipse 2019-09 RC1 build and the problem does NOT appear in there, the shortcuts stay in the package explorer for as long as there are no projects showing up.

We need to find out what is going wrong inside of the STS distro.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Kris De Volder:) 

It works fine for me in STS 4 nightly build for Eclipse 4.12. However with nighyly on Eclipse 4.13 the package explorer view remains empty (maybe the links show and disapear quickly? not sure, I just don't see them).

> I double checked this with an Eclipse 2019-09 RC1

Not sure how you checked this exactly.But I'll try as well.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Kris De Volder:) 

The reason it is not showing the links is because the workspace is not truely empty. There is a 'hidden' project called 'RemoteSystemsTempFiles'.

This project can be revealed by unchecking the corresponding 'filter' from the Package Explorer filter options.

Once I do that I can see this hidden project.

If I delete this project then all of a sudden the shortcut links re-appear.

I'm not sure how/why this project is being created. Don't think it's us, but its some Eclipse component which maybe isn't included in the Vanilla Eclipse 4.13 SDK but is included in STS 4.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Martin Lippert:) 

I will take a look, thanks for investigating

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Kris De Volder:) 

In our Eclipse 4.12 nightly distro, whatever component is responsible for this 'RemoteSystemTempFiles' project seems not installed. In our 4.12 distro I don't get this hidden project and also the filter options in the package explorer related to it are missing. 

Something changed in our packaging between 4.12 and 4.13? 

Maybe relevant... or not:

I vaguely recall we used to have a dependency on something providing  a 'Remote Systems Explorer' features. Some thing for seeing files in remote systems and doing stuff like telnet and ssh terminal emulation. If I recall correctly it had something to do with our legacy CF tooling providing ways to browse files on cloudfoundry instances and it was leveraging these eclipse components to do it. I also remember seeing this 'hidden project' back in the days, when we shipped the legacy CF tools.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Kris De Volder:) 

Definitily something changed.

In e413 we have these:

```
org.eclipse.rse.connectorservice.dstore_4.5.100.201901312252.jar
org.eclipse.rse.connectorservice.local_4.5.100.201901312252.jar
org.eclipse.rse.connectorservice.ssh_4.5.100.201901312252.jar
org.eclipse.rse.connectorservice.telnet_4.5.100.201901312252.jar
org.eclipse.rse.core_4.5.100.201901312252.jar
org.eclipse.rse.doc.user_4.5.100.201901312252.jar
org.eclipse.rse.dstore.security_4.5.100.201901312252.jar
org.eclipse.rse.efs_4.5.100.201901312252.jar
org.eclipse.rse.efs.ui_4.5.100.201901312252.jar
org.eclipse.rse.files.ui_4.5.100.201901312252.jar
org.eclipse.rse.importexport_4.5.101.201904091623.jar
org.eclipse.rse.processes.ui_4.5.100.201901312252.jar
org.eclipse.rse.services_4.5.100.201901312252.jar
org.eclipse.rse.services.dstore_4.5.100.201901312252.jar
org.eclipse.rse.services.files.ftp_4.5.100.201901312252.jar
org.eclipse.rse.services.local_4.5.100.201901312252.jar
org.eclipse.rse.services.ssh_4.5.100.201901312252.jar
org.eclipse.rse.services.telnet_4.5.100.201901312252.jar
org.eclipse.rse.shells.ui_4.5.100.201901312252.jar
org.eclipse.rse.subsystems.files.core_4.5.100.201901312252.jar
org.eclipse.rse.subsystems.files.dstore_4.5.100.201901312252.jar
org.eclipse.rse.subsystems.files.ftp_4.5.100.201901312252.jar
org.eclipse.rse.subsystems.files.local_4.5.100.201901312252.jar
org.eclipse.rse.subsystems.files.ssh_4.5.100.201901312252.jar
org.eclipse.rse.subsystems.processes.core_4.5.100.201901312252.jar
org.eclipse.rse.subsystems.processes.dstore_4.5.100.201901312252.jar
org.eclipse.rse.subsystems.processes.local_4.5.100.201901312252.jar
org.eclipse.rse.subsystems.processes.shell.linux_4.5.100.201901312252.jar
org.eclipse.rse.subsystems.shells.core_4.5.100.201901312252.jar
org.eclipse.rse.subsystems.shells.dstore_4.5.100.201901312252.jar
org.eclipse.rse.subsystems.shells.local_4.5.100.201901312252.jar
org.eclipse.rse.subsystems.shells.ssh_4.5.100.201901312252.jar
org.eclipse.rse.subsystems.shells.telnet_4.5.100.201901312252.jar
org.eclipse.rse.ui_4.5.100.201901312252.jar
```

Which we do not have in Eclipse 4.12.

I am guessing 'rse' stands for 'Remote System Explorer'.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Martin Lippert:) 

I removed the RSE component again from the distribution. Now everything looks just fine.
