### ISSUE TITLE
Wrong coloring during debugging for Spring components in the dark theme

### ISSUE THREAD

**Issue by vogella** [spring-projects/sts4#357]
While initially the colors are correct in the Java editor for Spring components, at some point they switch to yellow. See screenshot.

![image](https://user-images.githubusercontent.com/139910/63952328-a6d2c900-ca7f-11e9-8a0b-6a87a0aaea44.png)

Any idea where this coloring is coming from? I don't think we do this in standard Eclipse but I'm not sure.

**Comment by vogella** [comment]
Ah, just learned that this coloring is coming from the language server to show that additional information is available. If that color is defined as a preference you could style it better in the dark theme. Let me know if you want to do this, I can then search for an example how to style preferences via CSS.

**Comment by martinlippert** [comment]
Absolutely, any pointers and hints would be highly appreciated

**Comment by vogella** [comment]
OK, I assume you have a preference for this color already. In this case you can contribute styling to the dark theme for this color via an extension.

Not sure, if you have already a css for the dark theme? If not, create one file ("css/e4-dark_sts4_prefstyle.css") and point via an extension to it:

````
 <extension
        point="org.eclipse.e4.ui.css.swt.theme">
     <stylesheet uri="css/sts4.css" />
     <stylesheet
           uri="css/e4-dark_sts4_prefstyle.css">
        <themeid
              refid="org.eclipse.e4.ui.css.theme.e4_dark">
        </themeid>
     </stylesheet>
  </extension>
````

Within this file you can style your preferences.

Example (from egit)

/* ############################## EGIT preferences ############################## */
````
/* See bug 466075 about the pseudo-selector ":org-eclipse-egit-ui" */
IEclipsePreferences#org-eclipse-ui-workbench:org-eclipse-egit-ui {
		preferences:
			'org.eclipse.egit.ui.DiffAddBackgroundColor=11,121,90'
			'org.eclipse.egit.ui.DiffAddForegroundColor=216,254,245'
			'org.eclipse.egit.ui.DiffHeadlineBackgroundColor=71,71,71'
			'org.eclipse.egit.ui.DiffHeadlineForegroundColor=242,242,242'
			'org.eclipse.egit.ui.DiffHunkBackgroundColor=53,97,113'
			'org.eclipse.egit.ui.DiffHunkForegroundColor=233,242,254'
			'org.eclipse.egit.ui.DiffRemoveBackgroundColor=117,2,36'
			'org.eclipse.egit.ui.DiffRemoveForegroundColor=255,232,237'
			'org.eclipse.egit.ui.IgnoredResourceBackgroundColor=42,42,42'
			'org.eclipse.egit.ui.IgnoredResourceForegroundColor=120,120,120'
			'org.eclipse.egit.ui.UncommittedChangeBackgroundColor=42,42,42'
			'org.eclipse.egit.ui.UncommittedChangeForegroundColor=114,157,186'
}
````
The :org-eclipse-egit-ui  should be replaced with your plugin ID and is important as you otherwise override styling from other plugins.

**Comment by vogella** [comment]
@martinlippert do you have a preference for this color already? If yes, please let me know the key for it. I could use a preference initializer to set it to something readable for me until this bug is fixed.

**Comment by vogella** [comment]
Also the Dashboard could use CSS configured colors with the same approach as described above.

![image](https://user-images.githubusercontent.com/139910/64025454-0216c100-cb3d-11e9-8e08-1ea25d17c141.png)

**Comment by BoykoAlex** [comment]
> @martinlippert do you have a preference for this color already? If yes, please let me know the key for it. I could use a preference initializer to set it to something readable for me until this bug is fixed.
The plugin id: `org.springframework.tooling.ls.eclipse.commons`
Preference key: STS4BootMarkerIndicationColor

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Alex Boyko:) 

I have updated some colors to use theme in Boot Dash. Also updated green color for boot highlights to come from the Theme. However, I have updated it for the hacky version of marker that is used together with CodeLenses (to work around the bug with CodeLens and marker painting). If CodeLens is off then the marker looks come from `org.eclipse.ui.editors.markerAnnotationSpecification` ext point. There doesn't seem to be any theme support for this extension, but it is the culprit for the yellow color seen on the screenshot as looks like Eclipse is trying to invert this color automatically based on the background (didn't figure out where yet)
We do not need the second hacky version of the marker - it's going away. The marker from `org.eclipse.ui.editors.markerAnnotationSpecification` stays, I might introduce the second marker for the dark theme if i don't find any support for themes

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Martin Lippert:) 

one minor thing that I noticed: the background of the filter box in the boot dashboard is a bit too light (in the dark mode), would be better if the background would be darker.
