### ISSUE TITLE
Pixelated icon in dark theme

### ISSUE THREAD

**Issue by vogella** [spring-projects/sts4#359]
The icon in the screenshot looks bad, I suggest to use an png with real transparency. This looks like a gif.

![image](https://user-images.githubusercontent.com/139910/64025578-4609c600-cb3d-11e9-9f9e-3993a3e26824.png)

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Martin Lippert:) 

Alex, can you double check to also add and use a 2x version of the icon image for retina displays? That would be awesome.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Alex Boyko:) 

I did :-) I have updated both icons :-)

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Martin Lippert:) 

Right, but it looks like the high-res one is 24x24 pixel, not 32x32... :-)

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Alex Boyko:) 

Oops... good thing you noticed that... Corrected now.
