### ISSUE TITLE
spring-context/src/main/java/org/springframework/context/support/PostProcessorRegistrationDelegate.java

### ISSUE THREAD

**Issue by Tomcat201808** [spring-projects/sts4#360]
IN spring-context/src/main/java/org/springframework/context/support/PostProcessorRegistrationDelegate.java this class，I found a place in the class that can improve performance.
from line 82 to 109 ；
I think we can improve  like that:
`List<BeanDefinitionRegistryPostProcessor> priorityOrderedRegistryProcessors = null;
		List<BeanDefinitionRegistryPostProcessor> orderRegistryProcessors = null;
		// First, invoke the BeanDefinitionRegistryPostProcessors that implement PriorityOrdered.
		String[] postProcessorNames =
				beanFactory.getBeanNamesForType(BeanDefinitionRegistryPostProcessor.class, true, false);
		for (String ppName : postProcessorNames) {
			if (beanFactory.isTypeMatch(ppName, PriorityOrdered.class)) {
				currentRegistryProcessors.add(beanFactory.getBean(ppName, BeanDefinitionRegistryPostProcessor.class));
				priorityOrderedRegistryProcessors.add(ppName);
			}
			if (!processedBeans.contains(ppName) && beanFactory.isTypeMatch(ppName, Ordered.class)) {
				currentRegistryProcessors.add(beanFactory.getBean(ppName, BeanDefinitionRegistryPostProcessor.class));
				orderRegistryProcessors.add(ppName);
			}
		}`

**Comment by martinlippert** [comment]
Looks like something that should be reported against https://github.com/spring-projects/spring-framework
