### ISSUE TITLE
[bug] XML indexes are not updated when changing file

### ISSUE THREAD

**Issue by gayanper** [spring-projects/sts4#366]
When changing xml file the file changes are not reflected in the symbol dialog. If i close all editors and cause the language server to stop, on next file open which start a new LS the updated symbols will there. Seems that the file changes are not processed by the LS

**Comment by BoykoAlex** [comment]
Hopefully fixed with client/registerCapability

**Comment by gayanper** [comment]
Seems like this cause the java symbols and spring xml java property CA to be broken.

**Comment by martinlippert** [comment]
I think this all works in the latest versions, so closing this one here for now. If you come across this again, please comment and we can re-open anytime.
