### ISSUE TITLE
[bug] Java symbol index and java property CA for xml is not working

### ISSUE THREAD

**Issue by gayanper** [spring-projects/sts4#367]
The Symbol index and java property CA in xml files seems to be broken by the last commit which is 63a5a7e

**Comment by martinlippert** [comment]
Sorry for not coming back to this back then, apologize for that. As fas as I can see, content-assist and symbol indexing is working in the latest versions of the spring boot language server, so I am closing this one here. If you still observe this issue, please comment and we can re-open.
