### ISSUE TITLE
Can you provide debian arm aarch64 version or build tutorial?

### ISSUE THREAD

**Issue by Generalize** [spring-projects/sts4#368]

**Comment by martinlippert** [comment]
For the Spring Tools 4 for Eclipse we use the Eclipse platform as the underlying base platform, so the support for specific operating systems depends on what the Eclipse platform offers. The same applies to our extensions for Visual Studio Code and Theia. So in case you need special support for a specific OS, I would recommend to ask the corresponding project for help.
