### ISSUE TITLE
copy hang in 4.4.0

### ISSUE THREAD

**Issue by user20161119** [spring-projects/sts4#372]
After upgrade to 4.4.0,when copy in editor,hang for seconds.with previous version,work well.

Googled got to disable editor hyperlinking,but hyperlinking is important for java developer,need a better solution,thanks

**Comment by martinlippert** [comment]
@user20161119 Can you double check with the 4.4.1 release? I am pretty optimistic that this improved with the latest 4.4.1 release.

And in case this happens again, maybe capture a thread dump while the editor hangs? That would be awesome.

**Comment by user20161119** [comment]
I roll back to old version,everything is fine now.

At 2019-10-29 22:16:54, "Martin Lippert" <notifications@github.com> wrote:


@user20161119 Can you double check with the 4.4.1 release? I am pretty optimistic that this improved with the latest 4.4.1 release.

And in case this happens again, maybe capture a thread dump while the editor hangs? That would be awesome.

**Comment by kdvolder** [comment]
> I roll back to old version,everything is fine now.

While I am glad that this works as a solution for you, it doesn't tell us whether the problem you reported in 4.4.0 is solved in 4.4.1 or not, nor does it help in solving the problem if it does indeed still exist. So if you could try it with 4.4.1 and try to catch a thread-dump that would still be useful.  

BTW: For automatically catching thread dumps when the UI hangs, Eclipse can do this, and it is enabled via a preference under "Window >> Preferences >> General >> UI Responsiveness Monitoring".

**Comment by user20161119** [comment]
Just download the new version sts4.4.1,Work well with new installation.
Suggest do not upgrade from version less than 4.4.1,try new installation.

**Comment by martinlippert** [comment]
@user20161119 Glad to hear that and thanks for letting us know.
