### ISSUE TITLE
Update sites listed on wiki are wrong

### ISSUE THREAD

**Issue by ikonkere** [spring-projects/sts4#373]
Currently both https://download.springsource.com/release/TOOLS/sts4/update/e4.13/ and https://download.springsource.com/release/TOOLS/sts4/update/e4.12/ contain empty repositories, while https://download.springsource.com/release/TOOLS/sts4/update/latest points to Eclipse Release repository.
![image](https://user-images.githubusercontent.com/11472129/66111596-e0907580-e5d1-11e9-8402-949d62d1375a.png)
![image](https://user-images.githubusercontent.com/11472129/66111640-f30aaf00-e5d1-11e9-8a54-5e034663784b.png)

**Comment by martinlippert** [comment]
The mentioned p2 repository URLs are correct and provide the correct content. Please note that in your screenshots, you are using `http` versions of those URLS instead of `https`. Please try the `https` variants.

The `latest` repo URL is a composite one that refers to the main Spring Tools 4 repository as well as the latest Eclipse release repository. This allows Spring Tools 4 for Eclipse users to always update to the latest Eclipse and Spring Tools 4 versions in one go.

**Comment by ikonkere** [comment]
> The latest repo URL is a composite one that refers to the main Spring Tools 4 repository as well

There isn't a single "spring" component in the repo. 
![image](https://user-images.githubusercontent.com/11472129/66115595-cf4b6700-e5d9-11e9-9c39-2d4e96be9f1d.png)
Can you please provide a screenshot of your own that proves that it contains STS?

> Please try the https variants.

So `http` ones don't provide anything (which is the point of my question), only `https`?

**Comment by martinlippert** [comment]
In case you don't trust me (as the one maintaining the repository definitions) when I write that the p2 repository URLs are correct and point to the right content, here is a screenshot for you that shows you the exact content of the p2 repository definition under: https://download.springsource.com/release/TOOLS/sts4/update/e4.13/

![image](https://user-images.githubusercontent.com/107705/66116169-8d6af280-e5d2-11e9-851a-e1c831008159.png)

And in case you don't believe me that the `latest` p2 repository point to something beyond the Eclipse repo, here is the composite definition of the repo:

https://download.springsource.com/release/TOOLS/sts4/update/latest/compositeContent.xml

The `http` variants of the URLs work as well, but they also point at a composite site that points to `https` versions of the concrete p2 repositories. But we do not recommend to use `http` versions anymore.

From what I can see in your screenshots, it looks like there is probably a network-related issue with accessing the `https` versions of the update sites from your end. So, here is what I would try:

- use the `https` version of the p2 repo URL in the `Install New Software` dialog. The latest screenshot that you posted contains again a `http` URL in the dropdown box.

- try to access via a browser to see if the network access works in general: https://download.springsource.com/release/TOOLS/sts4/update/latest/compositeContent.xml

- you could try to use the exact p2 repo URL (including the STS4 version), as listed in the composite update site. This will prevent you from getting updates to newer versions automatically, but you could at least try this to see where the network access problem might come from.

**Comment by martinlippert** [comment]
You could also download the ready-to-use Spring Tools 4 for Eclipse distribution from https://spring.io/tools, it comes with a Eclipse 4.13 + Spring Tools 4 + additional useful add-ons pre-installed and ready-to-use.

**Comment by ikonkere** [comment]
> you could try to use the exact p2 repo URL (including the STS4 version), as listed in the composite update site. 
I can't, this is what i get when i try to go to https://download.springsource.com/release/TOOLS/sts4/update/4.4.0.RELEASE/e4.13
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>C85F650CA77C01F2</RequestId>
<HostId>
O++B+9JJgEYiX4GO7dHX2E81HQEWLKJWmMh7ehQxZHtq4waVxRoDJtPcAGSARg04DJzB9TrbsgI=
</HostId>
</Error>
```

**Comment by ikonkere** [comment]
>but you could at least try this to see where the network access problem might come from.

All other repos are fine and i have quite a few of them, the only issue i have is with STS, so it isn't to do with network for sure, but now i'm lost, maybe you blacklist some IP addresses on your servers?

**Comment by ikonkere** [comment]
Hmm, ok, sorry for being silly, this one still doesn't work for me: http://download.springsource.com/release/TOOLS/sts4/update/e4.13/, but this one does:
http://download.springsource.com/release/TOOLS/sts4/update/4.4.0.RELEASE/e4.13

**Comment by martinlippert** [comment]
Again, please use the `https` variant of the URLs, not the `http` version. We might disable them sometime in the future.

And the URL https://download.springsource.com/release/TOOLS/sts4/update/4.4.0.RELEASE/e4.13 is not meant to be accessed via a browser, therefore the `Access Denied` message that you got is correct. The URL doesn't serve any index pages for the browser.

Instead, to check the connection via a browser, you could use https://download.springsource.com/release/TOOLS/sts4/update/latest/compositeContent.xml - as I said.
