### ISSUE TITLE
Add support for bosh template editing to bosh editor

### ISSUE THREAD

**Issue by kdvolder** [spring-projects/sts4#374]
Example: https://github.com/cloudfoundry/nfs-volume-release/blob/master/jobs/nfsv3driver/templates/ctl.erb#L19

Layout of the folders is allways the same. 

WE want to validate and autocomplete stuff like this:

```
 mkdir -p "<%= p("nfsv3driver.driver_path") %>"
```

Property that are valid can be found in this file:

https://github.com/cloudfoundry/nfs-volume-release/blob/master/jobs/nfsv3driver/spec

The properties are the first level keys under `properties`.

**Comment by kdvolder** [comment]
This ideas came from @paulcwarren

**Comment by kdvolder** [comment]
CC: @royclarkson who might also be interested in this.

**Comment by martinlippert** [comment]
I don't expect us to do any work on the bosh editing support anytime soon. Therefore closing this one here.
