### ISSUE TITLE
Won't install on macOS Catalina 10.15 

### ISSUE THREAD

**Issue by mstarkie** [spring-projects/sts4#379]
Just upgraded my OS and SpringToolSuite is broken.  Tried to re-install it and got the following:

![Screen Shot 2019-10-15 at 8 55 21 AM](https://user-images.githubusercontent.com/5957774/66833529-fbe07680-ef29-11e9-84f4-0f88c000c150.png)

**Comment by martinlippert** [comment]
Probably a duplicate of #375. Can you try the workaround mentioned there and let us know if that works for you?
