### ISSUE TITLE
Error trying to find JVM: TypeError: Cannot read property 'isJdk' of null

### ISSUE THREAD

**Issue by agilob** [spring-projects/sts4#392]
![image](https://user-images.githubusercontent.com/2544251/69582276-25cc9480-0fd0-11ea-9ebe-582456f5e381.png)

Related settings.json:

```
    // "java.configuration.updateBuildConfiguration": "automatic",
    "java.completion.guessMethodArguments": true,
    "java.home": "/home/agilob/.sdkman/candidates/java/current",
    "java.completion.enabled": true,
    // "java.autobuild.enabled": true,
    "boot-java.change-detection.on": true,
    "boot-java.live-information.automatic-tracking.on": true,
    "vsintellicode.java.completionsEnabled": true
```

Java version:

```
java -version
openjdk version "13.0.1" 2019-10-15
OpenJDK Runtime Environment (build 13.0.1+9)
OpenJDK 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)
```

13.0.1 installed from sdkman.

**Comment by kdvolder** [comment]
I've quickly tried using a jdk 13.0.1 downloaded from https://jdk.java.net/13/ and manually unpacked. Seems to work fine for me. So maybe this bug is something specific to how sdkman installs jdk that trips up our code looking for jre/jdk on local machine.

**Comment by kdvolder** [comment]
Actuallly looking at your `settings.json`. I think you have only declared which JDK to use for the redhat java language server, but not for the pivotal spring boot language server.

Could you try adding this to your `settings.json` please?

```
"spring-boot.ls.java.home": "/home/agilob/.sdkman/candidates/java/current"
```

Let me know if that makes a difference.

**Comment by kdvolder** [comment]
I am using sdkman now, still trying to reproduce the problem but so far without success. These are my steps:

1. install sdkman 
2. `sdk install java 13.0.1-open`
3. Close and open new terminal (seems like we need to do that for the new jvm to become available on the path)
4. In terminal verify  java version:

```
$ java -version
openjdk version "13.0.1" 2019-10-15
OpenJDK Runtime Environment (build 13.0.1+9)
OpenJDK 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)
```

5. Launch vscode from this terminal using the cli. E.g:

```
$ code /tmp/testws-code
```

The settings.json in that workspace was prepared ahead of time and has a contents similar to yours. I.e. it sets only the redhat `java.home` but not the one for `spring-boot.ls`. 

```
{
    "java.home": "/home/kdvolder/.sdkman/candidates/java/current",
}
```

This seems to work fine for me, the spring boot ls server is started properly picking up the JDK 13 from the `PATH`.

Can you provide a precise set of steps that results in this error that you get? Do they differ somehow from my steps? In particular how are you launching vscode? Are you sure that there is a `java` executable on the PATH for the launched vscode process. I suspect maybe that could be what makes the difference.

**Comment by kdvolder** [comment]
I've have tried launching vscode, this time carefully removing all trace of a `java` executable from the `PATH` before launching. Still not able to reproduce the problem unfortunately.

**Comment by agilob** [comment]
I'll give more details today in a few hours

**Comment by agilob** [comment]
OK, the issue is gone after adding the following line to global vsc config and restarting vsc

```
"spring-boot.ls.java.home": "/home/agilob/.sdkman/candidates/java/current"
```

Notification with error no longer appears.

To answer your questions:

```
~/Projects/jhip  master +2 !13 ?26  which java 
/home/agilob/.sdkman/candidates/java/current/bin/java
~/Projects/jhip  master +2 !13 ?26  java -version
openjdk version "13.0.1" 2019-10-15
OpenJDK Runtime Environment (build 13.0.1+9)
OpenJDK 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)
```

Default shell for my user is zsh and `~/.zshrc` contains:

```
export JAVA_HOME=/home/agilob/.sdkman/candidates/java/current
export PATH=$PATH:/home/agilob/.sdkman/candidates/java/current/bin

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/agilob/.sdkman"
[[ -s "/home/agilob/.sdkman/bin/sdkman-init.sh" ]] && source "/home/agilob/.sdkman/bin/sdkman-init.sh"
```

**Comment by kdvolder** [comment]
Thanks for extra info and closing the ticket.

The error that you reported is basically the typescript/javascript equivalent of a 'NPE' and really should never happen. So I feel there is still a bug of some kind here to fix. But as I can't explain or reproduce how you got that error.  So not really able to do much about it right now. So closing ticket seems like the right action.

Should you see the problem again and gain any insight into what exactly we need to do to trigger it,  please re-open or raise a new ticket.
