### ISSUE TITLE
Error trying to find JVM:Error:ENOENT: 

### ISSUE THREAD

**Issue by jdbr11** [spring-projects/sts4#393]
Error trying to find JVM:Error:ENOENT:  no such file or directory,lstat 'C:\xxxxxx\xxx\xx'

**Comment by kdvolder** [comment]
Does it literally say `C:\xxxxxx\xxx\xx` ? Or are you editing it to hide something sensitive from public forum?

In any case, the error means that the file or directory called `C:\xxxxxx\xxx\xx` does not exist. We have to determine where this value came from. 

One possibility is that you specified this directory in one of your settings.json files for vscode (i.e. your workspace or user settings) or maybe in a OS environment variable.

If you please, try to find / remember if you specified this directory anywhere.

**Comment by jdbr11** [comment]
thank you for your reply,It's my OS environment variable error.
