### ISSUE TITLE
sts4 is freezing when I do right click.

### ISSUE THREAD

**Issue by tamerx** [spring-projects/sts4#396]
The operating system I use is ubuntu 18.04.
Video card, nvidia geforce 940mx.
it keeps me waiting for about five minutes after he starts to freeze.

**Comment by kdvolder** [comment]
Sounds annoying. Are you using Eclipse? Or Vscode? 

Can you try and catch some stackdumps during the freeze so we can try to determine what may be getting 'stuck'. You can use CLI tools 'jps' and 'jstack' (included with JVM) to get stackdumps.

If you are using Eclipse, please grab both a dump of the Eclipse process as well as the language servers. Here's an example of output from jps on my machine:

```
$ jps
8458 Jps
8251 BootLanguagServerBootApp
7951 org.eclipse.equinox.launcher_1.5.600.v20191014-2022.jar
```

In this case process '8251' is the spring boot language server. And '7951' is Eclipse. So you would then grab stacks by doing something like `jstack 8251 > ls-stacks.txt` and `jstack 7951 > eclipse-stacks.txt`.

**Comment by kdvolder** [comment]
Also it would be a good idea to attach log output from language servers. In vscode you must enable it by setting property `spring-boot.ls.logfile` in your workspace or user settings. In Eclipse you enable it via 'Window >> Preferences >> Language Servers >> Spring Language Servers". On that page check the boxes and log output will be streamed into a Eclipse console (next time server starts).

**Comment by kdvolder** [comment]
@tamerx Any more info you can provide? I will close this ticket now because nothing really can be done without further information. We can always re-open the ticket again later if more information is provided.
