### ISSUE TITLE
Improve user experience around 'JDK requirement'.

### ISSUE THREAD

**Issue by kdvolder** [spring-projects/sts4#397]
I've decided to take a stab at  https://www.pivotaltracker.com/story/show/170245300

This is a spin-off ticket from https://github.com/spring-projects/sts4/issues/340

Since the original issue was a public github ticket, I think the spin-off ticket should  be in the public view too. So I am creating this github ticket for public visibility.

**Comment by kdvolder** [comment]
Relevant snippet from the big ticket:

Using a JDK instead of a JRE to run Eclipse

The page at:
https://github.com/spring-projects/sts4/wiki/Known-Limitations-&-Issues
suggests that in order for some features to work, running Eclipse with a JDK instead of a JRE is required. However, is there a way to see if the requirement is satisfied? I mean, if I configure Eclipse to run with the server.dll library contained in the jre folder of the JDK (which ensures better integration with the Windows process manager), does it satisfy the requirement?
Example:

```
-vm
C:/Program Files/Java/jdk1.8.0_202/jre/bin/
```

**Comment by kdvolder** [comment]
I'm not sure the best way to 'solve' this in general is just through documentation (though improving the doc is of course good).

I see 3 ways that we could improve the experience:

- better docs 
- better error messages
- more robust detection / location of JDK.

For the snippet that Nieraj copy pasted here seems like we could attack it on at least 2 out of these 3:

- docs: add a relatively small and straightforward clarification to the docs that answer that specific question with a 'Yes'. I.e. pointing to a JRE inside of a JDK satisfies the requirent.
- robustness: test that specific scenario and make sure that it is properly handled and the JDK is detected found in such a setup.
- error messages: if the robustness isn't there yet then... make sure at least the error message is sensible (and then *also* still fix the robustness issue).

**Comment by kdvolder** [comment]
My first test case on Windows. I had just accepted Windows VM suggestion to update my main JRE installation for latest Java 8. The update however only installs a JRE.

Observations: 
- When STS starts up, I get no errors or warnings.
- When the language server starts I get a warning popup that clearly and correctly explains it cannot find tools.jar. And it also lists explicitly exactly which JRE it was using. 

This looks good to me.

Next let's try and make sure that if I replace this with a proper/typical JDK installation it works properly. We should also conduct a similar test with more recent JRE/JDK (i.e. one that no longer has tools.jar but uses java module system instead).

**Comment by kdvolder** [comment]
Second test case: using jre8 that is installed side-by-side with a 'twin' jdk of the exact same version (seems to be a common scenario, so we supported that explicitly). This works as expected.

Third test case: using jre from inside of the a jdk (i.e. in a setup exactly as @mauromol was describing with lines like these added to the .ini file:

```
-vm
C:/Program Files/Java/jdk1.8.0_231/jre/bin/
```

This works as well. 

I'm now moning on to trying out similar scenarios with more modern JDK and JRE.

**Comment by kdvolder** [comment]
I've added some clarifications to the wiki page: https://github.com/spring-projects/sts4/wiki/Known-Limitations-&-Issues

In the end I didn't really do much to make this better as the things I did test actually seemed to work just fine. 

I have no doubdt however that there are still situations in which error reporting and the 'robustness' of the JVM/JRE/JDK dectection could be still improved. But I think we'll need some specific bug reports describing specific situations where things actually go wrong to be able to act on them.

Also @mauromol, we welcome your 'complaints' and suggestions for improvments in this or any other area. I'm sorry it took us so long to do anything about it. Perhaps in future I would suggest trying not to create a 'mega' issue with all your complaints at once. It is in large part seeing such a wall of text that causes a delayed response. The mega issue can seem rather hard to pry apart into actionable items. So if perhaps instead you could try to raise tickets 'one issue at a time' it may be acted upon much easier and sooner.

**Comment by mauromol** [comment]
Hi Kris, yes, sorry for the "mega ticket", it was indeed a mixture of "help please" and "I found these issues", indeed I'm not a great fan of StackOverflow, although I know you're lately suggesting to use it to request for help. Anyway, since there were multiple issues related to the STS3->STS4 switch,. I thought GitHub was the right place, especially since some previous discussions on the topic had already taken place here (like in #108 or in #96). Splitting things in different tickets would have been useful indeed, but the whole context would have been probably lost.

This said, the main reasoning about this specific issue (Improve user experience around 'JDK requirement') is this: since I couldn't (and still can't) apparently get STS4 features work correctly in my non-boot classical Dynamic Web Project, I thought my problems could have been related to the JDK requirement. Since I could not find a way to determine whether STS4 plugins were happy or not regarding this requirement, I could not establish for sure whether my problems were caused by a JRE being detected in place of a JDK. Now that you have added the note regarding the "JRE inside a JDK" use case in the documentation, at least I can say that my problem is NOT related to this.

> Since the original issue was a public github ticket, I think the spin-off ticket should be in the public view too

Is there something public regarding the "Improving documentation on installing STS4 components into base Eclipse" story as well?

Thanks a lot, as always.

**Comment by kdvolder** [comment]
Happy New Year! Sorry for long delay, I went on vacation for a little over 2 weeks and just came back today. Just catching up on things now :-)

> Is there something public regarding the "Improving documentation on installing STS4 components into base Eclipse" story as well?

I don't think there is. The 'private' Pivotal tracker ticket is here but there's no indication of a corresponding github ticket:

https://www.pivotaltracker.com/n/projects/1346850/stories/170245267

I'll add a note to the ticket for whoever picks it up and works on it to create a public facing ticket and place comments in there. At present it doesn't look like anyone has done anything specifically to address the Pivotal tracker ticket (judging from comments in the ticket... though I gather Martin did do some improvements already to the docs in repsonse to your original 'big' ticket: https://github.com/spring-projects/sts4/issues/340

> indeed I'm not a great fan of StackOverflow

NP. Github tickets are fine for questions or issues alike. 

> I thought GitHub was the right place

I didn't say that it was the wrong place. I would just have prefered some more focused tickets.

>  Since I could not find a way to determine whether STS4 plugins were happy or not regarding this requirement, I could not establish for sure whether my problems were caused by a JRE being detected in place of a JDK.

Okay I get it and that's a valid concern. Basically, as my testing has confirmed, if you didn't see an error/warning about JDK vs JRE and the language server is running then the requirement is satisfied. The server should complain when the requirement is not satisfied.

It can also help to enable Server logging under Window >> Preferences >> Language Servers >> Spring Language Servers" as some diagnostic information may be printed there re server startup.

From my point of view... if we can count on a clear error/warning message when the constraint is not satisfied, then this addresses the concern. 

So, do you think its okay to leave this ticket closed as 'resolved' or do you think we need to do something else? (I'm not sure what else to do, so you'll have to tell me what you have in mind here :-)

**Comment by mauromol** [comment]
If, as you say, an error is clearly shown to the user when the JDK requirement is not satisfied, I think you can leave this ticket closed, thank you. Maybe just adding a note to the "known limitations" page to say that an error is produced by the language server on start when this requirement is not satisfied would be enough for anyone like me to exclude this as a potential problem when anything else does not work as expected.

Happy new year Kris! :-)

**Comment by martinlippert** [comment]
As Kris mentioned, I already worked on improving the install documentation, as mentioned here: https://github.com/spring-projects/sts4/issues/340#issuecomment-572558018 - but I forgot to mark the tracker item as started (did now). So no need to add additional GitHub tickets for that part, I think.

If the enhanced version of the doc is still missing important information or details, please open a new GitHub issue for that.

**Comment by kdvolder** [comment]
I have added a few sentences, near the bottom of the first bullet point in the section about 'JDK required instead of JRE'. Feel free to have a look and provide feedback on this if you want.
