### ISSUE TITLE
[Bug]-Quit Spring Tool Suite 4

### ISSUE THREAD

**Issue by szxyidao** [spring-projects/sts4#399]
Click  "Quit Spring Tool Suite 4" will open many "Progress Information"，Please look at the screenshots.
https://digi-1258122014.cos.ap-chengdu.myqcloud.com/20200105/9b76097ffaf545e2b10bed4bb9376d1b.png
https://digi-1258122014.cos.ap-chengdu.myqcloud.com/20200105/0fd7332c36da44e492f7490cd8895c68.png

**Comment by martinlippert** [comment]
I can't really load the screenshots (access seems to be super slow), but you should take a look at the "Progress View" prior to stopping the IDE. I guess the same background processes will appear there, too. Is that the case? If so, we need to find out what those background tasks are and why they are running. Can you list them here?

**Comment by szxyidao** [comment]
Thank you,I pasted the picture here
<img width="1576" alt="9b76097ffaf545e2b10bed4bb9376d1b" src="https://user-images.githubusercontent.com/52267733/72133291-0214b080-33bc-11ea-909f-a7f486454da6.png">
<img width="1569" alt="0fd7332c36da44e492f7490cd8895c68" src="https://user-images.githubusercontent.com/52267733/72133306-0d67dc00-33bc-11ea-8807-b1781ca6ba29.png">
sorry, I've uninstalled "Spring Tool Suite 4"

**Comment by martinlippert** [comment]
That is too bad, I would love to gather more details about this issue to find out that is going wrong, so whenever you decide to give this another try, let me know.

**Comment by szxyidao** [comment]
ok,thank you
