### ISSUE TITLE
Error: Could not find or load main class

### ISSUE THREAD

**Issue by froza** [spring-projects/sts4#407]
after update my sts4 to spring-tool-suite-4-4.5.1.RELEASE-e4.14.0 (and workspace)
all projects cannot start and print: "Could not find or load main class .." for all main spring boot classes and simple classes

I have tried following actions:
- Re-Import the Projects
- Maven Clean / Project Clean
- Change the JRE to JDK
- Create simple class with main (not work)

**Comment by kdvolder** [comment]
Probably this problem again: https://github.com/spring-projects/sts4/issues/406

Closing as a 'duplicate'. However if you can still reproduce the problem with latest CI build **on Ecllipse 4.15** then, it could be something else. If so please try to give some detailed steps we can try to reproduce and we can re-open this issue and debug it.

**Comment by froza** [comment]
tks, 
i updated to nightly spring-tool-suite-4-4.5.2.CI-B2150-e4.14.0 and not solved
after try e4.14,
try upgrade to spring-tool-suite-4-4.5.2.CI-B2150-e4.15.0 and this solved the problem

**Comment by kdvolder** [comment]
> upgrade to spring-tool-suite-4-4.5.2.CI-B2150-e4.15.0 and this solved the problem

Thanks for confirming that.
