### ISSUE TITLE
STS crash after connecting Windows Remote Desktop

### ISSUE THREAD

**Issue by gregsaint** [spring-projects/sts4#408]
This issue appears be affecting STS 4.5.1RELEASE as well (Build Id: 202001211336)

https://bugs.eclipse.org/bugs/show_bug.cgi?id=543747

**Comment by martinlippert** [comment]
Thanks for the pointer and good to see this got fixed already in the platform. We plan to ship the next Spring Tools 4 release on March 19, based on the then released Eclipse 2020-03 release, which includes the fix.

If you need an earlier update, feel free to give the nightly CI builds of Spring Tools 4 for Eclipse on Eclipse 2020-03 a try from here: http://dist.springsource.com/snapshot/STS4/nightly-distributions.html

**Comment by gregsaint** [comment]
OK, thanks :)
