### ISSUE TITLE
Spring tool suite 4 - not opening new Spring project, because of certification exception

### ISSUE THREAD

**Issue by sandorApati** [spring-projects/sts4#412]
Dear Spring!

"Installed" STS 4-4.5.1 on my laptop, but when i want to open a new Spring Starter Project, i get the following error:

 SunCertPathBuilderException: unable to find valid certification path to requested target

I have already downloaded the certification from start.spring.io and added to 
jre1.8.0_241\lib\security\cacerts

Regards
Sandor Apati

**Comment by martinlippert** [comment]
Hey @sandorApati, hard to say remotely what exactly is going wrong here. Can you double check whether your IDE is indeed running on top of that JRE that you mentioned? You can check that via the `About Dialog -> Installation Details -> Configuration Tab`.

Another check maybe worth a try could be to open an internal web browser view in your Eclipse/STS install and check whether you can access https://start.spring.io in there.

**Comment by tonytigerrong** [comment]
> Dear Spring!
> 
> "Installed" STS 4-4.5.1 on my laptop, but when i want to open a new Spring Starter Project, i get the following error:
> 
> SunCertPathBuilderException: unable to find valid certification path to requested target
> 
> I have already downloaded the certification from start.spring.io and added to
> jre1.8.0_241\lib\security\cacerts
> 
> Regards
> Sandor Apati

I have the same error

**Comment by tonytigerrong** [comment]
> Hey @sandorApati, hard to say remotely what exactly is going wrong here. Can you double check whether your IDE is indeed running on top of that JRE that you mentioned? You can check that via the `About Dialog -> Installation Details -> Configuration Tab`.
> 
> Another check maybe worth a try could be to open an internal web browser view in your Eclipse/STS install and check whether you can access https://start.spring.io in there.

I have the same situation, I can't access https://start.spring.io in STS browser. And I checked the Configuration Tab, be sure the certification was added into the jre which started my STS.

**Comment by sharsh** [comment]
When I am trying to access url from STS browser.
![image](https://user-images.githubusercontent.com/785772/86429107-1ad5a180-bd21-11ea-9691-252239f8147e.png)

![image](https://user-images.githubusercontent.com/785772/86429131-32ad2580-bd21-11ea-9ff6-e0d582e56924.png)

**Comment by HarshaVardhanAcharyAthaluri** [comment]
any update facing same issue

**Comment by martinlippert** [comment]
Is there any detailed log output from the Error Log that you can post here?

**Comment by martinlippert** [comment]
At the moment we don't have any further advice beyond what you can find on stackoverflow for making the JDK aware of the certificate. But we will dive deeper and try to find a way to describe a solution that works here. In the meantime, you can always use the https://start.spring.io service via a browser, download the project, unzip it on your machine, and import it via the "Import as existing Maven project..." wizard (in case you selected Maven on https://start.spring.io.

**Comment by Iandris** [comment]
I found that within an enterprise LAN there was an issue with proxy configuration.

To resolve, I followed this solution on stack : https://stackoverflow.com/a/56780302

**Comment by martinlippert** [comment]
Thanks @Iandris for the additional link, much appreciated.

With that, I will close this issue, as there doesn't seem to be anything that we can do directly.

**Comment by deekshitharajesh** [comment]
<img width="735" alt="image" src="https://user-images.githubusercontent.com/70856350/192299638-32db39f4-13f9-4d90-8d7e-3a281f928663.png">

**Comment by deekshitharajesh** [comment]
i am not able to create a spring project

**Comment by martinlippert** [comment]
@deekshitharajesh Did you try the solutions and recommendations from within this issue? Those should help to setup your environment to make this work.
