### ISSUE TITLE
question about annotation

### ISSUE THREAD

**Issue by talent2333** [spring-projects/sts4#419]
It is so strange that I can not use any annotation on sts4, such as @Component.No use!

**Comment by BoykoAlex** [comment]
What do you mean by that? Can you attach your project here? Your project is probably missing `spring-context` jar on the classpath. How did you create your project? There is a File -> New -> Spring Starter Project wizard that you should use for that.

**Comment by talent2333** [comment]
Thanks to answer my question so quickly,I really use the wizard.
[demo.zip](https://github.com/spring-projects/sts4/files/4324805/demo.zip)

**Comment by kdvolder** [comment]
I downloaded your project. Imported into my STS 4 in a new workspace. I had an error on the project related to the `spring-boot-configuration-processor`. That error was resolved by using 'Maven >> Update Project' from the project context menu (this menu actions asks maven tooling to fixup the various Eclipse project settings such as classpath and annototion processor factory path in accordance with the maven pom file).

After that, there seemed to be no problems with the project. I can use annotations such as `@Controller` and `@Component` and the do what I expect (i.e. create beans in the project at runtime).

**Comment by talent2333** [comment]
I use 'Maven>>Update Project',but I still have the same question that the @Autowired Person in Controller1 did not work.I really don't know how to solve this question and work for it one night.Maybe it's related to my Eclipse Oxygen?

**Comment by kdvolder** [comment]
The annotation in the controller appears to be on a method with no parameters. So It doesn't make sense and I'm not really sure what you are trying to do. However, I don't think this is a bug in STS. 

This really isn't the place to ask questions about Spring in general. For that there are other places like stackoverflow.

**Comment by kdvolder** [comment]
I've modified your project a little. Trying to guess a bit what you were trying to do. 

The controler now has a `@Autowired` Person and this seems to work just fine. You can try it by running the app and accessing the requestmapping I added to the controller at path '/'.  You will see it returns the toString value of the person object.
  
[`demo.zip](https://github.com/spring-projects/sts4/files/4325158/demo.zip)

**Comment by talent2333** [comment]
Thanks very much.
But you also `import com.example.demo.entity.Person;`  which means no use for annotation @Autowired

**Comment by kdvolder** [comment]
> But you also import com.example.demo.entity.Person;

Yes that is necessary or the code will not compiler.

> no use for annotation @Autowired

Yes there is a use and it works. What it does is tell spring to inject an *instance* of the class at runtime. You can try remove the annoation and run the program again. You will then see that the controller will not have an instance and will probably error with an NullPointerExcetpion when it tries to call 'toString'.

Anyway... it seems to me you are learning spring, and that is fine. But this is not the place to ask / answer basic questions about how spring works.

**Comment by talent2333** [comment]
It's my honor to get your help,thank you in indeed!
