### ISSUE TITLE
Exception after latest Eclipse updates

### ISSUE THREAD

**Issue by heruan** [spring-projects/sts4#421]
I'm getting this exception after the latest Eclipse updates.

<img width="1030" alt="Screenshot 2020-03-17 at 12 04 53" src="https://user-images.githubusercontent.com/851745/76850431-a34e3600-6847-11ea-9d6d-58f4f7b61b97.png">

I tried to reinstall Eclipse and STS4 works, but after updating again it stops working the same.

**Comment by martinlippert** [comment]
Which version of Eclipse did you install? And how did you install STS4 on top of it? And which components show up to be updated in the process?

**Comment by heruan** [comment]
Eclipse IDE for Enterprise Java Developers.

Version: 2019-12 (4.14.0)
Build id: 20191212-1212

STS4 installed via Marketplace. Components that show up to be updated are Mylin and m2e Tools (via Red Hat CodeReady Studio).

**Comment by martinlippert** [comment]
I tried a fresh Eclipse 4.14 Java package and installed STS4 into it via the marketplace. That went fine. Then I did a "Check for Updates" and two m2e components showed up as well as the Eclipse marketplace client. After the update, the IDE started fine and the boot dashboard also continued to work. That makes me think that the combination with additional plugins that you have installed (like the Red Hat CodeReady Studio components that you mentioned) might cause the issue. Can you tell me more about the additional plugins that you have installed and where to get them from?

To turn your installation into a working state again, I would recommend to roll-back the update via the `About -> Installation Details -> Installation History`, where you can revert to a previous state. Hope that helps to deal with the issue in the short term.

**Comment by heruan** [comment]
Thank you Martin, on the n-th time I reinstalled everything it went fine. Well, fine with STS4, now I don't have Java content assist suggestions 😖 Not sure what's going on, could be a combination of updates as you said. Hope Eclipse 2020-03 will solve these issues!

**Comment by martinlippert** [comment]
@heruan Glad to hear that is works now, but the broken content-assist doesn't sound good. Do you see an exception being logged to the Error Log view that might be related?

**Comment by martinlippert** [comment]
And you could double check if disabling the Spring Boot language server helps with this, just to see if this is related to the Spring Boot tooling or not.

**Comment by mweirauch** [comment]
Regarding the broken content-assist - I don't remember the constellations - also happened to me quite often. (Using STS already for a while.)
For me it's broken in that sense that - IIRC - after an STS install or update, the Java-Content-Assist just isn't checked anymore in the Content-Assist settings itself. Re-enabling helps.

Sorry for not being able to recap exactly what installation or update procedure this caused.

**Comment by kdvolder** [comment]
> For me it's broken in that sense that - IIRC - after an STS install or update, the Java-Content-Assist just isn't checked anymore in the Content-Assist settings itself. Re-enabling helps.

I remember vaguely this was a problem a while back and was something to do with transitioning between two versions of Eclipse. Something was going wrong there migrating workspace preferences from one version of Eclipse to another. As far as I know/remember that problem came to us via Eclipse, and Eclipse folks fixed this already a while back. But if you are *still* experiencing this still regularly with current Eclipse versions... then perhaps it merrits to be re-investigated.

**Comment by martinlippert** [comment]
In a previous version, we included the Eclipse Code Recommenders extensions, They replaced the existing standard Java content-assist with their own, specialized version and made that the default (and disabled the standard Java content-assist to avoid duplicates). This setting was stored in the workspace. When opening the same workspace with a newer version of Eclipse/STS that didn't contain the Code Recommenders extensions anymore, that setting in the workspace caused the regular Java content-assist to continue to be disabled, whereas the replacement from Code Recommenders wasn't there anymore, resulting in no Java content-assist showing up. Instead, there was a message showing up and informing the user about this and telling the user how to fix this (manually enable the Java content-assist again). But it was easy to miss that dialog or not look into the details of it.
