### ISSUE TITLE
open fail

### ISSUE THREAD

**Issue by weir2010** [spring-projects/sts4#422]
Last login: Thu Mar 19 13:51:18 on ttys000
/Applications/SpringToolSuite4.app/Contents/MacOS/SpringToolSuite4 ; exit;
➜  ~ /Applications/SpringToolSuite4.app/Contents/MacOS/SpringToolSuite4 ; exit;
Error: could not find libjava.dylib
Failed to GetJREPath()

**Comment by martinlippert** [comment]
Please try and specify the JVM to run the IDE with in the SpringToolSuite4.ini file, as described here: https://wiki.eclipse.org/Eclipse.ini.

Make sure that you specify `-vm` in the first line of the ini file and the path to the java executable in the second line, then everything else following after that.

Hope that helps!

**Comment by weir2010** [comment]
> Please try and specify the JVM to run the IDE with in the SpringToolSuite4.ini file, as described here: https://wiki.eclipse.org/Eclipse.ini.
> 
> Make sure that you specify `-vm` in the first line of the ini file and the path to the java executable in the second line, then everything else following after that.
> 
> Hope that helps!

It's settled. Thank you

**Comment by martinlippert** [comment]
In addition to specifying a different JVM in the `.ini` file, you are likely running into an issue with the JDK installation. Eclipse and Spring Tools 4 for Eclipse seem to fail to create the JVM at startup when running on JDK14, AdoptOpenJDK-11/14 and the solution is to slightly fix your JDK install, as described in comment 11 here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=559482#c11
