### ISSUE TITLE
Live hovers do not work when "spring.jmx.default-domain" is set to an alternate value.

### ISSUE THREAD

**Issue by tkvangorder** [spring-projects/sts4#44]
We have an application that sets the default JMX domain to our company prefix "com.build". Since STS4 is using JMX to provide the live hover support, it does not find any of the actuator endpoints because they are under a different domain. I am not sure you can detect the domain on startup (probably not), so this might just be a configuration property that is added to the tool: "Actuator JMX Domain" or maybe just something that is added to the documentation. 

I was able to work around the problem by setting the "endpoints.jmx.domain" back to "org.springframework.boot".

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Nieraj Singh:) 

Pushed some changes to SpringBootApp that take into account other domains used for Spring Boot Actuator in JMX. 

To test:

Test 1:
Ensure live hovers for app with default domain, `org.springframework.boot` ,  works fine

Test 2:
Stop the app, add applications.properties to the app's src/main/java default package, and add the following property:
`spring.jmx.default-domain=com.my.app`.
Should get live hovers.

Note that this test does not require restarting the LS. Switching domains should work with the same editor opened, as domains affects live information from running apps. Just need to restart the app with a different domain in application.properties
