### ISSUE TITLE
Eclipse update fails with certificate issues

### ISSUE THREAD

**Issue by 2019-05-10** [spring-projects/sts4#441]
Trying to update Eclipse with STS installed constantly fails with certificate errors for 
 https://download.springsource.com

An error occurred while collecting items to be installed
session context was:(profile=epp.package.jee, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Unable to read repository at https://download.springsource.com/release/TOOLS/sts4/update/4.6.0.RELEASE/e4.14/plugins/org.springframework.ide.eclipse.boot_3.9.12.202003180620-RELEASE.jar.
Certificate for <download.springsource.com> doesn't match any of the subject alternative names: [*.teakmoebel.com, sni.cloudflaressl.com, teakmoebel.com]

"Alternative names" varies, but this one is the most terrible.
No idea what happens, but it's chilling.

**Comment by martinlippert** [comment]
Hmmm... Strange, the certificates on the domain looks okay to me.

What happens if you replace `download.springsource.com` with `dist.springsource.com` in the update site preferences? Does that change anything?

**Comment by 2019-05-10** [comment]
dist.springsource.com did the trick.
Although I had to restart Eclipse to pick that change up.

**Comment by martinlippert** [comment]
Glad to hear that the change helped. Closing this for now.  In case you would like to debug the certificate issue further, let us know, and we can re-open and dive in the details here.
