### ISSUE TITLE
Update fails with Version: 4.5.2.CI-B2160

### ISSUE THREAD

**Issue by vogella** [spring-projects/sts4#443]
With Spring Tool Suite 4 
Version: 4.5.2.CI-B2160
Build Id: 202002240433
OS: Linux, v.5.3.0-45-generic, x86_64 / gtk 3.24.12, WebKit 2.28.0
Java version: 1.8.0_242
I tired to update and get the following error. 

![image](https://user-images.githubusercontent.com/139910/78772584-45b69080-7992-11ea-9af2-800c75680a0f.png)

Maybe this is expected and I need to download the new nighly?

**Comment by martinlippert** [comment]
"No repository found..." always sounds like stale p2 repo cache data. Try to reload the update sites in the preferences, maybe that helps already. If not, let me know and we can dive into the details. You should definitely be able to update an existing install. Also double check the Eclipse platform version and the update sites that you have in the prefs (in case we need to dive into the details).

**Comment by vogella** [comment]
Looks like http://download.eclipse.org/lsp4e/snapshots is broken. Feel free to close the ticket.

**Comment by martinlippert** [comment]
The latest lsp4e should also be around on the Spring Tools 4 update sites (for convenience), therefore I am wondering that exactly is going wrong here...

**Comment by martinlippert** [comment]
Looks like we can close this old item here. Please open a new item for any new installation or update issues... :-)
