### ISSUE TITLE
Link Download Windows 64-Bit invalid

### ISSUE THREAD

**Issue by emanueltobias** [spring-projects/sts4#445]
Link download invalid adjust from [Windows 64-Bit](https://download.springsource.com/release/STS4/4.6.0.RELEASE/dist/e4.15/spring-tool-suite-4-4.6.0.RELEASE-e4.15.0-win32.win32.x86_64.self-extracting.jar) to [Windows 64-Bit](https://download.springsource.com/release/STS4/4.6.0.RELEASE/dist/e4.15/spring-tool-suite-4-4.6.0.RELEASE-e4.15.0-win32.win32.x86_64.zip) in the website [Spring | Tools](https://spring.io/tools)

**Comment by martinlippert** [comment]
The provided download link is correct:

https://download.springsource.com/release/STS4/4.6.0.RELEASE/dist/e4.15/spring-tool-suite-4-4.6.0.RELEASE-e4.15.0-win32.win32.x86_64.self-extracting.jar

It points to the self-extracting JAR file that extracts the Spring Tools 4 for Eclipse distribution once downloaded and executed. This avoids issues with too long path names on Windows that caused many issues in the past. That is why we chose to use this distribution as the default download for Windows.

The alternative link is:

https://download.springsource.com/release/STS4/4.6.0.RELEASE/dist/e4.15/spring-tool-suite-4-4.6.0.RELEASE-e4.15.0-win32.win32.x86_64.zip

chic requires you to unzip the file yourself, which can cause the above mentioned issues if not done correctly. Therefore we will keep the self-extracting version as the default download URL.
