### ISSUE TITLE
When using the "Alt + /" smart code prompt to select a method, Eclipse inserts the current method body behavior by default, which will lead to the following situation, which is very frustrating:

### ISSUE THREAD

**Issue by 395053994** [spring-projects/sts4#446]
When using the "Alt + /" smart code prompt to select a method, Eclipse inserts the current method body behavior by default, which will lead to the following situation, which is very frustrating:
Please see the picture for the process description:
![11111111](https://user-images.githubusercontent.com/27546390/79176276-5e132900-7e32-11ea-938c-38523e848ed3.png)
![2222222](https://user-images.githubusercontent.com/27546390/79176292-68cdbe00-7e32-11ea-918a-55606d502db3.png)
![33333333333333](https://user-images.githubusercontent.com/27546390/79176319-7daa5180-7e32-11ea-8d40-da905b725883.png)
Can you see it? The previous method body still needs to be manually deleted, which is very troublesome in coding.

I don't know if this problem can be solved. If it can't be solved, please transfer it to the Eclipse IDE development team to solve it. What do you think?
Other IDEs replace the current method body by default, which is great. Can you understand what I mean by my description?
System: win10 enterprise x64
STS4: 4.6 x64
Memory: 8GB
Hard disk: 5400 rpm
JDK: 1.8

I hope you or the Eclipse IDE team can solve this problem. thank you very much!

**Comment by martinlippert** [comment]
You can configure this behavior in the `Preferences -> Java -> Editor -> Content-Assist`, it is the first option on that page. It lets you choose between insert and overwrite mode for completions.

**Comment by 395053994** [comment]
Although the method can be replaced, the method body can not be replaced with the selected method body, you still need to manually delete the useless parameter content

**Comment by 395053994** [comment]
Like, idea, visualstudio do not need to manually delete useless parameter content like this

**Comment by kdvolder** [comment]
If Martin's suggestions doesn't quite do what you want (and I agree personally that the 'overwrite' mode for completions in Eclipse isn't terribly useful) then It sounds like you have a valid complaint to me. 

However, this behavior is inherited by STS from Eclipse JDT. STS doesn't directly control it. 

If you have a good idea on how to improve this behavior then you could try raising a enhancement request as an Eclipse bugzilla ticket here: https://bugs.eclipse.org/bugs/

If you want to do this, try to be as precise as possible on what behavior you would like as opposed to what it does currently. If you explain it well then there is a decent chance that JDT developers will actually act on your suggestion and try to fix it.

**Comment by 395053994** [comment]
Thanks a lot

**Comment by martinlippert** [comment]
@395053994 You are right, the params are not being deleted automatically, I can totally see your point here. I would suggest to raise this with Eclipse JDT via: https://bugs.eclipse.org/bugs/enter_bug.cgi?product=JDT - auto-selects the right project for this. You should select "UI" as the component then, since most of the auto-completion is implemented there.
