### ISSUE TITLE
import spring-boot project，can‘t start

### ISSUE THREAD

**Issue by spiritelf** [spring-projects/sts4#448]
![image](https://user-images.githubusercontent.com/8556186/79245499-c1d93880-7eaa-11ea-9e65-c1ba4e8599f5.png)

have no error？

**Comment by spiritelf** [comment]
i can start this project  in Idea.

**Comment by BoykoAlex** [comment]
Hmm... any chance you attach you project here? Also, I don't see how STS is involved here... do you start the project from the CLI?

**Comment by kdvolder** [comment]
Maybe this problem: https://github.com/spring-projects/sts4/issues/434 ?

If not, then it is very hard  / impossible to say what the problem may be. Please provide a sample project and/or more information on exactly what you are trying to do. Things like:

- details about the project such as the dependencies / pom of the project
- your OS
- which version of Java you are running it with
- etc.

**Comment by spiritelf** [comment]
windows8   VScode 1.44.0    jdk1.8.0_22

![image](https://user-images.githubusercontent.com/8556186/79247084-9c4d2e80-7eac-11ea-848b-d7831c7a6f67.png)

**Comment by spiritelf** [comment]
![image](https://user-images.githubusercontent.com/8556186/79247238-d74f6200-7eac-11ea-8743-2c52dae9bd77.png)

![image](https://user-images.githubusercontent.com/8556186/79247265-e1716080-7eac-11ea-91d5-3298e997051f.png)

**Comment by kdvolder** [comment]
Okay if you are launching this from vscode then this is not the right place to report a problem with that. 

From the screenshots it looks like you are using the vscode redhat Java extension to launch your app. So you should report the problem with that extension:

https://github.com/redhat-developer/vscode-java/issues

**Comment by spiritelf** [comment]
![image](https://user-images.githubusercontent.com/8556186/79248093-f7335580-7ead-11ea-84c1-71b2b4c51c25.png)


![image](https://user-images.githubusercontent.com/8556186/79248097-f7cbec00-7ead-11ea-9b0e-0a525dac92bb.png)


the same result ?

**Comment by spiritelf** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.hsshy</groupId>
    <artifactId>beam-admin</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>beam-admin</name>
    <description>后台管理系统</description>

    <parent>
        <groupId>com.hsshy</groupId>
        <artifactId>beam-parent</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <dependencies>

        <dependency>
            <groupId>com.hsshy</groupId>
            <artifactId>beam-common</artifactId>
        </dependency>

        <dependency>
            <groupId>com.hsshy</groupId>
            <artifactId>beam-web</artifactId>
        </dependency>


        

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>




        
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
        </dependency>

        
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
        </dependency>

        
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
        </dependency>

        
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        
        <dependency>
            <groupId>org.apache.shiro</groupId>
            <artifactId>shiro-core</artifactId>
            <exclusions>
                <exclusion>
                    <artifactId>slf4j-api</artifactId>
                    <groupId>org.slf4j</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.shiro</groupId>
            <artifactId>shiro-spring</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.shiro</groupId>
            <artifactId>shiro-ehcache</artifactId>
            <exclusions>
                <exclusion>
                    <artifactId>slf4j-api</artifactId>
                    <groupId>org.slf4j</groupId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.ehcache</groupId>
            <artifactId>ehcache</artifactId>
        </dependency>

        <dependency>
            <groupId>org.quartz-scheduler</groupId>
            <artifactId>quartz</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>


        <dependency>
            <groupId>com.github.penggle</groupId>
            <artifactId>kaptcha</artifactId>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <configuration>
                    <nonFilteredFileExtensions>
                        <nonFilteredFileExtension>woff</nonFilteredFileExtension>
                        <nonFilteredFileExtension>woff2</nonFilteredFileExtension>
                        <nonFilteredFileExtension>eot</nonFilteredFileExtension>
                        <nonFilteredFileExtension>ttf</nonFilteredFileExtension>
                        <nonFilteredFileExtension>svg</nonFilteredFileExtension>
                        <nonFilteredFileExtension>otf</nonFilteredFileExtension>
                    </nonFilteredFileExtensions>
                </configuration>
            </plugin>

        </plugins>

    </build>


</project>

**Comment by kdvolder** [comment]
The spring boot dashboard for vscode is not the same as STS 4 Eclipse or the STS 4 language servers. For problems with vscode spring boot dashboard you should report them here:

https://github.com/Microsoft/vscode-spring-boot-dashboard/issues

However, I beleave vscode-spring-boot dashboard uses RedHat java to launch. So the problem is most likely with the redhat java extension. So I'd start by reporting it there. 

If you report it there, you should try to be precise in your report so that people trying to help you know what they need to do exactly to be able to reproduce it. Otherwise they will not be able to help you. So you should try to:

- attach a complete sample project in a zip
- provide step by step instructions on how to import the project to reproduce as close as possible how you did this yourself
- provide precise step by step instructions on how you launch the app

**Comment by spiritelf** [comment]
ok，i will try




| |
hq-power
|
|
邮箱：hq-power@163.com
|

Signature is customized by Netease Mail Master

On 04/15/2020 01:26, Kris De Volder wrote:

The spring boot dashboard for vscode is not the same as STS 4 Eclipse or the STS 4 language servers. For problems with vscode spring boot dashboard you should report them here:

https://github.com/Microsoft/vscode-spring-boot-dashboard/issues

However, I beleave vscode-spring-boot dashboard uses RedHat java to launch. So the problem is most likely with the redhat java extension. So I'd start by reporting it there.

If you report it there, you should try to be precise in your report so that people trying to help you know what they need to do exactly to be able to reproduce it. Otherwise they will not be able to help you. So you should try to:

attach a complete sample project in a zip
provide step by step instructions on how to import the project to reproduce as close as possible how you did this yourself
provide precise step by step instructions on how you launch the app

**Comment by spiritelf** [comment]
redhat-developer/vscode-java close my issues。。


import spring-boot project，can‘t start out-of-scope
#1392 by spiritelf was closed 22 hours ago
