### ISSUE TITLE
STS4 Eclipse: Failed to refresh live data from process 18225

### ISSUE THREAD

**Issue by alexmex90** [spring-projects/sts4#450]
Hello,

I'm running the stand alone STS4 based on Eclipse, and straight out of the box I get this error when I run a basic Hello World Sprinb Boot webapp.
![Screenshot from 2020-04-19 15-25-18](https://user-images.githubusercontent.com/43529725/79701495-66b09880-8252-11ea-91ef-8295517ed616.png)

Is there something that requires configuration? or am I doing something wrong?

**Comment by martinlippert** [comment]
You are doing nothing wrong. The tooling tries to show live hover information for your app: https://github.com/spring-projects/sts4/wiki/Live-Application-Information

But for some reason the tooling fails to make a connection to that running process. Do you have actuators on the project? And how did you start the app?

In case you are not interested in the automatic enablement of this live hover mechanism, you can just ignore this message.

You could also disable the automatic tracking of processes via `Preferences -> Language Server -> Spring Language Server -> Spring Boot Language Server -> Spring Boot Java` and deselect the `Live Information - Automatic Process Tracking`. Even if you disabled the automatic tracking, you can display the live information manually, as described here: https://github.com/spring-projects/sts4/wiki/Live-Application-Information

Hope this helps!

**Comment by alexmex90** [comment]
Hi Martin, thanks for your reply.

My application is a HelloWorld, I picked Spring Web MVC, thymeleaf, jpa and h2 database. As far as I can tell I don't have actuators, but I'm still a beginner, so that's why I asked if I was missing something.

![image](https://user-images.githubusercontent.com/43529725/79724901-27f40000-829d-11ea-8e3a-2fa0420c43a2.png)

![image](https://user-images.githubusercontent.com/43529725/79724918-33dfc200-829d-11ea-8767-f91ccd43e1f8.png)

This is literally all I have, and I'm starting the application by right clicking the project and selecting "run as... Spring Boot App" right after it starts it tries to connect to the process without success.

Good to know it is safe to ignore the error, I was confused by it, I previously used Eclipse 2019-12 with STS4 plugin and I don't remember seeing the error, so now that I moved to standalone STS4 I was confused if there was some setup I was missing.

**Comment by martinlippert** [comment]
Yes, it is absolutely safe to ignore the error and we will probably change that message dialog in the future anyway to not annoy or confuse users too much.

As a quick check, can you add the spring-boot-actuators module to your project to see if you can get the live hovers to work for your project? Would be interesting. And if not, maybe attach your project somewhere for us as an example to took at and think about possible improvements for those settings?

**Comment by alexmex90** [comment]
Adding spring-boot-actuators stopped the message entirely and looks like it is working as it should.

![Screenshot from 2020-04-23 20-35-38](https://user-images.githubusercontent.com/43529725/80172509-0a2ae180-85a2-11ea-8649-d6265c1d38e5.png)

Perhaps if there are no actuators in the project there should not be any attempt to connect to a process? To prevent having to display an error message when it should not be required? Although it looks useful, I may include in my future projects! :)

**Comment by martinlippert** [comment]
Glad to hear that this works just fine when you have the actuators on the project, that is good news.

As mentioned above, you can disable the automatic process tracking in the preferences and instead manually enable this for a running spring boot application. That way you would avoid the error message for projects without actuators.

**Comment by Librichard** [comment]
> Yes, it is absolutely safe to ignore the error and we will probably change that message dialog in the future anyway to not annoy or confuse users too much.
> 
> As a quick check, can you add the spring-boot-actuators module to your project to see if you can get the live hovers to work for your project? Would be interesting. And if not, maybe attach your project somewhere for us as an example to took at and think about possible improvements for those settings?

It is good of you mention the <depency> block we need to add to the pom.xml
Thanks.

**Comment by alexmex90** [comment]
I added
`<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>`

to my pom.xml and that stopped the error message.

**Comment by martinlippert** [comment]
Please keep in mind that you should only use the Spring Boot Actuators if you want to use this live information feature or other things the actuators are good for. Adding actuators to your project only and exclusively to get rid of this error message would be wrong. In that case, please note that you can disable the automatic process tracking in the preferences, which would avoid this error message as well - and still allow you to manually connect the live hover mechanism to the project.

**Comment by alexmex90** [comment]
I disabled the automatic process tracking since I'm just learning and have no real use for Actuator just yet, I think this should be disabled unless actuator is enabled in the project either by the spring boot project creation wizard or by manual insertion by the user.

**Comment by martinlippert** [comment]
I agree, sounds like a very good point and idea how to improve this. Will take a look.

**Comment by martinlippert** [comment]
I added a check to avoid this automatic process connection for projects that don't have the spring boot actuators on their classpath. Should make this a lot smoother and avoids the error message coming up for projects without actuators.

**Comment by alexmex90** [comment]
Hello, I am seeing the error message again. I have my STS4 installation updated up to the latest release

![image](https://user-images.githubusercontent.com/43529725/92336513-5c9f0300-f056-11ea-9996-f728f423b8a7.png)

It is again, a Spring Boot project without actuators. Let me know if you need any feedback or any help with debugging.

**Comment by martinlippert** [comment]
Hey @alexmex90, I double checked this with the latest snapshot build and it seems to work fine for my case, so it looks like my case is somewhat different from your case. Can you create a small sample project that reproduces the behavior? That would be awesome.

**Comment by alexmex90** [comment]
Not sure what happened, I was not able to replicate the issue.

I created two Spring Boot project, without anything, and other with Spring Web, none of which triggered the issue. I went to the project that triggered the issue initially and it didn't come up, so I guess everything's fine, if something new comes up, I will let you know.

Cheers!

**Comment by martinlippert** [comment]
@alexmex90 Ok, sounds good to me. Thanks for double-checking.
