### ISSUE TITLE
manually registered servlet mapping is missing from live request mapping tab in boot dashboard

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#452]
as described in this sample project from @soe78:
https://github.com/soe78/CxfDemo

the manually registered request mapping`/hello` doesn't show up in the boot dashboard properties view tab for the request mappings.

The live data from the actuator does contain information about this mapping:

`{mappings=[/hello], name=httpServlet, className=demo.config.ServletConfig$1}`

Even though the `className` can't point the tooling towards the exact location of the manual registration, the data allows the tooling to at least navigate to the referenced inner class (in this example case).

**Comment by soe78** [comment]
Hi Martin, 
I could retest my app, and STS does exactly, what I was looking for. I see my cxf path, my servlet produced by ServletRegistrationBean, and also added a Servlet which is registered by @ServletComponentScan - all three appear in Request Mapping view and in the path search.
Thanks again, looking forward to install the stable version!!!

**Comment by martinlippert** [comment]
Awesome, great to hear, and thanks for testing the CI build here!!! 4.6.2 will ship in late May.
