### ISSUE TITLE
In the process of writing Java code, for example: the string parameter STS4 in the method cannot automatically match and complete the double quotes "", can this be improved, IDEA and other editors can automatically match and complete the double quotes ""

### ISSUE THREAD

**Issue by 395053994** [spring-projects/sts4#454]
In the process of writing Java code, for example: the string parameter STS4 in the method cannot automatically match and complete the double quotes "", can this be improved, IDEA and other editors can automatically match and complete the double quotes ""

**Comment by 395053994** [comment]
Each time you need to manually enter the double quotation mark "" twice.

**Comment by martinlippert** [comment]
Since this is an improvement that affects the general Java coding experience, it should be reported against Eclipse here: https://bugs.eclipse.org/bugs/enter_bug.cgi?product=JDT

**Comment by martinlippert** [comment]
When doing so, please provide a code snippet example.

**Comment by 395053994** [comment]
I have feedback to the Eclipse JDT UI. But it never seemed to respond. . . This is very unfriendly. . .




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Martin Lippert"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月2日(星期六) 凌晨3:58
收件人:&nbsp;"spring-projects/sts4"<sts4@noreply.github.com&gt;;
抄送:&nbsp;"青春！"<395053994@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [spring-projects/sts4] In the process of writing Java code, for example: the string parameter STS4 in the method cannot automatically match and complete the double quotes "", can this be improved, IDEA and other editors can automatically match and complete the double quotes "" (#454)





 
Since this is an improvement that affects the general Java coding experience, it should be reported against Eclipse here: https://bugs.eclipse.org/bugs/enter_bug.cgi?product=JDT

**Comment by 395053994** [comment]
Please see the attachment

long cc=map.get(");
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Martin Lippert"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月2日(星期六) 凌晨3:58
收件人:&nbsp;"spring-projects/sts4"<sts4@noreply.github.com&gt;;
抄送:&nbsp;"青春！"<395053994@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [spring-projects/sts4] In the process of writing Java code, for example: the string parameter STS4 in the method cannot automatically match and complete the double quotes "", can this be improved, IDEA and other editors can automatically match and complete the double quotes "" (#454)





 
When doing so, please provide a code snippet example.

**Comment by 395053994** [comment]
I have feedback to the Eclipse JDT UI. But it never seemed to respond. . . This is very unfriendly. . .


I have given multiple feedbacks to Eclipse, and none of them got a response. . .
It seems that the Eclipse community is not suitable for ordinary people to participate



------------------ 原始邮件 ------------------
发件人:&nbsp;"Martin Lippert"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月2日(星期六) 凌晨3:58
收件人:&nbsp;"spring-projects/sts4"<sts4@noreply.github.com&gt;;
抄送:&nbsp;"青春！"<395053994@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [spring-projects/sts4] In the process of writing Java code, for example: the string parameter STS4 in the method cannot automatically match and complete the double quotes "", can this be improved, IDEA and other editors can automatically match and complete the double quotes "" (#454)





 
Since this is an improvement that affects the general Java coding experience, it should be reported against Eclipse here: https://bugs.eclipse.org/bugs/enter_bug.cgi?product=JDT

**Comment by martinlippert** [comment]
> I have feedback to the Eclipse JDT UI. But it never seemed to respond. . . This is very unfriendly. . . I have given multiple feedbacks to Eclipse, and none of them got a response. . . It seems that the Eclipse community is not suitable for ordinary people to participate

This doesn't reflect my experience with the Eclipse community, so lets see what is going on here. Can you please add the URL to the bug that you filed at Eclipse for this?
