### ISSUE TITLE
Cannot run on Java 9

### ISSUE THREAD

**Issue by dsyer** [spring-projects/sts4#46]
I'm just running a basic sample app from start.spring.io in STS4.

```
Error occurred during initialization of boot layer
java.lang.LayerInstantiationException: Package jdk.internal.jimage.decompressor in both module java.base and module jrt.fs
```
`jrt-fs.jar` is  the name of the 1 jar in the JDK library for Java 9

**Comment by kdvolder** [comment]
> I'm just running a basic sample app from start.spring.io in STS4.

I tried that and it works for me. So maybe some specific dependency selections are required or whatever. Can you attach the app please. Just zip up the folder and attach. Thanks.

**Comment by martinlippert** [comment]
Looks like this report is a bit outdated by now. I think we are able to run the IDEs as well as the language server on JDK8/9/10/11 as well as let people use JDK levels up to 10 for their projects just fine. Closing this for now. If something like this shows up again, please comment and we will re-open.
