### ISSUE TITLE
Exception Occurred while creating an instance of the stream connection provider 

### ISSUE THREAD

**Issue by SanthoshiBeeram** [spring-projects/sts4#460]
I have seen one of the posts from here and performed the clean. Even after that I am seeing the same issues. Can you please describe me briefly about how to resolve this issue.

**Comment by SanthoshiBeeram** [comment]
I am getting error as Exception Occurred while creating an instance of the stream connection provider

**Comment by martinlippert** [comment]
I commented on your additional comment here: https://github.com/spring-projects/sts4/issues/112#issuecomment-626694479 - lets continue the conversation over there.
