### ISSUE TITLE
No codelens in VSCode

### ISSUE THREAD

**Issue by gayanper** [spring-projects/sts4#461]
When running spring boot app no codelens information is shown from actuators.
Plugin Version : 1.17.0

[demo.zip](https://github.com/spring-projects/sts4/files/4604259/demo.zip)

**Comment by BoykoAlex** [comment]
Live boot process hover/codelens mechanics has changed. Now in VSCode/Theia one would need to select the process to connect to to see hovers/codelenses. Refresh of the hovers isn't automatic either. It would have to be explicitly invoked.
Please activate "Manage Live Spring Boot Process Connections" from the command palette and discover a bit what it does to show/refresh/hide hovers/codelenses.

**Comment by martinlippert** [comment]
And please do not forget to manually enable JMX for the boot app when running from VSCode, as described here: https://github.com/spring-projects/sts4/wiki/Live-Application-Information#spring-boot-22-and-beyond

**Comment by gayanper** [comment]
I was trying see why code lense are not working for my intellij implementation. I will try look how it is done for vscode.

**Comment by martinlippert** [comment]
@gayanper Ah, now I understand and sorry for the confusion. The mechanism for code lenses has changed quite a bit (and we should have let you know upfront while implementing it, sorry for that).

First of all, the language server connects to running processes only in very specific situations. In addition to that the user can trigger the process connection manually by invoking a command for the language server.

For VSCode, this is implemented here: https://github.com/spring-projects/sts4/blob/master/vscode-extensions/vscode-spring-boot/lib/live-hover-connect-ui.ts

It is all based on commands via the lsp protocol. One command is to list all the available processes (the user needs to trigger that first). This command returns a number of other commands that the user can trigger to connect or disconnect to/from a process. This is the list of choices for the quick pick in the code mentioned above.

Hope that makes sense and work for you. Please let us know if you need any more help with this.

**Comment by gayanper** [comment]
@martinlippert I don't find a java class called ProcessCommandInfo in java side. When I execute the command for process list I get a list of LinkedTreeMap entries. Is that the expected result from LS or am I missing something ?

**Comment by gayanper** [comment]
@BoykoAlex @martinlippert Also I do get a list of running java processors, but not the application I'm running. I tried to find it in vscode as well, but I cannot see the process which was started from IJ.

**Comment by gayanper** [comment]
Got it, it was due to using a openj9 jvm. after switching to openjdk now I can see the process.

**Comment by martinlippert** [comment]
@gayanper Ah, that is a good find. The library that we use to identify the running java processes on your machine uses a library of the JDK which doesn't work across different JVM implementations, so you can't use both at the same time. I think it might work when purely running on OpenJ9 (your applications as well as the language server), but it is a long time ago since I tried that, so I might not remember this detail correctly... :-)
