### ISSUE TITLE
Lombok compatibility

### ISSUE THREAD

**Issue by geoemm** [spring-projects/sts4#47]
Hello, it seems that lombok is unable to recognize STS4 as an IDE. Any thoughts?

![lombok](https://user-images.githubusercontent.com/62142/37511103-4d69aee0-2906-11e8-9cd9-d9582100c6f2.png)

**Comment by martinlippert** [comment]
Yes, this is a known limitation of Lombok, it doesn't recognize the new name of the STS4 executable. I would recommend to report that to the Lombok project... :-)

In the meantime, you can install Lombok manually by editing the SpringToolSuite4.ini file and add the vm argument that puts the Lombok agent on the VM.

**Comment by geoemm** [comment]
Already reported! Thanks a lot!
