### ISSUE TITLE
Dark theme - improve a few icons

### ISSUE THREAD

**Issue by vogella** [spring-projects/sts4#472]
Dark theme look great in STS4 with Eclipse 4.16. I just noticed three icons which still have white dots around them, see screenshot.

![icons-sts](https://user-images.githubusercontent.com/139910/83508329-0e63ec00-a4ca-11ea-91f9-b764c66c4692.png)

**Comment by kdvolder** [comment]
The icon in the bottom right... I don't think that is one of ours. I think it's the icon for the Ansi console plugin: https://github.com/mihnita/ansi-econsole

**Comment by vogella** [comment]
Reported https://github.com/mihnita/ansi-econsole/issues/52

**Comment by kdvolder** [comment]
I'll try and fix the restart icon it does look a bit off. 

For the light-bulb... I actually think we should just leave it as is (feel free to argue with me however :-). But, I mean... it is a light bulb... so it is kind of natural to have some 'glow' around it. If I remove these 'glow pixels' the next pixels around is the black line around the yellow area of the bulb. And those will be completely invisible in dark theme. So I think it would actually look worse.

**Comment by vogella** [comment]
Sounds good. Thanks

Kris De Volder <notifications@github.com> schrieb am Mi., 9. Sept. 2020,
20:27:
