### ISSUE TITLE
STS4 4.6.2 Java Hover over error not appearing

### ISSUE THREAD

**Issue by kilgorjn** [spring-projects/sts4#474]
I've recently installed STS4 4.6.2, and have noticed that when I hover over a java error, the popup describing the error does not appear.  Instead, there is a brief flash of a loading indicator, then nothing else happens. 
If I change the hover options (Preferences -> Java -> Editor -> Hovers) from 'Combined' to 'Problem Description', then the error will appear in the hover popup; however, the javadocs now do not appear when hovering over a type.

I tested fresh installations of 4.6.1 and 4.6.2 under the same conditions, and the error popup just doesn't appear in 4.6.2.  (works fine in 4.6.1).
I have attached screenshots from both releases.
Windows 10, java 8.0_2.5.1

![STS_4 6 1](https://user-images.githubusercontent.com/10893375/83893827-19ab5780-a716-11ea-9275-1d87e6098c07.png)

![STS_4 6 2](https://user-images.githubusercontent.com/10893375/83893846-1fa13880-a716-11ea-847e-c5b2dbfcd1ba.png)

**Comment by BoykoAlex** [comment]
This is dup of #470 
Update from the nightly update site: https://dist.springsource.com/snapshot/TOOLS/sts4-language-server-integrations/nightly
