### ISSUE TITLE
Ctrl + 1 Automatic prompt failure in STS 4.6.2

### ISSUE THREAD

**Issue by yl-yue** [spring-projects/sts4#476]
## describe
Ctrl + 1 Automatic prompt failure in STS 4.6.2

### The wrong sample: 
![image](https://user-images.githubusercontent.com/39790401/84040284-04b01c00-a9d5-11ea-84a4-65f9e21f694f.png)

### The correct sample（STS 4.6.1 normal）: 

Move the cursor to the error line and expand Ctrl + 1 directly

![image](https://user-images.githubusercontent.com/39790401/84040907-c9621d00-a9d5-11ea-938e-940e217d7e8e.png)

**Comment by BoykoAlex** [comment]
Dup of #470 
Update from https://dist.springsource.com/snapshot/TOOLS/sts4-language-server-integrations/nightly
