### ISSUE TITLE
Question > Mark final versions of STS4 as releases

### ISSUE THREAD

**Issue by Musikolo** [spring-projects/sts4#481]
Hi,

I wonder if it is possible to release version as real releases, i.e., mark them as releases in GitHub, so that people watching only releases, get notified. For instance [spring-boot ](https://github.com/spring-projects/spring-boot/releases) project gets released as real releases. You can see that in the green squared message that reads as "_Latest release_":

![image](https://user-images.githubusercontent.com/13580107/84459512-3a4f4200-ac2d-11ea-9a3e-ecf11cc698ed.png)

Thank you!

**Comment by martinlippert** [comment]
Yes, lets give this a try. I marked the 4.6.2 release here:
https://github.com/spring-projects/sts4/releases/tag/4.6.2.RELEASE

Please note that we don't upload all the artifacts here as release artifacts, they are still available from the download pages and the wiki.

Would this be sufficient?

**Comment by Musikolo** [comment]
Yes, awesome, it works like charm.

I hope to continue to get more notifications any time a final version is released.

Thank you! ;-)

**Comment by Musikolo** [comment]
Looks like [version 4.7.1](https://spring.io/tools) was not released at https://github.com/spring-projects/sts4/releases . So, email notifications didn't last long... :-(

**Comment by martinlippert** [comment]
Yepp, my bad, I missed this one. Apologize.
