### ISSUE TITLE
"software user agreement" refers to untraceable license

### ISSUE THREAD

**Issue by aleuner** [spring-projects/sts4#484]
The text of "SPRING IDE PROJECT SOFTWARE USER AGREEMENT" (shown when installing sts4 via e. g. Eclipse marketplace) refers to a "Metro Link Public License 1.00 (available at https://www.opengroup.org/openmotif/supporters/metrolink/license.html)".

That URL gives a "Sorry ... we cannot find this page". A quick web search gave no results.

BTW the referred licences list resembles that of "Eclipse Foundation Software User Agreement". I found [Eclipse Bug](https://bugs.eclipse.org/bugs//show_bug.cgi?id=431255) where removal of the "Metro Link Public License 1.00" reference was discussed and [this commit](https://git.eclipse.org/c/www.eclipse.org/legal.git/commit/?id=d4a805415efbf42b2b61da379d2d207643205d20) with the same goal.

Please clarify the sts user agreement (license).
Thank you.

**Comment by martinlippert** [comment]
Hey @aleuner , thanks for pointing at this. That license file of the Spring IDE components was created a long time ago and definitely needs an update. I will take a look and update the file as soon as possible.

The update will not make it into the 4.7.0 release, but definitely be part of the 4.7.1 release. Hope that works for you.

**Comment by martinlippert** [comment]
From a first look, the item for the Metro Link Public License should be removed from in the same way it was removed from the Eclipse user agreement.

**Comment by aleuner** [comment]
That seems sensible. Unfortunately discussion in that bug report didn't really consider if they were allowed to remove the license reference at all (i. e. whether no longer distributing code or having a better license for it).
I tried (unsuccessfully) to find such a discussions in their mailing list archives but didn't know the best place to look.

**Comment by martinlippert** [comment]
I updated the feature properties in Spring-IDE accordingly:
https://github.com/spring-projects/spring-ide/commit/e2be7c6dee67777ef93220597b092134d740fae3
