### ISSUE TITLE
Questions on new Symbols view

### ISSUE THREAD

**Issue by gayanper** [spring-projects/sts4#488]
@martinlippert i'm looking into how to provide support for IntelliJ with the similar symbols view functionality.

- For Eclipse do you use the same symbols LSP to populate the view ?
- Do you start the language server when opening the view or you wait until the first java file to be open to start the language server so that you can populate the view ?
- Even after closing all java files do you keep the language server up and running to populate the view ?

**Comment by martinlippert** [comment]
> @martinlippert i'm looking into how to provide support for IntelliJ with the similar symbols view functionality.

+1 :-)

> * For Eclipse do you use the same symbols LSP to populate the view ?

Yes, we query the language server for symbols and display them in the view. It is exactly the same as we do in Eclipse with the in-place Cmd-6 dialog to navigate to the symbols.

> * Do you start the language server when opening the view or you wait until the first java file to be open to start the language server so that you can populate the view ?

We do not startup the language server just for the view. If there is a language server running, we request the symbols from it. If there is no language server running, the view doesn't show anything.

> * Even after closing all java files do you keep the language server up and running to populate the view ?

Same as above, the view doesn't have any impact on when language servers are being started or stopped (at least it should not).

Having said all that, we are not 100% sure whether this is the right approach or not. The user should not really bother about when language servers are being started or shutdown. This might point towards the view should also cause the language servers to startup, but in that case, what should cause the shutdown? It is very unlikely that the user will close the view when it is not used anymore, it will probably stay open (but not visible or activated). Probably food for more thought here.

**Comment by gayanper** [comment]
Thanks @martinlippert
