### ISSUE TITLE
Feature Request: Pull All

### ISSUE THREAD

**Issue by SledgeHammer01** [spring-projects/sts4#490]
Can we add a "Pull All" command to pull multiple projects in a workspace at once? Right now we have to do it one at a time for 6 projects. If you want to get super fancy :), you can make a checkbox dialog to select which of the projects you want to pull.

**Comment by kdvolder** [comment]
This seems like a feature request for Eclipse 'Egit' component. So you should probably raise it as an Eclipse bugzilla ticket: https://bugs.eclipse.org/bugs/enter_bug.cgi?product=EGit
