### ISSUE TITLE
Push Preview Dialog? Can't seem to disable

### ISSUE THREAD

**Issue by SledgeHammer01** [spring-projects/sts4#491]
I just upgraded to STS4 4.7 on top of Eclipse. When I click the Commit And Push button, there is a new popup dialog confirming all my push settings. I've played around in the options and there doesn't seem to be a way to disable this. Am I missing something? Extremely annoying dialog :). Is this something that was broken in 4.7? In 4.6 the Commit And Push button only displayed a result dialog.

**Comment by martinlippert** [comment]
Sounds like a question for the EGit project over at Eclipse to me. Please file a bug for that at: https://bugs.eclipse.org/bugs/enter_bug.cgi?product=EGit

Spring Tools 4 for Eclipse 4.7.0 contains the latest EGit release from the Eclipse 2020-06 release train.
