### ISSUE TITLE
4.7.0 Application always uses Embedded MongoDB regardless of configuration

### ISSUE THREAD

**Issue by Szilex94** [spring-projects/sts4#493]
Mid development I upgraded my STS to the latest version and noticed an interesting side effect that each time I start an application from eclipse, it uses the embedded MongoDB regardless of the supplied configuration (we have dedicated MongoDB servers for development). If I remove the dependency to the embedded DB then it successfully connects to the remote DB. This also works if I use @ImportAutoConfiguration(exclude = EmbeddedMongoAutoConfiguration.class) however this sort of poses a problem for the integration tests.

I did check out this project to my laptop with an older STS and with the same run configuration it connects to the remote DB.

As for my project setup it`s a plain spring boot (v2.5.5) back end project. **de.flapdoodle.embed.mongo** is used for the embedded db with a **test** scope. Dependencies are handled by Maven.

**Comment by martinlippert** [comment]
Maybe the test classes are included on the class path when running the app from your IDE? In case that would explain the issue (just guessing here), there is a new checkbox on the launch configs (on the `Classpath` tab) to exclude the test classes from the classpath. Usually this is checked by default when creating launch configs, but maybe this doesn't happen when you reuse an existing launch config. Does that help?

**Comment by mweirauch** [comment]
I have also been observing this with existing launch configs after upgrading to 2020-06/4.7.0 and was kinda puzzled why something worked which shouldn't due to a Spring Boot test configuration being attracted.

I am still not sure about when this feature was introduced and what a plain Eclipse install would set it to. It's at least irritating to see a change of behaviour.

**Comment by Szilex94** [comment]
I checked and **exclude test code** is ticked by default. However I did unchecked it started the application and then checked it and after that it properly connects to the remote DB. 
This is just a hunch but perhaps this is the result of me updating the workspace to that of this latest eclipse?

**Comment by kdvolder** [comment]
> the result of me updating the workspace to that of this latest eclipse?

I beleave so, I think the 'exclude test code' behavior in Eclipse m2e has changed in the latest Eclipse and STS had to make some changes in boot launch to accomodate. The changes that we had to make was to switch on the 'Exclude Test Code' option by default. Unfortunately... defaults values for launch config attributes are set only when a launch config is created. Existing launch configs already have their options set and are persisted with whatever was set on them at creation time. So pre-existing launch configs will not have this option set.

**Comment by martinlippert** [comment]
We fixed the default behavior for existing launch configs a while ago, so this should be working now out-of-the-box. If not, please comment and we can re-open this.
