### ISSUE TITLE
Typo in README of  sts4/concourse/theia-docker-image/

### ISSUE THREAD

**Issue by bakshaykamath** [spring-projects/sts4#494]
Theai Docker Image
==================

We currently **plublish** a **docler** image that contains:

Publish and docker have been missplet in the readme of  sts4/concourse/theia-docker-image/

**Comment by martinlippert** [comment]
Thanks for the pointer, much appreciated. Fixed in https://github.com/spring-projects/sts4/commit/fc9f46cb200e2d97ece96fea7f3e85b0de115fd3.

**Comment by martinlippert** [comment]
and https://github.com/spring-projects/sts4/commit/8ece73e78ecf645d6d4ac40218417994f10bf5b1
