### ISSUE TITLE
The javascript file opened as text file

### ISSUE THREAD

**Issue by nandakumardtc** [spring-projects/sts4#501]
on new version  of sts v4.7 with eclipse v-4.17  the javascript file is opened as text document 
-> i tried to change to javascript editor but there is no option for javascript.
-> **I tried by preference tab but there is no option for javascript that are in previous version**

**Comment by martinlippert** [comment]
We still install and re-use the same features of the Eclipse WTP project to support JavaScript than before (in previous releases), but it looks like the JavaScript editor is no longer part of that WTP JavaScript tooling - and therefore doesn't show up anymore in the Spring Tools 4 for Eclipse 4.7.0 release.

In the longer run, the WTP support will be replaced with the Wild Web Developer extensions that are already part of some of the Eclipse packages that you can download from Eclipse. That Wild Web Developer feature also contains support for JavaScript (among other web-related file types). You can install this feature from the main Eclipse update site via the `Install New Software` action, select the latest Eclipse update site, and search for the "Wild Web" feature. This should also work for the latest Spring Tools 4 for Eclipse release.

In future releases, the Spring Tools 4 for Eclipse distribution will include the Wild Web Developer extension by default. But we have go an extra mile before we can do that, e.g. migrating the project-based XML namespace support. But in case you don't need that, you should be totally fine with using the Wild Web Developer feature inside of Spring Tools 4. If not, please raise an additional bug, those are things we should definitely fix.

Hope this helps.

If you want to follow the GitHub issue that tracks the migration to the Wild Web Developer feature, please subscribe to https://github.com/spring-projects/sts4/issues/354.
