### ISSUE TITLE
lambok

### ISSUE THREAD

**Issue by mohamadjalanbaki** [spring-projects/sts4#511]
lambok not working with vscode OS windows 10

**Comment by martinlippert** [comment]
Hey! I am not exactly sure what exactly doesn't work. If the Lombok support in general doesn't work in your VSCode setup, I would recommend to report that to the Lombok project or the Java support for VSCode, which contains a description how to setup Lombok (https://github.com/redhat-developer/vscode-java/wiki/Lombok-support).

Or is there something specific to the Spring Tools 4 not working with Lombok in VSCode?

**Comment by martinlippert** [comment]
No further details provided, therefore closing this issue.
