### ISSUE TITLE
[Question] Language server logs

### ISSUE THREAD

**Issue by gayanper** [spring-projects/sts4#514]
When running in vscode mode where can I find the language server error logs. I'm running the LS in vscode mode for IntelliJ integration, and recently it starts to crash when sending ClassPath message. I would like to see the server logs what happening and what causing the crash. Please let me know how to find them.

**Comment by kdvolder** [comment]
Indeed, this is a little tricky and I don't think its documented properly either. 

Short answer:

You must configure the location by adding something like this to user or workspace settings:

```
{
    "spring-boot.ls.logfile": "/tmp/boot-ls.log"
}
```

Longer explanation:

When extension starts its output is printed into an 'output window' inside vscode called `${extension-name}-debug-log`. For example I'm trying this right now with our 'vscode-concourse' extension (spring boot one should work the same). So I go to the 'Output' tab in vscode, then in the pulldown menu near upper right corner of the 'output' tab I find 'vscode-concourse-debug-log'.

When I open that I see some output like:

```
Activating 'vscode-concourse' extension
Found java exe: /usr/lib/jvm/java-8-oracle/bin/java
isJavaEightOrHigher => true
Redirecting server logs to /dev/null
ERR: Disabling server log output. No more output will be sent after this.

Child process connected on port 45556
```

This is output printed from the extension. Most of the interesting output however comes from the server (not the extension). Server output used to be logged here as well but it tends to overwhelm vscode. JVM server process is capabable of generating log output at a much faster rate than the vscode process (javascript) can handle. And vscode gets overwhelmed then it kills the server process to 'save itself'. 

To avoid this output from server is now being written by the language server into a file instead, without any interaction with the vscode extension. By default the location of the log is '/dev/null' meaning it is discareded. So to see it, you have to explicitly configure a different location.

**Comment by gayanper** [comment]
Thanks @kdvolder . I think i should set the `-Dsts.log.file`when i start the language server.

**Comment by gayanper** [comment]
@kdvolder unfortunately your suggestion didn't worked for me since i'm running my connection based on stdio, so enabling the logfile cause all jsonrpc messages to directed to log file as well i think and my IDE plugin doesn't receive any messages from the LS.

**Comment by kdvolder** [comment]
Okay, I thought you were asking about running with vscode. If you are not running with vscode, then I don't know how you are running yours and its a bit hard to help with that.

For another option... when we run it with Eclipse I think in that case we also use STDIO for communication and logs end up in system.err in that scenario. 

The solution for vscode is a bit awkward/custom because we had to make some special adjustment to avoid printing of large volumes of log output on system.err to overwhelm the vscode client.

**Comment by martinlippert** [comment]
@gayanper Is this still an open issue? Do you still need help here?

**Comment by gayanper** [comment]
No @martinlippert we can close it. Thanks for your support
