### ISSUE TITLE
ctrl + space not working on Mac OS Big sur

### ISSUE THREAD

**Issue by arayariquelmes** [spring-projects/sts4#517]
After Upgrade to Mac OS Big Sur, ctrl + space content assist stop working.
Reinstalling STS has no Effect.
The properties of Content Assist are defined propertly.

**Comment by martinlippert** [comment]
I don't have the latest beta of macOS Big Sur installed yet, so I need to find a way to get that version somewhere without installing it on my main work machine. Independent of that, do you see any related error message coming up in the Error Log view maybe? And what happens to a plain Eclipse 2020-06 install? Does the regular content-assist in the Java editor works when running on macOS Big Sur?

**Comment by martinlippert** [comment]
Got a macOS Big Sur machine setup and can confirm that the keyboard shortcut for content-assist is not working by default. The reason for that is that the OS itself captures that keyboard shortcut (Ctrl + Space) for switching input sources. You can go to the System Preferences -> Keyboard -> Shortcuts -> Input Sources and disable both shortcuts in there. This will make your Eclipse content-assist shortcuts work again.

**Comment by ojvm** [comment]
@martinlippert thank you a lot, I've searched a lot and i couldn't found an appropriated answer. it works¡¡¡

**Comment by lemessdavi** [comment]
ty man, save my life

**Comment by seyha30** [comment]
thank you a lot

**Comment by SidiqiJaved** [comment]
Member
martinlippert , thank you so much

**Comment by Pablion** [comment]
I don't know who cancelled my keyboard shortcut(maybe slack/xampp)... But I've got it back. Thank you!

**Comment by ranveer-kumar** [comment]
@martinlippert  Great, working fine

**Comment by tucomel** [comment]
Keyboard>Shortcuts>Input Source>UNCHECK the box for both shortcuts 
![image](https://user-images.githubusercontent.com/8607299/152879422-8a845890-9ae4-47bc-b223-01178f5017fb.png)

**Comment by wlailton** [comment]
Working!!!

Thanks man!

**Comment by aniketsamudra** [comment]
Thank You so much.. lifesaver tip.. after a full days googling, finally this thing worked.

**Comment by Fl4v** [comment]
It used to work, then it stopped, I googled, and this thread delivered, thank you!

**Comment by chad-cummings-rigil** [comment]
This worked for me as well.

**Comment by amandhaasil** [comment]
Content Assist is working for me using `option+space` instead of `crtl+space`. Do you know how can I reconfigure it?

**Comment by sbb3** [comment]
works, many thanks,

**Comment by Haseebshah936** [comment]
works for me m1 14 pro thanks. My issue was caused after I changed my input source. I guess OS automatically enabled the short cuts for switching between the input source.

**Comment by JasonHiew** [comment]
It works. Just want to add that you might have to restart after disabling the keyboard shortcut in MacOS' settings.

**Comment by edmondburnett** [comment]
Thanks for this. I discovered that these options can magically become enabled if you add a second keyboard layout. Suddenly my custom Control-Space keybinding for tmux prefix quit working.

**Comment by pedrovalido** [comment]
Exactly same issue here: added a keyboard layout and suddenly my tmux ctrl-space stopped working @edmondburnett . Huge thanks to @martinlippert for the answer. Everything is working now :)
