### ISSUE TITLE
After last mac os update I am getting this message when I try to open spring boot tool

### ISSUE THREAD

**Issue by bayati-code** [spring-projects/sts4#518]
Process:               SpringToolSuite4 [1650]
Path:                  /Volumes/VOLUME/SpringToolSuite4.app/Contents/MacOS/SpringToolSuite4
Identifier:            org.springframework.boot.ide.branding.sts4
Version:               4.7.1 (4.7.1.202007271558-RELEASE)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           SpringToolSuite4 [1650]
User ID:               501

Date/Time:             2020-08-06 22:53:21.036 -0400
OS Version:            Mac OS X 10.16 (20A5343i)
Report Version:        12
Bridge OS Version:     5.0 (18P50347c)
Anonymous UUID:        E3E7A165-75F1-0E32-8E37-5F358638EBF3

Time Awake Since Boot: 150 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [1650]

Application Specific Information:
*** CFRelease() called with NULL ***

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   com.apple.CoreFoundation      	0x00007fff2a0ba93e CFRelease.cold.1 + 14
1   com.apple.CoreFoundation      	0x00007fff29f1610f CFRelease + 108
2   com.apple.JavaVM              	0x00007fff2ecfbc61 MakeMatcher + 406
3   com.apple.JavaVM              	0x00007fff2ecfa804 CreateJVMDetector + 38
4   com.apple.JavaVM              	0x00007fff2ecfc5eb CheckForInstalledJavaRuntimes + 43
5   dyld                          	0x000000000d74bebd ImageLoaderMachO::doModInitFunctions(ImageLoader::LinkContext const&) + 559
6   dyld                          	0x000000000d74c2b8 ImageLoaderMachO::doInitialization(ImageLoader::LinkContext const&) + 40
7   dyld                          	0x000000000d746e78 ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, char const*, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 492
8   dyld                          	0x000000000d744d90 ImageLoader::processInitializers(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 188
9   dyld                          	0x000000000d744e30 ImageLoader::runInitializers(ImageLoader::LinkContext const&, ImageLoader::InitializerTimingList&) + 82
10  dyld                          	0x000000000d736261 dyld::runInitializers(ImageLoader*) + 82
11  dyld                          	0x000000000d740769 dlopen_internal + 609
12  libdyld.dylib                 	0x00007fff6b2fd26f dlopen_internal(char const*, int, void*) + 177
13  libdyld.dylib                 	0x00007fff6b2eb90e dlopen + 28
14  com.apple.CoreFoundation      	0x00007fff29fb2352 _CFBundleDlfcnLoadBundle + 147
15  com.apple.CoreFoundation      	0x00007fff2a02aada _CFBundleLoadExecutableAndReturnError + 503
16  com.apple.CoreFoundation      	0x00007fff29ff2b6e CFBundleGetFunctionPointerForName + 39
17  eclipse_1902.so               	0x000000000ad6d62e findSymbol + 62
18  eclipse_1902.so               	0x000000000ad6b679 startJavaJNI + 89
19  eclipse_1902.so               	0x000000000ad67f44 _run + 5732
20  eclipse_1902.so               	0x000000000ad664c0 run + 432
21  org.springframework.boot.ide.branding.sts4	0x000000000ac619f7 original_main + 1319
22  org.springframework.boot.ide.branding.sts4	0x000000000ac623a7 main + 1655
23  libdyld.dylib                 	0x00007fff6b2fb851 start + 1

Thread 1:
0   libsystem_pthread.dylib       	0x00007fff6b5334b4 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	0x00007fff6b5334b4 start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	0x00007fff6b5334b4 start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	0x00007fff6b5334b4 start_wqthread + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x00007fff2a2cbbc2  rbx: 0x0000000000000000  rcx: 0x000000000000001e  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x00007ffee4f9c818  rbp: 0x00007ffee4f9c7f0  rsp: 0x00007ffee4f9c7e8
   r8: 0x00000000000000a9   r9: 0x00000000000007fb  r10: 0x0000000000001140  r11: 0x0000000000000060
  r12: 0x0000000000000000  r13: 0x0000600000f58270  r14: 0x000060000105c720  r15: 0x000060000217ef80
  rip: 0x00007fff2a0ba93e  rfl: 0x0000000000010246  cr2: 0x00007fd0d7e0f000
  
Logical CPU:     2
Error Code:      0x00000000
Trap Number:     6

**Comment by martinlippert** [comment]
Can you double check this with a standard Eclipse 2020-06 package to see if this is a general issue with the underlying Eclipse platform?

**Comment by BoykoAlex** [comment]
10.16 is a Big Sur Beta where Big Sur is planned to be the mac os 11. I'd say it is somewhat expected to find issues with Mac OS 11 Beta... There is `ImageLoader` in the thread dump which is related to SWT which is the OS specific piece of Eclipse. I think it is likely we'd have a separate SWT bundle for mac os 11...

**Comment by jmiddleton** [comment]
I fixed setting the vm as this:

`
<string>-vm</string><string>/Library/Java/JavaVirtualMachines/jdk1.8.0_201.jdk/Contents/Home/bin/java</string>

to /Applications/Eclipse.app/Contents/Info.plist
`

**Comment by duanhairuo** [comment]
add vm arg to SpringToolSuite4.ini can work ok
-vm
/Library/Java/JavaVirtualMachines/jdk1.8.0_261.jdk/Contents/Home/bin

**Comment by Msimoneau** [comment]
@jmiddleton Your Info.plist addition fix it for me.

Thanks ! :-)

**Comment by martinlippert** [comment]
I also double checked the latest Spring Tools 4 for Eclipse 4.9.0 on a macOS Big Sur 11.3 Beta and it seems to work fine. Therefore closing this item now. If you still observe this issue on macOS Big Sur, please comment and we can re-open the issue.
