### ISSUE TITLE
include .vsix on each release

### ISSUE THREAD

**Issue by gsmachado** [spring-projects/sts4#519]
It would be very useful to include the .vsix file in each tagged release.

Thus, developers would be able to easily automate the download process for this plugin (Theia).

**Comment by kdvolder** [comment]
Our releases are being published ovsx repo which I think Theia uses: https://open-vsx.org/?search=pivotal&category=&sortBy=relevance&sortOrder=desc

Is that sufficient? 

If not, we also maintain wiki page with the releases here:

- https://github.com/spring-projects/sts4/wiki/Current-VSCode-Releases
- https://github.com/spring-projects/sts4/wiki/VSCode-Extensions-Downloads

Is that suffciient? If not... please explain exactly what you want.

**Comment by kdvolder** [comment]
FYI: Eclipse article for context about the creation of ovsx: https://www.eclipse.org/community/eclipse_newsletter/2020/march/1.php

**Comment by martinlippert** [comment]
> If not... please explain exactly what you want.

From what I understood it would be good to include the vsix files in the GitHub release, which I create manually every time we ship a release anyway, but without including those files yet. We can just do that in the future.

**Comment by gsmachado** [comment]
> From what I understood it would be good to include the vsix files in the GitHub release, which I create manually every time we ship a release anyway, but without including those files yet. We can just do that in the future.

Exactly. 😄 

You guys can keep publishing the .vsxi (or, ovsx) in the Wiki or open-vsx.org... but, honestly, it would make developers' life way easier if you could automate the release process and include those files in each (GitHub tagged release](https://github.com/spring-projects/sts4/releases/tag/4.7.1.RELEASE).

**Comment by kdvolder** [comment]
THe wiki release page is already updated automatically, as is the ovsx publishing. We can look at adding yet another automated publish step to our build pipeline. All of these build automations do require effort to setup and maintain but seeing as Martin is currently doing github releases manually, I suppose in this case automation would save us work. So seems like a good idea.

For consumption in Theia however, I would have thought that ovsx repo would actually be the most convenient option, I think ovsx was specifically created to provide a place to host extensions released specifically for Theia (well, I guess in principal any consumer of vscode extension could use it and would be welcome to do so... But Theia folks set it up explicitly to have an alternative to MS vscode marketplace so they can use it in Theia.

**Comment by martinlippert** [comment]
@gsmachado I added them to the 4.7.1 release in GitHub. Would that work for you this way?

**Comment by gsmachado** [comment]
@martinlippert that's perfect! 👍 
It would make life way easier to automate things from my end (and I believe for others too!).
Thanks!
