### ISSUE TITLE
Ctrl +Shift + F to css source format error

### ISSUE THREAD

**Issue by jhs512** [spring-projects/sts4#527]
![a](https://user-images.githubusercontent.com/4741844/91675786-94024100-eb78-11ea-98ba-89d55cd3db5b.jpg)

/* first */
@keyframes aniname { }

/* second */
div:not(:nth-child(2)) {
  width: 100px;
}

both all break when `Ctrl +Shift + F`

**Comment by wusongdashu** [comment]
Your input method may conflict with the STS shortcut key
你的输入法可能和sts快捷键冲突

**Comment by martinlippert** [comment]
The CSS file support is part of the Eclipse platform that we consume in STS as a base. If you have trouble with formatting CSS files, please report this to the corresponding Eclipse project (depending on which version of STS/Eclipse you are using).
