### ISSUE TITLE
Export WAR is missing in STS4

### ISSUE THREAD

**Issue by anthoniraj** [spring-projects/sts4#53]
Export WAR option is required for Spring Web Projects to Deploy in Tomcat Server. It is missing in Version 4.

**Comment by martinlippert** [comment]
Can you provide a sample project for this? And you want to export a WAR file from the IDE instead of the build? Is that correct? Just asking because working on the project within the IDE and using a Tomcat server from within the IDE should not require to export the project as a WAR.

**Comment by anthoniraj** [comment]
I know that but the export WAR was available in STS 3.x versions for any Spring Boot Project. It can be used for export spring boot project and can be deployed in dedicated tomcat server. (without using maven build)

**Comment by martinlippert** [comment]
The WAR export feature is part of the wider Java EE and web features of Eclipse, which we don't include by default anymore in the STS4 distribution builds. You can install those additional features via `Install New Software`, select the Photon update site, and search for `m2e-wtp - Maven Integration for WTP`. That one pulls in everything you need to get the WAR file export wizard back into STS4.

**Comment by pmohmta** [comment]
I tried to add additional feature with "Install New Software"
It is found "m2e-wtp - Maven Integration for WTP" is already installed.
What should I do?

**Comment by martinlippert** [comment]
@pmohmta Please go to `Install New Software`, select the main Eclipse update site, and install the `Eclipse Java EE Developer Tools` feature. That will bring back the `Export as WAR file...` action.

**Comment by pmohmta** [comment]
martinlippert,
Thanks. I will try and let you know the result.

**Comment by pmohmta** [comment]
Go to Install New Software. Can not find "main Eclipse update site"

**Comment by pmohmta** [comment]
Martin,


Thanks for replying.

Error found when install Eclipse Jee Package:

Unable to read repository at https://download.eclipse.org/releases/latest/content.xml.
Unable to read repository at https://download.eclipse.org/releases/latest/content.xml.
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

***@***.***

























Peter Moh

**Comment by pmohmta** [comment]
Martin,


Thanks for replying.

Error found when install Eclipse Jee Package:

Unable to read repository at https://download.eclipse.org/releases/latest/content.xml.
Unable to read repository at https://download.eclipse.org/releases/latest/content.xml.
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

***@***.***
























Peter Moh

**Comment by martinlippert** [comment]
I deleted one comment, it was a duplicate of the previous one here. With regards to the PKIX path failure, this is related to the certificate store of the JDK used to run the IDE, see https://stackoverflow.com/questions/21076179/pkix-path-building-failed-and-unable-to-find-valid-certification-path-to-requ for more details here.
