### ISSUE TITLE
RFE: Better error message when JDK is detected as  JRE due to missing jmods

### ISSUE THREAD

**Issue by space88man** [spring-projects/sts4#531]
Background: #530 

RHEL/CentOS/Fedora distribute jmod files in a separate package `java-11-openjdk-jmods` which user may inadvertently not install. STS4 requires the jmod files to function optimally and shows the cryptic message:

> The JRE you are running Eclipse with appears to not be a JDK.

In RHEL/CentOS/Fedora this was caused by not installing the jmods package.

Perhaps a better error message could be displayed like "Missing jmod files".

This has bugged me for months as STS4 would run fine with 3rd party JDK11s like AdoptOpenJDK/Zulu but not with the distro packaged JDK11.

**Comment by space88man** [comment]
@martinlippert  has explained that jmod files are not used at runtime; the `.exists()` test on `jmods/jdk.management.jmod` et al is a detection mechanism for JDK 9+.

Linux distros which don't install jmod files by default will be a covered by a test for `lib/libmanagement.so` instead.

**Comment by martinlippert** [comment]
Actually, after investigating this in more detail on a various platforms, it looks to me like it is not easy to identify from the outside which modules are around inside of a specific JDK (>= 9). Therefore we changed the implementation to do the specific check for the tools.jar on JDK8 only and skip this for JDK >= 9. Therefore, I think, we can close this issue.
