### ISSUE TITLE
Formatter tags not working

### ISSUE THREAD

**Issue by SujanKumarMitra** [spring-projects/sts4#535]
In eclipse, there are formatter tags which disable code formatting for a specific block. After updating to 4.7.2 it's bot working anymore.

**Comment by kdvolder** [comment]
I can confirm that indeed those tags are not obeyed. There is preference in Eclipse to disable / enable this as explained here:

https://stackoverflow.com/questions/5115088/turn-off-eclipse-formatter-for-selected-code-area#:~:text=2%20Answers&text=To%20prevent%20specific%20portions%20of,the%20formatting%20in%2Dbetween%20them.

To enable this functionality you can:

Go to "Window >> Preferences >> Java >> Code Style >> Formatter". Click the 'Edit' button. Then go to 'Off/on Tags' near bottom of the window. Make sure the setting is enabled.

I do not use this feature myself and haven't noticed that this changed, or when. It likely that the default value for this feature was changed in Eclipse either intentionally or by accident. I will raise an Eclipse bug ticket.

**Comment by kdvolder** [comment]
Eclipse bug raised here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=567016

I'm closing this as it doesn't seem to be an STS specific issue.
