### ISSUE TITLE
4.8.0 startup error on Windows 10 x64

### ISSUE THREAD

**Issue by SledgeHammer01** [spring-projects/sts4#537]
STS4 Eclipse 4.8.0
Windows 10 Pro x64

When I launch and open my workspace, it initializes everything as usual and then I get an error:

Update Job has encountered a problem.

An internal error occurred during: "Update Job".
Registry Directory not available: C:\Users\xxx%20xxx\.eclipse\org.eclipse.platform_4.16.0_1260125666_win32_win32_x86_64\p2\org.eclipse.equinox.p2.engine\profileRegistry.

My user directory on Windows has a space in it, not sure if that's the issue, but that's why I left the %20 in there.

I ran STS4 as Admin just for fun and the issue went away. It shouldn't need admin to write to my folder. If there is some new component that is writing to somewhere else, it might need a first time run as admin though.

**Comment by martinlippert** [comment]
@SledgeHammer01 Thanks for reporting this, looks like an issue with the underlying Eclipse platform. Can you double check whether this happens when running a regular Eclipse 2020-09 distribution?
