### ISSUE TITLE
4.8.0 UI glitch on Windows 10

### ISSUE THREAD

**Issue by SledgeHammer01** [spring-projects/sts4#538]
STS4 Eclipse 4.8.0
Windows 10 Pro x64

In the Git Staging view | Unstaged Changes... if I click on an empty area in the list box, its normal. But if I click on the filename itself, the screen flashes weird and the border disappears. So, have a Unstaged Changed and click somewhere else, I.e. in the project window or on the source window and then click directly on the file item.

**Comment by martinlippert** [comment]
@SledgeHammer01 Thanks for reporting this. Since it seems to be related to the Git support in the IDE,  I would recommend to report this to the EGit project at Eclipse via: https://bugs.eclipse.org/bugs/enter_bug.cgi?product=EGit.
