### ISSUE TITLE
spring expression language, expression auto complete is not working

### ISSUE THREAD

**Issue by yekota-copart** [spring-projects/sts4#541]
I am using Spring Tool Suite 4(4.7.1.RELEASE), And I am trying to write the below expression.
`   @Value("#{new Boolean(true)}")
    private boolean is24;`

But for spel expression, the code autocomplete or code suggestions are not working. 
Is this feature never exist or Am I missing any sts configuration.

Thanks for helping.

**Comment by martinlippert** [comment]
@yekota-copart We do not (yet) provide code completion or anything like that within SpEL expressions.

**Comment by yekota-copart** [comment]
@martinlippert  Thanks for sharing the info, Hoping to see that feature soon in sts.

**Comment by martinlippert** [comment]
More concrete issues have been created for auto completion for spec expressions recently: #1384, #1379, #1378
