### ISSUE TITLE
Spring Shell dependency not came in Spring Starter Project

### ISSUE THREAD

**Issue by Ayushnita** [spring-projects/sts4#545]
I am trying to create a new spring shell project and I am not able to find any option for spring shell dependency in Spring Starter Project.

**Comment by kdvolder** [comment]
We (STS team) do not control what dependencies are offered via the 'New Spring Starter' wizard. The wizard uses the 'start.spring.io' web service. It is this service that determines what dependencies are available in the wizard.

So please raise an issue here: https://github.com/spring-io/initializr
