### ISSUE TITLE
Publish Spring Boot Extension Pack to open-vsx.org

### ISSUE THREAD

**Issue by apupier** [spring-projects/sts4#548]
Currently, there is `Spring Boot Tools` extension which is published: https://open-vsx.org/extension/Pivotal/vscode-spring-boot

it would be nice to publish the whole extension pack too

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Kris De Volder:) 

Added a job to concourse pipeline to publish dev pack to ovsx.

Note: this pack has not changed in a very loooong time as it is basically just a list of extension names. So I expect this task to run very infrequently.

The job is setup now to run only when files in the directory at `vscode-extensions/boot-dev-pack` changes in master branch. At that time it triggers and publishes to ovsx automatically.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Kris De Volder:) 

Latest version published by us now:
https://open-vsx.org/extension/Pivotal/vscode-boot-dev-pack

Our consourse job: https://ci.spring.io/teams/tools/pipelines/sts4-master/jobs/boot-dev-pack-ovsx-publish/builds/3

**Comment by apupier** [comment]
Thank you!
