### ISSUE TITLE
Language server - plugin com.googlecode.maven-download-plugin:download-maven-plugin:1.6.0 - "Invalid plugin configuration: url"

### ISSUE THREAD

**Issue by ineffective** [spring-projects/sts4#549]
I have the following in my pom.xml:

```xml
            <plugin>
                <groupId>com.googlecode.maven-download-plugin</groupId>
                <artifactId>download-maven-plugin</artifactId>
                <version>1.6.0</version>
                <executions>
                    <execution>
                        <id>install-XXX</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>wget</goal>
                        </goals>
                        <configuration>
                            <url>http://XXX/XXXXX/XXX_1.0.3.zip</url>
                            <unpack>true</unpack>
                            <outputDirectory>${project.build.directory}/outdir/</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

Eclipse warns, that `<url>` tag is invalid for this configuration. Url provided is find, plugin downloads zip file and unpacks it. I'd like to know if this warning is caused by STS/Language Server or rather misconfiguration of the plugin.

I have Eclipse version:
Eclipse IDE for Java Developers (includes Incubating components)
Version: 2020-09 (4.17.0)
Build id: 20200910-1200
OS: Windows 10, v.10.0, x86_64 / win32
Java version: 11.0.8

Included incubation components are those resulting from installation recommended packages mentioned in ticket #529. 

Is there anything you can do or should I address authors of the plugin directly?

**Comment by BoykoAlex** [comment]
No this is independent of STS4. The error is reported via M2E (Maven Tools for Eclipse) most likely (may depend on the editor you opened the pom.xml file with. Which editor is it? XML Editor or Generic Editor). I think it is correct but If your Maven build works via the CLI or if you right click the project Maven -> Update Project... and the artifact is downloaded and is at the location it's supposed to be then it's working and you shouldn't worry about the error.
(Don't forget to refresh the project in Eclipse after the Maven build, right-click the project and find Refresh action)

**Comment by ineffective** [comment]
Thanks. So I believe I will take it to M2E mailing list. Everything works fine, but I strive to remove all and any warnings in my code base which is why I asked. I will close it and take it to proper place.
