### ISSUE TITLE
In spring boot suit main page , why download fail ?

### ISSUE THREAD

**Issue by shyding** [spring-projects/sts4#552]
![image](https://user-images.githubusercontent.com/24986567/96206797-4745be80-0f9c-11eb-9a09-c4a5f5990826.png)

**Comment by shyding** [comment]
windows 64 bit

**Comment by vvsheep** [comment]
i have the same issue.

**Comment by kdvolder** [comment]
The download works for me right now. Maybe it was a temporary issue. Please try again. I'll close this ticket for now.

If you still have problems please provide some information such as what kind of errors you are seeing and I can try to help understand the problem. The screenshot above however, just has a large black rectangle and chinese characters that I do not know how to read. So it isn't helpful. Please bear in mind that the people here who would be trying to help, unfortunately do not understand / read Chinese.

**Comment by martinlippert** [comment]
More reports about failing windows download, need to investigate this further...

**Comment by martinlippert** [comment]
To make sure we are talking about the same thing here. The download page points at this URL for the Windows 64bit version:

https://download.springsource.com/release/STS4/4.8.0.RELEASE/dist/e4.17/spring-tool-suite-4-4.8.0.RELEASE-e4.17.0-win32.win32.x86_64.self-extracting.jar

This download link works for me and I can download the file. What happens if you point your browser at this URL? If this download link doesn't work, please share the error message and details here. I would suspect there is a network issue happening along the way.

You could also try an alternative download URL:

https://dist.springsource.com/release/STS4/4.8.0.RELEASE/dist/e4.17/spring-tool-suite-4-4.8.0.RELEASE-e4.17.0-win32.win32.x86_64.self-extracting.jar

Does that work? Or does it produce the same error?

Given the reports, it looks like most of them coming from China (although just guessing here). So I wonder if this network issue is somehow region specific. Any thoughts?

**Comment by jeffreyyi11** [comment]
first link doesn't work. same error. failed - no file. alt dl link works

**Comment by kdvolder** [comment]
Not sure how hard it is to install a tool like `curl` on Windows. Or maybe a similar windows-specific tool...

But it might be possible to get a better idea why/how the request is failing by trying to download file using curl in verbose mode.

For example, I downloaded the 'download.springsource.com' link using curl on my Linux machine using `curl` on the commandline and used the `-v` (i.e. verbose) option. It produces this output:

```
$ curl -v https://download.springsource.com/release/STS4/4.8.0.RELEASE/dist/e4.17/spring-tool-suite-4-4.8.0.RELEASE-e4.17.0-win32.win32.x86_64.self-extracting.jar --output windows-sea.jar
*   Trying 172.67.75.139...
* TCP_NODELAY set
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to download.springsource.com (172.67.75.139) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /home/kdvolder/anaconda3/ssl/cacert.pem
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [106 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [2220 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [149 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=US; ST=CA; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
*  start date: Jul 19 00:00:00 2020 GMT
*  expire date: Jul 19 12:00:00 2021 GMT
*  subjectAltName: host "download.springsource.com" matched cert's "*.springsource.com"
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
} [5 bytes data]
> GET /release/STS4/4.8.0.RELEASE/dist/e4.17/spring-tool-suite-4-4.8.0.RELEASE-e4.17.0-win32.win32.x86_64.self-extracting.jar HTTP/1.1
> Host: download.springsource.com
> User-Agent: curl/7.52.1
> Accept: */*
> 
{ [5 bytes data]
< HTTP/1.1 200 OK
< Date: Wed, 21 Oct 2020 17:54:00 GMT
< Content-Type: application/octet-stream
< Content-Length: 542675848
< Connection: keep-alive
< Set-Cookie: __cfduid=dfcea48d10e334e066e264cba39fca0971603302840; expires=Fri, 20-Nov-20 17:54:00 GMT; path=/; domain=.springsource.com; HttpOnly; SameSite=Lax
< Last-Modified: Tue, 15 Sep 2020 19:26:48 GMT
< x-amz-version-id: XLu..IwedaUP2R7mtJU..w2MTo1uUgQM
< ETag: "ddf02638fa83ce5345bc2b263c5c6652"
< X-Cache: Hit from cloudfront
< Via: 1.1 476c2ba6d9f6cd69dbcedbd65688cbc0.cloudfront.net (CloudFront)
< X-Amz-Cf-Pop: SEA19-C2
< X-Amz-Cf-Id: KK4jPqpZOtXo1FiXn7o6_wy-rkUocFHZlnZODutP-4v2OdFmGyzjuw==
< Cache-Control: max-age=86400
< CF-Cache-Status: MISS
< cf-request-id: 05ede4f24d0000bb34c38f7000000001
< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?lkg-colo=28&lkg-time=1603302841"}],"group":"cf-nel","max_age":604800}
< NEL: {"report_to":"cf-nel","max_age":604800}
< Server: cloudflare
< CF-RAY: 5e5cd763adadbb34-SEA
< 
{ [284 bytes data]
 99  517M   99  513M    0     0  12.0M      0  0:00:43  0:00:42  0:00:01 11.5M* Curl_http_done: called premature == 0
100  517M  100  517M    0     0  12.0M      0  0:00:43  0:00:43 --:--:-- 11.6M
* Connection #0 to host download.springsource.com left intact
```

If something is going wrong then the verbose output from curl may give a clue exactly where/why/what is going wrong.

**Comment by shyding** [comment]
"Failed, file not found" still appears, curl also fails

**Comment by shyding** [comment]
Details of the curl command are as follows:



 schannel: encrypted data buffer: offset 3404 length 103424
* schannel: failed to decrypt data, need more data
* schannel: schannel_recv cleanup
* schannel: client wants to read 102400 bytes
* schannel: encrypted data buffer: offset 3404 length 103424
* schannel: encrypted data got 16384
* schannel: encrypted data buffer: offset 19788 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 16384 length 102400
* schannel: encrypted data length: 3375
* schannel: encrypted data cached: offset 3375 length 103424
* schannel: failed to decrypt data, need more data
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 16384
* schannel: decrypted data buffer: offset 0 length 102400
{ [16384 bytes data]
* schannel: client wants to read 102400 bytes
* schannel: encrypted data buffer: offset 3375 length 103424
* schannel: encrypted data got 6144
* schannel: encrypted data buffer: offset 9519 length 103424
* schannel: failed to decrypt data, need more data
* schannel: schannel_recv cleanup
* schannel: client wants to read 102400 bytes
* schannel: encrypted data buffer: offset 9519 length 103424
* schannel: encrypted data got 10240
* schannel: encrypted data buffer: offset 19759 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 16384 length 102400
* schannel: encrypted data length: 3346
* schannel: encrypted data cached: offset 3346 length 103424
* schannel: failed to decrypt data, need more data
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 16384
* schannel: decrypted data buffer: offset 0 length 102400
{ [16384 bytes data]
* schannel: client wants to read 102400 bytes
* schannel: encrypted data buffer: offset 3346 length 103424
* schannel: encrypted data got 28672
* schannel: encrypted data buffer: offset 32018 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 16384 length 102400
* schannel: encrypted data length: 15605
* schannel: encrypted data cached: offset 15605 length 103424
* schannel: failed to decrypt data, need more data
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 16384
* schannel: decrypted data buffer: offset 0 length 102400
{ [16384 bytes data]
* schannel: client wants to read 102400 bytes
* schannel: encrypted data buffer: offset 15605 length 103424
* schannel: encrypted data got 37888
* schannel: encrypted data buffer: offset 53493 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 16384 length 102400
* schannel: encrypted data length: 37080
* schannel: encrypted data cached: offset 37080 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 32768 length 102400
* schannel: encrypted data length: 20667
* schannel: encrypted data cached: offset 20667 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 49152 length 102400
* schannel: encrypted data length: 4254
* schannel: encrypted data cached: offset 4254 length 103424
* schannel: failed to decrypt data, need more data
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 49152
* schannel: decrypted data buffer: offset 0 length 102400
{ [49152 bytes data]
* schannel: client wants to read 102400 bytes
* schannel: encrypted data buffer: offset 4254 length 103424
* schannel: encrypted data got 10240
* schannel: encrypted data buffer: offset 14494 length 103424
* schannel: failed to decrypt data, need more data
* schannel: schannel_recv cleanup
* schannel: client wants to read 102400 bytes
* schannel: encrypted data buffer: offset 14494 length 103424
* schannel: encrypted data got 4096
* schannel: encrypted data buffer: offset 18590 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 16384 length 102400
* schannel: encrypted data length: 2177
* schannel: encrypted data cached: offset 2177 length 103424
* schannel: failed to decrypt data, need more data
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 16384
* schannel: decrypted data buffer: offset 0 length 102400
{ [16384 bytes data]
* schannel: client wants to read 102400 bytes
* schannel: encrypted data buffer: offset 2177 length 103424
* schannel: encrypted data got 12288
* schannel: encrypted data buffer: offset 14465 length 103424
* schannel: failed to decrypt data, need more data
* schannel: schannel_recv cleanup
* schannel: client wants to read 102400 bytes
* schannel: encrypted data buffer: offset 14465 length 103424
* schannel: encrypted data got 21504
* schannel: encrypted data buffer: offset 35969 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 16384 length 102400
* schannel: encrypted data length: 19556
* schannel: encrypted data cached: offset 19556 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 32768 length 102400
* schannel: encrypted data length: 3143
* schannel: encrypted data cached: offset 3143 length 103424
* schannel: failed to decrypt data, need more data
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 32768
* schannel: decrypted data buffer: offset 0 length 102400
{ [32768 bytes data]
* schannel: client wants to read 102400 bytes
* schannel: encrypted data buffer: offset 3143 length 103424
* schannel: encrypted data got 30720
* schannel: encrypted data buffer: offset 33863 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 16384 length 102400
* schannel: encrypted data length: 17450
* schannel: encrypted data cached: offset 17450 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 32768 length 102400
* schannel: encrypted data length: 1037
* schannel: encrypted data cached: offset 1037 length 103424
* schannel: failed to decrypt data, need more data
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 32768
* schannel: decrypted data buffer: offset 0 length 102400
{ [32768 bytes data]
* schannel: client wants to read 102400 bytes
* schannel: encrypted data buffer: offset 1037 length 103424
* schannel: encrypted data got 40960
* schannel: encrypted data buffer: offset 41997 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 16384 length 102400
* schannel: encrypted data length: 25584
* schannel: encrypted data cached: offset 25584 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 32768 length 102400
* schannel: encrypted data length: 9171
* schannel: encrypted data cached: offset 9171 length 103424
* schannel: failed to decrypt data, need more data
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 32768
* schannel: decrypted data buffer: offset 0 length 102400
{ [32768 bytes data]
* schannel: client wants to read 102400 bytes
* schannel: encrypted data buffer: offset 9171 length 103424
* schannel: encrypted data got 4096
* schannel: encrypted data buffer: offset 13267 length 103424
* schannel: failed to decrypt data, need more data
* schannel: schannel_recv cleanup
 69 2070k   69 1438k    0     0   287k      0  0:00:07  0:00:05  0:00:02  293k* schannel: client wants to read 102400 bytes
* schannel: encrypted data buffer: offset 13267 length 103424
* schannel: encrypted data got 25600
* schannel: encrypted data buffer: offset 38867 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 16384 length 102400
* schannel: encrypted data length: 22454
* schannel: encrypted data cached: offset 22454 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 32768 length 102400
* schannel: encrypted data length: 6041
* schannel: encrypted data cached: offset 6041 length 103424
* schannel: failed to decrypt data, need more data
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 32768
* schannel: decrypted data buffer: offset 0 length 102400
{ [32768 bytes data]
* schannel: client wants to read 102400 bytes
* schannel: encrypted data buffer: offset 6041 length 103424
* schannel: encrypted data got 17408
* schannel: encrypted data buffer: offset 23449 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 16384 length 102400
* schannel: encrypted data length: 7036
* schannel: encrypted data cached: offset 7036 length 103424
* schannel: failed to decrypt data, need more data
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 16384
* schannel: decrypted data buffer: offset 0 length 102400
{ [16384 bytes data]
* schannel: client wants to read 102400 bytes
* schannel: encrypted data buffer: offset 7036 length 103424
* schannel: encrypted data got 11264
* schannel: encrypted data buffer: offset 18300 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 16384 length 102400
* schannel: encrypted data length: 1887
* schannel: encrypted data cached: offset 1887 length 103424
* schannel: failed to decrypt data, need more data
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 16384
* schannel: decrypted data buffer: offset 0 length 102400
{ [16384 bytes data]
* schannel: client wants to read 102400 bytes
* schannel: encrypted data buffer: offset 1887 length 103424
* schannel: encrypted data got 7168
* schannel: encrypted data buffer: offset 9055 length 103424
* schannel: failed to decrypt data, need more data
* schannel: schannel_recv cleanup
* schannel: client wants to read 102400 bytes
* schannel: encrypted data buffer: offset 9055 length 103424
* schannel: encrypted data got 24576
* schannel: encrypted data buffer: offset 33631 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 16384 length 102400
* schannel: encrypted data length: 17218
* schannel: encrypted data cached: offset 17218 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 32768 length 102400
* schannel: encrypted data length: 805
* schannel: encrypted data cached: offset 805 length 103424
* schannel: failed to decrypt data, need more data
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 32768
* schannel: decrypted data buffer: offset 0 length 102400
{ [32768 bytes data]
* schannel: client wants to read 102400 bytes
* schannel: encrypted data buffer: offset 805 length 103424
* schannel: encrypted data got 102619
* schannel: encrypted data buffer: offset 103424 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 16384 length 102400
* schannel: encrypted data length: 87011
* schannel: encrypted data cached: offset 87011 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 32768 length 102400
* schannel: encrypted data length: 70598
* schannel: encrypted data cached: offset 70598 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 49152 length 102400
* schannel: encrypted data length: 54185
* schannel: encrypted data cached: offset 54185 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 65536 length 102400
* schannel: encrypted data length: 37772
* schannel: encrypted data cached: offset 37772 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 81920 length 102400
* schannel: encrypted data length: 21359
* schannel: encrypted data cached: offset 21359 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 98304 length 102400
* schannel: encrypted data length: 4946
* schannel: encrypted data cached: offset 4946 length 103424
* schannel: failed to decrypt data, need more data
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 98304
* schannel: decrypted data buffer: offset 0 length 102400
{ [98304 bytes data]
* schannel: client wants to read 102400 bytes
* schannel: encrypted data buffer: offset 4946 length 103424
* schannel: encrypted data got 84773
* schannel: encrypted data buffer: offset 89719 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 16384 length 102400
* schannel: encrypted data length: 73306
* schannel: encrypted data cached: offset 73306 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 32768 length 102400
* schannel: encrypted data length: 56893
* schannel: encrypted data cached: offset 56893 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 49152 length 102400
* schannel: encrypted data length: 40480
* schannel: encrypted data cached: offset 40480 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 65536 length 102400
* schannel: encrypted data length: 24067
* schannel: encrypted data cached: offset 24067 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 81920 length 102400
* schannel: encrypted data length: 7654
* schannel: encrypted data cached: offset 7654 length 103424
* schannel: failed to decrypt data, need more data
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 81920
* schannel: decrypted data buffer: offset 0 length 102400
{ [81920 bytes data]
* schannel: client wants to read 102400 bytes
* schannel: encrypted data buffer: offset 7654 length 103424
* schannel: encrypted data got 12288
* schannel: encrypted data buffer: offset 19942 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 16384 length 102400
* schannel: encrypted data length: 3529
* schannel: encrypted data cached: offset 3529 length 103424
* schannel: failed to decrypt data, need more data
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 16384
* schannel: decrypted data buffer: offset 0 length 102400
{ [16384 bytes data]
* schannel: client wants to read 102400 bytes
* schannel: encrypted data buffer: offset 3529 length 103424
* schannel: encrypted data got 12288
* schannel: encrypted data buffer: offset 15817 length 103424
* schannel: failed to decrypt data, need more data
* schannel: schannel_recv cleanup
* schannel: client wants to read 102400 bytes
* schannel: encrypted data buffer: offset 15817 length 103424
* schannel: encrypted data got 87607
* schannel: encrypted data buffer: offset 103424 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 16384 length 102400
* schannel: encrypted data length: 87011
* schannel: encrypted data cached: offset 87011 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 32768 length 102400
* schannel: encrypted data length: 70598
* schannel: encrypted data cached: offset 70598 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 49152 length 102400
* schannel: encrypted data length: 54185
* schannel: encrypted data cached: offset 54185 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 65536 length 102400
* schannel: encrypted data length: 37772
* schannel: encrypted data cached: offset 37772 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 81920 length 102400
* schannel: encrypted data length: 21359
* schannel: encrypted data cached: offset 21359 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 98304 length 102400
* schannel: encrypted data length: 4946
* schannel: encrypted data cached: offset 4946 length 103424
* schannel: failed to decrypt data, need more data
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 98304
* schannel: decrypted data buffer: offset 0 length 102400
{ [98304 bytes data]
* schannel: client wants to read 102400 bytes
* schannel: encrypted data buffer: offset 4946 length 103424
* schannel: encrypted data got 98478
* schannel: encrypted data buffer: offset 103424 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 16384 length 102400
* schannel: encrypted data length: 87011
* schannel: encrypted data cached: offset 87011 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 32768 length 102400
* schannel: encrypted data length: 70598
* schannel: encrypted data cached: offset 70598 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 49152 length 102400
* schannel: encrypted data length: 54185
* schannel: encrypted data cached: offset 54185 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 65536 length 102400
* schannel: encrypted data length: 37772
* schannel: encrypted data cached: offset 37772 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 81920 length 102400
* schannel: encrypted data length: 21359
* schannel: encrypted data cached: offset 21359 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 98304 length 102400
* schannel: encrypted data length: 4946
* schannel: encrypted data cached: offset 4946 length 103424
* schannel: failed to decrypt data, need more data
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 98304
* schannel: decrypted data buffer: offset 0 length 102400
{ [98304 bytes data]
* schannel: client wants to read 102400 bytes
* schannel: encrypted data buffer: offset 4946 length 103424
* schannel: encrypted data got 54555
* schannel: encrypted data buffer: offset 59501 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 16384 length 102400
* schannel: encrypted data length: 43088
* schannel: encrypted data cached: offset 43088 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 32768 length 102400
* schannel: encrypted data length: 26675
* schannel: encrypted data cached: offset 26675 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 49152 length 102400
* schannel: encrypted data length: 10262
* schannel: encrypted data cached: offset 10262 length 103424
* schannel: failed to decrypt data, need more data
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 49152
* schannel: decrypted data buffer: offset 0 length 102400
{ [49152 bytes data]
* schannel: client wants to read 102400 bytes
* schannel: encrypted data buffer: offset 10262 length 103424
* schannel: encrypted data got 68608
* schannel: encrypted data buffer: offset 78870 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 16384 length 102400
* schannel: encrypted data length: 62457
* schannel: encrypted data cached: offset 62457 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 32768 length 102400
* schannel: encrypted data length: 46044
* schannel: encrypted data cached: offset 46044 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 49152 length 102400
* schannel: encrypted data length: 29631
* schannel: encrypted data cached: offset 29631 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 65536 length 102400
* schannel: encrypted data length: 13218
* schannel: encrypted data cached: offset 13218 length 103424
* schannel: failed to decrypt data, need more data
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 65536
* schannel: decrypted data buffer: offset 0 length 102400
{ [65536 bytes data]
* schannel: client wants to read 40387 bytes
* schannel: encrypted data buffer: offset 13218 length 103424
* schannel: encrypted data got 8192
* schannel: encrypted data buffer: offset 21410 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 16384 length 102400
* schannel: encrypted data length: 4997
* schannel: encrypted data cached: offset 4997 length 103424
* schannel: failed to decrypt data, need more data
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 16384
* schannel: decrypted data buffer: offset 0 length 102400
{ [16384 bytes data]
 98 2070k   98 2046k    0     0   341k      0  0:00:06  0:00:06 --:--:--  429k* schannel: client wants to read 24003 bytes
* schannel: encrypted data buffer: offset 4997 length 103424
* schannel: encrypted data got 19064
* schannel: encrypted data buffer: offset 24061 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 16384 length 102400
* schannel: encrypted data length: 7648
* schannel: encrypted data cached: offset 7648 length 103424
* schannel: decrypted data length: 7619
* schannel: decrypted data added: 7619
* schannel: decrypted data cached: offset 24003 length 102400
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: decrypted data buffer: offset 24003 length 102400
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 24003
* schannel: decrypted data buffer: offset 0 length 102400
{ [24003 bytes data]
100 2070k  100 2070k    0     0   345k      0  0:00:06  0:00:06 --:--:--  480k
* Connection #0 to host download.springsource.com left intact

**Comment by kdvolder** [comment]
Is that the full output of the curl command. It doesn't look complete. I see an error 'failing to decrypt'. But do not see for example some things that we probably expect to see such as what ip address to connect to, negotiating the encryption algorithm and what ssl certificate store it uses.

I'm not much of a network expert myself, but the output looks incomplete to me. 

Anyhow, I'm not sure what is going on, we suspect maybe something todo with the fact that you are in China. Or maybe you are on a corporate network? Either way I suspect something on your end is interferring with the network connection.

Perhaps you can try using a VPN?

**Comment by kdvolder** [comment]
The only clue we have so far is that maybe something may be blocking or breaking ssl (encrypted) connection. Can you try if the plain http link works better (i.e. replace 'https' with 'http' in the url).

```
curl -v -o download.jar http://download.springsource.com/release/STS4/4.8.0.RELEASE/dist/e4.17/spring-tool-suite-4-4.8.0.RELEASE-e4.17.0-win32.win32.x86_64.self-extracting.jar
```

If that works it is another clue that the problem may have something to do with ssl encryption.

**Comment by martinlippert** [comment]
Closing this for now due to now further activities or feedback on this one. If this happens again, please comment and we can re-open this.
