### ISSUE TITLE
Debugging is not possible due to a 'An internal error occurred during: Debug children update' or 'Check debug command' problem

### ISSUE THREAD

**Issue by ingogriebsch** [spring-projects/sts4#553]
Hiho,

I'm running Windows 10 Version 2004 (Build 19041.572).

![image](https://user-images.githubusercontent.com/18695610/96571404-d10ec800-12cb-11eb-8995-381cd66ff802.png)

I'm using Spring Tool Suite 4 (Version: 4.8.0.RELEASE, Build Id: 202009151856).

![image](https://user-images.githubusercontent.com/18695610/96571484-eb48a600-12cb-11eb-9132-a7c427e83f01.png)

I'm using the preconfigured vm (plugins/org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_14.0.2.v20200815-0932/jre/bin)

![image](https://user-images.githubusercontent.com/18695610/96571363-c18f7f00-12cb-11eb-9101-ef38daf0cf0a.png)

I have several JDKs installed (Java 8, 11, 14). The Java version that is active on the OS is Java 1.8.

I have a Maven project that has configured Java 1.8. If I want to debug some code in that project and I debug for example a test of the project, the debug session is starting but stuck after a few seconds. Nothing is happen then anymore. If I then navigate to the debug view and want to expand the suspended Thread (that is obviously suspended through the set breakpoint), a "'Debug children update' has encountered a problem" dialog occurres.

![image](https://user-images.githubusercontent.com/18695610/96572247-e6382680-12cc-11eb-8747-c9b5a751bd85.png)

![image](https://user-images.githubusercontent.com/18695610/96572184-d3255680-12cc-11eb-8816-80ea73c8af0e.png)

Sometimes I do not get the mentioned error above but a 'Check debug command' error.

![image](https://user-images.githubusercontent.com/18695610/96572036-a7a26c00-12cc-11eb-9b73-23bc281e1582.png)

![image](https://user-images.githubusercontent.com/18695610/96572536-36af8400-12cd-11eb-98cf-cff3a391a47e.png)

If I close the dialog nothing happens. The execution is still stucked. The only thing I can do is to terminate the process.

It looks like it makes no difference if it is a Java 8 or Java 11 based project. It looks like it makes no difference if it is a Spring Boot poject or a more 'simple' project (e.g. a library).

Means that I'm currently not able to debug any code. I used version 4.7.x before and all things worked well on my machine. Therefore it would be really nice if someone could give me a hint what I can do to solve this problem.

**Comment by martinlippert** [comment]
What happens if you remove the embedded JRE from the preferences of your Java JREs and use one of your local JDKs instead within the workspace? (all that while not changing the `.ini` file)

**Comment by ingogriebsch** [comment]
@martinlippert Thanks for coming back to me! :)

I don't know exactly if I understand what you wanted what I should change in my local environment. Therefore, the following screenshots show my preferences:

My compile compliance level is set to 1.8:

![image](https://user-images.githubusercontent.com/18695610/96622348-1e118f00-130a-11eb-9e1d-e70b0dbc0d93.png)

I have the following JREs installed:

![image](https://user-images.githubusercontent.com/18695610/96622601-721c7380-130a-11eb-840a-f9257ac72452.png)

All these point to JDKs installed on my local machine.
- `jdk1.8.0_181`
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
- `jdk-11`
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
- `jdk-11.0.8+10`
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)
- `jdk-14.0.2+12`
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.2+12)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.2+12, mixed mode, sharing)

The execution environments point to the corresponding JRE:

![image](https://user-images.githubusercontent.com/18695610/96623354-8b71ef80-130b-11eb-8365-bb0ccc721824.png)

The Java Build Path of the project points to the JavaSE-1.8 (which should use the `jdk1.8.0_181`):

![image](https://user-images.githubusercontent.com/18695610/96623594-e0ae0100-130b-11eb-8551-f61ac7a8a1e0.png)

Can you please explain again what I should do/change in my local environment? :)

**Comment by kdvolder** [comment]
Not quite the same but this vaguely resembles a bug I reported to Eclipse a while back:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=563441

That bug was closed as a duplicate of another bug which is supposed to be fixed. The error in my case was bit different and I can't say I've ever seen a error quite like that one. Not sure what the error means.

**Comment by kdvolder** [comment]
> Can you please explain again what I should do/change in my local environment? :)

I think Martin is suggesting a bit trying to run STS or the project you are debugging with a different JRE. The error might be specific to a particular version of JRE. Though at first sight there's nothing all that unusual about your various JREs.

**Comment by ingogriebsch** [comment]
I played around with the different JDKs I have installed on my machine but I cannot get it running, regardless which combination I use. I changed the debug configuration and tried different 'Execution Environments' and 'Alternate JRE'. I also used the '-noverify' flag (because it is mentioned several times in issues related to the 'Expected stackmap frame at this location' error message). But this flag did not help as well,

Another thing I noticed during the tests: I get a different error ('Check Debug Command') if I have the 'debug' view open and visible while executing a test. 

```
An internal error occurred during: "Check Debug Command".
Expecting a stackmap frame at branch target 23
Exception Details:
  Location:
    org/eclipse/jdt/internal/debug/core/model/JDIStackFrame.exists()Z @7: aload_0
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0000000: 2ab4 0052 594c c22a b400 3d02 9f00 0704
    0000010: a700 0403 2bc3 ac2b c3bf               
  Exception Handler Table:
    bci [7, 22] => handler: 23
    bci [23, 25] => handler: 23
```

If the 'debug' view is open but not visible and I need to switch to this view, I get another error ('Debug children update'). In either way, the stack trace is the same:

```
An internal error occurred during: "Debug children update".
Expecting a stackmap frame at branch target 23
Exception Details:
  Location:
    org/eclipse/jdt/internal/debug/core/model/JDIStackFrame.exists()Z @7: aload_0
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0000000: 2ab4 0052 594c c22a b400 3d02 9f00 0704
    0000010: a700 0403 2bc3 ac2b c3bf               
  Exception Handler Table:
    bci [7, 22] => handler: 23
    bci [23, 25] => handler: 23
```

Can it have something to do with `org/eclipse/jdt/internal/debug/core/model/JDIStackFrame.exists()Z @7: aload_0`? I mean, could it be that the root of the problem is inside the debug view or plugin?

Means I'm still stuck and cannot solve the problem on my own. :(

**Comment by ingogriebsch** [comment]
It looks like I just solved the problem! :)

After searching a little bit more for `Expecting a stackmap frame at branch target 23` problem I stumbled about this quite old bug ticket:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=322126

The latest comments are quite new and the last comment points to the following bug ticket:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=567081

If you follow the comments you can see that the 'Kotlin for Eclipse' (https://github.com/JetBrains/kotlin-eclipse) plugin is the root of the problem. And guess what... I also had the plugin installed. 

After uninstalling the plugin and restarting STS I can debug my code again! :)

**Comment by ingogriebsch** [comment]
@martinlippert is it okay to leave this ticket open for a moment? I would like to check some more projects and different environments tomorrow. I will report back here...

**Comment by martinlippert** [comment]
> @martinlippert is it okay to leave this ticket open for a moment? I would like to check some more projects and different environments tomorrow. I will report back here...

Sure

**Comment by ingogriebsch** [comment]
@martinlippert Even after working with the IDE for several days after removing the Kotlin plugin I have no more issues related to debugging my projects. Therefore I will close this issue now.

**Comment by martinlippert** [comment]
@ingogriebsch Sounds good to me and thanks for letting us know here. Much appreciated.

**Comment by anydoby** [comment]
> It looks like I just solved the problem! :)
> 
> After searching a little bit more for `Expecting a stackmap frame at branch target 23` problem I stumbled about this quite old bug ticket:
> 
> https://bugs.eclipse.org/bugs/show_bug.cgi?id=322126
> 
> The latest comments are quite new and the last comment points to the following bug ticket:
> 
> https://bugs.eclipse.org/bugs/show_bug.cgi?id=567081
> 
> If following the comments in that ticket one can see that the 'Kotlin for Eclipse' (https://github.com/JetBrains/kotlin-eclipse) plugin is the root of the problem. And guess what... I also had the plugin installed.
> 
> After uninstalling the plugin and restarting STS I can debug my code again! :)

Indeed, uninstalling Kotlin plugin solved the issue for me.

**Comment by kriegfrj** [comment]
> Indeed, uninstalling Kotlin plugin solved the issue for me.

Although I haven't personally worked with STS or Spring, I was also having this issue and removing the Kotlin plugin fixed it for me too. Many thanks.
