### ISSUE TITLE
Add support for 'additional_tags' property for docker image resource type params

### ISSUE THREAD

**Issue by chaoyangnz** [spring-projects/sts4#56]
`Unknown property 'additional_tags' for type 'DockerImagePutParams'`

The support of builtin resources needs to be updated.

**Comment by kdvolder** [comment]
Thanks for reporting. We rely greatly on reports like this to help us keep the editor in sync with changes to concourse and its built-in resource types. This will be fixed shortly!

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Kris De Volder:) 

Looking at the docs for docker resource at moment.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Kris De Volder:) 

Added these to schema now:

- DockerImageSource
  - aws_session_token
  - max_concurrent_downloads
  - max_concurrent_uploads
- DockerImagePutParams
  - additional_tags
  - cache_from
  - load_bases
  - target_name
