### ISSUE TITLE
Add support for configuring vm parameters for sts4 language servers

### ISSUE THREAD

**Issue by gayanper** [spring-projects/sts4#560]
Add support for configuring vm parameters for sts4 language servers. This will help to control how much heap a language server must use. Today the language servers are consuming lot of memory on large workspaces since the heap is unlimited/too large.

**Comment by martinlippert** [comment]
You can already do that:
https://github.com/spring-projects/sts4/wiki/Custom-VM-Args

But the question remains why the language server is consuming so much heap (it should definitely not). Can you capture a head dump to see that is going on when this consumes a lot of heap? (and maybe go a GC before)

**Comment by gayanper** [comment]
Its a workspace that has many projects, nearly 20 projects. But not all projects has spring beans, but they have spring-core as a transitive dependency in their classpath and most of the projects has java Function implementations. Unfortunately i cannot share a heap dump because of proprietary class names and such.

**Comment by martinlippert** [comment]
@gayanper Can you share details about when the heap usage increases and what happens if you kick a manual GC? (using `jconsole`, for example, attached to the language server process)

And does changing the VM settings help? Can you explain more why and what exactly happens?

**Comment by martinlippert** [comment]
@gayanper Any idea how we can investigate why the language server is consuming so much heap space? Still would love to know more details or reproduce this locally in order to see what is going on.

**Comment by gayanper** [comment]
I found this while running with intellij, so i doubt if this is caused by how i implementing classpath notifications. Now i mostly work in eclipse, I didn't notice such an issue with eclipse.

**Comment by martinlippert** [comment]
@gayanper Okay, thanks for getting back on this. Lets close this for now. If you are coming across another spring-boot language server running out-of-heap space, we can re-open this or work from a new issue. Thanks again!
