### ISSUE TITLE
Failed to connect to process remote process - null after retries: 10

### ISSUE THREAD

**Issue by hunterlodge** [spring-projects/sts4#569]
Each time when I got VSCode restarted, I would receive this error message on the bottom right corner. I've googled quite a while for a solution, but ended up with no answer. Can anyone help me out? Thanks!

My VSCode version is 1.51.1 and the version of STS extension is v1.23.0, both of which I believe are the latest.

**Comment by martinlippert** [comment]
This message is coming from the live application information of the language server. It seems to try to connect to a remote application (to gather live data from) without success.

As a first step, we can take a look at your `settings.json` file. I am wondering why the language server tries to connect to a remote app. Usually it does that only when there is a remote app configured. In that case, the `settings.json` would contain a section for `boot-java.remote-apps`. If that is the case, please remove that section. That should prevent the language server from trying to fetch the live data from that remote app without much success.

**Comment by hunterlodge** [comment]
> This message is coming from the live application information of the language server. It seems to try to connect to a remote application (to gather live data from) without success.
> 
> As a first step, we can take a look at your `settings.json` file. I am wondering why the language server tries to connect to a remote app. Usually it does that only when there is a remote app configured. In that case, the `settings.json` would contain a section for `boot-java.remote-apps`. If that is the case, please remove that section. That should prevent the language server from trying to fetch the live data from that remote app without much success.

Thanks Martin. Your solution works for me. The `boot-java.remote-apps` must be added by accident as I had no idea what it was.

**Comment by martinlippert** [comment]
@hunterlodge Glad to hear that this solved it. Closing this issue.
