### ISSUE TITLE
Popup states "java_home or path environment variable seems to point to a jre. a jdk is required hence boot hints are unavailable"

### ISSUE THREAD

**Issue by gillespiejim78** [spring-projects/sts4#576]
![VSCode](https://user-images.githubusercontent.com/15959415/102689830-4402c500-41cf-11eb-8d80-f42677c59dd5.png)

JAVA_HOME is set to /usr/lib/jvm/java-11-openjdk-11.0.9.11-0.fc33.x86_64, which I can see from a terminal prior to launching code.

**Comment by martinlippert** [comment]
Maybe related to https://github.com/spring-projects/sts4/issues/347?

**Comment by gillespiejim78** [comment]
@martinlippert that fixed it, thank you!

**Comment by martinlippert** [comment]
@gillespiejim78 Great to hear. Thanks for letting us know and closing this issue. Much appreciated.
