### ISSUE TITLE
Error writing config: rename ~\.cf\temp-config025076595 ~\.cf\config.json: Access is denied.

### ISSUE THREAD

**Issue by dinurp** [spring-projects/sts4#577]
I am using Cloudfoundry Manifest YML Support (v1.24.0) in VS.Code (v 1.51.1) on Windows 10

I get **Error writing config: rename C:\Users\XX\.cf\temp-config025076595 C:\Users\XX\.cf\config.json: Access is denied.**
when using cf CLI.

If I disable the extension, the error goes away.

Is the file "~/.cf/config.json" kept open [here](https://github.com/spring-projects/sts4/blob/d86becebe7e672044de93b2da3afbed5bee47438/headless-services/commons/commons-cf/src/main/java/org/springframework/ide/vscode/commons/cloudfoundry/client/cftarget/CfCliParamsProvider.java#L96
)?

**Comment by martinlippert** [comment]
@dinurp I think you are absolutely correct, thanks for reporting this and pointing directly at the issue. That is very much appreciated.

I pushed a fix to master via https://github.com/spring-projects/sts4/commit/770137b6d37bde3e22c893eec16cc557178c3dea, now need to wait for CI builds to produce new snapshot versions of the VS Code extension files for you to try.

**Comment by martinlippert** [comment]
Finally I got the builds to work again, please feel free to grab the latest nightly VSIX file for the spring boot language server from http://dist.springsource.com/snapshot/STS4/nightly-distributions.html and try that in your VSCode install.
