### ISSUE TITLE
allow @SpringBootApplication's child annotation as Springboot app's main class

### ISSUE THREAD

**Issue by mattzhang27** [spring-projects/sts4#584]
in my case, i have an springboot application. but the main class is not directely annotated by @SpringBootApplication, it's annotated by a customized  annotation which is inherited from @SpringBootApplication, which means this is also a SpringBoot app. howerer, the springboot tool suits can't recognize this is a SpringBoot application, and dosn't show the run button in springboot dashboard.

**Comment by martinlippert** [comment]
@mattzhang27 The check whether an app is shown in the boot dashboard or not doesn't look for the annotation. Instead, the resolved classpath is taken into account, looking for the JAR files from spring-boot. Does your project have any spring-boot libraries on the classpath? If so and this still doesn't work, it would be good to point us to a sample app that reproduces this behavior, so that we could take a deeper look.

**Comment by mattzhang27** [comment]
thanks for you reply, martin.
my project have spring-boot libraries, in its parent poject's pom.xml.
sorry that  i cant publish a sample app to show the problem for now, because it may take some time to prepare for that.

below is some lines of my project's main class:

`
// ......

@CanaryCloudApplication(
                        applicationName = "b2b-consumer-app-edge",
                        serverServletContextPath = "/capp"
)
@EnableFeignClients(
        basePackages = {"com.vd.canary.**","com.kakarote.crm.api.**"}
)
public class ConsumerAppApplication{
    public static void main(String[] args) {
        CanaryApplication.run(ConsumerAppApplication.class, args);
    }
}

`

and below is some lines of my project's pom.xml, the spring-boot libararies are in the parent project's (or the parent project's parent project's) pom.xml
`
// ......

  <parent>
        <groupId>com.vd.canary</groupId>
        <artifactId>b2b-basic-parent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

// ......


`

**Comment by martinlippert** [comment]
I tried to setup something like this, but the project is still recognized as spring-boot app in the Spring Tools 4 for Eclipse. Are we talking about the Spring Tools 4 for Eclipse? Or are you using VSCode?

Can you attach a screenshot of your IDE with the project open and an expanded node for the classpath of that project?

**Comment by mattzhang27** [comment]
I'm using VScode, and my problem has been solved somehow when I open my project in VScode the second time. I lately changed my IDE from Jetbrains IDEA to VScode(with Spring Boot Extension Pack). Thank you.

**Comment by martinlippert** [comment]
@mattzhang27 Ah, okay, glad to hear it works again. So lets close the issue. Please comment if this happens again and we can re-open and investigate in more detail.
