### ISSUE TITLE
VSCode PROP_UNKNOWN_PROPERTY when using spring-boot-configuration-processor in a Gradle project

### ISSUE THREAD

**Issue by mdgilene** [spring-projects/sts4#585]
**Describe the bug**
In VSCode when using spring-boot-configuration-processor in a Gradle project, any custom properties report PROP_UNKNOWN_PROPERTY.

This issue does NOT occur when using a Maven project.

**To Reproduce**
1. Install Spring Boot Extension Pack
2. Initialize a new Spring Boot Gradle project with `spring-boot-configuration-processor`
3. Create a new `@ConfigurationProperties` class
4. Attempt to set newly created properties in `application.properties`

**Sample**
https://github.com/mdgilene/spring-unknown-config-bug

**Comment by kdvolder** [comment]
This is expected because Gradle tooling (BuildShip) doesn't support annotation processor configuration in Eclipse. The maven tooling (m2e) does.

This is a very long standing issue. See: https://github.com/eclipse/buildship/issues/329

You can try to comment there to try and add your vote/voice and motivate Gradle folks to fix this.

**Comment by RamenTurismo** [comment]
I am from the future and here to motivate gradle folks to fix this!
Getting the configuration right the first time without looking into the code is really a gain of time, especially on big projects.

**Comment by martinlippert** [comment]
@RamenTurismo I would recommend to comment on the above mentioned issue of the buildship project...

**Comment by gratisCobalt** [comment]
I got the same issue with a maven project

**Comment by martinlippert** [comment]
@gratisCobalt Can you share more details about when and how you are running into this issue and provide a few steps to reproduce this?
