### ISSUE TITLE
[Spring Boot Tools] How to set Custom VM Args on the VSCode extension

### ISSUE THREAD

**Issue by licam** [spring-projects/sts4#589]
Hello,
I see you support custom VM args in the eclipse edition.
We need to use it with the VSCode extension.
Based on your [wiki ](https://github.com/spring-projects/sts4/wiki/Custom-VM-Args) page I tried using "Dboot.ls.custom.vmargs": "-Xmx500m" in the settings.json but it didn't work.

Is it supported for the VSCode extension? And if not, please add it.

Also, please advice how much memory your VSCode extension should have in order to run properly?  (minimum limit)

**Comment by martinlippert** [comment]
Open the `Settings` in VSCode, navigate to the `Extensions -> Boot-Java Configuration -> Spring Boot-ls-java-vmargs` setting, there you can configure JVM args for the language server process. If you open the `settings.json` file, you can add an array for JVM args like:

```
    "spring-boot.ls.java.vmargs": [
        "-Xmx1G"
    ]
```

The exact memory usage of the language server varies a bit based on the workspace and the projects you have in the workspace. Usually it should not consume more than 1GB.

If it does, you can attach a profiler or something like that (VisualVM, JConsole, YourKit, etc.) to the language server process and observe the memory behavior. I am running the language server without any specific settings just fine, but if you observe that it is running out of memory, you can set the max settings, of course. In that case, we would be highly interested in learning more about why the language server is consuming that much memory.

**Comment by martinlippert** [comment]
Open the `Settings` in VSCode, navigate to the `Extensions -> Boot-Java Configuration -> Spring Boot-ls-java-vmargs` setting, there you can configure JVM args for the language server process. If you open the `settings.json` file, you can add an array for JVM args like:

```
    "spring-boot.ls.java.vmargs": [
        "-Xmx1G"
    ]
```

(also added that to the wiki page, thanks for the pointer to the missing information there)

The exact memory usage of the language server varies a bit based on the workspace and the projects you have in the workspace. You can attach a profiler or something like that (VisualVM, JConsole, YourKit, etc.) to the language server process and observe the memory behavior. I am running the language server without any specific settings just fine, but if you observe that it is running out of memory, you can set the max settings, of course. In that case, we would be highly interested in learning more about why the language server is consuming that much memory.

**Comment by licam** [comment]
Thank you for the response. It solved my problem.

**Comment by martinlippert** [comment]
Awesome, great to hear. If you are observing obsessive memory consumption in the language server process, please tell us, so that we can take a deeper look and improve on that, if possible.
