### ISSUE TITLE
Some identifiers produce warnings when using Lombok

### ISSUE THREAD

**Issue by chexmo** [spring-projects/sts4#590]
As we say where I live: A picture tells more than a thousand words
![imagen](https://user-images.githubusercontent.com/30608909/104941736-34bf9480-5992-11eb-86f3-918fa35bcc18.png)

I've copy-pasted this code in other IDE and it doesn't produce these warnings.
I've also tried updating the Lombok extension/module manually but it doesn't work neither.

**Comment by chexmo** [comment]
I restarted the IDE again and stuff started working well. IDK why this happened but it seems to be working fine now. Sorry for the inconvenience.

**Comment by martinlippert** [comment]
No worries, glad to hear that it works now.
