### ISSUE TITLE
I can't show it in vs code

### ISSUE THREAD

**Issue by zdf068** [spring-projects/sts4#591]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Sample**

A link to a GitHub repository with a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example).

Reports that include a sample will take priority over reports that do not.
At times, we may require a sample, so it is good to try and include a sample up front.

**Comment by martinlippert** [comment]
@zdf068 Can you please describe the issue you are facing in more detail? The title doesn't give enough details what is going wrong here. The template for bugs that you kept in the description provide some structure for this, so filling this out would be great.

**Comment by zdf068** [comment]
I'm sorry I made a mistake

**Comment by martinlippert** [comment]
No worries, thanks for letting us know.
