### ISSUE TITLE
spring-tool-suite-4-4.9.0.RELEASE has issues in supporting lombok.

### ISSUE THREAD

**Issue by github2033** [spring-projects/sts4#592]
Just downloaded and installed: spring-tool-suite-4-4.9.0.RELEASE-e4.18.0-win32.win32.x86_64.self-extracting.jar

4-4.9.0.RELEASE has issues in supporting lombok. 4.8.0.RELEASE works fine. With 4-4.9.0.RELEASE, the IDE shows errors for all gettters/setters (generated by lombok behind the scenes), but if you force to run it, it works fine. So the issues are only related to STS IDE (display).

**Comment by martinlippert** [comment]
@github2033 This is most likely related to the underlying version of Eclipse and JDT and whether the version of Lombok that you are using is already compatible with that version or not.

In this case, the version of Spring Tools 4 for Eclipse (4.9.0.RELEASE) is based on Eclipse 2020-12. There are basically two steps to investigate this issue. The first step would be to check whether this is indeed a problem specific to the Spring Tools 4 for Eclipse or a general incompatibility between Eclipse 2020-12 and Lombok. Would be great if you could check that with a plain Eclipse 2020-12 install and your Lombok version added to that. The second step will be to report this against the Lombok project.

**Comment by github2033** [comment]
Just checked with Eclipse 2020-12. It indeed has the issue. I reported the bug to Eclipse and hope it will be fixed soon. Thanks
    On Thursday, January 28, 2021, 03:48:34 AM EST, Martin Lippert <notifications@github.com> wrote:  
 
 


@github2033 This is most likely related to the underlying version of Eclipse and JDT and whether the version of Lombok that you are using is already compatible with that version or not.

In this case, the version of Spring Tools 4 for Eclipse (4.9.0.RELEASE) is based on Eclipse 2020-12. There are basically two steps to investigate this issue. The first step would be to check whether this is indeed a problem specific to the Spring Tools 4 for Eclipse or a general incompatibility between Eclipse 2020-12 and Lombok. Would be great if you could check that with a plain Eclipse 2020-12 install and your Lombok version added to that. The second step will be to report this against the Lombok project.

**Comment by martinlippert** [comment]
> Just checked with Eclipse 2020-12. It indeed has the issue. I reported the bug to Eclipse and hope it will be fixed soon. Thanks

You should report this against Lombok, not Eclipse (sorry for maybe being not clear about this upfront and the confusion). Once that bug is filed, it would be good to post the URL here, so that people can find that - and we can close this issue once we have the link to the filed issue at Lombok.

**Comment by martinlippert** [comment]
Looks like the latest Lombok release is compatible again with Eclipse 2020-12, so closing this one here.
