### ISSUE TITLE
Failed to Unzip: Spring STS 4.7.1

### ISSUE THREAD

**Issue by SwaraDeep** [spring-projects/sts4#595]
Failing to unzip https://download.springsource.com/release/STS4/4.7.1.RELEASE/dist/e4.16/spring-tool-suite-4-4.7.1.RELEASE-e4.16.0-win32.win32.x86_64.zip
It's showing corrupted.

**Comment by martinlippert** [comment]
The ZIP file on the server seems to be fine (double checked), so maybe something got corrupted while downloading the file or a proxy in between tried to unzip/zip again and damaged the zip on the way.

You can try to download the ZIP file again, try a different unzip tool (the Windows built-in ZIP support can run into issues with long paths inside of this ZIP), or download this: https://download.springsource.com/release/STS4/4.7.1.RELEASE/dist/e4.16/spring-tool-suite-4-4.7.1.RELEASE-e4.16.0-win32.win32.x86_64.self-extracting.jar

It is a self-extracting JAR file. Once you downloaded that one, double click, wait a bit, and it will extract itself.

Let us know if that helps!

**Comment by SwaraDeep** [comment]
Hello,
Self extracting jar is working but the zip is not working. It's not only
for me, around 20 people tried and it's same "Corrupted" while extracting.

Thank you

**Comment by martinlippert** [comment]
Okay, good to hear that the self-extracting JAR works for you. Are all of those 20 people that you mentioned on the same network, maybe inside the same company network? In most of those cases, the ZIP gets corrupted by proxies trying to look inside. Can you double check that with our network admins?

**Comment by martinlippert** [comment]
Closing this one now due to no additional input arrived here.
