### ISSUE TITLE
Publish VS Code extension to Open VSX

### ISSUE THREAD

**Issue by x80486** [spring-projects/sts4#596]
The `Spring Boot Extension Pack` extension is only published into the VisualStudio Marketplace.

Would it be possible to publish the same also to the Open VSX? — instructions [here](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions--marketplace).

**Comment by martinlippert** [comment]
We are waiting for #583 to be resolved, then we re-publish the extensions on the Open VSX. Therefore closing this as a duplicate of #583.
