### ISSUE TITLE
Strange behavior of STS 4.9.0 with Spring Security importation and Gradle synchronization

### ISSUE THREAD

**Issue by manueljordan** [spring-projects/sts4#597]
Please consider this how a strange situation, not sure if is a bug

I spent some days trying to find a solution and nothing. I do not post this in StackOverflow because is not a specific technical question and is a perfect candidate to be closed quickly by its moderators

I have STS 4.9.0 installed in 

* Mac (El Capitan) 
* Windows 10 

Both PCs have the same configuration, about JDK versions (8,11,15 - included STS) and all plugins (all of them currently updated)

Practically for each project, I create a dedicated workspace, for example, one for Spring Integration, Spring Boot, Hazelcast etc ... it for custom isolation for the local repositories.

Now, something important, I only have **one** STS installation and each workspace is started through command with:

```
$STS_HOME/SpringToolSuite4.app/Contents/MacOS/SpringToolSuite4 -data ${WORKSPACE_DIRECTORY} -vmargs -Xms512M -Xmx4G
```
Two weeks ago, I cloned and imported the `Spring Security` project (based on Gradle) into STS - for contribution purposes, it worked in peace for short time, but **suddenly** it stop to work, it does not open as is expected anymore. Even when I deleted the workspace directory (goodbye `.metadata` directory and the project itself) and repeat all the steps for importation purposes: 

* create new _workspace_
* git clone
* git remote add REMOTE_URL
* git fetch upstream
* git merge upstream/master 

happens the following:

It loads as follows (does not show each sub module)

![01](https://user-images.githubusercontent.com/2552795/107719360-0a69aa00-6ca6-11eb-9f37-40bb1dbf09b0.png)

If I delete the project from the workspace as follows:

![02](https://user-images.githubusercontent.com/2552795/107720463-659c9c00-6ca8-11eb-98d0-072dfbe65809.png)

![03](https://user-images.githubusercontent.com/2552795/107720468-67fef600-6ca8-11eb-8c0f-66ce2eefd910.png)

Therefore the workspace is empty, as follows:

![04](https://user-images.githubusercontent.com/2552795/107720469-68978c80-6ca8-11eb-88cf-597c58b48097.png)

So, if I _close_ and _open_ the IDE loads as follows, _shows the sub modules_ but **not** how should be (Figure _Alpha_):

![05](https://user-images.githubusercontent.com/2552795/107720471-68978c80-6ca8-11eb-99e9-6cc126d28cc1.png)

If I do the following (it after to be built the project by the console/terminal)

* `Gradle` -> `Refresh Gradle Project`

![06](https://user-images.githubusercontent.com/2552795/107720473-69302300-6ca8-11eb-9ed0-fc55317874f3.png)

Arises the following error:

![07](https://user-images.githubusercontent.com/2552795/107720475-69c8b980-6ca8-11eb-9060-6caf42646707.png)

![08](https://user-images.githubusercontent.com/2552795/107720476-69c8b980-6ca8-11eb-9f39-f1cbbc6a055c.png)

**Note**: I reported this error to Buildship, but now here, because in Windows all work fine

And then the project structure changes as follows: (btw - compare against _Alpha_):

![09](https://user-images.githubusercontent.com/2552795/107720478-6a615000-6ca8-11eb-9669-30444d5e7b03.png)

If I again do `Gradle` -> `Refresh Gradle Project` happens again

![10](https://user-images.githubusercontent.com/2552795/107720479-6a615000-6ca8-11eb-98ac-b78f3bd33153.png)

Now, Spring Security asks for Java 8 and the STS comes with JDK 15. In the previous figures, for the imported project, it always has its`JRE System Library` _by default_ pointing to **15**, even having the STS configured to work with JDK 8 (figures about this later). Therefore from the beginning and always (even in Windows) the imported project has/targets to JRE 15 by default. 

**Observation:** (_delta_ scenario) something interesting, if create a **new** workspace from the scratch, and prior to import the project, I delete the included JDK 15, with the importation and with `Gradle` -> `Refresh Gradle Project`, all happens again about the error, and the imported tries to refer the JDK 15 (shows an error because does not exist - it was deleted)

My IDE _global_ or _Preferences_ configuration for Java 8 is as follows (here JDK 15 exists, but is ignored)

![11](https://user-images.githubusercontent.com/2552795/107720480-6af9e680-6ca8-11eb-8fe3-412f6bedd5fb.png)

![12](https://user-images.githubusercontent.com/2552795/107720483-6af9e680-6ca8-11eb-8883-7e741cd20b13.png)

![13](https://user-images.githubusercontent.com/2552795/107720484-6b927d00-6ca8-11eb-9d59-129973e22266.png)

So, after to import the project, I change all manually from JDK 15 to 8 as follows:

![14](https://user-images.githubusercontent.com/2552795/107720485-6c2b1380-6ca8-11eb-96d7-d0c5384e9f65.png)

![15](https://user-images.githubusercontent.com/2552795/107720486-6c2b1380-6ca8-11eb-91f0-d07b2cd7dd72.png)

![16](https://user-images.githubusercontent.com/2552795/107720487-6cc3aa00-6ca8-11eb-8c88-4d2819744777.png)

![17](https://user-images.githubusercontent.com/2552795/107720489-6cc3aa00-6ca8-11eb-9328-32fb30506946.png)

![18](https://user-images.githubusercontent.com/2552795/107720490-6cc3aa00-6ca8-11eb-9b8f-84fb46246e7d.png)

![19](https://user-images.githubusercontent.com/2552795/107720491-6d5c4080-6ca8-11eb-81c8-23526a83949b.png)

So, if in this point If I do again `Gradle` -> `Refresh Gradle Project` appears the message error, and the project refers again to JDK 15, so the previous configurations from JDK 15 to 8 are totally reseted - even if the _delta_ scenario was applied or not.

So:

* Why the project always tries to refer to JDK 15?, even if was deleted prior to import the project.
* Why appears that error message when Gradle tries to synchronize? and how to fix it?

**Note** this problem happened suddenly I am absolutely sure that I did not do an update to the Buildship plugin. And like I said, all work (for the moment) in Windows 10

**Note**  I execute all the Gradle tasks commands by console/terminal because I am able to apply later (`.gradlew --stop`). STS creates its own Gradle Daemons that only appears with the `jps` command, I am going to create other issue about this to ask for that STS includes a new view to show its own Gradle Daemons and let the developer to stop it.

Your experience and guidance is extremely valuable.

Thanks for your understanding

**Comment by manueljordan** [comment]
BTW, like I said it was reported on Buildship 

* [Is not possible import Spring Security #1061](https://github.com/eclipse/buildship/issues/1061)

Sadly is very hard replicate this error or situation. If you read the comment of the other developer, he hadn't had problems. Perhaps you have none problems too.

**Comment by manueljordan** [comment]
Just how an update, I did do realise about the scenario for the JRE 15 automatic reference.

Consider the following:

[[Omicron]]
![Screen Shot 2021-02-17 at 10 41 04 AM](https://user-images.githubusercontent.com/2552795/108228639-0d80f200-710d-11eb-98a8-967c1f67ece8.png)

The problem was the following (`Preferences` -> `Gradle`):

[[Zulu]]
![Screen Shot 2021-02-17 at 10 41 22 AM](https://user-images.githubusercontent.com/2552795/108228722-21c4ef00-710d-11eb-99e3-e614c1772f16.png)

The problem was that I never defined the `java home` value, I took this approach because in _Omicron_ normally I deleted the JRE 15, because Spring Security only needs JDK 8, so I assumed that the Buildship would take the **unique** JRE defined and available in the STS. If you remember the _delta_ scenario, even when JRE 15 was deleted, after of the importation, the Plugin always refers that JRE 15 (even when was deleted)

**Comment by manueljordan** [comment]
Other difference is the following:

On Mac (does not appear nothing)

![Screen Shot 2021-02-17 at 11 40 17 AM](https://user-images.githubusercontent.com/2552795/108236622-1c6ba280-7115-11eb-8f04-e2f90fdaaf9e.png)

On Windows appears:

**Comment by manueljordan** [comment]
I found the solution, and it was about the final scenario to check.

I installed the `spring-javaformat` plugin (it never was installed on Windows - it is the unique difference). 
Since its installation I had problems. More details here:

* [Problems to import and compile the spring-javaformat project #259](https://github.com/spring-io/spring-javaformat/issues/259)

I uninstalled the plugin, now all is how is expected

![Screen Shot 2021-02-17 at 12 25 10 PM](https://user-images.githubusercontent.com/2552795/108243063-a74f9b80-711b-11eb-83f5-5a0c2989bacd.png)

![Screen Shot 2021-02-17 at 12 25 29 PM](https://user-images.githubusercontent.com/2552795/108243074-a9b1f580-711b-11eb-8818-f386736a7dbd.png)

Really wondered why the `spring-javaformat` plugin had affected indirectly to the Buildship plugin and the STS itself.

Do you have some ideas @martinlippert why the IDE itself was affected?- you are the expert here.

**Comment by martinlippert** [comment]
@manueljordan First of all, thanks for sharing all the details here with the community and glad to hear that you found a way to make this work again. I am also wondering why the presence of the `spring-javaformat` plugin causes this, so will need to do a bit of investigation on this.

**Comment by manueljordan** [comment]
Hi @martinlippert , remember I got an error from the beginning with the creation/importation of that project for a new and custom workspace, then I installed the plugin thinking that was mandatory. But that did not work. The details are in that link.

Thanks for the support in advance.
