### ISSUE TITLE
Add a new View to let STS show the Gradle's Daemons created by the IDE itself

### ISSUE THREAD

**Issue by manueljordan** [spring-projects/sts4#598]
**Expected Behavior**

Through the IDE itself, for example with a new View available or other approach, show the Gradle's Daemons **but** _only_ created by the STS itself

* **Observation** by Gradle's Daemon I mean: GradleDaemon/GradleMainWrapper/Kotlin[Daemon/Thread]/Runner, it can be any of them or even _many_ of them, by experience, the latter. It happens when a Gradle task is executed and it generates the execution/creation of other threads.

**Current Behavior**

Does not exist a way through the IDE itself to see what Gradle's Daemon was o were created by the IDE itself, i.e a task was executed. An approach to work around this is use the terminal and use the `jps` and try to guess what thread was created by the IDE ("guess" - because could exists other threads created by other app based on Java - based on Gradle or not). Consider the scenario where the developer has no idea about the `jps` command and the developer only works through `gradlew --status` and `gradlew --stop`.

The situation to resolve is about when some tasks would be executed by command and other through the IDE, why take this approach? - I found and reported the following experience and issue for example: 

* [Is not possible build Spring Security: java.lang.IllegalStateException: Could not load file 'etc/nohttp/allowlist.lines' #9346](https://github.com/spring-projects/spring-security/issues/9346)

Where the solution is work through either terminal or add an extra parameter. So, now you can see why would be mandatory use both or any of them.

**Context**

Is not critical, but exists Gradle Daemon Threads accessing at the same to the same resources, so locks events happens and some Threads must be stopped, it through `gradlew --stop` and by `jps` (using `kill -9 ID`)

Other situation is about the following experience that I had:

* [SEC-2691: Consistent Usage of LDAP Host #2912](https://github.com/spring-projects/spring-security/issues/2912#issuecomment-774809216)

Here is tricky to do realise how fix the situation, so here is very important know what are the Gradle's Daemons created by the STS itself

I know that the BuildShip plugin really creates the Gradle's threads, but the reporter should be the IDE in case a new Gradle plugin appears in the future. I hope you see my point.

**Comment by kdvolder** [comment]
Seems like a good idea to me, but it is probably something that should be filed as a feature request with Eclipse BuildShip. STS doesn't really provide any specific tooling to support working with Gradle and it is probably not something we should try to add on the STS side.

**Comment by kdvolder** [comment]
If you want to file a ticket to request something like this in BuildShip you can do it on the Eclipse bug tracker:

https://bugs.eclipse.org/bugs/describecomponents.cgi?product=Buildship

**Comment by manueljordan** [comment]
Understoot, btw

* https://github.com/eclipse/buildship/issues/1069
