### ISSUE TITLE
Server Option missing in configure build path in sts 4

### ISSUE THREAD

**Issue by snacoderz** [spring-projects/sts4#600]
**Server option missing in configure build path in maven web app 1.4**

Spring Tool Suite 4 
Version: 4.9.0.RELEASE
Build Id: 202012132054
OS: Linux, v.5.8.0-43-generic, x86_64 / gtk 3.24.20
Java version: 15.0.1

![Screenshot from 2021-02-14 13-08-11](https://user-images.githubusercontent.com/77742189/107871567-d4584000-6ec8-11eb-84f6-71e3d0815faf.png)

**Comment by martinlippert** [comment]
Can you provide a sample project that we could use to reproduce the issue and explain in more details what exactly you are missing here? That would be awesome. I can see the warning showing up there, complaining about two missing path entries, but a few more details would help here.

**Comment by snacoderz** [comment]
I am trying to create small spring based rest web service  using maven-archetype-webapp 1.4 and I need to deploy it on tomcat 10.0 / 9.0  server. **Server option is not displaying in (Build Path > Config Build Path)** or Run As >Tomcat Server where i can configure server for this project as shown in the image above. here is link to my maven project. simply clone it and import it on sts to reproduce condition [https://github.com/snacoderz/contactsapi](url)

**Comment by martinlippert** [comment]
You can select the Tomcat environment in the `Targeted Runtimes` section of the dialog that you have in your screenshot above. That brings the corresponding classpath container on the project and you will see it in the `Libraries` section of the `Java Build Path` config.

To run the app on the Tomcat server, you can right-click on the Tomcat server entry and select `Add and Remove...` to add your app to the server.

The `Run As...` entry to run the app directly on the Tomcat server is indeed missing. The reason for that is most likely that we don't install all the JEE tooling from Eclipse by default anymore. You can install those parts via the `Install New Software` dialog, select the main Eclipse update site, and then look into the `Web, XML, Java EE and OSGi Enterprise Development` category to install the parts (probably the `Java EE` and `Java Web` components).

Hope this helps!

**Comment by snacoderz** [comment]
> You can select the Tomcat environment in the `Targeted Runtimes` section of the dialog that you have in your screenshot above. That brings the corresponding classpath container on the project and you will see it in the `Libraries` section of the `Java Build Path` config.
> 
> To run the app on the Tomcat server, you can right-click on the Tomcat server entry and select `Add and Remove...` to add your app to the server.
> 
> The `Run As...` entry to run the app directly on the Tomcat server is indeed missing. The reason for that is most likely that we don't install all the JEE tooling from Eclipse by default anymore. You can install those parts via the `Install New Software` dialog, select the main Eclipse update site, and then look into the `Web, XML, Java EE and OSGi Enterprise Development` category to install the parts (probably the `Java EE` and `Java Web` components).
> 
> Hope this helps!

yes this works now Thanks
