### ISSUE TITLE
Facing issue while importing, creating the maven project.

### ISSUE THREAD

**Issue by sunkudinesh9** [spring-projects/sts4#603]
While i am creating are importing the maven project into the STS getting the below error.

**Errors occurred during the build.
Errors running builder 'Maven Project Builder' on project 'ProjectName'.
org/apache/commons/compress/parallel/InputStreamSupplier**

![image](https://user-images.githubusercontent.com/45383132/71815046-33cc0580-30a4-11ea-80a7-af731da11255.png)
![Capture](https://user-images.githubusercontent.com/45383132/71815076-48a89900-30a4-11ea-9f7e-637f45c3f7e5.PNG)

**Comment by sunkudinesh9** [comment]
Hi Team, 

Thanks all, My Issue got solved.

**Comment by martinlippert** [comment]
Thanks @sunkudinesh9 for letting us know and closing the item here. If you want to, please feel free to share the solution with the community here, so that others could find that solution here... :-)
