### ISSUE TITLE
hide projects without a main class from boot dashboard automatically

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#605]
**Expected Behavior**

The boot dashboard should hide projects that don't have a main class automatically. It doesn't really make a lot of sense to show a project in the boot dashboard that you can't run.

**Current Behavior**

All projects with Spring Boot on their classpath are shown and there is no filter in place to hide projects that don't have a main class.

**Solution**

We should add a filter that is activated by default to hide projects that don't have a main class. We need to take care to avoid any expensive analysis here. So it might be a challenge to actually find out whether a project has a main class or not, so we should be careful with regards to performance and UI-blocking behavior when implementing this.

**Comment by sukangfu** [comment]
Great, looking forward to this improvement.

**Comment by martinlippert** [comment]
@BoykoAlex already implemented this additional filter for the boot dashboard for the next release, so closing this item already.
