### ISSUE TITLE
Multiple Cursor for Editing

### ISSUE THREAD

**Issue by Abdullah8006** [spring-projects/sts4#610]
The current way to edit multiple lines in STS 4 is by using multi code block edit (Shift + Alt + A).
The problem with the current way of multi line editing is that it doesn't work when the different lines are not aligned vertically. 

In other words there is no multi cursor edit functionality.

Is there any way we can using multiple cursors, not necessarily vertically aligned, in Spring Tool Suite 4?

I am using the following STS build

**Spring Tool Suite 4** 

**Version: 4.6.0.RELEASE**
**Build Id: 202003181317**

**Comment by martinlippert** [comment]
@Abdullah8006 I am not aware of a possibility in Eclipse to have something like multi-cursor editing (beyond this multi-selection edit after you inserted a content-assist or template proposal which allows you to jump between edit sections using tab and changing the value at multiple places at the same time).

If you can describe in more detail what exactly you are looking for and how that should behave from the usage point of view, I would suggest to raise an enhancement request directly at Eclipse via: https://bugs.eclipse.org/bugs/enter_bug.cgi?product=Platform, select the `Text` component, and describe your enhancement proposal.
