### ISSUE TITLE
Boot Dash: flexible and configurable filters

### ISSUE THREAD

**Issue by 2019-05-10** [spring-projects/sts4#614]
There's not much one can do to manage the projects shown in Boot Dash:
a) the three hard coded (an not very intuitive) entries in the "Filters" menu
b) the unexpected checkbox in Run Configurations (at least for me, currently not working)

In a) I'd expect to be able to at least select projects not to be shown, or even the possibility to define expressions to match project names. 
As for b),  that may be a nice-to-have if you fiddle with the Run Configuration -- but certainly not the place where I'd look for it, especially for projects that are not supposed to be run at all (see #605 for a similar sentiment).

**Comment by martinlippert** [comment]
@BoykoAlex The new filters dialog looks good to me in general, but I would like to get a few little improvements into it... :-) (and therefore re-opening this):

- reduce the default size of the dialog, probably we should choose the same size as the filters dialog from the package explorer
- add a checkbox to enable the regex-match filter (like in the package explorer)
- change the regex pattern to hide projects that match the regex, not "show only projects that match"
- add "select all" and "deselect all" buttons
- remove the title section saying "select filters" from the dialog and have a window title instead
- put the filters menu item in the view dropdown menu into its own "section", surrounded by separators (after live data connections, before (Re)start items).

**Comment by BoykoAlex** [comment]
@martinlippert Here it is:
![Screen Shot 2021-05-21 at 11 33 02](https://user-images.githubusercontent.com/6433390/119162475-6a4fb980-ba28-11eb-9f89-a601c8325d7e.png)

Will push this is within an hour unless i see more comments :-)

**Comment by BoykoAlex** [comment]
Fixed with 9cc82fd598ada23e9cd83f1fe9f85e168036df76
