### ISSUE TITLE
Live data highlights disapearing after closing and reopening editor

### ISSUE THREAD

**Issue by kdvolder** [spring-projects/sts4#616]
**Describe the bug**

The 'green background highlight' indication for a live hover site sometimes isn't showing.

**To Reproduce**

1. Create a sample boot app using 'new spring starter' with 'web' and 'actuator' starters.
2. open application.properties
3. open main application class
4. start the boot app from boot dashboard.

=> observe the green highlight shows properly

5. close the java editor with the main class
6. re-open the main class

=> green highlight is gone.

Note: it is possible to enable codelenses support and do the same scenario again. The result is more or less the same... however while the 'green highlight' doesn't come back on re-open, the code lenses do.

**Comment by BoykoAlex** [comment]
Fixed with e4bffe7976ba712c394193cc680a577e662a4053
