### ISSUE TITLE
Maven / Parent artifacts are not resolved from Eclipse workspace

### ISSUE THREAD

**Issue by eliasbalasis** [spring-projects/sts4#617]
Importing a group of Maven repositories produces the following error:

`Non-resolvable parent POM for mygroup:myproject:<version>: Could not find artifact mygroup:root:pom:<version> and 'parent.relativePath' points at wrong local POM
`

**To Reproduce**

Use Spring Tools Suite 4.10.0 and clone the following repositories:

https://github.com/eliasbalasis/eclipse-m2e-bug-569907-root
https://github.com/eliasbalasis/eclipse-m2e-bug-569907-tools
https://github.com/eliasbalasis/eclipse-m2e-bug-569907-parent
https://github.com/eliasbalasis/eclipse-m2e-bug-569907-project

Then import the cloned repositories as Maven projects in the same order.

You will notice that even though the different Maven roots are detected and resolved by STS the error "Non-resolvable parent POM" is either already present or gets produced as soon as the pom.xml files are opened with the Maven editor.

This relates to https://github.com/eclipse-m2e/m2e-core/issues/152

**Comment by martinlippert** [comment]
As mentioned in https://github.com/eclipse-m2e/m2e-core/issues/152 this seems to be related to https://github.com/eclipse/lemminx-maven/issues/77.

To avoid going into circles here, let me explain this a bit further. The Spring Tools 4 for Eclipse distribution comes with the Wild Web Developer components pre-installed, including the XML language server and its connection to m2e (lemminx-maven). Therefore, whenever you open a `pom.xml` file in Spring Tools 4 for Eclipse, the XML language server will kick-in and try to do some work, resolve dependencies, etc.  That seems to what is causing the problem to be created, therefore this might be an occurrence of https://github.com/eclipse/lemminx-maven/issues/77.

If you install Spring Tools 4 components via the Marketplace into a plain Eclipse installation, the Wild Web Developer components will not be installed automatically, therefore you don't run into that issue. To double check, you could install the Wild Web Developer extensions into a plain Eclipse install and see if the problem appears (without the Spring Tools 4 components). My guess is that the problem will appear.

A simple workaround for this in the Spring Tools 4 for Eclipse distribution is to disable the `XML Language Server` in the `Preferences -> Language Servers` list.

I am closing this one here and add an additional comment to the m2e issue to explain this findings.
