### ISSUE TITLE
Maven repository is polluted with not existing dependencies.

### ISSUE THREAD

**Issue by picpicpic** [spring-projects/sts4#618]
**Describe the bug**
In a pom.xml file, each time we type a character in a version tag, a dependency lookup is done without waiting for the user to save the file.
As a result, the Maven local repository is polluted with lot of useless folders : 
```
.
└── junit
    ├── 3.8.1
    ├── 3.8.2
    ├── 4
    ├── 4.
    ├── 4.1
    ├── 4.13
    ├── 4.13.
    ├── 4.13.3
    ├── 4.13.3-
    ├── 4.13.3-S
    ├── 4.13.3-SN
    ├── 4.13.3-SNA
    ├── 4.13.3-SNAP
    ├── 4.13.3-SNAPS
    ├── 4.13.3-SNAPSH
    ├── 4.13.3-SNAPSHO
    └── 4.13.3-SNAPSHOT
```
This is problem occurs since the **STS 4.8.0**
In version **STS 4.7.2**, the lookup is done only when we save the file.

**Note :** This problem seems related to STS, it doesn't appear in a vanilla version of Eclipse **2021-03**.

**To Reproduce**
1. unzip a fresh version of STS 4.10
2. create a maven project ( simple one )
3. fill a groupid and an artifactid and click the finish button
4. open the pom.xml file
5. add a dependency eg : junit:junit:4.13.3-SNAPSHOT
6. take care to type the version number character per character ( no copy past and without saving the file )
each time you type a character of the version number, STS trigger a dependency lookup.
7. open your maven local repository ~/.m2/repository/junit/junit

**Sample**
Not sure if a sample is really needed here, this case is very easy to reproduce.

**Comment by martinlippert** [comment]
To me it looks like the XML language server support is causing this, so it should be reported against https://github.com/eclipse/lemminx-maven, I think.

**Comment by martinlippert** [comment]
Created this one here: https://github.com/eclipse/lemminx-maven/issues/213
