### ISSUE TITLE
Add SHA checksums for "Spring Tools 4 for Eclipse" downloads

### ISSUE THREAD

**Issue by dejan2609** [spring-projects/sts4#623]
Add SHA checksums for "Spring Tools 4 for Eclipse" downloads (all distributions: Windows, Mac and Linux).

Related issue: https://github.com/spring-io/sagan/issues/174 **_add links to md5 and sha checksums to STS/GGTS download page_**

I guess you could mimic Eclipse (and add links to SHA checksums to a https://spring.io/tools page).

![image](https://user-images.githubusercontent.com/19467899/114105734-9a565980-98cd-11eb-8e52-d2fd84448961.png)

**Comment by martinlippert** [comment]
Created a new issue for this here:
https://github.com/spring-io/sagan/issues/1028

Closing this one here as a duplicate.

**Comment by dejan2609** [comment]
Thank you @martinlippert ! I will close this issue as a duplicate now.
