### ISSUE TITLE
nothing shown in VS Code Outline view

### ISSUE THREAD

**Issue by Eskibear** [spring-projects/sts4#627]
**Describe the bug**
Spring Boot Tools extension provides nothing in outline view. 

![image](https://user-images.githubusercontent.com/2351748/114983348-1864c280-9ec3-11eb-8f1a-50e010e3c2d8.png)

**To Reproduce**
Open project [spring-petclinic](https://github.com/spring-projects/spring-petclinic), file `PetController.java`.

**Expected Behavior**
Previously it was like below:
![image](https://user-images.githubusercontent.com/2351748/114983163-d89ddb00-9ec2-11eb-9747-b5577c757fbf.png)

**Additional Info**
OS: Windows 10
VS Code: 1.55.2
Java Extension: 0.77.0
Spring Boot Tools: 1.25.1
JDK: 11.0.8.10-hotspot

Other features of this extension seem to be working well. No suspicious log from output window.

**Comment by martinlippert** [comment]
Here is what I observe when trying this:

- the outline doesn't show any symbols from the Spring Tools as long as you keep the editor active/open for the file that was open while the tooling started up in the background
- if you switch to another Java file, the symbols show up in the outline
- if you switch back to the same file that you had open in the first place, the symbols show up again

Can you verify this? Do you see the same behavior? Or do the symbols never show up in the outline view for you?

**Comment by Eskibear** [comment]
> if you switch to another Java file, the symbols show up in the outline
if you switch back to the same file that you had open in the first place, the symbols show up again

No, that's not my case. I switch between files, close and re-open, Spring-specific outline just doesn't show. 

Below is a quick example I just tried, please let me know if any detailed information is needed.
![spring-outline](https://user-images.githubusercontent.com/2351748/116224617-6dd28680-a783-11eb-8dd7-cb7ad2d1986b.gif)

**Comment by martinlippert** [comment]
Hm, okay, that is indeed different - and weird. Do the symbols show up when you search for symbols in workspace?
And can you enable the log files for the language server (`"spring-boot.ls.logfile": "<somepath>/vscode-logs"`)? Would be interesting to see what the Spring language server says here...

**Comment by Eskibear** [comment]
> Do the symbols show up when you search for symbols in workspace?

I just tested on my local Windows machine, no they didn't show.  

PS: The first screenshot above https://github.com/spring-projects/sts4/issues/627#issuecomment-827486700 was tried on Codespaces (vscode-remote), and after I configured spring-boot.ls.logfile and reloaded the window serveral times just now, the issue was gone. So I switched to my local machine, and the same issue occurred, see below for more details.

![spring-outline-local](https://user-images.githubusercontent.com/2351748/116366915-5eae1000-a839-11eb-95ff-2fc6717d351b.gif)

**Logs here**: [spring.log](https://github.com/spring-projects/sts4/files/6390020/spring.log)

**Comment by martinlippert** [comment]
Thanks for attaching the log file, that helps. It looks like the mechanism between the Java Language Server and the Spring Boot Language Server to send over information about projects and their class paths didn't happen here. Could this be related to https://github.com/spring-projects/sts4/issues/628?

Somehow it seems that the Spring Boot Language Server doesn't receive any project/classpath information from the Java Language Server...

**Comment by BoykoAlex** [comment]
Fixed with 4f007de1bd710463d9bef8c89456d73b4d4fcb5f
