### ISSUE TITLE
Extension fails to use java.home property

### ISSUE THREAD

**Issue by kecoliva** [spring-projects/sts4#629]
**Describe the bug**
I'm getting this error:

Spring Tools Language Server requires Java 11 or higher to be launched. Current Java C:\Program Files\Java\jdk1.8.0_281\bin\java.exe. (Note Java 8 can still be used in your own projects. Java 11 is only required to launch the Spring Tools Language Server process)

The problem is I've already set vscode's java.home property to point to my Java 11 installation but I noticed that the extension is using my computer's environment variable JAVA_HOME which is pointing to Java 8.

**To Reproduce**
1. Install Spring Boot Tools
2. Set computer environment variable JAVA_HOME to point to Java 8
3. Set vscode's java.home property to point to Java 11
4. Open a simple Spring Boot project

If this is how the extension should behave, is it possible to have it as a feature? To use vscode's java.home property when looking for Java 11 instead of the computer's environment variable JAVA_HOME

**Comment by BoykoAlex** [comment]
There is a preference under `Boot-Java Config` Java > Ls: Home, json property key `"spring-boot.ls.java.home"` specifically for this purpose of launching Spring Boot LS on a JVM different from your system java home. Use this preference and everything should work
