### ISSUE TITLE
SpringToolSuite4.app quit unexpectedly

### ISSUE THREAD

**Issue by shriramvaidhyanathan** [spring-projects/sts4#630]
The error details can be found below. I shutdown my Mac M1 mini yesterday and today when I started it and ran SpringToolSuite. I encountered this issue.

Process:               SpringToolSuite4 [820]
Path:                  /Applications/SpringToolSuite4.app/Contents/MacOS/SpringToolSuite4
Identifier:            org.springframework.boot.ide.branding.sts4
Version:               ???
Code Type:             X86-64 (Translated)
Parent Process:        ??? [1]
Responsible:           SpringToolSuite4 [820]
User ID:               501

Date/Time:             2021-04-23 15:03:25.348 -0400
OS Version:            macOS 11.2.3 (20D91)
Report Version:        12
Anonymous UUID:        A99A0EF6-7B18-BE54-570D-E7A12E90D5B6

Time Awake Since Boot: 200 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       EXC_ARM_BREAKPOINT at 0x00007ffdffcd136c (brk 1)
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Trace/BPT trap: 5
Termination Reason:    Namespace SIGNAL, Code 0x5
Terminating Process:   exc handler [820]

Application Specific Information:
rosetta error: /var/db/oah/a4e74257fed99be09de27acd5decf28c2a9f03dcfa2aecfcbf2aa9e38e7a9a36/91e34116e3332cd4f40a28b161fa00e0781e4154e2a22c02c95acb1418fd07c8/SpringToolSuite4.aot: attachment of code signature supplement failed: 3
 

Thread 0 Crashed:
0   runtime                       	0x00007ffdffcd136c 0x7ffdffc7e000 + 340844
1   runtime                       	0x00007ffdffcd1448 0x7ffdffc7e000 + 341064
2   runtime                       	0x00007ffdffc8c8d8 0x7ffdffc7e000 + 59608
3   runtime                       	0x00007ffdffc8de44 0x7ffdffc7e000 + 65092
4   runtime                       	0x00007ffdffc8d908 0x7ffdffc7e000 + 63752
5   runtime                       	0x00007ffdffc7fc60 0x7ffdffc7e000 + 7264
6   dyld                          	0x0000000100397000 0x100397000 + 0

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000003   x2: 0x000000000000003c   x3: 0x000000000000002c
    x4: 0x0000000000000303   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000228
    x8: 0x00007ffdffcfc000   x9: 0x0000000000000000  x10: 0x000000020480eaa6  x11: 0x00007ffdffce8530
   x12: 0x00007ffdffce8520  x13: 0x00007ffdffce38d3  x14: 0x0000000000000020  x15: 0x00000000ffffffff
   x16: 0xffffffffffffffe1  x17: 0x00007ffdffcd5e14  x18: 0x000000020481112b  x19: 0x000000020480e9c0
   x20: 0x00000002048117d8  x21: 0x0000000000378000  x22: 0x0000000000000203  x23: 0x0000000000378000
   x24: 0x0000000000000003  x25: 0x0000000000000001  x26: 0x0000000204810c30  x27: 0x0000000000000203
   x28: 0x000000000036c000   fp: 0x000000020480f9d0   lr: 0xa2367ffdffcd1364
    sp: 0x000000020480e9b0   pc: 0x00007ffdffcd136c cpsr: 0x60000000
   far: 0x00007ffdffcfd000  esr: 0xf2000001

Binary Images:
       0x100397000 -        0x100432fff  dyld (832.7.3) <0D4EA85F-7E30-338B-9215-314A5A5539B6> /usr/lib/dyld
    0x7ffdffc7e000 -     0x7ffdffcf1fff +runtime (203.30) <C98E75A6-BDC8-3D5C-B95B-6422005E96D8> /Library/Apple/*/runtime

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 157
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1324K resident=0K(0%) swapped_out_or_unallocated=1324K(100%)
Writable regions: Total=18.6M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=18.6M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8176K        1 
VM_ALLOCATE                       10.3M        1 
VM_ALLOCATE (reserved)              52K        1         reserved VM address space (unallocated)
__DATA                             272K        4 
__DATA_CONST                        32K        1 
__LINKEDIT                         272K        4 
__TEXT                            1088K        2 
mapped file                        4.7G        8 
===========                     =======  ======= 
TOTAL                              4.7G       23 
TOTAL, minus reserved VM space     4.7G       23 

Model: Macmini9,1, BootROM 6723.81.1, proc 8:4:4 processors, 8 GB, SMC 
Graphics: kHW_AppleM1Item, Apple M1, spdisplays_builtin
Memory Module: lp_ddr4
AirPort: spairport_wireless_card_type_airport_extreme, wl0: Dec 31 2020 21:39:03 version 18.20.222.20.7.8.104 FWID 01-1b2645bc
Bluetooth: Version 8.0.3d9, 3 services, 18 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
USB Device: USB 3.1 Bus
USB Device: USB 3.1 Bus
![Screen Shot 2021-04-23 at 3 06 22 PM](https://user-images.githubusercontent.com/83027472/115918465-8a9a5180-a445-11eb-952b-71f5c946ee4d.png)

USB Device: USB 3.0 Bus
USB Device: Microsoft® 2.4GHz Transceiver v8.0
Thunderbolt Bus: Mac mini, Apple Inc.
Thunderbolt Bus: Mac mini, Apple Inc.

**Comment by martinlippert** [comment]
Very hard to say what is going on here. Does this happen every time you start the IDE? Or just once?

**Comment by martinlippert** [comment]
@shriramvaidhyanathan 👆

**Comment by shriramvaidhyanathan** [comment]
Yes. It happened continuously for a few days. So, I did not use spring for a almost week or two and then last Friday when I opened it again to check to my luck and it started working again.

**Comment by martinlippert** [comment]
We, of course, hope to ship an M1-native version soon and I hope that this will also reduce crashes like this one here.

**Comment by martinlippert** [comment]
And thanks for coming back to this and for letting us know that this works again.

**Comment by satyampandeygit** [comment]
@martinlippert I am facing the same issue every time I open STS it is showing this error. If I install the new version it works for some time but it happens again after some time.

**Comment by martinlippert** [comment]
@satyampandeygit Are you running on an M1 machine as well? You could try the latest nightly build of STS4 for the M1 machines from here: http://dist.springsource.com/snapshot/STS4/nightly-distributions.html

But you would need to configure it to use the M1-native JDK on your machine, preferably the Azul OpenJDK builds for M1. Can you give that a try?

**Comment by satyampandeygit** [comment]
Yes, I am running STS4 on the M1 machine. I will try the above steps and will revert asap. thanks.

**Comment by acttosma** [comment]
sudo codesign --force --deep --sign - /Applications/SpringToolSuite4.app

Problem solved, I do NOT know why this happens.

**Comment by codermvn** [comment]
> sudo codesign --force --deep --sign - /Applications/SpringToolSuite4.app
> 
> Problem solved, I do NOT know why this happens.

this worked for my on M1 MacBook Pro

**Comment by amanFluke** [comment]
> sudo codesign --force --deep --sign - /Applications/SpringToolSuite4.app
> 
> Problem solved, I do NOT know why this happens.

awesome, this worked for my macOS Monterey as well, saved a ton of time. Many thanks!

**Comment by codergauravsharma** [comment]
> sudo codesign --force --deep --sign - /Applications/SpringToolSuite4.app
> 
> Problem solved, I do NOT know why this happens.

This worked for me as well, MBA2017

**Comment by unni2709** [comment]
> sudo codesign --force --deep --sign - /Applications/SpringToolSuite4.app
> 
> Problem solved, I do NOT know why this happens.

Worked for macOS Catalina. Thank you.

**Comment by Raghav-006** [comment]
Thanks, Worked on the macOS Monterey(MBA 2017). It replaces the existing signature.

**Comment by coddojrponce** [comment]
Thank you !! Worked like a charm , quick explanation for those wondering what it does https://kubadownload.com/news/codesign-sign-app/

**Comment by gaurichoudhari95** [comment]
> > sudo codesign --force --deep --sign - /Applications/SpringToolSuite4.app
> > Problem solved, I do NOT know why this happens.
> 
> this worked for my on M1 MacBook Pro

**Comment by gaurichoudhari95** [comment]
but after that which password we need to enter??

**Comment by gaurichoudhari95** [comment]
they've ask to enter password after that. which password they required??
