### ISSUE TITLE
Rename BootLanguagServerBootApp to BootLanguageServerBootApp

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/sts4#631]
As discussed with @kdvolder there's a typo in the name of `BootLanguagServerBootApp` that's visible when looking at the output from `jps` and the like. It would be good if it could be renamed to `BootLanguageServerBootApp`.

**Comment by martinlippert** [comment]
Thanks for pointing us at this @wilkinsona, much appreciated.
Fixed in https://github.com/spring-projects/sts4/commit/07459c6f5ed72d5865e6c48d68bec405a78d2e6f.
