### ISSUE TITLE
language server processes doesn't get shutdown properly in VSCode

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#636]
**Describe the bug**
Dave observed a number of zombie language server processes, probably after using VSCode. The thread dumps of the VSCode processes look okay, nothing serious in there, but the shutdown process must have gone wrong somewhere.

**To Reproduce**
We need to investigate this, use VSCode for a while and see if language server processes are shutdown properly or not.

**Comment by andriassundskard** [comment]
Happens to me on MacOS 11.3.1 and VSCode 1.56.2. I start my VSCode using this command: `code --user-data-dir ~/.vscode_MyApp/user-data --extensions-dir ~/.vscode_MyApp/exts MyApp.code-workspace`

MyApp.code-workspace
`{"folders":[{"path":"."}],"settings":{"[yaml]":{"editor.insertSpaces":true,"editor.detectIndentation":false,"editor.tabSize":2,"editor.autoIndent":"advanced","editor.quickSuggestions":{"other":true,"comments":false,"strings":true}},"[java],[xml]":{"editor.suggest.snippetsPreventQuickSuggestions":false,"editor.tabSize":4,"editor.insertSpaces":false,"editor.detectIndentation":false},"java.configuration.updateBuildConfiguration":"automatic","java.completion.enabled":true,"java.format.enabled":true,"java.format.settings.profile":"GoogleStyle","java.format.settings.url":"/eclipse-java-google-style.xml","java.autobuild.enabled":true,"java.saveActions.organizeImports":true,"gradle.autoDetect":"on","editor.autoIndent":"full","spring.initializr.defaultLanguage":"Java","files.exclude":{"**/.classpath":true,"**/.project":true,"**/.settings":true,"**/.factorypath":true,"**/.gradle":true},"java.dependency.packagePresentation":"flat"},"extensions":{"recommendations":["vscjava.vscode-java-pack","GabrielBB.vscode-lombok","richardwillis.vscode-gradle","alphabotsec.vscode-eclipse-keybindings","vscjava.vscode-spring-initializr","Pivotal.vscode-spring-boot","vscjava.vscode-spring-boot-dashboard","ms-azuretools.vscode-docker","adamhartford.vscode-base64","redhat.vscode-xml"]},"launch":{"configurations":[{"type":"java","name":"Launch MyApp","request":"launch","mainClass":"com.example.MyApp","projectName":"MyApp"}],"compounds":[]}}`

Running `ps ax | grep java | grep language-server` after closing VSCode gives this:

> 3724   ??  S      0:11.61 /usr/bin/java -cp /Users/username/.vscode_MyApp/exts/pivotal.vscode-spring-boot-1.25.1/language-server/BOOT-INF/classes:/Users/username/.vscode_MyApp/exts/pivotal.vscode-spring-boot-1.25.1/language-server/BOOT-INF/lib/* -Dspring.lsp.client-port=45556 -Dserver.port=45556 -Dsts.lsp.client=vscode -Dsts.log.file=/dev/null -XX:TieredStopAtLevel=1 -Dspring.config.location=file:/Users/username/.vscode_MyApp/exts/pivotal.vscode-spring-boot-1.25.1/language-server/BOOT-INF/classes/application.properties org.springframework.ide.vscode.boot.app.BootLanguagServerBootApp

**Comment by andriassundskard** [comment]
[exthost.log](https://github.com/spring-projects/sts4/files/6495653/exthost.log)
I managed to get some kind of debug log out of the system. Hopefully it is of some help!

**Comment by martinlippert** [comment]
@andriassundskard Thanks for the additional details, much appreciated. How did you get these debug log output?

**Comment by andriassundskard** [comment]
I enabled logging through the properties file: `~/.vscode_MyApp/exts/pivotal.vscode-spring-boot-1.25.1/language-server/BOOT-INF/classes/application.properties`

I removed the # from these lines and restarted VSCode. 
`
#logging.level.org.springframework.ide.vscode.commons.languageserver.util.SimpleLanguageServer=debug
#logging.level.org.springframework.ide.vscode.boot.java.utils.SpringIndexerJava=debug
#logging.level.org.springframework.ide.vscode.boot.app.SpringSymbolIndex=debug
#logging.level.org.springframework.ide.vscode.commons.boot.app.cli.SpringBootApp=off
`

**Comment by martinlippert** [comment]
Those log levels are for the Spring Boot language server itself, but the `exthost.log` output seems to be from VSCode directly, not the Spring Boot language server.

**Comment by andriassundskard** [comment]
I found, that there is a `logs` folder in `~/.vscode_MyApp/user-data/`. After enabling the Spring Boot logging through the `application.properties` file I realized, that some log entries ended up in the `exthost.log` file located in `~/.vscode_MyApp/user-data/logs/yyyyMMddTHHmmss/exthost1` folder.

**Comment by Artur-** [comment]
I guess this is also what I see on Big Sur

```
$ ps ax|grep BootLanguagServerBootApp|wc -l
      48
```

**Comment by zlargon** [comment]
I also see this on my mac.

Mac: macOS Catalina 10.15.7
VSCode: 1.56.2 (Universal)

```bash
$ ps aux | grep BootLanguagServerBootApp

chhuang          22530   0.0  0.1 10439568  13348   ??  S     2:14PM   0:18.97 /Users/chhuang/.sdkman/candidates/java/11.0.11-zulu/bin/java -cp /Users/chhuang/.vscode/extensions/pivotal.vscode-spring-boot-1.25.1/language-server/BOOT-INF/classes:/Users/chhuang/.vscode/extensions/pivotal.vscode-spring-boot-1.25.1/language-server/BOOT-INF/lib/* -Dspring.lsp.client-port=45557 -Dserver.port=45557 -Dsts.lsp.client=vscode -Dsts.log.file=/dev/null -XX:TieredStopAtLevel=1 -Dspring.config.location=file:/Users/chhuang/.vscode/extensions/pivotal.vscode-spring-boot-1.25.1/language-server/BOOT-INF/classes/application.properties org.springframework.ide.vscode.boot.app.BootLanguagServerBootApp
chhuang           8964   0.0  0.1 10590152  16252   ??  S     9:42AM   0:38.26 /Users/chhuang/.sdkman/candidates/java/11.0.11-zulu/bin/java -cp /Users/chhuang/.vscode/extensions/pivotal.vscode-spring-boot-1.25.1/language-server/BOOT-INF/classes:/Users/chhuang/.vscode/extensions/pivotal.vscode-spring-boot-1.25.1/language-server/BOOT-INF/lib/* -Dspring.lsp.client-port=45556 -Dserver.port=45556 -Dsts.lsp.client=vscode -Dsts.log.file=/dev/null -XX:TieredStopAtLevel=1 -Dspring.config.location=file:/Users/chhuang/.vscode/extensions/pivotal.vscode-spring-boot-1.25.1/language-server/BOOT-INF/classes/application.properties org.springframework.ide.vscode.boot.app.BootLanguagServerBootApp
chhuang           8869   0.0  0.1 10594272  16452   ??  S     9:41AM   0:39.97 /Users/chhuang/.sdkman/candidates/java/11.0.11-zulu/bin/java -cp /Users/chhuang/.vscode/extensions/pivotal.vscode-spring-boot-1.25.1/language-server/BOOT-INF/classes:/Users/chhuang/.vscode/extensions/pivotal.vscode-spring-boot-1.25.1/language-server/BOOT-INF/lib/* -Dspring.lsp.client-port=45556 -Dserver.port=45556 -Dsts.lsp.client=vscode -Dsts.log.file=/dev/null -XX:TieredStopAtLevel=1 -Dspring.config.location=file:/Users/chhuang/.vscode/extensions/pivotal.vscode-spring-boot-1.25.1/language-server/BOOT-INF/classes/application.properties org.springframework.ide.vscode.boot.app.BootLanguagServerBootApp
chhuang           7237   0.0  0.1 10441616  13516   ??  S     9:17AM   0:31.23 /Users/chhuang/.sdkman/candidates/java/11.0.11-zulu/bin/java -cp /Users/chhuang/.vscode/extensions/pivotal.vscode-spring-boot-1.25.1/language-server/BOOT-INF/classes:/Users/chhuang/.vscode/extensions/pivotal.vscode-spring-boot-1.25.1/language-server/BOOT-INF/lib/* -Dspring.lsp.client-port=45556 -Dserver.port=45556 -Dsts.lsp.client=vscode -Dsts.log.file=/dev/null -XX:TieredStopAtLevel=1 -Dspring.config.location=file:/Users/chhuang/.vscode/extensions/pivotal.vscode-spring-boot-1.25.1/language-server/BOOT-INF/classes/application.properties org.springframework.ide.vscode.boot.app.BootLanguagServerBootApp
...
```

**Comment by martinlippert** [comment]
I think I can reproduce this on my local machine, seems a more general issue here. Will investigate.

**Comment by martinlippert** [comment]
I implemented some improvements here, so feel free to manually install the latest CI build as VSIX file from here: http://dist.springsource.com/snapshot/STS4/nightly-distributions.html - and let me know if this is better now.

I am sure there are still a few cases in which the process is not stopped accordingly. If you still observe dangling BootLanguageServerApp processes, it would be great if you could share some details how you got to that point, so that I can follow the steps precisely to reproduce this.

**Comment by andriassundskard** [comment]
Seems to be working now. I'm not sure if it is a problem, but with this new version there is no `org.springframework.ide.vscode.boot.app.BootLanguagServerBootApp` in my `ps ax` list while VSCode is running. Plugin seems to work as intended.

**Comment by martinlippert** [comment]
@andriassundskard The name has changed, we fixed the typo, it is now `BootLanguageServerBootApp`

**Comment by andriassundskard** [comment]
Ok. `ps ax | grep BootLanguageServerBootApp` is also empty, so it seems that your solution works!

**Comment by martinlippert** [comment]
@andriassundskard great to hear that and thanks for checking it out. Much appreciated. Closing this now.

**Comment by merlyncheung** [comment]
Same issue here on the new mac with M1 Chip. I am currently using the Big Sur 11.4. As I observed, the Vscode Plugin will create more than one java process after times of open and close the Vscode Editor. 
<img width="1068" alt="Screenshot 2021-06-10 at 11 21 06 am" src="https://user-images.githubusercontent.com/52489415/121459730-5e7b6580-c9de-11eb-86c7-8a4921e8d9cb.png">
