### ISSUE TITLE
[vscode-concourse] Add support form missing attributes to `GitGetParams` schema

### ISSUE THREAD

**Issue by mikemimik** [spring-projects/sts4#64]
There have been some iterations to the resources in the current release of concourse. Git resources now has a `clean_tags` param as an example. How do we update the validation inside the extension to account for this. Right now I have a bunch of "errors" in my pipeline files because we're using these new parameters that aren't accounted for.

**Comment by kdvolder** [comment]
You could try doing a PR, but its relatively easy for me to update stuff like this (may be harder for someone not familiar with my messy code :-).

The easiest thing for you to do would be the raise one or more tickets to let me know precisely what's missing from the schema and it will be added probably within a day or two and a snapshot build will be available for you to try it out use it.

By this ticket I gather you like to add 'clean_tags' to the git resource schema. But it sounds there's other things you found missing?

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Kris De Volder:) 

Comparing schema for GitGetParams to current docs. All these are missing.

-  `submodule_recursive`
- `submodule_remote`
-  `clean_tags`

**Comment by kdvolder** [comment]
I dleivered a fix for the missing properties as listed above. You can download a snapshot from here: http://dist.springsource.com/snapshot/STS4/nightly-distributions.html instructions on how to use the snapshots (instaill a .vsix file) are in the README for the vscode extension.

If there are other things that need updating, let me know by raising tickets and I'll fix them ASAP.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Alex Boyko:) 

Verified with release Atom concourse package 0.4.0 from the Atom marketplace
