### ISSUE TITLE
STS can't find JpaRepository method with loose coupling technique

### ISSUE THREAD

**Issue by RobbiNespu** [spring-projects/sts4#640]
**Describe the bug**
STS couldn't find JpaRepository method . Originally I use InteliJ but i want to share this project with other and s/he use STS. The project is WIP but STS could t found the method (from RestController) as screenshot below:

![image](https://user-images.githubusercontent.com/3077875/119305206-008b1600-bc9b-11eb-8714-fddc55931d1a.png)

At first I thought it maybe InteliJ mess the path class or something, so I created all files from scratch using STS.. but I getting same issue. Weirdly when I press run on Boot dashboard, it run!

![image](https://user-images.githubusercontent.com/3077875/119305587-814a1200-bc9b-11eb-8491-296b495c5f19.png)

```
Spring Tool Suite 4 

Version: 4.10.0.RELEASE
Build Id: 202103111225
```

Could be issue to read loose coupling technique I applied on services?
**To Reproduce**
May use my code here https://github.com/RobbiNespu/ESS/releases/tag/v0.0.2 

**Sample**
![image](https://user-images.githubusercontent.com/3077875/119305867-e3a31280-bc9b-11eb-8381-915036a1693b.png)

**Comment by martinlippert** [comment]
It looks like the class for `Subjects` (something from your domain objects, I guess) doesn't have the used getter methods implemented. A wild guess here might be: Do you use something like Lombok for that and didn't install the Lombok extension for Eclipse into your Spring Tools 4 for Eclipse distribution?

If you don't use anything like that to auto-generate getter methods, I would recommend to create a small sample project that reproduces the issue and attach that here, so that we can take a deeper look.

**Comment by RobbiNespu** [comment]
Ah you are right.. I never thought lombok need to be glue with IDE first.. 
![Screenshot_20210526_074439](https://user-images.githubusercontent.com/3077875/119582430-17df1600-bdf7-11eb-9a0d-f7fb0978cbb0.png)

![Screenshot_20210526_074549](https://user-images.githubusercontent.com/3077875/119582457-20375100-bdf7-11eb-9c5d-b0fe86704ed8.png)

![Screenshot_20210526_075146](https://user-images.githubusercontent.com/3077875/119582522-41983d00-bdf7-11eb-977e-07631df4c923.png)

after install lombok on IDE, go to project (package explorer), maven > update project.. then the IDE recognize all method that not recognize before.

So it not STS issue. Thanks for informative information @martinlippert .I will close this issue

**Comment by martinlippert** [comment]
@RobbiNespu Glad to hear that this solved the issue.
