### ISSUE TITLE
Dynamic Web Project missing in STS 4.10

### ISSUE THREAD

**Issue by Osolemio44** [spring-projects/sts4#641]
I am using Spring tool Suite 4.10 and there is no option to create Dynamic Web project.
i already tried this https://github.com/spring-projects/sts4/issues/96#issuecomment-484522744 but it didnt worked. 
I installed the  m2e-wtp from http://download.eclipse.org/releases/2019-09/  and it didnt work. also tried withthe sts4/tools/latest and didnt work too.
How can i fix this ?

**Comment by martinlippert** [comment]
The Spring Tools 4 for Eclipse distribution does not contain those features by default, but you can install them into an existing Spring Tools 4 distribution by going to the `Install New Software` dialog, select the main Eclipse download repository, and install the `Eclipse Java EE Developer Tools` feature from it.

Assuming you have the latest version of the Spring Tools 4 distribution, the main Eclipse repo (`https://download.eclipse.org/releases/latest`) should work for that.

**Comment by Osolemio44** [comment]
Hi. youre solution doesnt work
![image](https://user-images.githubusercontent.com/55595063/119635754-45868800-be14-11eb-9d2b-1c0bf12dade8.png)
