### ISSUE TITLE
spring boot language server causing long waits for Java outline view when running in lightweight mode

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#642]
**Describe the bug**
I am running the Java language support in Lightweight launch mode only. When I open a Java file and there is no Spring Boot tooling enabled, the outline view will show Java content pretty quickly.

However, when I have the Spring Boot tooling enabled, it takes a long time until the outline content from the Java tooling gets populated.

My assumption is:
VS Code asks all the language servers for the symbols on the file. The Spring Boot tooling waits for a timeout before it returns, and VS Code is waiting for the language servers to return something before it shows the combined results.

**Comment by martinlippert** [comment]
@BoykoAlex My assumption (but I haven't verified this) is that this is related to the changes to wait for projects to get resolved. Any thoughts here?

**Comment by martinlippert** [comment]
We definitely need to solve this before we can ship those changes...

**Comment by BoykoAlex** [comment]
Likely to be related to work we've done to wait for symbols to show... We'll have a look at it.

**Comment by BoykoAlex** [comment]
Should be fixed with b2ebc43bc0d86709b94f664561f12d1a02c601cb
