### ISSUE TITLE
sts4 becomes not responding 

### ISSUE THREAD

**Issue by sj250381** [spring-projects/sts4#645]
whenever tried to search some files by using ctrl+H ..its get kind hanged.
Please suggest how much minimum RAM is required for the same

**Comment by martinlippert** [comment]
It would be great if you could provide more information what exactly you are running and steps are causing the slowdown and something not responding. What exactly are you using? The Spring Tools 4 for Eclipse distribution? On which OS?

In addition to that it would be great if you could capture a thread dump (using `jps` and `jstack` for the IDE process) while it is not responding, that can reveal useful information for identifying the problem.

**Comment by martinlippert** [comment]
Not having heard anything back here, so closing this issue now.
