### ISSUE TITLE
Little UX improvement for Tags Editor in the Properties View

### ISSUE THREAD

**Issue by MahatmaFatalError** [spring-projects/sts4#649]
**Expected Behavior**

In the spring boot properties view, the Tags field should be easily identifiable as an **editable** field.
Probably as it is for the Path field.

**Current Behavior**

It looks like a non-editable field. (Similar to URL field)
![grafik](https://user-images.githubusercontent.com/776825/122515337-96e9f780-d00d-11eb-93f1-513b2fc381d6.png)

**Context**
I did not notice that Tags are a thing that can be set in the IDE. Totally missed that feature.

**Comment by BoykoAlex** [comment]
Lets try a simple border around style text editor control. The only downside of it is not native focus highlight border when control has focus (there is no way around it unfortunately)

**Comment by BoykoAlex** [comment]
![Screen Shot 2021-08-24 at 16 09 28](https://user-images.githubusercontent.com/6433390/130682962-15cf7878-cb2a-4893-8d40-409920d89672.png)

**Comment by BoykoAlex** [comment]
Fixed with 478eabb6f1bb9742fef34625d4c2707e22c2ac2d and available in the nightly build via update site: https://dist.springsource.com/snapshot/TOOLS/sts4/nightly/e4.20
