### ISSUE TITLE
[vscode-concourse] missing params in extension

### ISSUE THREAD

**Issue by mikemimik** [spring-projects/sts4#65]
@kdvolder as you mentioned in #64 I have a list of two more missing params.

git-resource - put - params - `merge`: `Unknown property 'merge' for type 'GitPutParams'`

pipeline job - plan - task - `on_abort`: `Unknown property 'on_abort' for type 'TaskStep'`

I believe in combination with the others you noted in #64 are all the missing items I've encountered. Thanks so much for helping with this.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Kris De Volder:) 

Splitting this ticket in two in our internal tracker. This one is for fixing 'TaskStep' / `Step` schema.

**Comment by kdvolder** [comment]
Sibling ticket: https://www.pivotaltracker.com/story/show/159110430 for the `GitPutParams`.

Missing in `GitPutParams`:
- merge
- notes

have been added.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Kris De Volder:) 

The 'on_abort' attribute appears to be valid for any kind of step. See: https://concourse-ci.org/on-abort-step-hook.html#on_abort

It is also valid as a attribute on a Job itself. See:
https://concourse-ci.org/jobs.html#job-on-abort

**Comment by kdvolder** [comment]
Delivered fixes for all of the following:

- `on_abort`: added to `Job` and all `Step`
- `merge`: added to `GitPutParams`
- `notes`: added to `GitPutParams`
- Validation that `merge` and `rebase` in 'GitPutParams' should not both be defined.

Snapshot available for testing/use here: http://dist.springsource.com/snapshot/STS4/nightly-distributions.html

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Alex Boyko:) 

Verified with release Atom concourse package 0.4.0 from the Atom marketplace
