### ISSUE TITLE
Add file completion from classpath for @ContextConfiguration

### ISSUE THREAD

**Issue by gayanper** [spring-projects/sts4#650]
**Expected Behavior**
When trying to complete the location on @ContextConfiguration(locations = ".."), provide file completions for xml files from the classpath. Even though most of the configurations are moved to Annotation based configurations, there are some legacy application use xml files to boostrap the application and some tests which use xml files to define the configuration to use for different tests.

**Comment by ksankaranara-vmw** [comment]
Working on adding this feature

**Comment by BoykoAlex** [comment]
Merged with 992a7c742838a381443a5a86ed0327523b1f3086

**Comment by BoykoAlex** [comment]
Looks like I jumped the gun with this issue.

Still to fix missing proposals if the prefix starts with `/`

**Comment by ksankaranara-vmw** [comment]
Merged with [007ba15](https://github.com/spring-projects/sts4/commit/007ba15da2beefbee1550da874852d1d71e9ce4a)
