### ISSUE TITLE
Debugger: Non-ASCII string variables are shown wrongly - like concatenation of charcodes

### ISSUE THREAD

**Issue by IvankoB** [spring-projects/sts4#652]
Spring Tool Suite 4  Version: 4.11.0.RELEASE Build Id: 202106180608 OS: Windows 10, v.10.0, x86_64 / win32 Java vendor: Oracle Corporation Java runtime version: 15.0.2+7-27 Java version: 15.0.2

**Describe the bug**
---------------------------------------
ASCII strings as OK: 
"proxyma0certav.ru" --shown as--> "proxyma0certav.ru"

non-ASCII strings are wrong :  
"Проксенко Проксима Центавровна" --shown as--> "9F80BEBA81B5BDBABE09F80BEBA81B8BCB00A6B5BD82B0B280BEB2BDB0"

"Ташкентские подворотни, 1/2"  --shown as--> "A2B088BAB5BD8281BAB8B50BFBEB4B2BE80BE82BDB8C01F2"

**To Reproduce**
---------------------------------------------
- stop on a breakpoint with a non-ASCII string variable in scope then look at value of  the variable in the "Variable" debug pane

![non-ascii-as-codes](https://user-images.githubusercontent.com/11945571/123223006-f2beef80-d4e9-11eb-8b77-c03aa74df859.jpg)

**Comment by martinlippert** [comment]
Please report this to the Eclipse JDT/Platform project, this is where this is implemented:
https://bugs.eclipse.org/bugs/enter_bug.cgi?product=JDT

**Comment by IvankoB** [comment]
Me know but they will definetly respond with "use a new version not 4.11.0".
And the problem seems to relate to strings parsed directly from HTTP queries (SPRING controller in MVC)

where "Ташкентские подворотни, 1/2" is encoded as 

addressProxy=%D0%A2%D0%B0%D1%88%D0%BA%D0%B5%D0%BD%D1%82%D1%81%D0%BA%D0%B8%D0%B5%20%D0%BF%D0%BE%D0%B4%D0%B2%D0%BE%D1%80%D0%BE%D1%82%D0%BD%D0%B8%2C%201%2F2

in GET-request.
...
@RequestParam(name="addressProxy",required=false) String addressProxy_s,
...

Non-ASCII string constants (defined in JAVA code ) are show well in debugger.

**Comment by IvankoB** [comment]
And a coupe of day before there was no this issue :

![non-ascii-as-codes-were-ok](https://user-images.githubusercontent.com/11945571/123226076-bfca2b00-d4ec-11eb-9ac0-a807fa83168c.jpg)

**Comment by martinlippert** [comment]
Understand. The important piece here will be to identify where exactly the problem comes from. Can you try to run this app with a vanilla Eclipse 2021-06 release (not the Spring Tools distribution) and maybe an older version like Eclipse 2021-03 to see whether that works or not?

If you could attach or point us at a sample app that reproduces the issue, we could also take a look.

Also does the JDK that you use to run the IDE make a difference here? Maybe also worth a try.

**Comment by IvankoB** [comment]
The whole "curl" request
======================
curl -X GET "http://localhost:8080/birth-certificate/rest-api/push/?task_id=123456789&filedThroughProxy=1&organizationCertificateDic=8&purposeSubmitting=%D0%90%D0%9F%D0%98%20%D0%BE%D1%82%D0%BB%D0%B0%D0%B6%D0%B8%D0%B2%D0%B0%D0%B5%D0%BC&fullnameProxy=%D0%9F%D1%80%D0%BE%D0%BA%D1%81%D0%B5%D0%BD%D0%BA%D0%BE%20%D0%9F%D1%80%D0%BE%D0%BA%D1%81%D0%B8%D0%BC%D0%B0%20%D0%A6%D0%B5%D0%BD%D1%82%D0%B0%D0%B2%D1%80%D0%BE%D0%B2%D0%BD%D0%B0&pinflProxy=12345677654321&indTinProxy=1234567&addressProxy=%D0%A2%D0%B0%D1%88%D0%BA%D0%B5%D0%BD%D1%82%D1%81%D0%BA%D0%B8%D0%B5%20%D0%BF%D0%BE%D0%B4%D0%B2%D0%BE%D1%80%D0%BE%D1%82%D0%BD%D0%B8%2C%201%2F2&phoneProxy=996666666&emailProxy=proxyma%40certav.ru&whoAreYouApplicant=2&fullNameFiz=%D0%A4%D0%B8%D0%B7%D0%BB%D1%8E%D0%BA%20%D0%A0%D0%B5%D0%B0%D0%BB%20%D0%9B%D0%B8%D1%86%D0%B5%D0%B2%D0%B8%D1%87&birthdayFiz=1966-06-06&pinflFiz=76543211234567&indTinFiz=7654321&regionFiz=1726&districtFiz=1726292&phoneFiz=669999999&emailFiz=phys%40licy.uk&dateCivilRegistrFiz=2000-01-01&periodRequiredInfoFiz=%D0%B2%2021-%D0%BC%20%D0%B2%D0%B5%D0%BA%D0%B5&applicationType=2&repoLangValue=ru&allowPhoneNumber=1&userPhoneNumber=666999666&rejectedTaskId="

**Comment by IvankoB** [comment]
Strange that the same data sent by web-browser is handled well, no issues at all. 
But this application is intended to be used in an API not with web-browser. What is so specific can be in web-browser's GET-requests ?

**Comment by IvankoB** [comment]
Seems is's not a debugger issus, it ends HTTP GET-request parsing from CURL etc with wrong non-ASCII data in string request variables.

**Comment by IvankoB** [comment]
Me'll try to intercept network traffic to compare CUPL & web-browser data sent.

**Comment by IvankoB** [comment]
There're some differences in the headers, me''ll try to find out which of  them  are substantial.

![get-is-ok-sent-by-browser](https://user-images.githubusercontent.com/11945571/123240265-99f75300-d4f9-11eb-8b05-2f597fe3ca02.jpg)
![get-is-wrong-sent-by-curl](https://user-images.githubusercontent.com/11945571/123240279-9d8ada00-d4f9-11eb-81f7-759c380efbca.jpg)

**Comment by IvankoB** [comment]
Or not headers but smth like Windows CMD's intepreting %var% expressions in the URL string.
Non-ASCII strings in URI in the images look quite different.

**Comment by IvankoB** [comment]
Me can't manage Win10's CURL to send properly (matching browser's) encoded GET-data. Seems to the unusable way of testing.
