### ISSUE TITLE
Support notification level for unknown properties in configuration files likes in STS 3.x

### ISSUE THREAD

**Issue by jebeaudet** [spring-projects/sts4#654]
**Expected Behavior**

In STS 3.x, you were able to configure the "unknown property" warning level that you can get in yaml/properties files when you enter an unknown key. I think we should bring back this feature as I don't think _every_ configuration key should have metadata (ie. configuration key exclusive to your service don't necessarily need to be documented) and I want a warning free experience in eclipse without having to manually generate metadata for every unknown key.

**Current Behavior**

Currently, we don't have the option to ignore this so it generates a lot of warning in my eclipse console and this makes it easy to miss a real warning that I care about.

**Context**
Some related SO thread that got me here (I couldn't find the but that the SO user said he would log) : 
https://stackoverflow.com/questions/56151581/in-sts-4-0-ignoring-unknown-property-support-missing
https://stackoverflow.com/questions/43562880/springboot-unknown-property-in-application-properties

Thanks!

**Comment by martinlippert** [comment]
You can configure the severity level of those validations in the preferences: `Preferences -> Language Servers -> Spring Language Servers -> Spring Boot Language Server -> Properties Editor`.

Can you double check to see if this works for you?

**Comment by jebeaudet** [comment]
🤦🏻 You're totally right, I didn't see that section originally, it works thanks.

I would have expected to see this category in the `Spring` section of the preferences though, like it was in STS 3! In all cases I'll update the SO thread to help others in the same boat as me.

**Comment by martinlippert** [comment]
And I agree that the location of that preference is not very intuitive...
