### ISSUE TITLE
Add support for eclipse lemmnix xml language server

### ISSUE THREAD

**Issue by gayanper** [spring-projects/sts4#656]
**Expected Behavior**
When opening a bean definition xml file in Eclipse Lemmnix XML editor (Generic Editor) I would expect class and property completions from STS4 tooling support. 

**Current Behavior**
Not working in Lemmnix Editor

This can be implemented using the lemmnix extension for STS4 like it has been done for Maven.

**Comment by gayanper** [comment]
This is already working, tested on latest eclipse i-build with lemminx plugin 

`	Eclipse Wild Web Developer project	XML support using Language Server	0.12.0.202106200920	org.eclipse.wildwebdeveloper.xml`

**Comment by martinlippert** [comment]
I double checked this again to make sure everything runs fine in the upcoming release and it looks like everything is indeed running smoothly. One thing to add here is that the Spring completion support for classes, packages, and properties is coming from the Spring Boot language server directly (when looking at an XML file), this runs in parallel to the Lemminx language server support and is not built on top of it.
