### ISSUE TITLE
latest CI builds do not show port of running app anymore

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#659]
- I downloaded the latest CI build for STS 4.11.1 for Eclipse 4.20
- started with empty workspace
- created getting started guide (Rest Service)
- added actuator
- start the project via the boot dashboard

The dashboard does not show the port of the running app anymore and therefore also doesn't allow me to double click on the app anymore to open a browser.

The same steps work fine with STS 4.11.0.RELEASE.

**Comment by BoykoAlex** [comment]
Fixed with 72d4f43810370b7ee2fe791af6ca8048af4ed507
