### ISSUE TITLE
vscode-concourse does not recognise tags in resources

### ISSUE THREAD

**Issue by skytfdm** [spring-projects/sts4#66]
Hi,

When working on a concourse configuration in VSCode with the concourse extension installed, when I added a tag to a resource in the form

```
resources:
  - name: abc
    tag: [test]
```

"tag" is underlined with the error stating

```
unknown property 'tag' for type 'Resource'
```

I think this is a newer feature to concourse added in responce to [this issue](https://github.com/concourse/concourse/issues/152), closed in March 2017 with the feature now available as described [here](https://concourse-ci.org/resources.html#resource-tags).

Thanks

**Comment by kdvolder** [comment]
Thanks for the report. Just in time to fix for the next milestone build :-)

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Martin Lippert:) 

please note that the element is called `tags`, not `tag`, as described in the issue here.
