### ISSUE TITLE
Problem with the STS/eclipse initializr for custom project types

### ISSUE THREAD

**Issue by marc06210** [spring-projects/sts4#660]
Hello, 

I have customized the initializer with new project types.
When initializing a new project on IntelliJ those new types are available but they do not show up in the STS/eclipse project creation popup. 

The custom SpringInitializr code is available [here](https://github.com/marc06210/MguInitializr)

Import the project, start it and from the IDE when trying to initialize a new Spring project select **http://localhost:8080** as **server URL**.

have you already tried to define a new project type and create such a project within STS/eclipse?

Thx for your answer

Marc

edit: addition of the GitHub repository with source code with custom project type **Mgu**

**Comment by BoykoAlex** [comment]
I think **type** is misused in the custom initializr project. The starter project is a Maven project and should be **Maven Project** type. Types are reserved for build type of the project: Maven, Gradle etc. Thus one could use the same starter with a different build: Maven or Gradle. The type makes it into the path of a URL used to download the proper `starter.zip` (Maven or Gradle version of it).
I suppose IntelliJ simply shows in the wizard what it gets from the Initializr endpoint. In the case of the **type** Eclipse does not. It has predefined build types for which project import is supported by the Eclipse tooling. Everything not matching is ignored. This is done for a good reason. If a new build type comes in Eclipse tooling would need to execute some **build** tooling specific command to properly import the project into Eclipse. The new build type would most likely require including some build tooling plugins into STS hence build types are predefined and feels like they should be as you can't import an arbitrary build type project into Eclipse.
Of course we could make it work like IntelliJ by showing this new type and probably based on build type tags figure out that it is really a maven project to be imported. This seems like a wrong thing to do to me though... 
It would make sense to do something for extra "type(s)" if there was really a new build type...
What are you thoughts on this @kdvolder and @martinlippert

**Comment by marc06210** [comment]
Thx for your quick reply. It makes sense to me (no other type than the one supported by STS/eclipse).
I will think about another implementation 🙂

**Comment by kdvolder** [comment]
If the project you are generating is a maven project anyways, then why is a new 'type'? I guess I don't really understand what you mean by type if it isn't to distinguish between maven and gradle.

**Comment by snicoll** [comment]
> Of course we could make it work like IntelliJ by showing this new type and probably based on build type tags figure out that it is really a maven project to be imported. This seems like a wrong thing to do to me though...

I disagree with that. The documentation [states that](https://docs.spring.io/initializr/docs/0.10.0/reference/html/#create-instance-types):

> The build system must be defined with a build tag providing the name of the BuildSystem to use (e.g. maven, gradle).

In the case of STS, I agree you can't support a custom build system but, as long as the `build` tag provides the ID of the build system, you should be fine to support additional types.

**Comment by martinlippert** [comment]
Thanks @snicoll for pointing us at this. So re-opening this one here, turning it into an enhancement request to support different "types".

We could also go one step further:
- if there is a build type that the IDE understands (Maven or Gradle in our case), use it and import the generated project as a Maven or Gradle project
- if there is a build type that the IDE doesn't understand, tell the user and provide an option to import the project as a plain project
- if there is no build type specified, tell the user and provide an option to import the project as a plain project

WDYT?

**Comment by BoykoAlex** [comment]
Fixed with 51842c87082b817ed96f46b97753733da82122cb and available in the nightly build via update site: https://dist.springsource.com/snapshot/TOOLS/sts4/nightly/e4.20
