### ISSUE TITLE
JAVA_Home should be right but still shows "Note Java 8 can still be used in your own projects"

### ISSUE THREAD

**Issue by doggy8088** [spring-projects/sts4#664]
**Describe the bug**

I think my Java setup in my Visual Studio Code should be right. But this extension still show me this:

```txt
Spring Tools Language Server requires Java 11 or higher to be launched. Current Java /usr/lib/jvm/java-8-openjdk-amd64/bin/java. (Note Java 8 can still be used in your own projects. Java 11 is only required to launch the Spring Tools Language Server process)

Source: Spring Boot Tools (Extension)
```

**To Reproduce**

1. Initialize a Spring Boot project using this: 

    ```txt
    https://start.spring.io/#!type=maven-project&language=java&platformVersion=2.5.3&packaging=jar&jvmVersion=11&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=lombok,web
    ```

2. Use `Remote-SSH: Connect to Host...' open Spring Boot project

3. Open **MAVEN** view in EXPLORER, expand `demo` node, click the `+` sign in the **Dependencies** noe

4. Search for `spring-boot-starter-validation`, choose the `org.springframework.boot` one.

5. The VSCode will show this message immediately.

    ![image](https://user-images.githubusercontent.com/88981/128618582-4f6a8b2a-6658-4d11-8780-e6c694cac12e.png)

6. My `JAVA_HOME` should be right.

    ![image](https://user-images.githubusercontent.com/88981/128618894-9478f2ff-d351-42fe-a941-6defb13ec832.png)

7. The VSCode setting is empty.

    ![image](https://user-images.githubusercontent.com/88981/128618904-aee88407-d7e5-40ff-ba5d-79e21e8d9303.png)

**Sample**

Here is my sample project:

https://github.com/doggy8088/spring-boot-demo

**Comment by doggy8088** [comment]
It seems I have to restart VS Code Server on Host.

> `F1` > `Remote-SSH: kill VS Code Server on Host...`

**Comment by martinlippert** [comment]
The error message that you mentioned above looks like the Spring Boot Tools extension is picking up a JDK8 to run the language server process (a tooling-internal process, not related to your projects), but it needs JDK11. I don't exactly know why the JDK8 is selected instead of the JDK11 that you have in your JAVA_HOME environment variable... :-(

In case this problem persists, you can specify which JDK the Spring Boot tools should use internally (again, just internally, not for your project) via the settings:

`"spring-boot.ls.java.home": "/usr/lib/jvm/java-11-openjdk-amd64/bin/java"`

(or whatever the right path to the Java executable of your JDK11 install is)

**Comment by doggy8088** [comment]
@martinlippert 

I finally found a way to reproduce the problem.

1. VSCode User Settings

    ```json
    {
        "java.home": "/usr/lib/jvm/java-11-openjdk-amd64",
        "java.debug.settings.hotCodeReplace": "auto",
        "java.configuration.runtimes": [
            {
                "name": "JavaSE-1.8",
                "path": "/usr/lib/jvm/java-8-openjdk-amd64/",
                "sources": "/usr/lib/jvm/java-8-openjdk-amd64/src.zip",
                "default": true
            },
            {
                "name": "JavaSE-11",
                "path": "/usr/lib/jvm/java-11-openjdk-amd64",
                "sources": "/usr/lib/jvm/java-11-openjdk-amd64/lib/src.zip",
                "javadoc": "https://docs.oracle.com/en/java/javase/11/docs/api"
            }
        ]
    }
    ```

2. My `JAVA_HOME` environment variable 

    ```txt
    /usr/lib/jvm/java-8-openjdk-amd64
    ```

3. My Spring Boot project created using Java 11.

---

I added `"spring-boot.ls.java.home": "/usr/lib/jvm/java-11-openjdk-amd64/bin/java"` to my `settings.json`. Kill my VS Code Host. The error still exists.

![image](https://user-images.githubusercontent.com/88981/128723460-136140c0-8401-42f3-8f88-b5e48cc33b20.png)

**Comment by doggy8088** [comment]
@martinlippert 

I found a way to workaround this problem.

```sh
sudo update-alternatives --set java /usr/lib/jvm/java-11-openjdk-amd64/bin/java
```

**Comment by doggy8088** [comment]
@martinlippert 

I think this might works. I tested without any error:

```json
"spring-boot.ls.java.home": "/usr/lib/jvm/java-11-openjdk-amd64"
```

**Comment by doggy8088** [comment]
@martinlippert I think STS4 can read `"java.home"` user setting by default if it's been defined. So that I don't have to setup `"spring-boot.ls.java.home"` to a JDK path manually.

**Comment by martinlippert** [comment]
> @martinlippert I think STS4 can read `"java.home"` user setting by default if it's been defined. So that I don't have to setup `"spring-boot.ls.java.home"` to a JDK path manually.

Agree, exactly what @BoykoAlex is already implementing at the moment... :-)

**Comment by martinlippert** [comment]
This is covered by the latest changes, I think, which is looking at the STS4 specific property first and tries `java.home` next, if the STS4 property is not set or not set to an existing JDK.
