### ISSUE TITLE
java.exe not running in background even we stop the spring boot

### ISSUE THREAD

**Issue by shamsheerothayoth** [spring-projects/sts4#665]
**Describe the bug**
java.exe not running in background even we stop the spring boot

**To Reproduce**
start spring boot web server and stop (run or debug mode). You can see the java.exe or javaw.exe is still there in the background,

in sts3 its closing properly.
**Sample**

A link to a GitHub repository with a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example).

Reports that include a sample will take priority over reports that do not.
At times, we may require a sample, so it is good to try and include a sample up front.

**Comment by martinlippert** [comment]
Can you provide a few more details here, for example steps how to reproduce this, the system you are running on, how you identify that the process is still running (in case I understand this correctly)? That would be great.

Trying a simple example on my end works just fine in general, so we need to investigate this in more detail. Please keep in mind that the Spring Tools 4 IDE itself is running as a Java process and creates at least one more Java process for the Spring Boot Language Server process, which is also running in the background - in case this is causing confusion (just guessing here).

**Comment by martinlippert** [comment]
No further feedback or details on this one here, so closing this one now.
