### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by vanniuner** [spring-projects/sts4#666]
sts4-main/eclipse-language-servers/
sh local-build.sh
the output blew:
[ERROR] An error occurred while transferring artifact canonical: osgi.bundle,org.jsoup,1.9.2 from repository https://dist.springsource.com/release/TOOLS/third-party/misc-p2-repo/3.9.4.202003091750:
[ERROR]    Unable to read repository at https://dist.springsource.com/release/TOOLS/third-party/misc-p2-repo/3.9.4.202003091750/plugins/org.jsoup_1.9.2.jar.
[ERROR] Internal error: org.eclipse.tycho.repository.local.MirroringArtifactProvider$MirroringFailedException: Could not mirror artifact osgi.bundle,org.jsoup,1.9.2 into the local Maven repository.See log output for details. Read timed out -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: org.eclipse.tycho.repository.local.MirroringArtifactProvider$MirroringFailedException: Could not mirror artifact osgi.bundle,org.jsoup,1.9.2 into the local Maven repository.See log output for details.

**Comment by martinlippert** [comment]
This looks a lot like a problem with the local maven repo or maven hitting some temporary network glitch. I would recommend to clean the local maven repo and try again.

**Comment by martinlippert** [comment]
No further feedback on this since Aug 2021, so closing this one here.
