### ISSUE TITLE
Cannot copy/paste from ANSI console without escape sequences

### ISSUE THREAD

**Issue by rwellman-ats** [spring-projects/sts4#667]
Hopefully this is completely self-explanatory.
I have tried this multiple ways (keyboard Ctrl-C, Ctrl-V, right-click, and the confusing button labelled "copy text with escapes")

Spring Tool Suite 4 
Version: 4.11.0.RELEASE
Build Id: 202106180608

**Comment by martinlippert** [comment]
Yes, I agree, this is confusing and doesn't work as expected. I think some time ago we implemented the standard copy/paste feature to exclude the escape sequences and therefore added a button to get the full text sequence including the escape sequences. But that doesn't seem to work anymore.

I raised an issue here https://github.com/mihnita/ansi-econsole/issues/65

**Comment by martinlippert** [comment]
Waiting for the next ANSI Console release to get a fix in.

**Comment by martinlippert** [comment]
A new version of the ANSI Console plugin has been published and will be included in the upcoming 4.13.0.RELEASE

**Comment by priyankawadekar** [comment]
am facing this issue - copy/paste console output showing escape characters in notepad. My sts version is 4.19.0.RELEASE

**Comment by martinlippert** [comment]
@priyankawadekar The ANSI Console plugin functionality is now integrated into the Eclipse platform, the issue you are describing might be related to this one here: https://github.com/eclipse-platform/eclipse.platform/issues/536

Closing this item here as a duplicate of the mentioned one at Eclipse platform. Please follow up on the above mentioned issue.
