### ISSUE TITLE
P2 URL link broken

### ISSUE THREAD

**Issue by abhinavrk** [spring-projects/sts4#67]
P2 URL link doesn't seem to work with Eclipse-Photon.

The link in the wiki (https://github.com/spring-projects/sts4/wiki/Installation), namely http://download.springsource.com/release/TOOLS/sts4/update/latest/ , doesn't work.

**Comment by martinlippert** [comment]
What exactly does not work? I tried it in the "Install New Software" dialog, the content showed up, I selected both "Spring Tools 4" categories, and pressed install. Therefore not sure what exactly you experienced that didn't work. Can you elaborate?

Please keep in mind that the latest STS4 public beta (milestone 14) is based on Eclipse 2018-09, the release after Photon. Therefore the `latest` update site also contains a pointer to the corresponding staging repository for that Eclipse version and your Eclipse Photon installation would be updated to that version. Therefore I would recommend to start with an Eclipse 2018-09 M2 build and install STS4 M14 into that, if you prefer to start with an Eclipse install. As an easy alternative, you could always download the ready-to-use Eclipse distribution of STS4 M14 (from the links on that wiki page that you mentioned).

**Comment by abhinavrk** [comment]
Hey,

My bad. Was behind a private network that blocked that link. Connected at home and it worked like a charm.

Sorry again.

**Comment by martinlippert** [comment]
No problem, glad to hear that is works for you and thanks for letting us know.
