### ISSUE TITLE
[vscode Concourse extension] exclude Ansible folders and tasks by default

### ISSUE THREAD

**Issue by sfuerte** [spring-projects/sts4#672]
**Describe the bug**
The extension description says:
> The Concourse editor automatically activates when the name of the .yml file you are editing follows a certain pattern:
**/*pipeline*.yml | **/pipeline/*.yml : activates support for editing pipelines
**/tasks/*.yml | **/*task.yml : activates support for editing tasks.

which interferes with Ansible role tasks big time as for anything in the following folders will be using `Concourse Task` YAML schema:
```
**/roles/tasks/*.yml
**/ansible/roles/tasks/*.yml
```

Nor there is a way to override the extension default patterns.

**To Reproduce**
As per above.

**Versions**

```
Concourse CI Pipeline Editor extension - v1.26.0

VS Code - Version: 1.59.0 (Universal)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:14:40.191Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 20.6.0
```

**Comment by kdvolder** [comment]
> Nor there is a way to override the extension default patterns.

I think there is a way to override the default patterns as stated right below the line in the readme from where you quoted:

> You can also define your own patterns and map them to the language-ids concourse-pipeline-yaml or concourse-task-yaml by defining files.associations in workspace settings. See [vscode](https://code.visualstudio.com/Docs/languages/overview#_adding-a-file-extension-to-a-language) documentation for details.

It is true though that it isn't totally clear that you can override the existing patterns this way. (I.e. it states there that you can add patterns only not how to override behavior of existing patterns. However that is also possible:

I tried and added the following to my settings.json file:

```
    "files.associations": {
        "*pipeline*.yml": "plaintext",
        "**/pipeline/*.yml": "plaintext"
    }
```

This switched pipeline editors to plaintext.

**Comment by kdvolder** [comment]
I also tried the following:

```
    "files.associations": {
        "**/roles/tasks/*.yml": "plaintext",
        "**/ansible/roles/tasks/*.yml": "plaintext"
    }
```

Subsequently when I open a yml file like `ansible/roles/something.yml` it opens in plain text.

I understand having to do this might be annoying. And it would be nice if this wasn't necessary, I'm just not sure how we can accomplish this and so I am inclined to close this ticket without any further action. 

I am open to suggestions however if you have an idea on what we could change to avoid this conflict without a user needing to add their own `files.associations`.

**Comment by kdvolder** [comment]
Closing this for now, but can be re-opened if we have an idea what to do about addressing it.

**Comment by martinlippert** [comment]
There is a similar issue (although not exactly the same) with `application.properties` files being associated with Spring Boot Properties file editors and Quarkus-specific support for those files. I think the Quarkus extension solved this by having an additional look into the file to avoid this, but I can't remember the exact details. With that in mind, we can spend some time in a future release schedule to dive deeper into this and think about doing something to narrow down the focus for our editors beyond pure file associations.

**Comment by kdvolder** [comment]
I don't know if what you suggest is possible. The file association is not controlled by an api at the moment but by a simple declaration of patterns in package.json. See: https://github.com/spring-projects/sts4/blob/main/vscode-extensions/vscode-concourse/package.json#L83

**Comment by aussielunix** [comment]
What about the idea of the default that comes with the extension is to limit the associations to the `ci/` directory ?
```json
"ci/pipeline/*.yml": "concourse-pipeline-yaml",
"ci/*pipeline*.yml": "concourse-pipeline-yaml",
"ci/tasks/*.yml": "concourse-task-yaml",
"ci/*task.yml": "concourse-task-yaml"
```

I have a repo with mixed Concourse and Ansible which is why I ended up here.
 
The new Ansible extension currently does not have any built in file associations however someone has just suggested the [following](https://github.com/ansible/vscode-ansible/issues/162#issuecomment-908133169) which I am using with success.

```json
"files.associations": {
        "**/playbooks/*.yml": "ansible",
        "**/playbooks/*.yaml": "ansible",
        "**/hostvars/*.yml": "ansible",
        "**/group_vars/*.yml": "ansible",
        "**/tasks/*.yaml": "ansible",
        "**/tasks/*.yml": "ansible",
        "**/defaults/*.yaml": "ansible",
        "**/defaults/*.yml": "ansible",
        "**/vars/*.yaml": "ansible",
        "**/vars/*.yml": "ansible",
        "**/meta/*.yaml": "ansible",
        "**/meta/*.yml": "ansible",
        "**/handlers/*.yaml": "ansible",
        "**/handlers/*.yml": "ansible"
    }
```

**Comment by kdvolder** [comment]
Sadly, it looks like both Ansible and Concourse editor would both seem eager to claim patterns like `**/tasks/**.yml` as their own.

Anyhow:

I am changing our tasks pattern to:
```
          "**/ci/*task.yml",
          "**/ci/**/tasks/*.yml",
          "**/concourse/*task.yml",
          "**/concourse/**/tasks/*.yml"
```

I'm leaving pipeline pattern unchanged since I beleave having the word 'pipeline' in either the folder or file name is already sufficiently specific to avoid common name/pattern clashes.
