### ISSUE TITLE
Run microservice with profile in VS Code

### ISSUE THREAD

**Issue by getaceres** [spring-projects/sts4#678]
**Expected Behavior**

Right now, in VS Code, we get a very limited Spring Boot dashboard compared to the Eclipse one. It's basically a list of the microservices open in the workspace and you can start and stop them but there isn't any option to either select a configuration if more than one is present in the launch.json file or run them with some arguments like a profile for Spring Boot.

**Current Behavior**

There's only the option of Start, Debug and Stop when the service is running. It would be nice to have also the option of Run as... and Debug as... and be able to select a profile set in the launch.json file present in the project.

I have some microservices that can be run with different profiles. In the Eclipse plugin I can select the Spring Boot profile directly in the UI but that's not possible in VS Code. To do so, I've created some entries in each launch.json file with different values as "vmArgs": "-Dspring.profiles.active=<profile>". I can run them through the "Run and debug" section in VS Code and select them individually but it shows all different profiles of all different projects in the workspace. It would be nice to be able to select this profiles for each project in the Spring Boot Dashboard.

**Comment by martinlippert** [comment]
Hey @getaceres, since the boot dashboard for VSCode is implemented in a different project, I raised the issue here: https://github.com/microsoft/vscode-spring-boot-dashboard/issues/145 - pointing back to this one - in case you want the issue on the boot dashboard project for VSCode.

**Comment by getaceres** [comment]
That's great. Thanks.
