### ISSUE TITLE
Use `extensionPack` instead of `extensionDependencies` property for defining pack

### ISSUE THREAD

**Issue by sandy081** [spring-projects/sts4#68]
From release v1.26, defining an Extension Pack now uses a new property called `extensionPack` instead of `extensionDependencies` in package.json. This is because extensionDependencies is mainly used to define functional dependencies and an Extension Pack should not have any functional dependencies with its bundled extensions and they should be manageable independent of the pack. 

So please use `extensionPack` property for defining the pack.

For more details refer to [Release notes](https://code.visualstudio.com/updates/v1_26#_extension-packs-revisited)

This extension is categorised as extension pack and hence this issue is filed. If you think this does not impact the extension, please close it.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Kris De Volder:) 

I've update our package.json for boot-dev-pack and pushed out new version of the pack to the vscode marketplace.
