### ISSUE TITLE
In-place upgrade STS-4.10 to STS-4.12 failing

### ISSUE THREAD

**Issue by space88man** [spring-projects/sts4#691]
**Describe the bug**
I am trying to upgrade an STS 4.10 directory to STS 4.12 and failing at "Check for Updates".
Platform is Linux.

**To Reproduce**
- already installed STS 4.10 
- upgrade as much as possible using Marketplace: Markeplace shows 4.12.0.RELEASE and is at state Change
- goto Available Software Sites
- reload https://download.springsource.com/release/TOOLS/sts4/update/latest
- reload https://download.springsource.com/release/TOOLS/sts4-language-server-integrations
- reload https://download.eclipse.org/releases/latest

**Error**

```
An error occurred while collecting items to be installed
session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.springframework.boot.ide.branding,4.12.0.202109130635-RELEASE
No repository found containing: org.eclipse.update.feature,org.springframework.boot.ide.branding.feature,4.12.0.202109130635
No repository found containing: binary,org.springframework.boot.ide.branding.sts4.executable.gtk.linux.x86_64,4.12.0.202109130635```
```

![Screenshot from 2021-09-30 18-27-41](https://user-images.githubusercontent.com/29966967/135438975-4b550aaf-8c7f-4b08-89fa-3fc0cc5535d1.png)
![Screenshot from 2021-09-30 18-29-53](https://user-images.githubusercontent.com/29966967/135439133-3cbab8e1-19b3-4f23-ab58-48ab1f254ab0.png)

**Comment by space88man** [comment]
I saw this: https://stackoverflow.com/questions/69214960/cannot-satisfy-dependency-in-sts4-org-springframework-boot-ide-branding-sts4-4-1.

However this is not an existing Eclipse installation - it is sts-4.10.0.RELEASE trying to move to sts-4.12.0.RELEASE.

**Comment by space88man** [comment]
Well to my surprise this method worked:
- add two more update sites
- copy Eclipse site and replace `/latest` with `/2021-091
- STS 4 replace `/latest` with `/e4.21`

Then the in-place upgrade works.

**Comment by martinlippert** [comment]
Glad to hear you found a solution for this. My guess is that this is related to stale cache data for the repositories, so deleting the update sites from the preferences, restarting the IDE, and adding them back should have worked as well. Looks like your added update sites worked around this as well... :-)

Ideally, you don't need all those update sites. This one should be enough:

```
https://download.springsource.com/release/TOOLS/sts4/update/latest/
```

It refers to the latest Eclipse release as well as the latest matching STS4 release for that Eclipse version, so updating from that should keep you up-to-date with the latest Eclipse and STS4 - in case you want to clean up your preferences... :-)
