### ISSUE TITLE
Always pop up a prompt box: indexing spring boot properties

### ISSUE THREAD

**Issue by zhiyiYo** [spring-projects/sts4#697]
**Describe the bug**
As shown in the figure below, a prompt box always pops up in the lower right corner of VS Code: indexing spring boot properties. This prompt is very annoying. Is there a way to turn it off?
![indexing](https://user-images.githubusercontent.com/65096819/138998917-ffd75b2a-d47c-49d7-adc0-081e5e8ff33d.gif)

**Comment by BoykoAlex** [comment]
Two latest commits from me and @kdvolder should fix the the pesky popup indirectly:
- cdf585c7fbf0eea12730b66093b8c6d4cbee29fe
- f36671814cfc103302458219d2fb528a455eef37
