### ISSUE TITLE
springci/sts4-theia-snapshot:latest image can not run, http://127.0.0.1:3000/ only have blank

### ISSUE THREAD

**Issue by aaa0long** [spring-projects/sts4#698]
**Describe the bug**
springci/sts4-theia-snapshot:latest image can not run, http://127.0.0.1:3000/ only have blank

**To Reproduce**
docker run -it --init  -p 3000:3000 -p 8080:8080 -v "$(pwd):/home/project:cached" springci/sts4-theia-snapshot:latest --name theia4

url: http://127.0.0.1:3000/
![image](https://user-images.githubusercontent.com/86939787/139203617-a8b60945-f4e9-463d-a9c5-42a9a0a40c9d.png)

**Comment by martinlippert** [comment]
We do not ship and support these theia containers anymore, they are a left-over from quite some time ago. If you want to use Spring Tools 4 in a Theia environment, you can get the extension from the Open VSX marketplace at https://open-vsx.org/extension/Pivotal/vscode-spring-boot.
