### ISSUE TITLE
About code tip suggest

### ISSUE THREAD

**Issue by drc5521** [spring-projects/sts4#699]
**Expected Behavior**

hi friend，When I open the code prompt, although there are no letters, it still prompts. When I hit enter, there will be a selection, and I must press Esc to disappear. This is very unfriendly.Please watch the video.
**Current Behavior**

https://user-images.githubusercontent.com/55195642/139794347-5bf6f892-62e7-4d2d-a245-24a4bc204903.mp4

**Context**
When there are no letters, the prompt box should disappear.

**Comment by martinlippert** [comment]
This is the default behavior of the Java tooling in Eclipse. If you would like this to be changed (or have a preference to disable this behavior), please report that at: https://bugs.eclipse.org/bugs/enter_bug.cgi?product=JDT and select the "UI" component.
