### ISSUE TITLE
Typescript comparison: An internal error occurred during: "LSP4E Linked Editing Highlight".

### ISSUE THREAD

**Issue by 4javier** [spring-projects/sts4#700]
Opening versions comparison view on TypeScript or Html files trigger this error.

> An internal error occurred during: "LSP4E Linked Editing Highlight".
> Cannot enter synchronized block because the return value of "org.eclipse.lsp4e.operations.linkedediting.LSPLinkedEditingReconcilingStrategy.getLockObject(org.eclipse.jface.text.source.IAnnotationModel)" is null

No problem with Java files.

Don't know if it fits better to LSP4E or WildWebDeveloper bugtracker.

Issue introduced with STS 4.12.1, tho.
`Version: 4.12.1.RELEASE
Build Id: 202110260750
`

**To Reproduce**
Compare two revisions of the same ts or html file.

**Comment by martinlippert** [comment]
I think this got fixed in LSP4E with https://github.com/eclipse/lsp4e/commit/860ffbc0c2d4d5083108a4a489971fd9561bde53, so will be included in upcoming STS 4.13.0.RELEASE
