### ISSUE TITLE
[Eclipse] js syntax highlight disabled by STS4

### ISSUE THREAD

**Issue by tree1891** [spring-projects/sts4#702]
STS 4.12.1
eclipse-jee 2021-09

**Comment by cypher256** [comment]
STS 4.12.1 Plugin
eclipse-jee-2021-12-M2-win32-x86_64 (Wild Web Developer Generic Text Editor)

The above also causes problems.
It does not occur in STS 4.12.0 Plugin.

**Comment by nexodex-dev** [comment]
https://github.com/eclipse/wildwebdeveloper/issues/750

**Comment by martinlippert** [comment]
I can reproduce this issue, thanks for reporting this. I do not immediately see the reason why this breaks, so this needs some deeper investigation. My initial guess is that this is related to newer versions of the tm4e bundles being installed when the Spring Tools 4 get installed and maybe causing some incompatibility here, but this is just initial guesswork. I will continue the investigations here.

**Comment by martinlippert** [comment]
This works out-of-the-box in the Spring Tools 4 for Eclipse distributions that you can download from https://spring.io/tools or even the latest nightly builds on Eclipse 2021-12 milestones from https://dist.springsource.com/snapshot/STS4/nightly-distributions.html, but I can reproduce this after installing the Spring Tools into an existing Eclipse JEE package.

Now need to find out why this breaks when the Spring Tools are installed as an extension to an existing Eclipse JEE package.

**Comment by martinlippert** [comment]
The solution to this is to install the latest TM4E via:

- open `Install New Software` dialog
- add `https://download.eclipse.org/tm4e/releases/latest/` to the `Work With` field
- only select the `TextMate Core` feature from the `TextMate` category
- install

This should bring back the syntax highlighting for JavaScript files.

This problem doesn't seem to occur in the latest Eclipse 2021-12 RC1 when installing the latest Spring Tools 4 extension from https://dist.springsource.com/snapshot/TOOLS/sts4/nightly/e4.22 - if you want to use the latest for the upcoming Eclipse 2021-12 release.

**Comment by martinlippert** [comment]
@cdiama Can you share a few more details here? I have a fresh STS 4.17.2.RELEASE running, created a JS file and it looks like I get syntax highlighting just fine. Do you open the JS files with the `Generic Editor`? And is there anything showing up in the `Error Log` view maybe?

**Comment by cdiama** [comment]
Hello Martin (@martinlippert), 

Thanks for your prompt reply!

Let me share the steps I went through:

1. As you I have a fresh latest STS as fetched from [here](https://download.springsource.com/release/STS4/4.17.2.RELEASE/dist/e4.26/spring-tool-suite-4-4.17.2.RELEASE-e4.26.0-win32.win32.x86_64.self-extracting.jar).

2. After starting it and without any single configuration I import a project using the very basic `Import... -> General -> Projects From Folder or Archive`. For the sake of the issue reproduction let's take this [sample project](https://github.com/PacktPublishing/JavaScript-by-Example/tree/master/Chapter01).

3. I double click the file `/Chapter01/CompletedCode/src/scripts.js` and it opens in the `Generic Text Editor` by default.

... then, an interesting sequence follows ...

4. The file opens with its syntax highlighted as expected, while Outline view tries to "calculate the symbols..."
![InkedCapture](https://user-images.githubusercontent.com/33286715/223234135-bfc842e2-993a-479f-9f7e-17e45e84bea4.jpg)

5. After that, syntax highlighting is getting lost for functions, vars, properties and so on, and we are left with the reserved words properly shown only.
![Capture2](https://user-images.githubusercontent.com/33286715/223234672-5b6df352-0c03-41a8-893a-fb8ee5b41a32.PNG)

Exported Error Logs:
[ErrorLog.log](https://github.com/spring-projects/sts4/files/10902929/ErrorLog.log)

**Comment by martinlippert** [comment]
Thanks a lot @cdiama for the detailed description, this helps a lot to actually see the issue in action. That is great. I can reproduce this with the latest STS builds as well. I also tried the latest Eclipse WWD release, which does NOT have the issue. The latest Eclipse JEE 2023-03 milestone builds also do NOT show the issue, so it seems to be very specific for the STS builds.

Based on the error log, it might be related to the snapshot version of lsp4e that we use and ship (to include a number of important fixes), so let's see if we can get to the root cause of this.

**Comment by martinlippert** [comment]
Let's track this in a separate issue: https://github.com/spring-projects/sts4/issues/993

**Comment by martinlippert** [comment]
Thanks again @cdiama for the detailed report, this is now fixed in the latest lsp4e snapshot builds, will be included in the upcoming STS 4.18.0 release (scheduled for next week).
