### ISSUE TITLE
Ease of debug for gradle based projects.

### ISSUE THREAD

**Issue by hanct** [spring-projects/sts4#708]
Hi all,

Currently, in order to do debugging,  i have to do the below one-time setup

1) Add the below to build.gradle
bootRun {
      jvmArgs=["-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=32323"]
}

2) Add a debug configuration for the "Remote Java Configuration" type, with the port field set to 32323

 Once above done, to do debug, i need to do the 2 steps
**Step 1)** Via the gradle task pane, double click on bootRun task.  This will launch the spring boot application , but it will suspend immediately upon launching.

**Step 2)** Then run the debug configuration. 

The application will now resume from suspend and start running in debug mode,  pausing at any breakpoint (if set).

My question is, the above process is so troublesome.  Each time i debug, i have to go thru the 2 steps .  To improve developer experience, can we have also debug button for the bootRun task in the gradle task pane., so that clicking on the debug button will actually execute the above 2 steps. In fact, the aforementioned setup can even be automated for developer.

This is exactly what the "gradle for java" extension in visual studio code is doing, making life so simple for developer.

**Do note that my above discussion focus on how to debug via gradle, not debug via the STS**

**Comment by martinlippert** [comment]
There is a Gradle Integration for Eclipse called Buildship, which is included in the Spring Tools 4 for Eclipse distribution by default. Using that, you can import projects that use Gradle and run them in debug mode from within the IDE as you would do that with any other Java project in Eclipse.

**Comment by hanct** [comment]
> There is a Gradle Integration for Eclipse called Buildship, which is included in the Spring Tools 4 for Eclipse distribution by default. Using that, you can import projects that use Gradle and run them in debug mode from within the IDE as you would do that with any other Java project in Eclipse.

Yes. I am currently using the Buildship tool to run the gradle task interactively (instead of using the command line).  Do u mean that clicking on the debug button will run the gradle task "bootRun" behind the scene?

Do note that my question is referring to how to debug via gradle, so that if i set system properties inside the build.gradle, the system properties will be passed to the application during debug

**Comment by martinlippert** [comment]
I don't think the Debug button will run the gradle task behind the scenes. My assumption is that the Java/Debug tooling will run/debug the application via the corresponding debug launch config and whatever you specify in there if you need anything specific for the app at runtime (like specific environment vars, system properties, etc.), so I don't see a real need to execute the gradle task directly.

If you are looking for more details here, I would suggest to report this to the Buildship project/team to get more detailed advice on this: https://github.com/eclipse/buildship
