### ISSUE TITLE
An internal error occurred during "updating maven project

### ISSUE THREAD

**Issue by jawale204** [spring-projects/sts4#714]
An internal error occurred during "updating maven project" in STS(4.8.0)

I have cloned a repo from bitbucket to my local machine and when it tries to build i am getting the above error. Rather i am getting errors on every maven related stuff (build , update ,clean) and I am not sure what's wrong . I am not even able to open pom.xml file in STS. 
error -> An internal error occurred during "updating maven project" [org/springframework/tooling/boot/ls/xml/xmlrootelementcontentdescriber2$qualifiedelement]

detailed error
!(https://user-images.githubusercontent.com/56351438/149526725-1b5bab41-fb59-4bfc-8b72-69023d5249fa.jpeg)
!(https://user-images.githubusercontent.com/56351438/149526737-89ae5ea2-8432-431d-a1e2-f30df20c052e.jpeg)

**Comment by BoykoAlex** [comment]
Any chance you can try STS 4.13.0?

**Comment by jawale204** [comment]
> Any chance you can try STS 4.13.0?
unfortunately no i am working on a client VDI

**Comment by jawale204** [comment]
the issue got resolved after i switched to sts verion 4.7.0

**Comment by aravindkesavarapu** [comment]
Facing same issue in STS 4.27.0.0 Version
