### ISSUE TITLE
Spring Boot Tools for VS Code incorrectly misidentifies internal JDK for Language Support for Java as a JRE

### ISSUE THREAD

**Issue by alvint** [spring-projects/sts4#715]
Now that Language Support for Java is platform-specific, it embeds a JDK by default. On my linux VM (which I connect to via Remote-ssh), the path to this JDK is `~/.vscode-server/extensions/redhat.java-1.2.0/jre/17.0.1-linux-x86_64/`.

However, if I try to use this JDK for Spring Boot Tools by setting `spring-boot.ls.java.home`, it complains that it's a JRE (see picture). My guess is the extension is simply checking the path for the string "jre" to determine if it's a JRE or JDK.

The way I see it, there are two issues that need to be addressed:

- a more robust check needs to be done to determine if the folder is a JDK or JRE
- since Spring Boot Tools requires Language Support for Java, and Language Support for Java now includes a JDK by default, Spring Boot Tools should scan for and automatically use this JDK by default, if it's not overridden by `spring-boot.ls.java.home` (OK, this part is more of an enhancement)

To reproduce, set `spring-boot.ls.java.home` to a JDK whose path includes the string "jre".

<br>

<img width="578" alt="Screen Shot 2022-01-13 at 08 20 51" src="https://user-images.githubusercontent.com/622202/149800305-1dc0cec2-97e0-4266-b39f-19ddcc9b48f8.png">

**Comment by BoykoAlex** [comment]
@kdvolder and I fixed it:
- Better criteria for JDK d71b70b39bafaec754f731b7830280dd1e41dd66
- Use embedded JDK into java ls if it is around 29db241bb20a71064f3568f77041ccbeba366c0a

**Comment by alvint** [comment]
Works great here. Thanks!
