### ISSUE TITLE
avoid live hover connection attempt when deploying app to docker without actuator

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#716]
At the moment, when the user deploys a Spring Boot app to docker using the Spring Boot Dashboard, the live hover mechanism automatically kicks in and tries to connect to the app to visualize the live hovers. While this makes sense in general, this should not happen when the application doesn't have spring boot actuator in the classpath.

For apps that are running locally, this check is done automatically in the `SpringProcessConnectorLocal` based on the workspace project, but that information isn't around at this level for apps that are running in a docker container (and set to the language servers live hover mechanism via the remote processes mechanism).

I think this requires the necessary information to be passed via the remote apps mechanism to the live hovers mechanism of the language server in order to determine whether to auto-connect to the app or not.

**Comment by kdvolder** [comment]
Fix was pushed.
