### ISSUE TITLE
MacOs  Monterey  12.2  You cannot open the application "SpringToolSuite4" because it is not supported on this Mac.

### ISSUE THREAD

**Issue by dds0922** [spring-projects/sts4#719]
My system version: MacOs Monterey 12.2 

Computer Model: MacBookPro

I downloaded https://spring.io/tools 4.13.0-MACOS ARM_64.dmg from the spring.io website, installed it and opened it, but it says "You cannot open the application "SpringToolSuite4", because this Mac does not support this application."  Reinstallation also does not work

**Comment by martinlippert** [comment]
@dds0922 You closed this, so I guess you solved the issue. Can you share your solution here, so that others can benefit and learn from it? That would be awesome. Thanks!!!
