### ISSUE TITLE
VSCode Spring boot tools 1.30.0 error trying to find JVM

### ISSUE THREAD

**Issue by RohacRichard** [spring-projects/sts4#726]
**Describe the bug**
This morning there was a new version of Spring boot tools installed to my VS code instance. I was unable to start any Spring projects from dashboard. I managed to resolve the problem by downgrading to previous version. Maybe there is problem with something on my side. Just throwing this out in case anybody else has this problem.

**To Reproduce**
Install Spring boot tools 1.30.0 and restart java workspace. Throws this error:
![Screenshot 2022-02-02 134256](https://user-images.githubusercontent.com/44978845/152155937-f43ca261-8457-4bde-ba06-011433792e4e.png)

**Comment by BoykoAlex** [comment]
Looks like the issue is:
```
ChildProcess.execSync(javaExecutable + ' --list-modules', {windowsHide: true, encoding: 'utf8'});
```
command string doesn't like spaces in paths./ Need to wrap `javaExecutable` in double quotes.

The workaround would b e have Java somewhere under the path not having spaces :-/

**Comment by BoykoAlex** [comment]
Feel free to remove java home setting value in your VSCode settings. New Java extension for vscode comes with embedded java. If your vscode is located under the path without space then everything should start working if you remove java home setting from VSCode settings.

**Comment by martinlippert** [comment]
We are in the process of pushing out another update release to get this into the hands of our users quickly. Stay tuned.

**Comment by martinlippert** [comment]
Update releases with a fix for this published on the VSCode marketplace.
