### ISSUE TITLE
Cannot install both STS 4.13.1 and Spring Tools 3 Add-On plugin

### ISSUE THREAD

**Issue by buyukim** [spring-projects/sts4#728]
Cannot install both STS 4.13.1 and Spring Tools 3 Add-On plugin right now from Eclipse Marketplace.  Looks like Eclipse is complaining about conflicting Spring IDE Buildship versions.  Is there going to be a new release of Spring Tools 3 Add-On that is compatible?

Here is the install failure message:
```
Cannot complete the install because of a conflicting dependency.
  Software being installed: Spring Tool Suite 4 Main Feature 4.13.1.202201311654 (org.springframework.boot.ide.main.feature.feature.group 4.13.1.202201311654)
  Software currently installed: Spring IDE Core (required) 3.9.20.202112202132-RELEASE (org.springframework.ide.eclipse.feature.feature.group 3.9.20.202112202132-RELEASE)
  Only one of the following can be installed at once: 
    Spring IDE Buildship Integration 4.13.1.202201311654 (org.springframework.ide.eclipse.buildship30 4.13.1.202201311654)
    Spring IDE Buildship Integration 4.13.0.202112031748 (org.springframework.ide.eclipse.buildship30 4.13.0.202112031748)
  Cannot satisfy dependency:
    From: Spring Tool Suite 4 Main Feature 4.13.1.202201311654 (org.springframework.boot.ide.main.feature.feature.group 4.13.1.202201311654)
    To: org.eclipse.equinox.p2.iu; org.springframework.ide.eclipse.buildship30 [4.13.1.202201311654,4.13.1.202201311654]
  Cannot satisfy dependency:
    From: Spring IDE Core (required) 3.9.20.202112202132-RELEASE (org.springframework.ide.eclipse.feature.feature.group 3.9.20.202112202132-RELEASE)
    To: org.eclipse.equinox.p2.iu; org.springframework.ide.eclipse.buildship30 [4.13.0.202112031748,4.13.0.202112031748]
```

**To Reproduce**
Install STS 4.13.1 and then try to install the Spring Tools 3 Add-On (or vice versa)

**Comment by buyukim** [comment]
Okay, reading into some links on the various Eclipse Marketplace, it looks like Spring Tools 3 Add-On is no longer supported?  I will try to check out the XML features in STS 4

**Comment by martinlippert** [comment]
We haven't updated the STS3 Add-On Pack for STS4 to the latest STS 4.13.1 release yet, but I will look into this. Please note that the STS3 parts are in the minimal maintenance mode to provide a smooth transition to STS4, so I would like to encourage you to adopt STS4 and let us know if you find anything missing there that you used from STS3.

**Comment by martinlippert** [comment]
I updated the version of the STS3 Add-On Pack for Spring Tools 4 on the Eclipse Marketplace to the latest STS4 release, so that you can install this on top of the latest STS4 again.

This is available for the latest Spring Tools 4 version and the latest Eclipse release only.
