### ISSUE TITLE
Slow hyperlink popup when STS4 plugin is active

### ISSUE THREAD

**Issue by gayanper** [spring-projects/sts4#730]
Eclipse Versions:
Version: 2022-03 (4.23)
Build id: I20220131-0800

STS Versions:
Spring Boot Language Server Feature 4.13.1.202201310830 org.springframework.tooling.boot.ls.feature.feature.group VMware, Inc.
Spring IDE Boot Microservices Dash 4.13.1.202201311003 org.springframework.ide.eclipse.boot.dash.feature.feature.group Spring IDE Developers
Spring Tool Suite 4 Main Feature 4.13.1.202201311003 org.springframework.boot.ide.main.feature.feature.group VMware, Inc.
Spring XML Namespace Support 4.13.1.202201311003 org.springframework.ide.eclipse.xml.namespaces.feature.feature.group VMware, Inc.

- Open a large spring projects workspace
- Open a java file and trigger hyperlink popup by CTRL+Hover

![image](https://user-images.githubusercontent.com/7471994/152805675-4305a5d6-7847-4e66-bfe9-e559a305880c.png)

**Comment by gayanper** [comment]
Disabling hyperlinks from settings for lsp4e will remove the delay.

**Comment by BoykoAlex** [comment]
Don't think I'm seeing this issue...  Is this on Windows?

**Comment by gayanper** [comment]
I will check again collect some sample snapshots.

**Comment by martinlippert** [comment]
No further activity on this one since Feb 2022, so closing this one here for now. If you come across this again, please let us know and we can re-open this.
