### ISSUE TITLE
Spring boot não abre(acesso negado)

### ISSUE THREAD

**Issue by AgnaldoSouza47** [spring-projects/sts4#731]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Sample**

A link to a GitHub repository with a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example).

Reports that include a sample will take priority over reports that do not.
At times, we may require a sample, so it is good to try and include a sample up front.

**Comment by martinlippert** [comment]
Can you describe the problem in more detail, in English language, and with details how to reproduce this? That would be great.

**Comment by martinlippert** [comment]
No further information provided, so closing this one.
