### ISSUE TITLE
Could not initialize class org.testng.eclipse.util.ClassMethodsSuite

### ISSUE THREAD

**Issue by soundlift** [spring-projects/sts4#732]
OS:archlinux
sts:4.13.1.RELEASE
![深度截图_选择区域_20220211100612](https://user-images.githubusercontent.com/17586660/153528248-32cb72f9-701c-47e2-94b4-405616f97301.png)
![深度截图_选择区域_20220211100652](https://user-images.githubusercontent.com/17586660/153528252-6c514237-e9db-41be-80c4-ade4220e5db4.png)

**Comment by martinlippert** [comment]
Hey @soundlift, thanks for reporting this. From your screenshot, this looks more a problem with some TestNG integration rather than an STS4 issue itself. Can you provide a few steps how to reproduce this? We could at least have a look to see where the issue is coming from and then see where the best place is to report this to.

**Comment by soundlift** [comment]
yeah,my apologies.
testng downgrade to 7.4.0 can fix it

**Comment by divyakkothapalli** [comment]
Hello, 
I still encounter the same error could you help

**Comment by thomasillikkattil** [comment]
Hello,
I am also getting a similar issue when I try running a test case. This issue surprises me as I was able to run the same before smoothly. Kindly help if anyone has a solution for this issue.
Thanks

![image](https://user-images.githubusercontent.com/94443710/159118472-1885f2eb-262d-4075-b51d-1afa9a4340de.png)

**Comment by thomasillikkattil** [comment]
> Hello, I still encounter the same error could you help

I solved this issue by uninstalling and re-installing the TestNG plugin. 
To uninstall the TestNG from your eclipse, go to Help-> About Eclipse IDE-> Installation Details and enter TestNG in the search box. Uninstall all libraries related to TestNG. 
Install the same again. Hopefully, it will solve your problem.
Thanks

**Comment by martinlippert** [comment]
@divyakkothapalli Does the solution from @thomasillikkattil work for you?

**Comment by AbhijitBiradar** [comment]
Hi All,

I am facing the below error while executing TestNG test. I have tried all the above suggestions like re-install the TestNG plugin and downgrading the TestNG version but didn't work for me.

STS Error : Could not initialize class org.testng.eclipse.util.ClassMethodsSuite

Can anyone help me on this, please

![image](https://user-images.githubusercontent.com/37665481/170853255-7d9a2920-b493-4298-82d6-c0cb577bcc4a.png)

**Comment by martinlippert** [comment]
@AbhijitBiradar Can you provide a few more details about your setup (which version of Spring Tools you have installed, which TestNG extension you installed), and maybe refer to a sample project and a few steps how to reproduce this?

Also, does this problem happen with a regular Eclipse install as well? And did you maybe check the TestNG project for similar reports and solutions?

**Comment by AbhijitBiradar** [comment]
it worked for me. Many Thanks @soundlift
