### ISSUE TITLE
Errors running builder 'Maven Project Builder' '.

### ISSUE THREAD

**Issue by EXCELLENCE-CLASSES** [spring-projects/sts4#734]
**Describe the bug**
Errors running builder 'Maven Project Builder' on project 'StartProjectOnline-5'.
Error on Starting new starter project.
org/springframework/tooling/boot/ls/xml/XMLRootElementContentDescriber2$QualifiedElement

A link to a GitHub repository with a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example).

Reports that include a sample will take priority over reports that do not.
At times, we may require a sample, so it is good to try and include a sample up front.

**Comment by martinlippert** [comment]
Hey @EXCELLENCE-CLASSES, thanks for reporting this. Can you provide a sample project that helps us to reproduce this and a few steps how to reproduce this? Would also be interesting to see which version of Eclipse or STS4 you use.

**Comment by martinlippert** [comment]
No further feedback or details provided, so closing this for now. If you are coming across this using the latest versions of the Spring Tools for Eclipse, let us know and we can re-open anytime.
