### ISSUE TITLE
STS sts-4.13.1.RELEASE acting terribly slow

### ISSUE THREAD

**Issue by sudipta-adhikary** [spring-projects/sts4#740]
**Describe the bug**
I've installed sts-4.13.1.RELEASE today and it's responding awfully slow. Even when i click on any java class its seems to hang after 20 to 30 second it will become normal state. Please look into the .ini file for your reference.

-startup
plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.2.400.v20211117-0650
-product
org.springframework.boot.ide.branding.sts4
--launcher.defaultAction
openFile
-vm
plugins/org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_17.0.1.v20211116-1657/jre/bin
-vmargs
-Dosgi.requiredJavaVersion=11
-Dosgi.dataAreaRequiresExplicitInit=true
-Xms256m
-Xmx2048m
--illegal-access=permit
--add-modules=ALL-SYSTEM
-javaagent:C:\Data\Softwares\sts-4.13.1.RELEASE\lombok.jar

**To Reproduce**
Steps to reproduce the behavior.

**Sample**

A link to a GitHub repository with a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example).

Reports that include a sample will take priority over reports that do not.
At times, we may require a sample, so it is good to try and include a sample up front.

**Comment by martinlippert** [comment]
Can you remove the Lombok config from the install and the ini file and try again to see if that makes a difference?

**Comment by sudipta-adhikary** [comment]
Although removing lombok from IDE is not an option for me, I did remove it. Not much significant difference apparently.

**Comment by sudipta-adhikary** [comment]
It's little better this morning. 

1. I can see STS is not getting hung frequently
2. Hovering is little slower but working

**Comment by martinlippert** [comment]
@sudipta-adhikary Thanks for trying the Lombok removal, good to know that this is not the reason. Here are a few things that we could try to identify the reason for the slowness. It would be good to know where exactly the slowness happens (does it happen in the java editor only, does it happen all across the place, etc.)

- in case this is specific for opening and working in Java files, you could try to disable the Spring Boot language server to see if that makes a difference (via the Preferences -> Language Servers, then disable the Spring Boot Language Server for the Java Source File)
- in case disabling the language server solves this, you could enable the language server again and turn the console output on the Preferences -> Language Servers -> Spring Language Servers, then click on the Spring Boot item, this will push the logs of the language server process to the Console view and you could attach the output here
- you can capture a few thread dumps (using jps and jstack) of the IDE process while it is slow and attach the thread dumps here for further analysis
- you can attach a profiler to the IDE process and record a profiling session while it is slow and send us the profiling data for further analysis

**Comment by sudipta-adhikary** [comment]
Thanks Martin. Closing the ticket as of now.

**Comment by martinlippert** [comment]
@sudipta-adhikary You closed the ticket? Is this resolved already?

**Comment by sudipta-adhikary** [comment]
@martinlippert It's much better now apparently. Although I didn't have to try anything specific, just went better with time. Hence, closed the ticket for now.

**Comment by martinlippert** [comment]
@sudipta-adhikary Thanks for the additional feedback. Just wondering why it got better over time, sounds like it might be something outside of the IDE itself. Make sure you have your IDE as well as your projects on a local hard drive (and not a network-mounted drive) - since this can cause quite significant performance issues.

**Comment by sudipta-adhikary** [comment]
@martinlippert I got curious as well. To make it precise again, there were no significant changes in my workspace from the load perspective. As a matter of fact I keep my IDE clean always (just delete unused/projects not in currently use). I guess the windows update could play a difference also.

**Comment by raneymjohnGit** [comment]
My STS 4.18 is dead slow. If is click on a button or create new class, it hangs for 40 to 50 seconds. It is really annoying

**Comment by martinlippert** [comment]
@raneymjohnGit Can you share more details, please? Any specific operation being slow? Can you capture a few thread dumps while the IDE hangs for those 40 to 50 seconds and attach them here?

Also, maybe walking through the comment https://github.com/spring-projects/sts4/issues/740#issuecomment-1048495743 could be interesting and reveal more details.

**Comment by raneymjohnGit** [comment]
Thankyou Martin. It seems like the issue was the extraction. I was doing it through BreeZip tool to extract. 
So I downloaded the jar again, extracted with below command through command line and the issue is now resolved.

java -jar spring-tool-suite-xxx.jar

**Comment by martinlippert** [comment]
@raneymjohnGit Okay, thanks for letting us know and glad to hear that is runs fine now.
