### ISSUE TITLE
Can't update to 4.14.0

### ISSUE THREAD

**Issue by stephenlam520** [spring-projects/sts4#744]
I can't using "Help->check for updates" to update to 4.14.0.

My Version: 4.13.1.RELEASE
Build Id: 202201311654

error msg:
An error occurred while collecting items to be installed
session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,com.google.gson,2.8.9.v20220111-1409
No repository found containing: osgi.bundle,com.sun.jna,4.5.1.v20210503-0343
No repository found containing: osgi.bundle,org.apache.httpcomponents.httpclient.win,4.5.13.v20211010-1849
No repository found containing: osgi.bundle,org.apache.httpcomponents.httpcore,4.4.15.v20220209-2345
No repository found containing: osgi.bundle,org.apache.sshd.osgi,2.8.0.v20211227-1750
No repository found containing: osgi.bundle,org.apache.sshd.sftp,2.8.0.v20211227-1750
No repository found containing: osgi.bundle,org.apache.xerces,2.12.2.v20220131-0835
No repository found containing: osgi.bundle,org.bouncycastle.bcpg,1.70.0.v20220105-1522
No repository found containing: osgi.bundle,org.bouncycastle.bcpkix,1.70.0.v20220105-1522
No repository found containing: osgi.bundle,org.bouncycastle.bcprov,1.70.0.v20220105-1522
No repository found containing: osgi.bundle,org.bouncycastle.bcutil,1.70.0.v20220105-1522
No repository found containing: osgi.bundle,org.eclipse.ant.core,3.6.300.v20220214-2001
No repository found containing: osgi.bundle,org.eclipse.ant.launching,1.3.200.v20220214-2001
No repository found containing: osgi.bundle,org.eclipse.ant.ui,3.8.200.v20220214-2001
No repository found containing: osgi.bundle,org.eclipse.cdt.core.native,6.2.100.202202231938
No repository found containing: osgi.bundle,org.eclipse.cdt.core.win32.x86_64,6.0.500.202203091838
No repository found containing: osgi.bundle,org.eclipse.compare,3.8.300.v20220121-1000
No repository found containing: osgi.bundle,org.eclipse.core.databinding,1.11.0.v20220118-1028
No repository found containing: osgi.bundle,org.eclipse.core.databinding.observable,1.12.0.v20211231-1006
No repository found containing: osgi.bundle,org.eclipse.core.externaltools,1.2.200.v20220125-2302
No repository found containing: osgi.bundle,org.eclipse.core.filebuffers,3.7.200.v20220202-1008
No repository found containing: osgi.bundle,org.eclipse.core.filesystem,1.9.300.v20220121-1426
No repository found containing: osgi.bundle,org.eclipse.core.jobs,3.12.100.v20220120-1329
No repository found containing: osgi.bundle,org.eclipse.core.resources,3.16.100.v20220214-1012
No repository found containing: osgi.bundle,org.eclipse.core.runtime,3.24.100.v20220211-2001
No repository found containing: osgi.bundle,org.eclipse.debug.core,3.19.0.v20220125-2302
No repository found containing: osgi.bundle,org.eclipse.debug.ui,3.16.0.v20220228-0706
No repository found containing: osgi.bundle,org.eclipse.debug.ui.launchview,1.0.100.v20220121-1856
No repository found containing: osgi.bundle,org.eclipse.e4.core.commands,1.0.100.v20211204-1536
No repository found containing: osgi.bundle,org.eclipse.e4.tools.emf.ui,4.7.200.v20220114-0046
No repository found containing: osgi.bundle,org.eclipse.e4.ui.dialogs,1.3.200.v20211210-1500
No repository found containing: osgi.bundle,org.eclipse.e4.ui.workbench.renderers.swt,0.15.400.v20220308-0630
No repository found containing: osgi.bundle,org.eclipse.e4.ui.workbench.swt,0.16.400.v20220222-1128
No repository found containing: osgi.bundle,org.eclipse.ecf.provider.filetransfer,3.2.800.v20220215-0126
No repository found containing: osgi.bundle,org.eclipse.egit,6.1.0.202203080745-r
No repository found containing: osgi.bundle,org.eclipse.egit.core,6.1.0.202203080745-r
No repository found containing: osgi.bundle,org.eclipse.egit.doc,6.1.0.202203080745-r
No repository found containing: osgi.bundle,org.eclipse.egit.gitflow,6.1.0.202203080745-r
No repository found containing: osgi.bundle,org.eclipse.egit.gitflow.ui,6.1.0.202203080745-r
No repository found containing: osgi.bundle,org.eclipse.egit.ui,6.1.0.202203080745-r
No repository found containing: osgi.bundle,org.eclipse.emf.common,2.24.0.v20220123-0838
No repository found containing: osgi.bundle,org.eclipse.emf.common.ui,2.20.0.v20220226-1304
No repository found containing: osgi.bundle,org.eclipse.emf.ecore,2.26.0.v20220123-0838
No repository found containing: osgi.bundle,org.eclipse.emf.edit,2.17.0.v20220201-1551
No repository found containing: osgi.bundle,org.eclipse.emf.edit.ui,2.21.0.v20220226-1304
No repository found containing: osgi.bundle,org.eclipse.epp.mpc.core,1.9.3.v20220121-1317
No repository found containing: osgi.bundle,org.eclipse.epp.mpc.core.win32,1.9.3.v20220121-1317
No repository found containing: osgi.bundle,org.eclipse.epp.mpc.help.ui,1.9.3.v20220121-1317
No repository found containing: osgi.bundle,org.eclipse.epp.mpc.ui,1.9.3.v20220121-1317
No repository found containing: osgi.bundle,org.eclipse.epp.mpc.ui.css,1.9.3.v20220121-1317
No repository found containing: osgi.bundle,org.eclipse.equinox.common,3.16.0.v20220211-2322
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.artifact.repository,1.4.400.v20220223-1131
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.core,2.9.0.v20220210-1157
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.director,2.5.200.v20220127-1112
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.director.app,1.2.100.v20211220-1825
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.discovery.compatibility,1.2.200.v20220210-1157
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.engine,2.7.300.v20220209-1714
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.extensionlocation,1.4.100.v20220213-0541
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.jarprocessor,1.2.200.v20220207-0719
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.publisher,1.7.0.v20220127-1312
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.publisher.eclipse,1.4.2.v20220127-1658
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.reconciler.dropins,1.4.100.v20211217-1131
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.repository,2.6.0.v20220215-0840
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.touchpoint.natives,1.4.300.v20220210-1319
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.ui,2.7.400.v20220214-1604
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.ui.sdk,1.2.4.v20220213-1624
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.ui.sdk.scheduler,1.5.300.v20211214-1242
No repository found containing: osgi.bundle,org.eclipse.equinox.security,1.3.900.v20220108-1321
No repository found containing: osgi.bundle,org.eclipse.equinox.security.ui,1.3.200.v20220115-0654
No repository found containing: osgi.bundle,org.eclipse.help.base,4.3.600.v20220308-0310
No repository found containing: osgi.bundle,org.eclipse.help.webapp,3.10.600.v20220121-1305
No repository found containing: osgi.bundle,org.eclipse.jdt,3.18.1100.v20220308-0310
No repository found containing: osgi.bundle,org.eclipse.jdt.compiler.tool,1.3.100.v20211201-1611
No repository found containing: osgi.bundle,org.eclipse.jdt.core,3.29.0.v20220214-1307
No repository found containing: osgi.bundle,org.eclipse.jdt.core.manipulation,1.16.0.v20220214-0655
No repository found containing: osgi.bundle,org.eclipse.jdt.debug,3.19.100.v20220301-0551
No repository found containing: osgi.bundle,org.eclipse.jdt.debug.ui,3.12.600.v20220226-0801
No repository found containing: osgi.bundle,org.eclipse.jdt.doc.user,3.15.1300.v20220302-1215
No repository found containing: osgi.bundle,org.eclipse.jdt.junit,3.14.0.v20220127-1854
No repository found containing: osgi.bundle,org.eclipse.jdt.junit.core,3.11.200.v20220204-2234
No repository found containing: osgi.bundle,org.eclipse.jdt.launching,3.19.500.v20220125-2008
No repository found containing: osgi.bundle,org.eclipse.jdt.ui,3.26.0.v20220222-0629
No repository found containing: osgi.bundle,org.eclipse.jface,3.25.0.v20220218-1636
No repository found containing: osgi.bundle,org.eclipse.jface.text,3.20.0.v20220218-1549
No repository found containing: osgi.bundle,org.eclipse.jgit,6.1.0.202203080745-r
No repository found containing: osgi.bundle,org.eclipse.jgit.archive,6.1.0.202203080745-r
No repository found containing: osgi.bundle,org.eclipse.jgit.gpg.bc,6.1.0.202203080745-r
No repository found containing: osgi.bundle,org.eclipse.jgit.http.apache,6.1.0.202203080745-r
No repository found containing: osgi.bundle,org.eclipse.jgit.ssh.apache,6.1.0.202203080745-r
No repository found containing: osgi.bundle,org.eclipse.jgit.ssh.apache.agent,6.1.0.202203080745-r
No repository found containing: osgi.bundle,org.eclipse.jst.j2ee.core,1.4.300.v202201160251
No repository found containing: osgi.bundle,org.eclipse.jst.server.tomcat.core,1.1.1800.v202202161755
No repository found containing: osgi.bundle,org.eclipse.linuxtools.docker.core,5.6.0.202203082138
No repository found containing: osgi.bundle,org.eclipse.linuxtools.docker.docs,5.6.0.202203082138
No repository found containing: osgi.bundle,org.eclipse.linuxtools.docker.editor.ls,1.0.0.202203082138
No repository found containing: osgi.bundle,org.eclipse.linuxtools.docker.ui,5.6.0.202203082138
No repository found containing: osgi.bundle,org.eclipse.linuxtools.jdt.docker.launcher,1.0.0.202203082138
No repository found containing: osgi.bundle,org.eclipse.lsp4e.debug,0.13.2.202202011433
No repository found containing: osgi.bundle,org.eclipse.osgi,3.17.200.v20220215-2237
No repository found containing: osgi.bundle,org.eclipse.osgi.compatibility.state,1.2.600.v20220207-1403
No repository found containing: osgi.bundle,org.eclipse.pde,3.13.1800.v20220308-0310
No repository found containing: osgi.bundle,org.eclipse.pde.api.tools,1.2.800.v20220204-0559
No repository found containing: osgi.bundle,org.eclipse.pde.api.tools.ui,1.2.600.v20220210-1335
No repository found containing: osgi.bundle,org.eclipse.pde.core,3.15.100.v20220221-1314
No repository found containing: osgi.bundle,org.eclipse.pde.doc.user,3.14.1500.v20220302-1713
No repository found containing: osgi.bundle,org.eclipse.pde.ds.annotations,1.2.300.v20220210-1335
No repository found containing: osgi.bundle,org.eclipse.pde.ds.core,1.2.400.v20211215-1038
No repository found containing: osgi.bundle,org.eclipse.pde.ds.ui,1.2.200.v20211223-1606
No repository found containing: osgi.bundle,org.eclipse.pde.genericeditor.extension,1.1.200.v20211215-1038
No repository found containing: osgi.bundle,org.eclipse.pde.launching,3.9.600.v20220214-1856
No repository found containing: osgi.bundle,org.eclipse.pde.runtime,3.7.300.v20211215-1038
No repository found containing: osgi.bundle,org.eclipse.pde.spy.core,1.0.100.v20211229-0835
No repository found containing: osgi.bundle,org.eclipse.pde.spy.css,0.12.200.v20211229-0835
No repository found containing: osgi.bundle,org.eclipse.pde.spy.model,0.12.200.v20211229-0835
No repository found containing: osgi.bundle,org.eclipse.pde.spy.preferences,0.12.200.v20211229-0835
No repository found containing: osgi.bundle,org.eclipse.pde.ua.ui,1.2.300.v20211215-1133
No repository found containing: osgi.bundle,org.eclipse.pde.ui,3.13.400.v20220215-1440
No repository found containing: osgi.bundle,org.eclipse.pde.ui.templates,3.7.500.v20220202-1226
No repository found containing: osgi.bundle,org.eclipse.platform,4.23.0.v20220308-0310
No repository found containing: osgi.bundle,org.eclipse.platform.doc.user,4.23.0.v20220302-1425
No repository found containing: osgi.bundle,org.eclipse.rcp,4.23.0.v20220308-0310
No repository found containing: osgi.bundle,org.eclipse.search,3.14.100.v20220120-1549
No repository found containing: osgi.bundle,org.eclipse.swt,3.119.0.v20220223-1102
No repository found containing: osgi.bundle,org.eclipse.swt.win32.win32.x86_64,3.119.0.v20220223-1102
No repository found containing: osgi.bundle,org.eclipse.team.core,3.9.300.v20220204-0611
No repository found containing: osgi.bundle,org.eclipse.team.ui,3.9.200.v20211130-1532
No repository found containing: osgi.bundle,org.eclipse.text.quicksearch,1.1.300.v20211203-1705
No repository found containing: osgi.bundle,org.eclipse.tm.terminal.connector.ssh,4.7.200.202201122357
No repository found containing: osgi.bundle,org.eclipse.tm.terminal.control,5.3.100.202202251626
No repository found containing: osgi.bundle,org.eclipse.tm.terminal.view.core,4.8.200.202201122357
No repository found containing: osgi.bundle,org.eclipse.tm.terminal.view.ui,4.10.200.202201122357
No repository found containing: osgi.bundle,org.eclipse.ui,3.201.0.v20220124-1108
No repository found containing: osgi.bundle,org.eclipse.ui.genericeditor,1.2.200.v20211217-1247
No repository found containing: osgi.bundle,org.eclipse.ui.ide,3.18.500.v20220215-1304
No repository found containing: osgi.bundle,org.eclipse.ui.ide.application,1.4.300.v20220114-0859
No repository found containing: osgi.bundle,org.eclipse.ui.monitoring,1.2.100.v20220204-0910
No repository found containing: osgi.bundle,org.eclipse.ui.navigator.resources,3.8.400.v20220203-1803
No repository found containing: osgi.bundle,org.eclipse.ui.themes,1.2.1700.v20220210-1145
No repository found containing: osgi.bundle,org.eclipse.ui.trace,1.2.100.v20211215-1038
No repository found containing: osgi.bundle,org.eclipse.ui.workbench,3.125.0.v20220308-0722
No repository found containing: osgi.bundle,org.eclipse.ui.workbench.texteditor,3.16.400.v20220218-1619
No repository found containing: osgi.bundle,org.eclipse.wst.css.core,1.3.1.v202201311924
No repository found containing: osgi.bundle,org.eclipse.wst.html.core,1.4.100.v202112071542
No repository found containing: osgi.bundle,org.eclipse.wst.server.discovery,1.3.400.v202201160313
No repository found containing: osgi.bundle,org.eclipse.wst.sse.core,1.2.700.v202112071542
No repository found containing: osgi.bundle,org.eclipse.wst.xml.core,1.2.500.v202201311924
No repository found containing: osgi.bundle,org.eclipse.xsd,2.18.0.v20211216-0527
No repository found containing: osgi.bundle,org.eclipse.xtext.xbase.lib,2.26.0.v20220228-0748
No repository found containing: osgi.bundle,org.springframework.boot.ide.branding,4.14.0.202203131612-RELEASE
No repository found containing: osgi.bundle,org.apache.httpcomponents.client5.httpclient5,5.1.2.v20211217-1500
No repository found containing: osgi.bundle,org.apache.httpcomponents.client5.httpclient5-win,5.1.2.v20211217-1500
No repository found containing: osgi.bundle,org.apache.httpcomponents.core5.httpcore5,5.1.2.v20211217-1500
No repository found containing: osgi.bundle,org.apache.httpcomponents.core5.httpcore5-h2,5.1.2.v20211217-1500
No repository found containing: org.eclipse.update.feature,org.eclipse.e4.rcp,4.23.0.v20220308-0630
No repository found containing: org.eclipse.update.feature,org.eclipse.ecf.filetransfer.feature,3.14.1800.v20220215-0126
No repository found containing: org.eclipse.update.feature,org.eclipse.ecf.filetransfer.httpclient5.feature,1.1.600.v20220215-0126
No repository found containing: osgi.bundle,org.eclipse.ecf.provider.filetransfer.httpclient5,1.0.300.v20220215-0126
No repository found containing: osgi.bundle,org.eclipse.ecf.provider.filetransfer.httpclient5.win32,1.0.400.v20220109-1926
No repository found containing: org.eclipse.update.feature,org.eclipse.egit,6.1.0.202203080745-r
No repository found containing: org.eclipse.update.feature,org.eclipse.egit.gitflow.feature,6.1.0.202203080745-r
No repository found containing: org.eclipse.update.feature,org.eclipse.emf.common,2.25.0.v20220123-0838
No repository found containing: org.eclipse.update.feature,org.eclipse.emf.ecore,2.27.0.v20220123-0838
No repository found containing: org.eclipse.update.feature,org.eclipse.epp.mpc,1.9.3.v20220121-1317
No repository found containing: org.eclipse.update.feature,org.eclipse.equinox.p2.core.feature,1.6.1300.v20220223-1131
No repository found containing: org.eclipse.update.feature,org.eclipse.equinox.p2.discovery.feature,1.2.1100.v20220210-1157
No repository found containing: org.eclipse.update.feature,org.eclipse.equinox.p2.extras.feature,1.4.1500.v20220223-1131
No repository found containing: org.eclipse.update.feature,org.eclipse.equinox.p2.rcp.feature,1.4.1500.v20220223-1131
No repository found containing: org.eclipse.update.feature,org.eclipse.equinox.p2.user.ui,2.4.1500.v20220223-1131
No repository found containing: org.eclipse.update.feature,org.eclipse.help,2.3.900.v20220308-0310
No repository found containing: org.eclipse.update.feature,org.eclipse.jdt,3.18.1100.v20220308-0310
No repository found containing: org.eclipse.update.feature,org.eclipse.jgit,6.1.0.202203080745-r
No repository found containing: org.eclipse.update.feature,org.eclipse.jgit.gpg.bc,6.1.0.202203080745-r
No repository found containing: org.eclipse.update.feature,org.eclipse.jgit.http.apache,6.1.0.202203080745-r
No repository found containing: org.eclipse.update.feature,org.eclipse.jgit.ssh.apache,6.1.0.202203080745-r
No repository found containing: org.eclipse.update.feature,org.eclipse.jst.server_adapters.ext.feature,3.4.400.v202202161755
No repository found containing: org.eclipse.update.feature,org.eclipse.pde,3.14.1100.v20220308-0310
No repository found containing: osgi.bundle,org.eclipse.pde.spy.bundle,0.12.100.v20220125-1245
No repository found containing: osgi.bundle,org.eclipse.pde.spy.context,1.0.200.v20220218-1824
No repository found containing: org.eclipse.update.feature,org.eclipse.platform,4.23.0.v20220308-0722
No repository found containing: binary,org.eclipse.platform_root,4.23.0.v20220308-0722
No repository found containing: org.eclipse.update.feature,org.eclipse.rcp,4.23.0.v20220308-0722
No repository found containing: binary,org.eclipse.rcp_root,4.23.0.v20220308-0722
No repository found containing: org.eclipse.update.feature,org.eclipse.tips.feature,0.2.1700.v20220220-0850
No repository found containing: org.eclipse.update.feature,org.eclipse.tm.terminal.connector.local.feature,10.6.0.202201122357
No repository found containing: org.eclipse.update.feature,org.eclipse.tm.terminal.connector.ssh.feature,10.6.0.202201122357
No repository found containing: org.eclipse.update.feature,org.eclipse.tm.terminal.connector.telnet.feature,10.6.0.202201122357
No repository found containing: org.eclipse.update.feature,org.eclipse.tm.terminal.control.feature,10.6.0.202202251626
No repository found containing: org.eclipse.update.feature,org.eclipse.tm.terminal.feature,10.6.0.202201121907
No repository found containing: org.eclipse.update.feature,org.eclipse.tm.terminal.view.feature,10.6.0.202201122357
No repository found containing: org.eclipse.update.feature,org.eclipse.wst.jsdt.feature,2.4.0.v202201270041
No repository found containing: org.eclipse.update.feature,org.eclipse.wst.server_ui.feature,3.3.1300.v202201160314
No repository found containing: org.eclipse.update.feature,org.eclipse.wst.web_core.feature,3.25.0.v202201311924
No repository found containing: org.eclipse.update.feature,org.eclipse.wst.web_ui.feature,3.25.0.v202201311924
No repository found containing: org.eclipse.update.feature,org.eclipse.wst.xml_core.feature,3.25.0.v202201311924
No repository found containing: org.eclipse.update.feature,org.eclipse.wst.xml_ui.feature,3.25.0.v202201160258
No repository found containing: org.eclipse.update.feature,org.springframework.boot.ide.branding.feature,4.14.0.202203131612
No repository found containing: binary,org.springframework.boot.ide.branding.sts4.executable.win32.win32.x86_64,4.14.0.202203131612

**Comment by martinlippert** [comment]
Hey @stephenlam520, this usually happens when the internal update mechanism has stale cache data. The easiest way to solve this is to go to the Preferences -> Install/Update -> Available Update Sites, export them all to a file, then delete them all and restart the IDE. After that, re-import them again from the file and do a "Check for Updates" again. This usually solves the stale cache data issue. Hope this helps.

**Comment by stephenlam520** [comment]
@martinlippert  Thanks, It worked.

**Comment by martinlippert** [comment]
@stephenlam520 Great to hear that and sorry for the inconvenience.
