### ISSUE TITLE
Could not initialize class org.testng.eclipse.util.ClassMethodsSuite

### ISSUE THREAD

**Issue by thomasillikkattil** [spring-projects/sts4#745]
**Describe the bug**
It returns an error message "Could not initialize class org.testng.eclipse.util.ClassMethodsSuite" when I try running a simple TestNG class.

**Sample**
Following is my code. There is nothing complicated:

package tutorialPackage;
import org.testng.annotations.Test;
public class TestClass {	
	@Test
	public void demo() {
		System.out.println("Hello");
	}
}

When I run the above code, I get an error message as:
![testng_error](https://user-images.githubusercontent.com/94443710/159208652-75c29958-6497-4a5d-970a-f125038ac56b.jpg)

I tried referring "https://github.com/spring-projects/sts4/issues/732". Still, I get the same issue. Tried re-installing the TestNG plugin after uninstalling the same. It has not solved the problem yet. 

Kindly suggest a solution to this problem.

**Comment by thomasillikkattil** [comment]
I solved this issue by uninstalling and re-installing the TestNG plugin.
To uninstall the TestNG from your eclipse, go to Help-> About Eclipse IDE-> Installation Details and enter TestNG in the search box. Uninstall all libraries related to TestNG.
Install the same again. Hopefully, it will solve your problem.
Thanks

**Comment by martinlippert** [comment]
Thanks for letting us know and glad to hear you found a solution here.
