### ISSUE TITLE
[vscode-spring-boot] Support navigating to a Spring property file when inspecting on @Value annotations 

### ISSUE THREAD

**Issue by nickzhums** [spring-projects/sts4#761]
Currently, when we have a @Value annotation on a variable and there is corresponding value in a Spring property file, our extensions won’t allow us to directly navigate to this property file and inspect this value. 

![1649314440(1)](https://user-images.githubusercontent.com/56864335/162138225-81fdf31f-55ac-403a-b17e-64a97124072f.png)

(cc: @martinlippert @Eskibear)

**Comment by BoykoAlex** [comment]
Fixed with ca0bc47c9317cc88bcfc07e29ce23af569eac5d4 

(Looks for value definition within the same project. If values in case of not found in the current project should be looked up in upstream projects support required then please create a new issue)

**Comment by nickzhums** [comment]
nice!
