### ISSUE TITLE
Random error when trying to run springboot app inside a multi module setup

### ISSUE THREAD

**Issue by gayanper** [spring-projects/sts4#770]
- Open a multi module spring boot project where the boot app is in one child module and other components such as REST controllers and repositories are in respective sub modules.
- While no editor is opened, try to run the boot app using the spring boot app launcher already created
- The following error is shown

```
Errors occurred during the build.
Errors running builder 'Integrated External Tool Builder' on project 'random-childmodule'.
The builder launch configuration could not be found.
The builder launch configuration could not be found.
````

Workaround:
Open the SpringBoot application class and make sure it is the active editor. Then the launcher works without any errors

STS4 Versions:
Spring Tool Suite 4 Main Feature 4.14.1.202204131622 org.springframework.boot.ide.main.feature.feature.group VMware, Inc.

Eclipse Version:
Version: 2022-06 (4.24)
Build id: I20220419-1800

**Comment by gayanper** [comment]
This can be also reproduced if the active editor is not from the same child module which contains the spring boot app class while the launcher is triggered

**Comment by martinlippert** [comment]
Hey @gayanper, can you create/attach a sample project? That would be awesome!!!

**Comment by gayanper** [comment]
@martinlippert sure i will create one very similar in coming days and attach.

**Comment by martinlippert** [comment]
Hey @gayanper, any news on this?

**Comment by gayanper** [comment]
No it didn’t occurred again, lets close this
