### ISSUE TITLE
vscode-sts: an edge case of workspace symbol for @PutMapping

### ISSUE THREAD

**Issue by Eskibear** [spring-projects/sts4#781]
Originally reported from an interview. See https://github.com/microsoft/vscode-spring-boot-dashboard/issues/180#issuecomment-1152043751

```java
// a)
@PutMapping("")
/ * a method definition */

// b)
@PutMapping
/ * a method definition */

```
For style a, it works well. But for style b, corresponding workspace symbol doesn't indicate it's a "PUT".

**Comment by martinlippert** [comment]
The same problem happens for `@GetMapping` as well, so probably a more general problem. Let me investigate this.

**Comment by martinlippert** [comment]
Found the issue, this should be fixed now. Will be available with the next release (probably next week).
Thanks for the simple-to-reproduce bug report here, much appreciated.
