### ISSUE TITLE
VScode incorrectly suggests removing @Autowired annotation from methods

### ISSUE THREAD

**Issue by jeffduhamel** [spring-projects/sts4#787]
**Describe the bug**
Following the most recent update, VScode quick fix and Problem view are incorrectly suggesting removing @Autowired annotation from autowired methods.  The issue is flagged as JAVA_AUTOWIRED_CONSTRUCTOR, but these are not constructors.

![image](https://user-images.githubusercontent.com/11542780/173908860-ae525b77-58ad-4a01-bf4e-2d49912cdd09.png)

**Comment by BoykoAlex** [comment]
Great, thanks for reporting this. Will be adjusted.

**Comment by BoykoAlex** [comment]
The fix is 382d0bbac672b1180bf6189938491d2786e74512.
We'll be creating another release in a few days from now to include this fix. Once the RC is tested I'll mark it as fixed.

**Comment by BoykoAlex** [comment]
@jeffduhamel here is the RC that has it fixed: https://s3.us-west-1.amazonaws.com/s3-test.spring.io/sts4/vscode-extensions/snapshots/vscode-spring-boot-1.36.0-RC.1.vsix
