### ISSUE TITLE
Not able to extract the new version of spring-tool-suite-4-4.15.0.RELEASE-e4.24.0-win32.win32.x86_64.self-extracting.jar on windows 11

### ISSUE THREAD

**Issue by shankarwww** [spring-projects/sts4#788]
I am not able to extract the jar file "spring-tool-suite-4-4.15.0.RELEASE-e4.24.0-win32.win32.x86_64.self-extracting.jar" on my windows 11. Below is the error that is coming in the alert :

![image](https://user-images.githubusercontent.com/18091406/173939066-de051e00-0aae-45f3-a8a3-dc1b9e091d9b.png)

**Comment by wsw186** [comment]
SAME ISSUE ON WIN10

**Comment by saikrishnayadav1998** [comment]
same issue for me on win 11

**Comment by martinlippert** [comment]
We are working on a fix, this is probably the same difficulty that we had with the VSCode extension not installing on Windows, so I am confident that we can get this fixed quickly. So please stay tuned for a new version to be released.

**Comment by martinlippert** [comment]
You can grab the latest 4.15.1 snapshot build from here: https://dist.springsource.com/snapshot/STS4/nightly-distributions.html, extracting on Windows should work again. Release coming up soon, but if you want to give this snapshot version a try to verify, that would be appreciated.

**Comment by martinlippert** [comment]
Grab the latest spring-tool-suite-4-4.15.1.CI-B2725-e4.24.0-win32.win32.x86_64.self-extracting.jar (or whatever snapshot build version there is for self-extracting on Windows)

**Comment by wsw186** [comment]
> Grab the latest spring-tool-suite-4-4.15.1.CI-B2725-e4.24.0-win32.win32.x86_64.self-extracting.jar (or whatever snapshot build version there is for self-extracting on Windows)

spring-tool-suite-4-4.15.1.CI-B2725-e4.24.0-win32.win32.x86_64.self-extracting.jar  is ok for me on win10

**Comment by hantsy** [comment]
Same issue on Windows 10 with Java 17.

```bash 
sts-4.15.0.RELEASE/plugins/org.springframework.tooling.boot.ls_1.34.0.202206140708/servers/spring-boot-language-server/META-INF/third-party-open-source-licenses/bsd 3-clause "new" or "revised" license (bsd-3-clause) - apl-v10.html
...

\org.springframework.tooling.boot.ls_1.34.0.202206140708\servers\spring-boot-language-server\META-INF\third-party-open-source-licenses\bsd 3-clause "new" or "revised" license (bsd-3-clause) - apl-v10.html (The filename, directory name, or volume label syntax is incorrect)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
        at SelfExtractor.unpack(SelfExtractor.java:147)
        at SelfExtractor.run(SelfExtractor.java:47)
        at SelfExtractor.main(SelfExtractor.java:31)
```

**Comment by hantsy** [comment]
It seems a license file is not found, how to skip it?

**Comment by martinlippert** [comment]
@hantsy A fixed version of the distribution will be released shortly.

**Comment by mast76** [comment]
I have a similar issue with spring-tool-suite-4-4.19.1.RELEASE-e4.28.0-win32.win32.x86_64.self-extracting.jar
