### ISSUE TITLE
Failing to install STS4 on Eclipse 2018-09 RC1

### ISSUE THREAD

**Issue by gayanper** [spring-projects/sts4#79]
```
An error occurred while collecting items to be installed
session context was:(profile=epp.package.java, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.springsource.ide.eclipse.commons.livexp,3.9.6.201808291957-CI-B411
No repository found containing: org.eclipse.update.feature,org.springframework.boot.ide.main.feature,4.0.0.201809050738-M15
No repository found containing: osgi.bundle,org.springframework.ide.eclipse.boot,3.9.6.201808300249-CI-B2053
No repository found containing: osgi.bundle,org.springframework.ide.eclipse.boot.launch,3.9.6.201808300249-CI-B2053
No repository found containing: osgi.bundle,org.springframework.ide.eclipse.boot.restart,3.9.6.201808300249-CI-B2053
No repository found containing: osgi.bundle,org.springframework.ide.eclipse.boot.templates,3.9.6.201808300249-CI-B2053
No repository found containing: osgi.bundle,org.springframework.ide.eclipse.boot.validation,3.9.6.201808300249-CI-B2053
No repository found containing: osgi.bundle,org.springframework.ide.eclipse.boot.wizard,3.9.6.201808300249-CI-B2053
No repository found containing: osgi.bundle,org.springframework.ide.eclipse.buildship20,3.9.6.201808300249-CI-B2053
No repository found containing: osgi.bundle,org.springframework.ide.eclipse.editor.support,3.9.6.201808300249-CI-B2053
No repository found containing: osgi.bundle,org.springframework.ide.eclipse.imports,3.9.6.201808300249-CI-B2053
No repository found containing: osgi.bundle,org.springframework.tooling.boot.ls,0.6.0.201809050727
No repository found containing: org.eclipse.update.feature,org.springframework.tooling.boot.ls.feature,4.0.0.201809050727
No repository found containing: osgi.bundle,org.springframework.tooling.jdt.ls.commons,1.0.0.201809050727
No repository found containing: osgi.bundle,org.springframework.tooling.ls.eclipse.commons,4.0.0.201809050727
No repository found containing: osgi.bundle,org.springframework.tooling.ls.eclipse.gotosymbol,4.0.0.201809050727
No repository found containing: osgi.bundle,org.springsource.ide.eclipse.commons.completions,3.9.6.201808291957-CI-B411
No repository found containing: osgi.bundle,org.springsource.ide.eclipse.commons.core,3.9.6.201808291957-CI-B411
No repository found containing: osgi.bundle,org.springsource.ide.eclipse.commons.frameworks.core,3.9.6.201808291957-CI-B411
No repository found containing: osgi.bundle,org.springsource.ide.eclipse.commons.frameworks.ui,3.9.6.201808291957-CI-B411
No repository found containing: osgi.bundle,org.springsource.ide.eclipse.commons.ui,3.9.6.201808291957-CI-B411
```

It also shows unwanted components as part of the STS4 update site
![image](https://user-images.githubusercontent.com/7471994/46030277-53d7ef80-c113-11e8-8193-90f412a64377.png)

**Comment by kdvolder** [comment]
This is a bit strange the screenshot shows using a release update site, yet the error message shows that its trying to find (and failing) snapshot artefacts. Snapshots are somewhat transient and its not a surprise they go missing, but what is strange is, they show up at all when you are trying to install from a release update site.

If you want to install release, please check the 'Available update sites' from Eclipse preference and if you see any snapshot or nightly update sites there, make sure to remove or disable them. I suspect you are having some snapshot sites there and they are muddying the waters when trying to install from release update site.

**Comment by martinlippert** [comment]
OK, the stuff that shows up in the screenshot as being "too much" is coming from the Eclipse 2018-09 update site that I added to our "latest" composite in order to let people update to that version of Eclipse via that p2 URL, but I think that doesn't make a lot of sense anymore. I removed that, it should not show up anymore.

Regarding the `no repository found...` messages, those are typically coming from stale cache data (could be caused by various reasons). You should go to the preferences for the available update sites, select the STS4 update site, and press `Reload`. That usually helps to resolve that. To be sure, you could also hit the `Reload` button for the other update URLs, too (just to be sure).

Also make sure that there isn't another STS4 update site in that list, as Kris mentioned.

Hope that makes it work.

**Comment by martinlippert** [comment]
There will be an Eclipse marketplace entry for this shortly, in case you would like to wait for that... :-)

**Comment by gayanper** [comment]
Now the unwanted entries are gone, but still the `no repository found...` error is there even after reloading the update site.

**Comment by gayanper** [comment]
Cannot install even in a fresh eclipse installation either :(

**Comment by martinlippert** [comment]
@gayanper that is super strange, especially with a fresh Eclipse install. Do you get the exact same error message when trying to install into a fresh Eclipse?

Can you try to use this p2 URL, too? Maybe that one helps:
http://download.springsource.com/release/TOOLS/sts4/update/4.0.0.RELEASE/e4.9

Or if that produces the same issue, would be interesting if this URL makes a difference:
http://dist.springsource.com/release/TOOLS/sts4/update/4.0.0.RELEASE/e4.9

And please paste the full error message again, would be great to see the details here.

**Comment by gayanper** [comment]
The first update site in the above comment works on both fresh installation and a existing installations 👍

**Comment by martinlippert** [comment]
Great to hear that the other update site worked for you. So it looks like there was indeed some stale cache data in your installation that you could workaround by using the other update site URL (which technically points to the same one than the one you used first).

If someone else hits this issue, another option would be to completely delete the update site URL from the preferences, restart Eclipse, and go to the `Install New Software` dialog again. This makes the stale cache data go away. Sometimes pressing `Reload` is enough, sometimes you need to remove it completely, restart, and add it back.
