### ISSUE TITLE
error when install spring tools 3 add-on parallel with sts 4

### ISSUE THREAD

**Issue by xiexie2904** [spring-projects/sts4#800]
I installed spring tool suite 4  and after that I install spring tools 3 add-on but I meet these problems

I have search but can't find the same problems and solutions
![image](https://user-images.githubusercontent.com/77282670/182017301-6334ea87-26d9-4276-a634-6f04c6f917ea.png)

![image](https://user-images.githubusercontent.com/77282670/182017306-bbc781a1-9215-440e-bc0c-0895f523116b.png)

so why these problems happened and any suggestions to fix these error ?

thanks in advance

**Comment by martinlippert** [comment]
We do not ship a version of the STS3 Add-On anymore that in compatible with the latest Spring Tools 4 or Eclipse distributions: https://spring.io/blog/2022/06/14/goodbye-spring-ide-welcome-spring-tools-4
