### ISSUE TITLE
ask user to save dirty editors before deploying on docker

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#803]
I have a dirty editor with unsaved changes open.

When I start the corresponding project from the boot dashboard, a dialog shows up and asks me whether I want to save the dirty editor or not. This is correct.

When I deploy the app on docker using the boot dashboard, the build runs and the app gets deployed, and a dialog that asks me about the dirty editor shows up afterwards (which doesn't make a lot of sense). This dialog should be shown upfront, before the build is kicked off.

**Comment by nierajsingh** [comment]
Pushed fix. User is now prompted to save when starting/debugging a docker app if there are dirty editors in the project.
