### ISSUE TITLE
Failed to create the part's controls

### ISSUE THREAD

**Issue by WangShaolin-GitHub** [spring-projects/sts4#805]
Hi, Eclipse > SVN > Team > Display the resource history and open the POM file,
![image](https://user-images.githubusercontent.com/35981782/182337972-48a0bb25-9b70-4952-9d8f-46c1c17938ef.png)

**Comment by martinlippert** [comment]
The stack trace doesn't reveal anything special about the Spring Tools being involved here, so I am guessing that this is maybe an issue of the SVN extension and m2e. Which SVN extension did you install? And which version of Eclipse/Spring Tools do you use?

I guess the best would be to reproduce this with a plain Eclipse installation with added SVN and m2e extensions. In case we can reproduce the issue in that environment, we should report this against the m2e project (probably).

If you provide me the additional versions I can try to reproduce this - although it might be easier for you to try this out yourself quickly... :-)

**Comment by WangShaolin-GitHub** [comment]
![image](https://user-images.githubusercontent.com/35981782/182503602-2356fd0d-a36c-4d97-9da4-4319c95d66ec.png)
![image](https://user-images.githubusercontent.com/35981782/182503622-f3fc8085-5a4d-4821-bfe3-be8fc888b2fa.png)
![image](https://user-images.githubusercontent.com/35981782/182503659-b6662421-f607-4d44-b0de-dcbdd78ae45b.png)

**Comment by martinlippert** [comment]
Thanks @WangShaolin-GitHub for investigating this a bit deeper and for letting us know. So we can close the issue here and you let the SVN team know about it instead?

**Comment by WangShaolin-GitHub** [comment]
Thank you for your
