### ISSUE TITLE
Copied files should retain copyright ownership

### ISSUE THREAD

**Issue by fbricon** [spring-projects/sts4#807]
I was browsing the STS4 changelog when I noticed you guys fixed https://github.com/spring-projects/sts4/issues/704 by copying jdt.ls' ParentProcessWatcher.java. Surely an honest mistake but you can't change the original copyright owner from https://github.com/eclipse/eclipse.jdt.ls/blob/64b15c5a9e5b11f62ceb5163ceb6930d5dea7129/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ParentProcessWatcher.java

https://github.com/spring-projects/sts4/blob/22eb13cc9fa4a3d92e4381ab6a69216404f0aa9b/headless-services/commons/commons-language-server/src/main/java/org/springframework/ide/vscode/commons/languageserver/util/ParentProcessWatcher.java#L1-L10

Original license is EPLv2. It might be OK to downgrade, but I dunno, IANAL

cc @martinlippert

**Comment by martinlippert** [comment]
Hey @fbricon, you are absolutely right, this file should keep the original copyright notice, absolutely no question about this. Not sure why this happened, very sorry about this. Many thanks for pointing this out.

Fix is already pushed to the repo.

**Comment by fbricon** [comment]
Thanks @martinlippert!
