### ISSUE TITLE
[vscode] Spring Boot Tools slow down code complete

### ISSUE THREAD

**Issue by degbug** [spring-projects/sts4#808]
**Describe the bug**
when I install Spring Boot Tools in vscode, it slow down the speed of code completions.

![Kapture 2022-08-05 at 11 47 36](https://user-images.githubusercontent.com/11486075/182998223-2c3f1138-f2f7-43d8-a425-7d4aae92d138.gif)

I seen the plugin log show :
```
11:47:32.155 [pool-8-thread-1] INFO  o.s.i.v.c.l.u.SimpleTextDocumentService - change message work done in 1723ms
```

**To Reproduce**

**Sample**

https://github.com/degbug/demo

this is the log file:
[boot.log.txt](https://github.com/spring-projects/sts4/files/9265115/boot.log.txt)

**Comment by martinlippert** [comment]
Thanks for reporting this @degbug. Slowing down typing speed or completion performance is an absolute no-go here. We need to investigate. Thanks for attaching the log output, that is a great starting point.

From what I can see, it looks like the slowdown happens sometimes, and sometimes it doesn't. Did you observe any special action or sequence of activities that triggers the slowdown?

**Comment by degbug** [comment]
> Thanks for reporting this @degbug. Slowing down typing speed or completion performance is an absolute no-go here. We need to investigate. Thanks for attaching the log output, that is a great starting point.
> 
> From what I can see, it looks like the slowdown happens sometimes, and sometimes it doesn't. Did you observe any special action or sequence of activities that triggers the slowdown?

@martinlippert No,  I didn't observed.  When I first open the project and first typing is quickly, but then it become very easy to triggers the slowdown. But I don't know what cause this. 
The log file contains many error log, this may affect this?

**Comment by youngm** [comment]
I'm having a similar issue with 4.15.2 on eclipse. I didn't have time to dig deep into it. I had to revert to 4.15.1

**Comment by BoykoAlex** [comment]
@degbug please try this vsix and let us know if this works better for you: https://s3.us-west-1.amazonaws.com/s3-test.spring.io/sts4/vscode-extensions/snapshots/vscode-spring-boot-1.38.0-202208052243.vsix

**Comment by degbug** [comment]
> @degbug please try this vsix and let us know if this works better for you: https://s3.us-west-1.amazonaws.com/s3-test.spring.io/sts4/vscode-extensions/snapshots/vscode-spring-boot-1.38.0-202208052243.vsix @youngm please try upgrading STS eclipse from the snapshot update site. Should be good to update on Monday. Curious if it works any better: https://dist.springsource.com/snapshot/TOOLS/sts4/nightly/e4.24

@BoykoAlex I have try [vscode-spring-boot-1.38.0-202208052243.vsix](https://s3.us-west-1.amazonaws.com/s3-test.spring.io/sts4/vscode-extensions/snapshots/vscode-spring-boot-1.38.0-202208052243.vsix), It works better than before. but still work slow than disable the vscode-spring-boot extensions.

this is the log file:
[boot.log6.txt](https://github.com/spring-projects/sts4/files/9274298/boot.log6.txt)

And I saw error in log:
```
11:19:21.762 [pool-3-thread-1] ERROR o.s.i.v.b.j.utils.SymbolCacheOnDisc - cannot write symbol cache
java.io.FileNotFoundException: /Users/degbug/.sts4/.symbolCache/degbug-auto-task-java--A71297B3246476FA87DEC5893F93A8BB.json (Too many open files)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(Unknown Source)
	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
	at java.base/java.io.FileWriter.<init>(Unknown Source)
	at org.springframework.ide.vscode.boot.java.utils.SymbolCacheOnDisc.save(SymbolCacheOnDisc.java:259)
	at org.springframework.ide.vscode.boot.java.utils.SymbolCacheOnDisc.update(SymbolCacheOnDisc.java:236)
	at org.springframework.ide.vscode.boot.java.utils.SpringIndexerJava.scanFilesInternally(SpringIndexerJava.java:316)
	at org.springframework.ide.vscode.boot.java.utils.SpringIndexerJava.scanAffectedFiles(SpringIndexerJava.java:347)
	at org.springframework.ide.vscode.boot.java.utils.SpringIndexerJava.scanFiles(SpringIndexerJava.java:191)
	at org.springframework.ide.vscode.boot.java.utils.SpringIndexerJava.updateFiles(SpringIndexerJava.java:145)
	at org.springframework.ide.vscode.boot.app.SpringSymbolIndex.lambda$updateItems$28(SpringSymbolIndex.java:727)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by BoykoAlex** [comment]
@degbug does it feel slower than 1.36 of spring boot tools extension?

**Comment by degbug** [comment]
> 

@BoykoAlex I tried and feel it slower than 1.36.

[vscode-spring-boot-1.38.0-202208052243.vsix](https://s3.us-west-1.amazonaws.com/s3-test.spring.io/sts4/vscode-extensions/snapshots/vscode-spring-boot-1.38.0-202208052243.vsix):
![Kapture 2022-08-07 at 19 33 16](https://user-images.githubusercontent.com/11486075/183288584-a2732d8b-91b7-4f4c-89ea-5e377f75f631.gif)


1.36: 
![Kapture 2022-08-07 at 19 26 08](https://user-images.githubusercontent.com/11486075/183288337-4dfecda2-4af0-491b-9b27-37e3dd94ce8f.gif)

**Comment by martinlippert** [comment]
Thanks again @degbug for attaching the log output. The latest one looks okay-ish from the completion standpoint, so I am really surprised to see that version 1.38 is so much slower (thanks for the recordings, looks indeed quite terrible). More investigations on our side necessary, I guess. Will keep you updated here.

And thanks a lot for testing snapshot builds for us, this is extremely useful. Hope you find the time to test additional snapshots in the future around this issue.

**Comment by degbug** [comment]
> 

@martinlippert This the logs:

vscode-spring-boot-1.38.0-202208052243:

[boot.log1.38.txt](https://github.com/spring-projects/sts4/files/9277870/boot.log1.38.txt)

1.36:
[boot.log1.36.txt](https://github.com/spring-projects/sts4/files/9277872/boot.log1.36.txt)


And I am glad to test additional snapshots in the future.

**Comment by martinlippert** [comment]
Quick update:

I tried this with the various versions. I can clearly reproduce the slowdown when using the latest release version `1.37.0`, I can clearly see it running A LOT faster and more fluent with `1.36.0`. The snapshot version `1.38.0-202208052243` seems to be a lot faster than `1.37.0` faster than your recording from above, but not quite at the `1.36.0` level.

The question is, why. The log indicate that the overall content-assist performance from the Spring Boot language server seems to be okay-ish and fast, so it doesn't look like the editor waits for the language server to return content-assist information.

Looks like some additional investigations are necessary here... We will continue with that...

**Comment by martinlippert** [comment]
When looking at what exactly the language server is doing, it looks to me like nothing is really blocking the code completion anymore, but too much other stuff is going on:

[thread-dump-while-busy.txt](https://github.com/spring-projects/sts4/files/9281438/thread-dump-while-busy.txt)

**Comment by BoykoAlex** [comment]
@degbug Here is the new build to try: https://dist.springsource.com/snapshot/STS4/nightly-distributions.html At the bottom of the page please download vscode-spring-boot vsix file. I hope typing will become the same as before. If this is the case wonder if you could find in Preferences -> Settings then under Extensions -> Boot-Java Config find the setting `Boot-java › Rewrite: Reconcile` (should be unchecked by default) check mark and try typing again just like before. Do you see much difference?

**Comment by degbug** [comment]
> @degbug Here is the new build to try: https://dist.springsource.com/snapshot/STS4/nightly-distributions.html At the bottom of the page please download vscode-spring-boot vsix file. I hope typing will become the same as before. If this is the case wonder if you could find in Preferences -> Settings then under Extensions -> Boot-Java Config find the setting `Boot-java › Rewrite: Reconcile` (should be unchecked by default) check mark and try typing again just like before. Do you see much difference?

@BoykoAlex 
I tried [vscode-spring-boot-1.38.0-202208091607.vsix](https://s3-us-west-1.amazonaws.com/s3-test.spring.io/sts4/vscode-extensions/snapshots/vscode-spring-boot-1.38.0-202208091607.vsix) and feel it faster than vscode-spring-boot-1.38.0-202208052243.vsix。 And feel like 1.36.

But no matter I enable or disable the Rewrite: Reconcile option. I feel it behavior is same.

This is the log first install the vscode-spring-boot-1.38.0-202208091607.vsix
[boot.log1.38.nightly_open_and_close.txt](https://github.com/spring-projects/sts4/files/9295409/boot.log1.38.nightly_open_and_close.txt)

And I notice that when I enable the Rewrite: Reconcile option, the log can not output.

When I reopen the project it appear.
this is the log after I reopen project:
[boot.log1.38.nightly_close.txt](https://github.com/spring-projects/sts4/files/9295408/boot.log1.38.nightly_close.txt)


And this is the log of vscode-spring-boot-1.38.0-202208052243.vsix.
When I rollback to vscode-spring-boot-1.38.0-202208052243.vsix it become slowly.
[boot.log1.38_0805.txt](https://github.com/spring-projects/sts4/files/9295435/boot.log1.38_0805.txt)

**Comment by BoykoAlex** [comment]
Sounded like https://s3-us-west-1.amazonaws.com/s3-test.spring.io/sts4/vscode-extensions/snapshots/vscode-spring-boot-1.38.0-202208091607.vsix worked just like 1.36 and in both cases: rewrite reconcile off and on. If this is correct I suppose we should get to start releasing STS4 with the fix we've put in.

**Comment by youngm** [comment]
FWIW, I tried out the snapshot in eclipse and the slowness I was experiencing appears to be fixed as well.

**Comment by martinlippert** [comment]
@youngm Thanks for trying this and letting us know, very very much appreciated. The maintenance release 4.15.3 should go live tomorrow (most likely).
