### ISSUE TITLE
rename java class field   is not working  Spring tool suite 4.15.2  4.15.1

### ISSUE THREAD

**Issue by j2eekingcn** [spring-projects/sts4#809]
alt+shift+r    and  right-click menu   rename java class field is not work
sts4.15.1  sts4.15.2

**Comment by martinlippert** [comment]
Hey @j2eekingcn, thanks for reporting this issue. I tried this myself in a STS 4.15.2 installation and it seems to work fine for me, so this doesn't look like a general issue, but probably depending on some specifics. Can you provide a few more details and steps how to reproduce this?

Questions would be:
- which operating system are you on?
- and can you reproduce this from a clean STS 4.15.2 installation for a newly created project from start.spring.io (for example)?
- or can you attach a sample project that reproduces this?
- is there maybe anything related showing up in the Error Log view, like stack traces, etc.?

**Comment by Shiaming** [comment]
because of lombok, change the version
