### ISSUE TITLE
Concourse extension doesn't know about "check_every: never" for a resource

### ISSUE THREAD

**Issue by guillaumBrisard** [spring-projects/sts4#816]
`check_every: never` is not recognize for a resource

The extension wrongly reports

`'never' is not a valid 'Duration'.  A duration string is a sequence of decimal numbers, each with optional fraction and a unit suffix, such as '300ms', '1.5h' or '2h45m'. Valid time units are 'ns', 'us' (or 'µs'), 'ms', 's', 'm', 'h'.vscode-concourse(YamlSchemaProblem)`

The documentation about `check_every` for `resource`: https://concourse-ci.org/resources.html#schema.resource.check_every

**Comment by kdvolder** [comment]
Indeed, the way it is implemented is that it just checks syntax for a 'Duration', it doesn't allow for the `never` value. It should be an easy thing to fix.

**Comment by kdvolder** [comment]
Fix pushed: https://github.com/spring-projects/sts4/commit/cfa1aa790cdc28da4ec1976fa86722365d852554

**Comment by kdvolder** [comment]
I've confirmed the fix with latest vscode vsxi snapshot build. It can be downloaded from this page if you want to try it (or if you just want early access to the fix before the next release).

https://dist.springsource.com/snapshot/STS4/nightly-distributions.html
