### ISSUE TITLE
Workspace symbol null on custom annotations

### ISSUE THREAD

**Issue by cedbesafilm** [spring-projects/sts4#818]
**Describe the bug**
Once a custom annotation has been created, is set as null in workspace symbols

**To Reproduce**
Create custom annotation

```
@Target({ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Component
public @interface PersistenceAdapter {

  @AliasFor(annotation = Component.class)
  String value() default "";

}
```

Search for symbol in workspace

![image](https://user-images.githubusercontent.com/2351748/186364423-f8c3846f-060d-4a0f-afc9-f04cbd1368b1.png)

microsoft/vscode-spring-boot-dashboard#207

**Comment by martinlippert** [comment]
Thanks @cedbesafilm for reporting this, will work on a fix for the next release.

**Comment by martinlippert** [comment]
Fixed via https://github.com/spring-projects/sts4/commit/bd34877b73b6d9795473f87537e9b226fbf30d76
