### ISSUE TITLE
codeassit/autocompletion not working

### ISSUE THREAD

**Issue by imod** [spring-projects/sts4#82]
I migrated workspace with about 30 projects and 4 SpringBoot apps to sts4. The build runs fine and the apps also start without any issue.
But unfortunate the is no code assist in any of the classes, please see this screenshot:

<img width="392" alt="screen shot 2018-09-26 at 09 20 01" src="https://user-images.githubusercontent.com/543297/46063972-66cbdd80-c16e-11e8-9595-4eeef0245b08.png">

**Comment by martinlippert** [comment]
That looks bad indeed. Did you check the preferences for content-assist to see if maybe something got disabled (for whatever strange reason)?

If everything looks fine on the preferences side for content-assist, than it would be nice if you could attach a sample project (if possible) that reproduces the issue. Did you try a fresh simple Java project, too? Does content-assist for there?

**Comment by ncarnevali** [comment]
Same here, settings are the default ones:
![image](https://user-images.githubusercontent.com/21259127/46092241-c8af3600-c1b4-11e8-8d55-ccb0850e69eb.png)

In my case, workspace was imported from STS 3.9.4.

**Comment by ncarnevali** [comment]
Update on my previous comment. 
I tried to delete .metadata and .recommenders from workspace's folder and then I restarted STS.

Now it works, content assist is back, so maybe it's related to the migration of the workspace from previous versions of STS

**Comment by huyng1147** [comment]
I did use workspace of sts 3.9.6 for sts 4.0. Maybe that is the reason.

**Comment by vvalencia-cl** [comment]
Same problem here.
Scenario: Spring Tools 4 with a workspace migrated from Eclipse Photon

Tried `./SpringToolSuite4 -clean` and the problem remained.

**Fix**: Using @kdvolder and @ncarnevali advices, went to Preferences -> Java -> Editor -> Content Assist -> Advanced, and enabled: 

- Java Proposals
- Java Type Proposals

Then hit Apply... and it worked.

Thanks a lot @kdvolder 

![screenshot from 2018-09-26 18-34-17](https://user-images.githubusercontent.com/1178505/46110931-9d7c1500-c1bb-11e8-9e98-ab32f013c320.png)

**Comment by imod** [comment]
enabling 
* Java Proposals
* Java Type Proposals

fixed it for me too - thanks @vvalencia-cl 

not sure you want to keep this issue open or document it (or just point people here)...

**Comment by matthewlowry** [comment]
For the record - I had this same issue after migrating from STS 3.something to 4.
Checked the settings and sure enough Java Proposals and Java Type Proposals had mysteriously been deselected. Thanks @vvalencia-cl.

**Comment by martinlippert** [comment]
I think we found the reason for that a while ago (and forgot to mention it here): The Eclipse Code Recommenders feature was installed by default in the STS3 distributions. This feature replaced the regular Java content-assist processors with other ones. To be more exact, the feature disabled the regular Java content-assist processors and installed/enabled others.

STS4 (and newer versions of STS3) come without the Eclipse Code Recommenders feature. That means when you open an old workspace, this workspace still has the regular Java content-assist processors disabled (in the settings), but the other ones, the new ones from Code Recommenders, are not there. Therefore, no Java content-assist is showing up.

When invoking Java content-assist for the first time after you opened the workspace with a newer version, there is an error message from the Java tooling showing up, telling the user that the regular Java content-assist is disabled without any replacement and that the user can re-enable that by going to the preferences and resetting those for the content-assist processors. There is a direct link to that preference page included in that error message.

In case you missed that error message dialog or you didn't yet reset the preferences, you can do that by going to the preferences for content-assist and reset those or re-enable the JDT content-assist processors.

**Comment by gchiarapa** [comment]
I'm facing the same issue, I try to solve by uncheck and then apply, and then check Java Proposal and Java Type Proposals, but does not work.

`Spring Tool Suite 4 

Version: 4.14.0.RELEASE
Build Id: 202203131612

Copyright (c) 2007 - 2022 VMware, Inc.
All rights reserved. Visit https://spring.io/tools

This product includes software developed by the
Eclipse Foundation https://www.eclipse.org

This product includes software developed by the
Apache Software Foundation https://www.apache.org

Lombok v1.18.10 "Envious Ferret" is installed. https://projectlombok.org/`

![image](https://user-images.githubusercontent.com/50337428/163818745-a21d27e7-abff-4e17-a558-e1d3db3ff93f.png)


Does anyone could help me? 

Thanks a lot.

**Comment by martinlippert** [comment]
The previous comment got raised as a separate issue here: https://github.com/spring-projects/sts4/issues/766
