### ISSUE TITLE
Duplicate items in workspace/symbol requests

### ISSUE THREAD

**Issue by Eskibear** [spring-projects/sts4#820]
**Describe the bug**
Sometimes `workspace/symbol` request returns duplicate items. I'm seeing it on VS Code, haven't checked with STS-Eclipse.

**To Reproduce**
- Use initializr to create a simple spring boot Maven app, mine with Spring Web starter at beginning.
- Manually add actuator as dependency.
```
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-actuator</artifactId>
</dependency>
```
- Add and remove the actuator starter for several times, and each time observe response of `workspace/symbol` requests, sometimes the results contain another copy of all symbols.

**Sample**

I used the `client` in extension API to send requests, and below is the response.
```ts
const beans = await stsApi.client.sendRequest("workspace/symbol", {"query": "@+"});
```

![image](https://user-images.githubusercontent.com/2351748/186575693-72185139-c812-4a75-b52e-88d2d72b2dee.png)

It's more straightforward to use Spring boot dashboard, see below recording.

https://user-images.githubusercontent.com/2351748/186575878-aa6ef747-cc22-4e1f-8ba9-b8ded8e54cd0.mp4

**Comment by martinlippert** [comment]
Thanks for reporting this @Eskibear and for attaching the video and the detailed description. I will try to reproduce and dig into this.

**Comment by BoykoAlex** [comment]
@martinlippert seems like it might be fixed in **main** branch indirectly

**Comment by Eskibear** [comment]
@BoykoAlex Thank you for the information. The latest nightly build works well without this issue.

**Comment by martinlippert** [comment]
Thanks for verifying @Eskibear , closing this now.
