### ISSUE TITLE
open-rewrite-based parsing throws exceptions when parsing is too slow

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#826]
When parsing using open-write takes a long time (e.g. if the parsed file is large or if you insert a sleep during parsing to simulate this situation), and I quickly type things into the editor, I see this appearing in the log of the language server:

```
INFO  o.s.i.v.b.j.r.RewriteCompilationUnitCache - exception happened during parsing: java.lang.IllegalStateException: Call reset() on JavaParser before parsing anotherset of source files that have some of the same fully qualified names
```

It seems to be related to the way we deal with parsing requests coming in and being started, then being canceled, the parser is reset, and another parsing starts - but this is just guessing.

**Comment by martinlippert** [comment]
I also See this showing up as well:

```
INFO  o.s.i.v.b.j.r.RewriteCompilationUnitCache - exception happened during parsing: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
```

**Comment by martinlippert** [comment]
For the sleep (maybe a few seconds), I would recommend to insert it in `RewriteCompilationUnitCache` somewhere in the `doParse` method, that should help to reproduce this.

**Comment by BoykoAlex** [comment]
```
java.lang.IllegalStateException: Call reset() on JavaParser before parsing anotherset of source files that have some of the same fully qualified names
```
The above exception occurs if the previously parsed source is being parsed again with the same parser... I'll try to reproduce it with a `Thread.sleep(...)` as you  suggested.

**Comment by martinlippert** [comment]
I haven't seen this anymore with the latest versions, so closing this one here.
