### ISSUE TITLE
Some Lombok decorators do not work unless `SpringToolSuite4.ini` gets a `-javaagent:` property pointing to the Lombok JAR

### ISSUE THREAD

**Issue by kirisakow** [spring-projects/sts4#828]
**Describe the bug**

* As described [here on StackOverflow](https://stackoverflow.com/questions/56596416/lombok-constructor-is-undefined/) in 2019 (and experienced by myself earlier today with the latest `sts-4.15.3.RELEASE` for Linux), using Lombok decorators such as `@Data`, `@NoArgsConstructor`, `@AllArgsConstructor` doesn't seem to produce the expected effect, and results in compilation errors and a `Constructor ... is undefined` error message during runtime.

* There is [a solution](http://codeomitted.com/setup-lombok-with-stseclipse-based-ide/) (which works) which consists in copying a Lombok JAR or its symbolic link to the STS installation directory, and putting a special mention about that JAR in the `SpringToolSuite4.ini` file, also located in the STS installation directory: `-javaagent:lombok.jar`.

  * As a matter of fact, there's another bug: The aforementioned solution's last step is to restart the IDE to take effect, yet applying `File > Restart` command is not enough for the solution to take effect. The IDE needs to be closed and opened for it to take effect. See issue #829

**Comment by martinlippert** [comment]
Thanks @kirisakow for reporting. As far as I know, this Is the way Lombok integrates with the Eclipse IDE, so you could call it "works as designed". I would recommend to file this issue against the Lombok project itself in case you would like to see this changed or would like to contribute to a different implementation here.
