### ISSUE TITLE
Applying `File > Restart` has different effect than closing (or applying `File > Exit`) and opening the IDE manually

### ISSUE THREAD

**Issue by kirisakow** [spring-projects/sts4#829]
**Describe the bug**

* The IDE needs to be restarted as last step of the solution to the issue #828, yet applying `File > Restart` command is not enough for the solution to take effect. The IDE needs to be closed and opened for it to take effect.

**Comment by martinlippert** [comment]
Thanks @kirisakow for reporting this. We inherit this behavior from the underlying Eclipse platform, so a change for this behavior should be reported against the Eclipse platform project, I think: https://github.com/eclipse-platform/eclipse.platform
