### ISSUE TITLE
"Update Maven Project" shortcut does not work as before

### ISSUE THREAD

**Issue by imod** [spring-projects/sts4#83]
I often use the keyboard shortcut "Update Maven Project" (option + F5, on Mac):

In previous versions of STS, it worked like this:
1. select all projects in the workspace (including "**non maven projects**")
2. press shortcut "option + F5"
3. "Update Maven Project" dialog with all maven projects selected appears

In sts4, the shortcut has no effect anymore (dialog does not open) and makes it really cumbersome to select and update all maven projects.

**Comment by paulvi** [comment]
If the projects are modules of the same maven project, 
then using Eclipse hierarchical representation may help to view and select better.

**Comment by imod** [comment]
what do you mean by "hierarchical representation"? 
I only know/found the 'Java Type Hierarchy" and the "Package presentation > Hierarchical". Or do you you mean "Top Level Elements > Working Sets" in the Package Explorer?

**Comment by paulvi** [comment]
OK, it is only available in "Project Explorer" View

![image](https://user-images.githubusercontent.com/1614482/46088405-f0b38f00-c1de-11e8-88ae-6057a3455c15.png)

to switch from default

![image](https://user-images.githubusercontent.com/1614482/46088508-20629700-c1df-11e8-8b0d-533811c88735.png)

It looked like Eclipse team was going to replace "Package Explorer" with "Project Explorer" as default.

Also as user hint, when importing maven multi-module project, it is possible to add a prefix to all Eclipse projects, so even if module names do not from base package name, the will still be ordered and cose to each other

**Comment by paulvi** [comment]
![import-maven-project](https://user-images.githubusercontent.com/1614482/46088822-d3cb8b80-c1df-11e8-9854-708b2fb3e225.JPG)

Name template, e.g. `myimportedname-[artifactId]`

**Comment by imod** [comment]
ah nice, I did not know about this - thanks!

**Comment by martinlippert** [comment]
Sounds like we can close those issue here, right?

**Comment by imod** [comment]
@martinlippert up to you... even though I now have easier ways to select only maven projects, but I for myself would still love to have the old functionality back

**Comment by kdvolder** [comment]
@imod I see martin just added this to our next milestone. We can take a look, but I suspect its not something under our control because that menu item comes from Eclipse / M2E and if it changed its behavior when you select a mix of maven and non-maven projects, I would assume its something changed in either M2E or the Eclipse platform.

We can still take a look and determine who to blame and ask nicely if perhaps they could change it back. But I don't think its something that we would be able to fix in STS itself.

**Comment by imod** [comment]
@kdvolder totally fine, thanks! - let's close this issue then :)

**Comment by shiol** [comment]
Check the GeForce Experience shortcuts, disable Alt + F5.
