### ISSUE TITLE
switch live hovers in Eclipse to direct-connect after launch

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#832]
We should switch the approach the tooling auto-connects to running applications to show live hovers from the auto-detect java processes running on the local machine to a direct "connect to this app" call from the tooling in Eclipse once a spring boot app has been launched (similar to the way we do this in VSCode nowadays) and disable the automatic tracking of processes by default.

**Comment by BoykoAlex** [comment]
Hopefully addressed with c51b97ad56d1d9a9d2ce5a8cc564919db7eab6da
Auto-connects to boot apps launched via **Spring Boot** launch with JMX enabled, i.e. default launch settings. There is also a preference for auto-connect under Boot Dash preferences.
