### ISSUE TITLE
Support maven-mvnd

### ISSUE THREAD

**Issue by wsq93** [spring-projects/sts4#835]
**Expected Behavior**

   STS supports maven-mvnd

**Current Behavior**

-  Cannot configure maven-mvnd with M2E.
-  Cannot use mvnd directive in the terminal of project.

**Context**

 I have configured the system environment variable of mvnd. 

 If it is already supported, please tell me how to configure it.

**Comment by martinlippert** [comment]
This sounds to me like something that should be reported against m2e directly: https://github.com/eclipse-m2e/m2e-core
