### ISSUE TITLE
[validation] changing the preferences while language server is not around doesn't have any effect

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#836]
I am looking at the following case:

- I start the language server, it runs the validation, and adds a bunch of warnings/errors on my source files (all great)
- I close all the editors, the errors and warnings stay around (makes sense)
- The language server is shutdown being the scenes, the errors and warnings stay around (makes sense, too)
- I open the preferences and switch the errors/warnings off because I want to get rid of them - BUT THIS DOESN'T REMOVE OR CHANGE THE EXISTING ERRORS/WARNINGS. They stay around.

The reason for this is obvious (the language server is not running to take the new preferences into account and update the errors/warnings). When I startup the language server, it reconciles everything and the errors/warnings are gone (for my case described above).

But it might probably not make a lot of sense to the user that the errors/warnings wait for the language server to kick-in before they get removed (due to my changed preferences).

**Comment by BoykoAlex** [comment]
@martinlippert what about removing validations that came from LS when the LS is shut down?

**Comment by martinlippert** [comment]
@BoykoAlex I think that makes sense.

**Comment by BoykoAlex** [comment]
Validation are removed if LS is shutting down with 35f4e9899b336a087f02f67506246e58b8f719a3
Therefore, this concern should be addressed. If LS is down there won't be any validations from LS left on the client
