### ISSUE TITLE
[validation] add new validation for @Autowired annotation on field

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#837]
We should have a validation for fields with `@Autowired` that triggers the "turn into constructor" quick fix. The default for this validation should still be "ignore", but having this as a validation seems to be more homogenous to the other validations and refactorings that we offer over time.

**Comment by BoykoAlex** [comment]
Should be fixed with: 6c9543c174f0c010f4f09ec9029b91a875bc0ade
