### ISSUE TITLE
spring tool suite linux arm distribution

### ISSUE THREAD

**Issue by Bradmoon** [spring-projects/sts4#841]
**Expected Behavior**

i am running ubuntu on a vm using vmware that is hosted by mac apple silicon machine.

**Current Behavior**

there is no install for sts running on linux arm.  

**Context**

i know have to use intellij in this environment

**Comment by martinlippert** [comment]
You can find an early nightly build here: https://dist.springsource.com/snapshot/STS4/nightly-distributions.html - we will include this in the upcoming 4.16.0.RELEASE as experimental, since it goes out largely untested. Can you have a look and let us know if that all works for you?

**Comment by Bradmoon** [comment]
yes, i would definitely do this.

**Comment by martinlippert** [comment]
@Bradmoon Take a look at https://dist.springsource.com/snapshot/STS4/nightly-distributions.html, there you can already find the distribution build for linux on arm for testing. Or do you mean something else?

**Comment by Bradmoon** [comment]
it must be the [spring-tool-suite-4-4.16.0.CI-B2782-e4.25.0-linux.gtk.aarch64.tar.gz](https://download.springsource.com/snapshot/STS4/nightly/dist/e4.25/spring-tool-suite-4-4.16.0.CI-B2782-e4.25.0-linux.gtk.aarch64.tar.gz) is for ARM?

**Comment by martinlippert** [comment]
@Bradmoon Yes
