### ISSUE TITLE
update signing certificate for pre-built third-party bubdles

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#852]
As reported here: https://stackoverflow.com/questions/73840447/how-do-i-resolve-an-expired-x509-certificate-issue-while-installing-sts4-from-ec

we need to update the signing certificate of the pre-built third-party bundles that we include (basically re-sign the bundles).

**Comment by Buzzardo** [comment]
Will this make it run on a Mac? It fails to run at present. I think the relevant bit of the crash report is `Exception Type:  EXC_CRASH (SIGKILL (Code Signature Invalid))`.

**Comment by martinlippert** [comment]
@Buzzardo No, the problem you are facing is a different one. You can solve it via executing this on the command line:

`codesign --force --deep --sign - SpringToolSuite4.app`

**Comment by Buzzardo** [comment]
Ah, OK. Thanks, Martin.

**Comment by martinlippert** [comment]
Done, will be included in the next release (4.17.0)
