### ISSUE TITLE
installation of spring tools in eclipse

### ISSUE THREAD

**Issue by SANJITHL** [spring-projects/sts4#857]
I am currently using the eclipse version of 2022-06 in this for spring tools at first i installed the spring tools 4 but i didn't receive the spring folder ad the spring files in the eclipse page so again installed the spring tools 3 add-on for spring tools 4 but i have received an error of 
Unable to read repository at https://marketplace.eclipse.org/content/spring-tools-3-add-aka-spring-tool-suite-3.
Unable to read repository at https://marketplace.eclipse.org/content/spring-tools-3-add-aka-spring-tool-suite-3.
https://marketplace.eclipse.org/content/spring-tools-3-add-aka-spring-tool-suite-3 is not a valid repository location. 

what is the solution to install spring ide tool files to get installed in eclipse version 2022-06

**Comment by martinlippert** [comment]
No further feedback or details on this so far, so closing this for now. Probably solved with the comment above.
