### ISSUE TITLE
Web Tools Platform (WTP) validation is acitvated by default but can not be suspended (or configured) via GUI preferences 

### ISSUE THREAD

**Issue by mplukas** [spring-projects/sts4#859]
STS 4 includes Maven WTP support and basic support for WAR projects. By default in STS 4 WTP validation is enabled and WAR project building/refreshing activates various (default) WTP validators. However STS 4 is missing preferences for WTP validation configuration and also there is not direct way to suspend WTP validators. On bigger projects (e.g. having a lot of XML files) validation can take considerable amount of time and usually is not desired. 

To reproduce create a new Java faceted project with facet "Dynamic Web Project" (or facet "Utility") - e.g. by creating Spring Starter maven WAR project.  Add some XML resources (with errors). Initiated project build/update (e.g. Alt+F5 for m2e project) project. Notice "Validating 'project'" in progress view (that can take considerable time if there are a lot of XML or other resources that WTP validates by default). Also notice validation errors in the problems view of the type "XML problems" (not of the type "Language Server").

Workaround: import Eclipse preference (*.epf) with the setting
`/instance/org.eclipse.wst.validation/suspend=true`
in order to suspend all WTP validators.

STS 4 should disable WTP validation out of the box.

**Comment by BoykoAlex** [comment]
I'm thinking of setting `org.eclipse.wst.validation/suspend=true` in the sts product. Thus if one downloads STS distro this setting is going to be set. I suppose we wouldn't want to mess with this setting STS plugins installed via update site...

**Comment by BoykoAlex** [comment]
Here is the fix: 2cb7b921d586dfc4aaf7aa65c1ca464e41587917

**Comment by BoykoAlex** [comment]
Please look for the fix in 4.16.1
