### ISSUE TITLE
Installing Lombok in STS4 for Mac

### ISSUE THREAD

**Issue by Alos** [spring-projects/sts4#86]
Hello!

It looks like the Lombok installer JAR does not recognize STS4 and it will not install the plugin. Is there a way to do this?

**Comment by Alos** [comment]
To fix this I selected the .ini file inside `STS4/Contents/Eclipse` the  after clicking on the `Specify location…​`

**Comment by kdvolder** [comment]
Great you found the answer already. Thanks for letting us know the solution. It might help someone else with the same problem/question.

**Comment by muthhus** [comment]
when i browsed into STS4/Contents/Eclipse, I can't choose or i don't have option to select ini file. @Alos . would you please advise me how did you solve the problem

**Comment by Alos** [comment]
Unfortunately I'm now using IntelliJ and I can't remember how I fixed this :S Sorry!

**Comment by muthhus** [comment]
Thanks, @Alos. Yes, I am using IntelliJ ultimate 2018.3 as well. How do i install Lombok manually into Intellj with out using Plugins.(I configured in the pom from local artifactory and IDE recognizing the @Getter annotations. but i can make the call the any Getters and Setters from other classes. I uploaded into project modules external jar eventhough it doesn't work. Any Advise please...
Thanks

**Comment by martinlippert** [comment]
@muthhus As far as I remember, the Lombok installer doesn't identify the STS4 product as an Eclipse installation yet, so you would need to manually edit the SpringToolSuite4.ini file to include the necessary arguments for Lombok.

**Comment by amoljore751986** [comment]
You add **.ini** file stored at this location : _/Applications/SpringToolSuite4.app/Contents/Eclipse_
