### ISSUE TITLE
[refactoring] open rewrite refactoring menu item is broken when no language server is running

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#865]
The menu item to select and run OpenRewrite recipes is broken and throws exceptions if there is no language server around. We should probably start a language server in case there is no language server running when selecting the menu item or executing a recipe from the dialog.

**Comment by BoykoAlex** [comment]
I think the only solution is whatever we come up for #880

**Comment by BoykoAlex** [comment]
It should have worked in the case of VSCode. This commit should address this issue for VSCode: 5b5ac912ad589f17bc3762632309eb422af14142

**Comment by BoykoAlex** [comment]
Should be fixed with dd2f60ad914db564be066d1d8f16b8e8b847dc18
