### ISSUE TITLE
[refactoring] when converting a project to Spring Boot 3, always use the latest 3.0.x version

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#869]
When we convert a project to use Spring Boot 3 using the recipes from OpenRewrite, we need to make sure that we always convert the project to the latest 3.0.x version and that we don't need to ship a new tooling version for patch releases.

A new minor release (3.1.x) might be different though.

**Comment by BoykoAlex** [comment]
Tried changing this now. Looks like recipes don't support `newVersion: 3.0.x-SNAPSHOT`. Instead the recipe supports: `newVersion: 3.0.x`. Therefore, we'd have to wait for Boot 3 to be released and then can switch `3.0.x` in the recipe.

**Comment by BoykoAlex** [comment]
Should be fixed with 61d6d1ded07f079dae7c1eedf42fa2a1fba29a2c
