### ISSUE TITLE
Splash screen kind of blurry on retina displays

### ISSUE THREAD

**Issue by MahatmaFatalError** [spring-projects/sts4#87]
Little side note: On my 15" MBP with 2880 x 1800 px the new splash screen image looks kind of blurry.

Maybe @2x HiDPI image missing?

**Comment by martinlippert** [comment]
This is a known limitation of the splash screen support from the underlying Eclipse platform. Unfortunately nothing we can do about that at the moment as far as I know. I investigated that a while ago already.
