### ISSUE TITLE
README-dev-env.md is outdated

### ISSUE THREAD

**Issue by Eskibear** [spring-projects/sts4#873]
I want to run/debug spring LS in standalone mode, and make vscode-spring-boot extension to connect to it. The docs looks outdated, as it doesn't match current project structure and how it runs. And I have to find my own way to launch the LS.

I'm not sure what's the best practice to launch `BootLanguageServerBootApp` and debug it. So it would be helpful for potential contributors if the docs can be update.

**Comment by BoykoAlex** [comment]
I made some corrections to that readme... Hopefully enough. Please re-open it you feel it requires more work.
