### ISSUE TITLE
[validation] converting petclinic results in wrong warnings on application.properties 

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#882]
VSCode + working on standard petclinic sample. When converting this to Spring Boot 3 using the OpenRewrite recipes (and clicking the button on the popup to update the project config afterwards), I end up seeing warnings for various properties in the `application.properties` file (those that got introduced during the conversion). Those warnings seem to be incorrect. Opening the application.properties file makes those warnings go away.

**Comment by BoykoAlex** [comment]
This is is likely to be fixed due to commits around clearing and sending diagnostics on the same thread as well as work arounds for rewrote recipes throwing NPEs.
