### ISSUE TITLE
Creating a Spring Starter with Gradle and Java 11 does not work

### ISSUE THREAD

**Issue by abhishek2bommakanti** [spring-projects/sts4#89]
I'm trying to create a new Spring Starter project using Gradle and Java 11. The project creation fails with the following error:

IllegalArgumentException: Could not determine java version from '11'.
java.lang.reflect.InvocationTargetException

**Comment by kdvolder** [comment]
The Java 11 support for Eclipse platform is still experimental not yet included in the STS 4 build. You can try it out though, but you have to install it manually from Eclipse marketplace:

https://marketplace.eclipse.org/content/java-11-support-eclipse-photon-49

**Comment by martinlippert** [comment]
The support that is available works for basic Java projects, but the Maven support (and the same applies probably to the Gradle integration for Eclipse) isn't ready for Java 11 yet. Looks like we need to wait for the next Eclipse release to get real Java 11 support across the various pieces.

**Comment by abhishek2bommakanti** [comment]
Creating it as a Maven project actually works, but Gradle (my preference) does not. As you said, we will perhaps have to wait for the next Eclipse release to properly support Java 11. Are you gong to have STS4 releases to correspond to the Eclipse release cycle?

**Comment by kdvolder** [comment]
I'm not sure how well it will hold up if you really use it in earnest but I just tried setting up a gradle project and it seemed to be working. Here's what I did:

- STS 4 release
- installed the Java Eclipse support for Java 11 from marketplace
- Downloaded and configured Java 11 open jdk as a workspace JRE
- Created a "New Spring Starter" project with Gradle and Java 11 selected.

A bit to my suprise the generated project didn't atually select Java 11 in the `build.gradle`. That is probably a bug in the 'start.spring.io' webservice (not STS). I will have to follow up with that and make sure it is reported.

I worked around this problem simply by opening `build.gradle` and changing the line:
`sourceCompatibility = 1.8` to `sourceCompatibility = 11.0`. Then selected from project context menu "Gradle >> Refresh Gradle Project". After that the project looked like it was a correctly configured Java 11 / Gradle / Spring boot application.

Maybe give those steps a try and see if it works for you.

**Comment by martinlippert** [comment]
You can give it a try, as Kris described, but I have the Java 11 support installed and quickly tried Maven for creating a project, but I immediately run into issues... :-(

And yes, we will push out new Spring Tools 4 releases quickly after new Eclipse releases are being released (as we did in the past with STS3). There is no exact release plan yet, but I expect us to release in even shorter release cycles than Eclipse.

**Comment by kdvolder** [comment]
Looks like Martin already reported this problem for maven projects. 
https://github.com/spring-io/initializr/issues/739

So I just added a note about gradle also being broken.

**Comment by martinlippert** [comment]
In addition to that I also run into:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=539578

**Comment by abhishek2bommakanti** [comment]
@kdvolder You were correct about the version issue. I followed all your steps, but am still facing the same issue. Moreover, if I try to import the project as a Gradle project, on the import preview, I get all the home directories as unknown, due to which the import fails too.

<img width="649" alt="screen shot 2018-09-27 at 11 41 07 am" src="https://user-images.githubusercontent.com/11429644/46161140-538e4000-c24a-11e8-969f-4fc9c35baa6f.png">

**Comment by abhishek2bommakanti** [comment]
@kdvolder Thanks for the info. I wasn't aware of this either. I tried the 2.1.0.M4 version but am still facing the same issue where the Gradle import does not get any of the Home Directories...

**Comment by kdvolder** [comment]
BTW: We are not the best people to help trouble-shoot your BuildShip problem. I'm not really sure how BuildShip tries to determine the Java home, but it seems that is somehow failing for you. If you can't figure it out, perhaps the best course of action would be raise an [Eclipse bugzilla ticket](https://bugs.eclipse.org/bugs/) against BuildShip. Perhaps this is a BuildShip bug, or at the very least they might be able to help figure out why BuildShip can't figure out which version/installation of Java to use on your machine / workspace.

**Comment by abhishek2bommakanti** [comment]
Yep, I figure it’s a BuildShip issue. I’ve raised Bugzilla ticket https://bugs.eclipse.org/bugs/show_bug.cgi?id=539588 for this.

**Comment by martinlippert** [comment]
Thanks for cross-posting the bug reference, now lets see what happens on the buildship side.
