### ISSUE TITLE
[refactoring] convert autowired field to constructor should make field final

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#896]
The refactoring to turn an autowired field into a constructor param should make the field final.

**Comment by BoykoAlex** [comment]
See https://github.com/openrewrite/rewrite-spring/pull/243

**Comment by BoykoAlex** [comment]
The PR above is pushed in but there is a fix required: https://github.com/openrewrite/rewrite-spring/pull/247

**Comment by BoykoAlex** [comment]
Seems fixed now with the latest Rewrite snapshot
