### ISSUE TITLE
[validation] check for superfluous @Repository annotations on standard Spring Data repositories

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#898]
add validation/preference/recipe to detect and remove superfluous @Repository annotations on standard Spring Data repositories.

**Comment by BoykoAlex** [comment]
See https://github.com/openrewrite/rewrite-spring/pull/245

**Comment by BoykoAlex** [comment]
Fix with fb3f20c3ea400926030d6361c179a274faac2023
