### ISSUE TITLE
[refactoring] double check differences in manually and automatically converted petclinic

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#901]
When converting the standard petclinic example from 2.7.x to 3.0.x using the new Spring Tools feature (which uses the OpenRewrite recipes behind the scenes), there are a few minor differences (beyond the ordering of the updated imports, where the OpenRewrite recipe seems to sort them in a specific order compared to the manually changed version):

__`pom.xml`  file changes:__

- OpenRewrite adds a persistence-api dependency, the manual version does not list that dependency.

```
    <dependency>
      <groupId>jakarta.persistence</groupId>
      <artifactId>jakarta.persistence-api</artifactId>
    </dependency>
```

Technically, it is not necessary to add this dependency (comes as a transitive dependency from `spring-boot-data-starter-jpa`). Should we keep this or avoid adding this dependency?

- OpenRewrite adds:

```
    <dependency>
      <groupId>org.glassfish.jaxb</groupId>
      <artifactId>jaxb-runtime</artifactId>
      <scope>runtime</scope>
    </dependency>
```

Doesn't seem necessary. Avoid adding this dependency? Or only under certain conditions?

- OpenRewrite keeps ehcache in this form:

```
    </dependency>
    <!--~~(No version provided)~~>--><dependency>
      <groupId>org.ehcache</groupId>
      <artifactId>ehcache</artifactId>
      <classifier>jakarta</classifier>
    </dependency>
```

whereas the manually converted version gets this instead:

```
    <dependency>
      <groupId>com.github.ben-manes.caffeine</groupId>
      <artifactId>caffeine</artifactId>
    </dependency>

```

__`application.properties` file changes:

- OpenRewrite adds these four lines:

```
management.endpoints.jmx.exposure.include=*
management.endpoint.configprops.show-values=ALWAYS
management.endpoint.env.show-values=ALWAYS
management.endpoint.quartz.show-values=ALWAYS
```

to keep the behavior consistent with previous versions (since the default configs changed in Spring Boot 3). Do we want to push those changes into converted projects or do we want to keep the defaults? I tend to keep the defaults (since there is a good reason why those defaults have changed) and not automatically add those changes to keep the old behavior. Thoughts?

**Comment by BoykoAlex** [comment]
- **jakarta.persistence-api** added unnecessarily - Seems that `AddDependency` recipe needs some work to avoid adding dependencies available via transitive dependencies
- **jaxb-runtime** - Unsure about this one. TBD
- **ehcache** - Used to be there in some version of Boot 3 upgrade. ** caffeine** probably includes it. Don't think Rewrite can help here
- properties - I think Rewrite is not to add these. Lets wait a day or two and check again. (Tyler mentioned he'll revert adding at least the top two but likely the other two as well)

**Comment by BoykoAlex** [comment]
@martinlippert hopefully properties are fixed as PR https://github.com/openrewrite/rewrite-spring/pull/248 is merged
