### ISSUE TITLE
make sure VSCode shows an error message when running on a JDK <17

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#903]
We need to make sure that the VSCode extension double checks the version of the JDK is runs the language server on and reports anything that is <17 to the user as a wrong setting.

See the comment here: https://github.com/spring-projects/sts4/issues/893#issuecomment-1324521291

**Comment by BoykoAlex** [comment]
@martinlippert Is this for all spring extensions or just the Spring Boot extension?
