### ISSUE TITLE
[validation] prepare version validation for 4.17.0 release 

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#904]
In order to prepare for the existing API at `https://spring.io/api` to go away sometime soon, we decided to realize the following changes for the upcoming  4.17.0 (that we currently use to validate versions and generations of Spring Boot projects):

- remove the generations validation from the 4.17.0 release. This will be included again in the 4.17.1 release, based on the new API.
- switch the versions validation to pull version information from maven central instead of the old API.

If possible, we might even query the configured repositories on the projects for the available versions. This would have the benefit of being precise about the available Spring Boot versions in the environment of the user - instead of showing which versions are available in general. But that depends on the amount of work that is necessary to implement this part.

**Comment by BoykoAlex** [comment]
I have moved asking Maven/Gradle repo for available spring-boot versions into a separate issue as this would take some time and effort to implement - see #905.
Otherwise should be good to for 4.17.0 with:
- b408bb91214472c1281036bccd2abbef2ee0454d
- ae0cc6dc114fe7d4492df9564ce62e416d85c9b3

**Comment by martinlippert** [comment]
We need to temporarily remove the preferences around the generations checks as well

**Comment by martinlippert** [comment]
From looking at the code, it is still fetching the generations information and fails if that information is not around. I will take a deeper look to disable this altogether, not fetching any information, and especially not failing if this information is not around - since we don't do generation validation for this release.

**Comment by BoykoAlex** [comment]
@martinlippert I can finish this off... resolved this in a hurry unfortunately.

**Comment by BoykoAlex** [comment]
Seems to be fixed with 8f3e0f3664bd4ad50aae16be116de1b543002ac4
