### ISSUE TITLE
Use project's Maven/Gradle repository to determine latest available Spring Boot versions

### ISSUE THREAD

**Issue by BoykoAlex** [spring-projects/sts4#905]
Query the configured repositories on the projects for the available spring-boot versions. This would have the benefit of being precise about the available Spring Boot versions in the environment of the user - instead of showing which versions are available in general. But that depends on the amount of work that is necessary to implement this part.

Currently available Spring Boot versions are determined by querying maven central for available versions of spring-boot artifact. This should be replaced with getting available spring boot versions directly from artifact repositories specified for the project via maven/gradle build file.

The idea is get `IMaven` instance from MavenCore plugin, then call `readProject(...)` then the result of this call would be Maven Project object that has `getRemoteArtifactRepositories()` method where each `ArtifactRepository` has an instance method `findVersions(Artifact)` where artifact is the spring-boot artifact which should be hard coded.
Gradle is unclear at the moment but likely be something similar.
For both Maven and Gradle project we'd need a command handler in JDT (Eclipse) and in JDT LS extension (VSCode) to provide  versions of an artifact given the project or more likely the build file URI. In other words we'd need a protocol extension to ask JDT/JDT LS for available versions

**Comment by BoykoAlex** [comment]
Available versions of an artifact in Maven example: https://github.com/eclipse-m2e/m2e-core/discussions/1213#discussioncomment-4734373

**Comment by martinlippert** [comment]
We are pausing the work on this and instead focus on getting the version information from either Maven Central or spring.io.
