### ISSUE TITLE
[refactoring] convert project to Spring Boot 3 doesn't update Java to 17 anymore

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#909]
The latest nightly builds don't set the Java level to 17 anymore when converting a project to Spring Boot 3 - for example when converting standard petclinic.

**Comment by BoykoAlex** [comment]
See https://github.com/openrewrite/rewrite-spring/pull/246

**Comment by BoykoAlex** [comment]
Should be fixed
