### ISSUE TITLE
nonsupport tomcat

### ISSUE THREAD

**Issue by rongflag** [spring-projects/sts4#91]
STS4 ,when I wang to change server ,no choice for tomcat ,Not commonly used。 

It's very strange

**Comment by kdvolder** [comment]
Sorry, I am not sure what you are exactly trying to change and where. So can you please be more precise?

Although I don't know precisely what you are talking about. I'll try to comment. 

Are you trying to change the embedded server for a spring boot app? If so, I think it automatically comes with Tomcat by default for a typical boot app with the `web` starter on it, so you wouldn't need to change it. You could change it to use jetty instead though, which is explained here: https://docs.spring.io/spring-boot/docs/current/reference/html/howto-embedded-web-servers.html

I hope that will answer your question. So I'm closing this ticket. If this isn't what you meant, please explain it more precisely and we can re-open the ticket.

**Comment by rongflag** [comment]
Sorry, my English is not good enough to describe clearly.I mean if I don't use springboot, I just want to develop a spring-project. How do I integrate Tomcat to run my project?When I open “window->Prefrences->server->runtime envoriments->add”   You can find a lot of server, but there is no Tomcat or jetty. Did I find the wrong place? Or does STS4 no longer support the introduction of Tomcat or jetty?

**Comment by kdvolder** [comment]
Okay. I think you are asking the same question as this one then: https://github.com/spring-projects/sts4/issues/81

So please read the answers there.
