### ISSUE TITLE
[refactoring] execute quick fix to update patch version doesn't work when pom.xml file is not open

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#913]
I have a simple Rest Service project in my workspace and the warning appears that there is a new patch version available. I execute the quick fix from the problems view in Eclipse without opening the `pom.xml` file in an editor. The quick fix gets executed, but nothing is changed afterwards.

When I have the `pom.xml` file open in an editor and then execute the quick fix from the problems view, the patch version is updated correctly.

**Comment by BoykoAlex** [comment]
See https://github.com/eclipse/lsp4e/pull/329

**Comment by BoykoAlex** [comment]
@martinlippert This is not just for the patch upgrade. If pom is closed then upgrade initiated from the problems view via quickfix won't touch the pom. The issue is we need to take care of connect/disconnect to text buffers while working with code actions/marker resolutions

**Comment by martinlippert** [comment]
We already included a snapshot build that fixes this in the latest 4.17.0 release build, so we can close this as fixed for that release.
