### ISSUE TITLE
STS4 multi moudules get the warning Unknown property

### ISSUE THREAD

**Issue by KrakenMing** [spring-projects/sts4#92]
I upgrade the STS 3 to STS4(eclipse), and a multi modules project get warning "Unknow property xxxx". Some property defined in project A and useing in projectB get warning, and they can't use content assist, but it's still working. How can I fix it?

**Comment by KrakenMing** [comment]
[kraken-framework.zip](https://github.com/spring-projects/sts4/files/2459021/kraken-framework.zip)
This is the multimodules project, some properties defined with @ConfigurationProperties. The properties  in "kraken-core : pers.kraken.framework.core.config.DefaultSuccessReturnData", I want use these properties in "kraken-framework-test : application.yml", its still works, but no code content assist.

**Comment by KrakenMing** [comment]
Its looks like the same as #101

**Comment by kdvolder** [comment]
It doesn't look the same as #101 to me. But, I did fix some problem recently that I think might be the same, we only have ticket for it in our internal tracker https://www.pivotaltracker.com/story/show/160969280 (sorry the ticket is probably not public accessible).

Anyway, thank you for adding more details that will allow me to verify whether my fix also fixes your problem.

**Comment by KrakenMing** [comment]
Ok. Thanks for help.
