### ISSUE TITLE
Give user more information about what is "java sources reconciling"

### ISSUE THREAD

**Issue by yennor** [spring-projects/sts4#920]
**Expected Behavior**

When asking the user if java sources reconciling should be activated, maybe give a little hint or link to documentation, what it's supposed to do.
**Current Behavior**

just ask if to enable it or not. Afterwards I was unable to find the setting to deactivate it again.

**Context**
I've updated Eclipse and the Spring Tools Extension when I was asked if I want to enable "additional Spring java sources reconciling". Without any further explanation. Couldn-t find anything on google about it. But found out that the question was probably its from the Spring Tool extension (if not, close that issue). Tried to find the  setting, to enable/disable it to see what difference it makes. But also can't find that setting anywhere.

**Comment by martinlippert** [comment]
The user guide also contains a short section on this: https://github.com/spring-projects/sts4/wiki/Validations-And-Quick-Fixes.

But I agree, we need to put more details out on the UI directly.

**Comment by BoykoAlex** [comment]
I'll mark it as fixed with c1accd1016d4c938ad2fa7d901d6fdf80754b262
I have add the URL hyper link to the popup in VSCode and Eclipse. I have re-worked Eclipse's popup using JFace Notification such that it looks like the popup in VSCode.

**Comment by tommai78101** [comment]
If you're on the latest Eclipse IDE for Java (using Eclipse IDE 2023-03 as an example), and you're using Spring Tool Suite 4 plugin from Eclipse Marketplace, the settings, shown by BoykoAlex, are in a different location:

![image](https://github.com/spring-projects/sts4/assets/6444116/a24b5a9d-7e9c-4c40-972a-e733acec2ac2)
