### ISSUE TITLE
Outdated "new and noteworthy" Eclipse URL in release notes

### ISSUE THREAD

**Issue by ParkerM** [spring-projects/sts4#921]
The most recent release [here](https://github.com/spring-projects/sts4/releases/tag/4.17.0.RELEASE) points to https://www.eclipse.org/eclipseide/2022-12/, but the link redirects to the homepage.

It looks like the page may have moved to https://eclipseide.org/release/noteworthy/

**Comment by martinlippert** [comment]
Thanks @ParkerM for reporting this, I updated this throughout the place. Thanks again!!!
