### ISSUE TITLE
[validation] investigate highly increased memory consumption with new Java source reconciling

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#922]
We are seeing a highly increased memory consumption when having the new Java source code reconciling enabled (as reported by various users).

**Comment by martinlippert** [comment]
I added a section to the user guide explaining the experimental nature of this and how to workaround this by deactivating the new Java source reconciling - to see if that makes a difference: https://github.com/spring-projects/sts4/wiki/Validations-And-Quick-Fixes#experimental-nature-of-this-new-feature-and-potential-side-effects

**Comment by martinlippert** [comment]
The goal here is to analyze what exactly is causing this memory spikes and fix that. From what I've seen so far, it looks like the language server process uses a lot of memory, but it seems like this memory usage is not permanently, but reduced when a GC kicks in.

**Comment by jan-z** [comment]
The language server process (BootLanguageServerBootApp) also uses a lot of CPU.

For me it uses about four cpu minutes every time I save any Java file.

I had to disable Java source reconciling to make Eclipse usable again.

**Comment by martinlippert** [comment]
As a summary of the things you can disable in order to avoid the high CPU usage and performance issues:

Go to `Preferences -> Language Servers -> Spring Language Servers -> Spring Boot Language Server`, then:
- Deactivate `Start Language Server at startup...`
- `OpenRewrite` -> deactivate `Reconciling of Java sources`
- `Spring Boot Version Validation`, set `Enablement`to `Off`

**Comment by beatjost** [comment]
The Update 4.17.1 seems to solve the issue (also after undo the workaround). Thank you for the quick fix 👍

**Comment by martinlippert** [comment]
Thanks @beatjost for letting us know, glad to hear this.

**Comment by BoykoAlex** [comment]
I think in general this reconciling will take up memory. Parsing all sources in a project does take memory. The difference now is that it is batches of 50 sources at once and there is only one thread dedicated to project reconciling. Thus, I think memory usage peaks should be lower. This is in since 4.17.2
