### ISSUE TITLE
[validation] add navigation to release notes from version validation messages

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#923]
It would be nice if the version validation could add a way to let users easily navigate and find the release notes for the mentioned new release.

**Comment by BoykoAlex** [comment]
@martinlippert I only have one solution to open release notes. Provide "Open Release Noted for Spring Boot x.y.z" quick fix. Activating the quick fix would open the release notes in the browser. What is the release notes URL? Is this the one we'd use: https://github.com/spring-projects/spring-boot/releases/tag/v3.0.2 ? Seems like the best approach to me...

**Comment by BoykoAlex** [comment]
Here it is: 5fd85a919b1485d830136fb3fb228f79256ca8db
