### ISSUE TITLE
[refactoring] sometimes the project is not updated after converting it to Spring Boot 3

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#927]
I am in VSCode, running the latest Java and Spring Boot extensions. I have petclinic in my workspace and the new version validation shows a new major version (configured the severity of that check accordingly). Now I execute the quick fix to covert to Spring Boot 3, the language server executes all the recipes, all the files are changed. But - sometimes - there are a lot of errors showing up in the problems view from the Java tooling, complaining about the new jakarta types not being found.

As soon as I open the corresponding Java file, the errors for that file are gone, so the file itself is absolutely correct and fine. Even the project configuration in the projects view looks file, so it seems like the Java tooling is a bit confused somehow.

I tried "Reloading Projects" as well as "Rebuild Projects" actions, but nothing helped. When I quit VSCode and re-open it again, everything is fine again, the problems are gone. Same happens when I execute "Developer: Reload Window" from the command palette.

It seems like sometimes the Java tooling gets confused when we execute those OpenRewrite recipes. Maybe this is the same problem that we also saw in Eclipse when having a Java source open is still showing errors before you save the file manually. But this is just guessing...

**Comment by BoykoAlex** [comment]
This is is likely to be fixed due to commits around clearing and sending diagnostics on the same thread as well as work arounds for rewrote recipes throwing NPEs.
