### ISSUE TITLE
Tomcat port issue

### ISSUE THREAD

**Issue by PNPavanKumar** [spring-projects/sts4#935]
Hi ,
I am facing a issue regarding Tomcat server.port as i changed the default port using server.port=9090 but still the Tomcat is running in default port 8080 only . Please give suggestions on this issue ASAP.

**Comment by BoykoAlex** [comment]
This is a duplicate of #929. Specify the port in launch config Boot tab as a workaround

**Comment by martinlippert** [comment]
Looks like you posted the same question on SO as well: https://stackoverflow.com/questions/74940624/server-port-issue-in-java
