### ISSUE TITLE
Add instance_vars to Concourse schema

### ISSUE THREAD

**Issue by ab18465** [spring-projects/sts4#942]
**Describe the bug**

Concourse CI Pipeline Editor VSCode extensions are falsely reporting a problem with instance_vars. 

Error message: 
`Unknown property 'instance_vars' for type 'SetPipelineStep'vscode-concourse(YamlSchemaProblem)`

**To Reproduce**

```json
---
resources:
  - name: concourse
    type: git
    icon: github
    source:
      uri: https://github.com/concourse/concourse.git
      branch: main

jobs:
  - name: example
    plan:
      - get: concourse
      - set_pipeline: examples
        file: concourse/pipelines/example.yml
        instance_vars:
          pipeline: example
        var_files:
          - concourse/parameters/example.yml
```

![Screenshot 2023-01-06 at 13 24 15](https://user-images.githubusercontent.com/121949272/211023270-9358ee42-955a-4346-a77b-1dd5ab528efc.png)

**Fix**

Please add instance_vars to concourse schema.

**Comment by BoykoAlex** [comment]
Fixed with 054e3e25a09d5cf36d1b293d8b4432d137a03438
