### ISSUE TITLE
set focus on name field in starters wizard

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#943]
The starter wizard should set the focus on the `name` field instead of the `service URL` field when opening the wizard, so that you can start typing in the name of the project to generate right away.

In addition to that, the focus on the next page (where you select the starters) should be on the search input text field, so that you can start searching for starters directly.

**Comment by BoykoAlex** [comment]
Should be fixed with b16c7894a87a0e3bb693b5b4520b8ab223455e45
