### ISSUE TITLE
update generated parser for Java properties with latest ANTLR runtime version

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#946]
This error message appears in the log when opening an `application.properties` file:
`ANTLR Tool version 4.5.3 used for code generation does not match the current runtime version 4.9.3`

I think we need to re-generate the parser for Java properties with the ANTLR version that we use in the dependencies, which seems to be `4.9.3`.

**Comment by BoykoAlex** [comment]
@martinlippert I had an idea of switching to OR Properties parser and AST.

**Comment by BoykoAlex** [comment]
Fixed with 39de9aaf46a46f1bb6d0b4f9c8d377e825407428
Rewrite parser rather than our own is moved to: #949
