### ISSUE TITLE
remove support and integration for ngrok tunnels

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#954]
At the moment, the integration of the ngrok tunnels in the dashboard is put into comments (in order to make this compile against versions of apache http client that is missing the fluent API). As a next step, we need to either re-implement the functionality without the fluent API or remove the ngrok integration altogether. I think we should remove the ngrok tunnel integration altogether.

**Comment by BoykoAlex** [comment]
@martinlippert are we sure to remove this support? I have the removal in the local branch...

**Comment by martinlippert** [comment]
@BoykoAlex Yes, let's remove this instead of re-implementing this without the fluent API. We don't really have any usage numbers here, but I haven't come across any mentions of this in a long while. If requested, we can bring it back on demand.

**Comment by BoykoAlex** [comment]
Removed NGROK: 65551c084a08f6720e18a3e31c23c4e55079d506
