### ISSUE TITLE
STS Tools 4.17.1 for Eclipse is ignoring files from src/main/resources

### ISSUE THREAD

**Issue by iwanzarembo** [spring-projects/sts4#956]
**Description**
The new STS Tools **4.17.1** for Eclipse version is ignoring files from **src/main/resources**. At the end also profile dependent settings. In fact it seems to ignore all files and configs in the resource folder.

**To Reproduce**
Create a new project (build tool maven) from the starter functionality with dependencies below:

- Spring Boot DevTools
- Spring Web

Then I copied a different[banner.txt](https://github.com/spring-projects/sts4/files/10445097/banner.txt) into the **src/main/resources** folder and started the application from the Boot Dashboard view.
The result is that the banner is not shown in the console. 
See this simple demo video:

[Short demo with the bug](https://user-images.githubusercontent.com/9989906/213152932-1c2b9b10-2c60-4ecf-b9a3-100e4f3d61d9.mp4)

The issue does not occur using STS Tools 4.16.0. See video:

[Working with IDE 4.16.0](https://user-images.githubusercontent.com/9989906/213153272-7aea2fae-c9d9-48d8-9b9f-3950dff78b87.mp4)

I am not sure if it helps, but I also checked out the command line when starting the application. The only difference is the used java agent.
**Not working:**
"-javaagent:C:\usr\IDEs\sts-bundle\sts-4.17.1.RELEASE\configuration\org.eclipse.osgi\267\0\.cp\lib\javaagent-shaded.jar"
**Working:**
"-javaagent:C:\usr\IDEs\sts-bundle\sts-4.16.0.RELEASE\configuration\org.eclipse.osgi\268\0\.cp\lib\javaagent-shaded.jar"

**Comment by martinlippert** [comment]
I think you are hitting this issue: https://github.com/spring-projects/sts4/issues/929 - therefore closing this as a duplicate. https://github.com/spring-projects/sts4/issues/929#issuecomment-1371888038 contains a description how to grab the latest snapshot from m2e to fix the issue. I hope that there will be a new release of m2e around when we ship 4.17.2 in early Feb to include this fix.
