### ISSUE TITLE
STS 4 for Eclipse Download Links Broken

### ISSUE THREAD

**Issue by banahene** [spring-projects/sts4#964]
On the main site (https://spring.io/tools), the download links for MACOS X86, MACOS_ARM, and WINDOWS X86 appear to be broken. I was trying to download a new installation for my windows PC after troubleshooting a bunch of errors trying to update my current STS installation [4.13.0.RELEASE].

Clicking on the windows download link redirects to >> https://download.springsource.com/release/STS4/4.17.1.RELEASE/dist/e4.22/spring-tool-suite-4-4.17.1.RELEASE-e4.22.0-win32.win32.x86_64.self-extracting.jar

Instead of the download starting though, the below is shown on the web page.

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>33SDMA8ST3DDNQHX</RequestId>
<HostId>tDVfsCPnVnkcGcdvjKyXtV0+4CwKcg6gkb8eKw0mbajbGNWAGyK7Bhhph9EZO71ta3e6ro0sEqnRNMJXjLvSaQ==</HostId>
</Error>
```

Hopefully this will be a quick fix.

P.S.: The same issue persists in Chrome, Microsoft Edge, and Firefox

**Comment by Debraj1** [comment]
same thing I am also facing now

**Comment by Achuth568** [comment]
i am also facing the same issue

**Comment by sonson1023** [comment]
I am also facing the same issue too

**Comment by martinlippert** [comment]
Thanks a lot for reporting this, the download links are fixed again (and updated to the new version). Sorry for the inconvenience.
