### ISSUE TITLE
Version 1.44 no longer compatible with Spring Boot Dashboard

### ISSUE THREAD

**Issue by Super169** [spring-projects/sts4#965]
**Describe the bug**
Cannot start Spring Boot Dashboard with the following error:
Cannot activate the 'Spring Boot Dashboard' extension because it depends on an unknown 'Pivotal.vscode-spring-boot' extension.

**To Reproduce**
Upgrade from 1.43 to 1.44

**Sample**
For any spring project.

In fact, there has similar issue for newly installed machine as the Spring Boot Dashboard has not include Spring Boot Tools (already because it still related to old version with id Pivotal.vscode-spring-boot).  But it still compatible in 1.43, so it still work if we install Spring Boot Tool manually.  But for 1.44, it cannot start anymore.

I understand that this should be Spring Boot Dashboard issue, and I will submit another issue for Spring Boot Dashboard.  But can it still be compatible with the old id Pivotal.vscode-spring-boot as in 1.43 until it has been fixed in Spring Boot Dashboard?   Thanks.

**Comment by martinlippert** [comment]
A fixed version of the Spring Boot Dashboard extension will be published today.

**Comment by Super169** [comment]
Thanks a lot.  I have fallback to 1.43 to continue my work, waiting for the fix in Spring Boot Dashboard.

**Comment by Super169** [comment]
The problem has been solved with Spring Boot Dashboard v0.10.1.  Thanks a lot.

**Comment by martinlippert** [comment]
Huge thanks to @Eskibear for pushing out a new version that fixes the issues. Many many thanks!!!
