### ISSUE TITLE
application.properties issues 

### ISSUE THREAD

**Issue by akashgupta2703** [spring-projects/sts4#97]
Hi,

I have recently migrated from sts 3.9.5 to sts 4.0. After importing projects to new workspace, I am facing few issues related to application.properties file. 

1) If I open the file using 'Generic Editor - Spring properties', the toggle comment (or CTRl+/) option is not working and I have to put # in front of every property to comment it out. This is working fine if I open the property file using 'Properties File Editor'. 

2) Quick-fix for unknown properties is showing as 'No suggestions available' for both Generic Editor and Properties File Editor. If I remember correctly, I was able to fix unknown properties by adding meta-data using quick-fix option. Moreover, there is no option to configure this in preference now so that it does not show warning. When using previous versions of STS, there was a option in preferences (Spring -> boot -> properties Editor) where it can be set to ignore. There doesn't seem to be any such option in STS4. I tried installing STS 3 add-on and tried setting this preference, even then it didn't work. 

Can you please help this? I tried searching all the open and closed issues but couldn't find any question related to this; hence opening a new issue.

**Comment by kdvolder** [comment]
Thanks for your report. I'm afraid both of these issues are a consequence of adopting the generic editor + language server approach for the properties editor. While it does make it possible for us to support the editor across different platforms (Eclipse / Atom / Vscode)... there are some drawbacks as well. Notably, some features are still missing from the new implementation.

Report like yours are therefore very welcome as they help us identify the gaps in the new implementation and also help us prioritize re-implementing those features that our users seem to be missing the most.

BTW: In the future if you are reporting two different issues, it would be nicer if you actually created two separate tickets. We use the tickets as planning items we can move around in our tracker and they are really two separate work items for us to move around. So it is a bit constraining to have them tied to each other in only a single ticket. For this reason I will close this ticket now and create two new separate tickets for it instead.

**Comment by kdvolder** [comment]
I've split this into two tickets. You can follow the tickets above if you want remain in the loop as to how/when we tackle fixing them.

**Comment by akashgupta2703** [comment]
Thank you! I'll subscribe to mentioned tickets,

I'll create separate tickets for different issues next time onwards.
