### ISSUE TITLE
move preferences from language server category to spring category

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#970]
In Eclipse, we still have all the language-server related preferences showing up in the preferences in a deep hierarchy below the language server category. This is somewhat hard to find for users (and more an implementation detail of the internal architecture that some parts of the spring tooling are implemented as part of a language server).

Therefore we should move all preferences to the `Spring` category and have them all show up there, independent whether they are coming from the language server or not.

**Comment by BoykoAlex** [comment]
Fixed with 63b321ad69292ea65c8981814cfa6e753e4daa12
