### ISSUE TITLE
Link to p2 repo for Eclipse 2022-06 broken

### ISSUE THREAD

**Issue by nils-christian** [spring-projects/sts4#974]
Hi,

The link on https://github.com/spring-projects/sts4/wiki/Previous-Versions for p2 repo for Eclipse 2022-06 (4.24) points to https://download.springsource.com/release/TOOLS/sts4/update/4.17.2.RELEASE/e4.24/. This side leads currently to an "AccessDenied" page.

**Comment by martinlippert** [comment]
The item is indeed wrong and should not be in that list, since there is no e4.24-based build. I removed that item from the wiki page. Thanks for pointing us at this, much appreciated.

**Comment by OLibutzki** [comment]
@martinlippert  the same applies to https://download.springsource.com/release/TOOLS/sts4/update/e4.24/ being referenced here: https://marketplace.eclipse.org/content/spring-tools-4-aka-spring-tool-suite-4

**Comment by martinlippert** [comment]
> @martinlippert the same applies to https://download.springsource.com/release/TOOLS/sts4/update/e4.24/ being referenced here: https://marketplace.eclipse.org/content/spring-tools-4-aka-spring-tool-suite-4

Correct, fixed as well.
