### ISSUE TITLE
[validation] report progress when reconciling projects

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#984]
The language server should report progress when reconciling full projects, especially when reconciling all the projects in the workspace after startup - to inform the user what is going on behind the scenes.

Otherwise, it is somewhat unclear to users what is going on when they (more or less) see nothing happening in the IDE, but the CPU of the language server process is constantly busy for as long as the initial reconciling is running.

**Comment by BoykoAlex** [comment]
Should be fixed with 2f743fe9a8abfb25c50c9be60974bb347fd36b99
