### ISSUE TITLE
automatically add import for types when applying content-assist proposals for query methods

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#991]
I invoke content-assist within a Spring Data repository interface and select the one that generates the full method signature, e.g.:

```
List<Customer> findByFirstName(String firstName);
```

But there is no import statement added for the `java.util.List` type in this case. The content-assist should add that necessary import automatically if the import is not yet there.

**Comment by BoykoAlex** [comment]
Should be fixed with e273a94db7f185d5e439ae41d3d1418629c6e8e6
