### ISSUE TITLE
Add support for spring potential injection points discovery while indexing

### ISSUE THREAD

**Issue by gayanper** [spring-projects/sts4#994]
When indexing symbols today we only index symbols which are annotated by known spring related annotations. For example

```
@RestController
public class StockController {
    public StockController(@Autowired StockRepository repo){}
}
```

Both the symbols will be available in symbols. This information could be used to show a potential hierarchy in the spring dash board or provide actions to navigate or find reference. But if we write the same code like

```
@RestController
public class StockController {
    public StockController(StockRepository repo){}
}
```

Now the constructor injection is not identified as a symbol. But ideally this will be considered as injection point (like it was annotated with Autowired) at runtime. 

So the suggestion / question is, could we identify this constructors as similar to @Autowired symbols when we satisfy the spring's injection criteria for implicity constructor injection ?

**Comment by gayanper** [comment]
@martinlippert I would like get your feedback on this feature.

**Comment by martinlippert** [comment]
Hey @gayanper, thanks a lot for these thoughts and the enhancement requests. Makes a lot of sense to me. We already generate symbols for things that are not annotated (e.g. in the case of Spring Data repositories), so this idea of indexing these implicit injection points sounds like a great idea.

This raises the question whether we should distinguish injection points somehow from other annotations and Spring symbols and give a bit more structure to them than what we have nowadays. And while doing that, we should probably revisit your PR from back then about indexing certain `javax.annotation` annotations as well.

**Comment by martinlippert** [comment]
I created https://github.com/spring-projects/sts4/issues/1006 for initial work on a new internal Spring component model that would contain this injection point information (as well as other details). Please take a look and add your thoughts around this model + corresponding API.

**Comment by martinlippert** [comment]
The initial work on the new index covers this, the information for injection points that the index contains for beans takes since case into account now. This is not yet surfaced anywhere, so this doesn't show up in symbols or any other location yet, but I think we can close this item here as fixed and open another one that deals with the overall thoughts and steps towards surfacing the new index information in symbols and elsewhere.
