### ISSUE TITLE
update default settings for generations validation

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#999]
Before we ship the new release, we should adjust the default settings for the new generations validations:

- `ends on...` validations should be set to `Ignore` for now
- `has ended on...` validations should be set to `Hint` for now

This is a little bit less aggressive from the perspective of adding potentially lots of markers to existing workspaces. We will publish a blog post and short videos in order to spread the word about these settings in addition to that to make users aware.

**Comment by BoykoAlex** [comment]
Fixed with 5be12bde129b933860821b37c6009b4469b326ea
